LIBSEDML API: SedVectorRange Class Reference
SedVectorRange Class Reference
#include <SedVectorRange.h>
Public Member Functions
int addValue (double value)
int clearValues ()
virtual SedVectorRange * clone () const
virtual const std::string & getElementName () const
unsigned int getNumValues () const
virtual int getTypeCode () const
const std::vector< double > & getValues () const
virtual bool hasRequiredAttributes () const
bool hasValues () const
SedVectorRange & operator= (const SedVectorRange &rhs)
SedVectorRange (const SedVectorRange &orig)
SedVectorRange (SedNamespaces *sedmlns)
SedVectorRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setValues (const std::vector< double > &value)
virtual ~SedVectorRange ()
Public Member Functions inherited from SedRange
virtual bool isSedDataRange () const
virtual bool isSedFunctionalRange () const
virtual bool isSedUniformRange () const
virtual bool isSedVectorRange () const
SedRange & operator= (const SedRange &rhs)
SedRange (const SedRange &orig)
SedRange (SedNamespaces *sedmlns)
SedRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedRange ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedVectorRange class.
Constructor & Destructor Documentation
SedVectorRange() [1/3]
SedVectorRange::SedVectorRange (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedVectorRange using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedVectorRange.
version an unsigned int, the SED-ML Version to assign to this SedVectorRange.
Referenced by clone().
SedVectorRange() [2/3]
SedVectorRange::SedVectorRange (SedNamespaces * sedmlns)
Creates a new SedVectorRange using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedVectorRange() [3/3]
SedVectorRange::SedVectorRange (const SedVectorRange & orig)
Copy constructor for SedVectorRange.
Parameters
orig the SedVectorRange instance to copy.
~SedVectorRange()
SedVectorRange::~SedVectorRange () virtual
Destructor for SedVectorRange.
Member Function Documentation
addValue()
int SedVectorRange::addValue (double value)
Adds another value to the "value" attribute of this SedVectorRange.
Parameters
value double of the "value" attribute to be added.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
clearValues()
int SedVectorRange::clearValues ()
Clears the "value" element of this SedVectorRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
clone()
SedVectorRange * SedVectorRange::clone () const virtual
Creates and returns a deep copy of this SedVectorRange object.
Returns
a (deep) copy of this SedVectorRange object.
Reimplemented from SedRange.
References SedVectorRange().
getElementName()
const std::string & SedVectorRange::getElementName () const virtual
Returns the XML element name of this SedVectorRange object.
For SedVectorRange, the XML element name is always "vectorRange".
Returns
the name of this element, i.e. "vectorRange".
Reimplemented from SedRange.
getNumValues()
unsigned int SedVectorRange::getNumValues () const
Return the number of elements in this SedVectorRange's "value" attribute.
Returns
the number of elements in the SedVectorRange's "value" attribute.
getTypeCode()
int SedVectorRange::getTypeCode () const virtual
Returns the libSEDML type code for this SedVectorRange object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_RANGE_VECTORRANGE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedRange.
References SEDML_RANGE_VECTORRANGE.
getValues()
const std::vector< double > & SedVectorRange::getValues () const
Returns the value of the "value" attribute of this SedVectorRange.
Returns
the value of the "value" attribute of this SedVectorRange as a vector.
hasRequiredAttributes()
bool SedVectorRange::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedVectorRange object have been set.
Returns
true to indicate that all the required attributes of this SedVectorRange have been set, otherwise false is returned.
Reimplemented from SedRange.
References SedRange::hasRequiredAttributes().
hasValues()
bool SedVectorRange::hasValues () const
Predicate returning true if this SedVectorRange's "value" attribute is set.
Returns
true if this SedVectorRange's "value" attribute has been set, otherwise false is returned.
operator=()
SedVectorRange & SedVectorRange::operator= (const SedVectorRange & rhs)
Assignment operator for SedVectorRange.
Parameters
rhs the SedVectorRange object whose values are to be used as the basis of the assignment.
References SedRange::operator=().
setValues()
int SedVectorRange::setValues (const std::vector< double > & value)
Sets the value of the "value" attribute of this SedVectorRange.
Parameters
value std::vector<double> value of the "value" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedVectorRange.h
SedVectorRange.cpp