LIBSEDML API: SedPlot3D Class Reference
SedPlot3D Class Reference
#include <SedPlot3D.h>
Public Member Functions
int addSurface (const SedSurface *ss)
virtual SedPlot3D * clone () const
SedSurface * createSurface ()
SedAxis * createZAxis ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfSurfaces * getListOfSurfaces ()
const SedListOfSurfaces * getListOfSurfaces () const
unsigned int getNumSurfaces () const
SedSurface * getSurface (const std::string &sid)
const SedSurface * getSurface (const std::string &sid) const
SedSurface * getSurface (unsigned int n)
const SedSurface * getSurface (unsigned int n) const
SedSurface * getSurfaceByStyle (const std::string &sid)
const SedSurface * getSurfaceByStyle (const std::string &sid) const
SedSurface * getSurfaceByXDataReference (const std::string &sid)
const SedSurface * getSurfaceByXDataReference (const std::string &sid) const
SedSurface * getSurfaceByYDataReference (const std::string &sid)
const SedSurface * getSurfaceByYDataReference (const std::string &sid) const
SedSurface * getSurfaceByZDataReference (const std::string &sid)
const SedSurface * getSurfaceByZDataReference (const std::string &sid) const
virtual int getTypeCode () const
SedAxis * getZAxis ()
const SedAxis * getZAxis () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetZAxis () const
SedPlot3D & operator= (const SedPlot3D &rhs)
SedSurface * removeSurface (const std::string &sid)
SedSurface * removeSurface (unsigned int n)
SedPlot3D (const SedPlot3D &orig)
SedPlot3D (SedNamespaces *sedmlns)
SedPlot3D (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setZAxis (const SedAxis *zAxis)
int unsetZAxis ()
virtual ~SedPlot3D ()
Public Member Functions inherited from SedPlot
SedAxis * createXAxis ()
SedAxis * createYAxis ()
double getHeight () const
bool getLegend () const
double getWidth () const
SedAxis * getXAxis ()
const SedAxis * getXAxis () const
SedAxis * getYAxis ()
const SedAxis * getYAxis () const
bool isSetHeight () const
bool isSetLegend () const
bool isSetWidth () const
bool isSetXAxis () const
bool isSetYAxis () const
SedPlot & operator= (const SedPlot &rhs)
SedPlot (const SedPlot &orig)
SedPlot (SedNamespaces *sedmlns)
SedPlot (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setHeight (double height)
int setLegend (bool legend)
int setWidth (double width)
int setXAxis (const SedAxis *xAxis)
int setYAxis (const SedAxis *yAxis)
int unsetHeight ()
int unsetLegend ()
int unsetWidth ()
int unsetXAxis ()
int unsetYAxis ()
virtual ~SedPlot ()
Public Member Functions inherited from SedOutput
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedPlot3D class.
Constructor & Destructor Documentation
SedPlot3D() [1/3]
SedPlot3D::SedPlot3D (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedPlot3D using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedPlot3D.
version an unsigned int, the SED-ML Version to assign to this SedPlot3D.
Referenced by clone().
SedPlot3D() [2/3]
SedPlot3D::SedPlot3D (SedNamespaces * sedmlns)
Creates a new SedPlot3D using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedPlot3D() [3/3]
SedPlot3D::SedPlot3D (const SedPlot3D & orig)
Copy constructor for SedPlot3D.
Parameters
orig the SedPlot3D instance to copy.
References clone().
~SedPlot3D()
SedPlot3D::~SedPlot3D () virtual
Destructor for SedPlot3D.
Member Function Documentation
addSurface()
int SedPlot3D::addSurface (const SedSurface * ss)
Adds a copy of the given SedSurface to this SedPlot3D.
Parameters
ss the SedSurface object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createSurface()
getSurface(const std::string& sid)
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedSurface::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedPlot3D * SedPlot3D::clone () const virtual
Creates and returns a deep copy of this SedPlot3D object.
Returns
a (deep) copy of this SedPlot3D object.
Reimplemented from SedPlot.
References SedPlot3D().
Referenced by operator=(), and SedPlot3D().
createSurface()
SedSurface * SedPlot3D::createSurface ()
Creates a new SedSurface object, adds it to this SedPlot3D object and returns the SedSurface object created.
Returns
a new SedSurface object instance.
See also
addSurface(const SedSurface* object)
getSurface(const std::string& sid)
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
createZAxis()
SedAxis * SedPlot3D::createZAxis ()
Creates a new SedAxis object, adds it to this SedPlot3D object and returns the SedAxis object created.
Returns
a new SedAxis object instance.
getAllElements()
List * SedPlot3D::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedPlot.
References SED_ADD_FILTERED_LIST, and SED_ADD_FILTERED_POINTER.
getElementBySId()
SedBase * SedPlot3D::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedPlot.
References SedBase::getElementBySId().
getElementName()
const std::string & SedPlot3D::getElementName () const virtual
Returns the XML element name of this SedPlot3D object.
For SedPlot3D, the XML element name is always "plot3D".
Returns
the name of this element, i.e. "plot3D".
Reimplemented from SedPlot.
getListOfSurfaces() [1/2]
SedListOfSurfaces * SedPlot3D::getListOfSurfaces ()
Returns the SedListOfSurfaces from this SedPlot3D.
Returns
the SedListOfSurfaces from this SedPlot3D.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(const std::string& sid)
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
getListOfSurfaces() [2/2]
const SedListOfSurfaces * SedPlot3D::getListOfSurfaces () const
Returns the SedListOfSurfaces from this SedPlot3D.
Returns
the SedListOfSurfaces from this SedPlot3D.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(const std::string& sid)
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
Referenced by SedDocument::sortOrderedObjects().
getNumSurfaces()
unsigned int SedPlot3D::getNumSurfaces () const
Get the number of SedSurface objects in this SedPlot3D.
Returns
the number of SedSurface objects in this SedPlot3D.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(const std::string& sid)
getSurface(unsigned int n)
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
getSurface() [1/4]
SedSurface * SedPlot3D::getSurface (const std::string & sid)
Get a SedSurface from the SedPlot3D based on its identifier.
Parameters
sid a string representing the identifier of the SedSurface to retrieve.
Returns
the SedSurface in the SedListOfSurfaces within this SedPlot3D with the given sid or NULL if no such SedSurface exists.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
getSurface() [2/4]
const SedSurface * SedPlot3D::getSurface (const std::string & sid) const
Get a SedSurface from the SedPlot3D based on its identifier.
Parameters
sid a string representing the identifier of the SedSurface to retrieve.
Returns
the SedSurface in the SedListOfSurfaces within this SedPlot3D with the given sid or NULL if no such SedSurface exists.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
getSurface() [3/4]
SedSurface * SedPlot3D::getSurface (unsigned int n)
Get a SedSurface from the SedPlot3D.
Parameters
n an unsigned int representing the index of the SedSurface to retrieve.
Returns
the nth SedSurface in the SedListOfSurfaces within this SedPlot3D or NULL if no such object exists.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(const std::string& sid)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
getSurface() [4/4]
const SedSurface * SedPlot3D::getSurface (unsigned int n) const
Get a SedSurface from the SedPlot3D.
Parameters
n an unsigned int representing the index of the SedSurface to retrieve.
Returns
the nth SedSurface in the SedListOfSurfaces within this SedPlot3D or NULL if no such object exists.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(const std::string& sid)
getNumSurfaces()
removeSurface(const std::string& sid)
removeSurface(unsigned int n)
getSurfaceByStyle() [1/2]
SedSurface * SedPlot3D::getSurfaceByStyle (const std::string & sid)
Get a SedSurface from the SedPlot3D based on the Style to which it refers.
Parameters
sid a string representing the "style" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given style attribute or NULL if no such SedSurface exists.
getSurfaceByStyle() [2/2]
const SedSurface * SedPlot3D::getSurfaceByStyle (const std::string & sid) const
Get a SedSurface from the SedPlot3D based on the Style to which it refers.
Parameters
sid a string representing the "style" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given style attribute or NULL if no such SedSurface exists.
getSurfaceByXDataReference() [1/2]
SedSurface * SedPlot3D::getSurfaceByXDataReference (const std::string & sid)
Get a SedSurface from the SedPlot3D based on the XDataReference to which it refers.
Parameters
sid a string representing the "xDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given xDataReference attribute or NULL if no such SedSurface exists.
getSurfaceByXDataReference() [2/2]
const SedSurface * SedPlot3D::getSurfaceByXDataReference (const std::string & sid) const
Get a SedSurface from the SedPlot3D based on the XDataReference to which it refers.
Parameters
sid a string representing the "xDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given xDataReference attribute or NULL if no such SedSurface exists.
getSurfaceByYDataReference() [1/2]
SedSurface * SedPlot3D::getSurfaceByYDataReference (const std::string & sid)
Get a SedSurface from the SedPlot3D based on the YDataReference to which it refers.
Parameters
sid a string representing the "yDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given yDataReference attribute or NULL if no such SedSurface exists.
getSurfaceByYDataReference() [2/2]
const SedSurface * SedPlot3D::getSurfaceByYDataReference (const std::string & sid) const
Get a SedSurface from the SedPlot3D based on the YDataReference to which it refers.
Parameters
sid a string representing the "yDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given yDataReference attribute or NULL if no such SedSurface exists.
getSurfaceByZDataReference() [1/2]
SedSurface * SedPlot3D::getSurfaceByZDataReference (const std::string & sid)
Get a SedSurface from the SedPlot3D based on the ZDataReference to which it refers.
Parameters
sid a string representing the "zDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given zDataReference attribute or NULL if no such SedSurface exists.
getSurfaceByZDataReference() [2/2]
const SedSurface * SedPlot3D::getSurfaceByZDataReference (const std::string & sid) const
Get a SedSurface from the SedPlot3D based on the ZDataReference to which it refers.
Parameters
sid a string representing the "zDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedPlot3D based on the given zDataReference attribute or NULL if no such SedSurface exists.
getTypeCode()
int SedPlot3D::getTypeCode () const virtual
Returns the libSEDML type code for this SedPlot3D object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_OUTPUT_PLOT3D, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedPlot.
References SEDML_OUTPUT_PLOT3D.
getZAxis() [1/2]
SedAxis * SedPlot3D::getZAxis ()
Returns the value of the "zAxis" element of this SedPlot3D.
Returns
the value of the "zAxis" element of this SedPlot3D as a SedAxis*.
getZAxis() [2/2]
const SedAxis * SedPlot3D::getZAxis () const
Returns the value of the "zAxis" element of this SedPlot3D.
Returns
the value of the "zAxis" element of this SedPlot3D as a SedAxis*.
Referenced by SedSurface::getLogZ().
hasRequiredAttributes()
bool SedPlot3D::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedPlot3D object have been set.
Returns
true to indicate that all the required attributes of this SedPlot3D have been set, otherwise false is returned.
Reimplemented from SedPlot.
References SedPlot::hasRequiredAttributes().
hasRequiredElements()
bool SedPlot3D::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedPlot3D object have been set.
Returns
true to indicate that all the required elements of this SedPlot3D have been set, otherwise false is returned.
Note
The required elements for the SedPlot3D object are:
Reimplemented from SedPlot.
References SedPlot::hasRequiredElements().
isSetZAxis()
bool SedPlot3D::isSetZAxis () const
Predicate returning true if this SedPlot3D's "zAxis" element is set.
Returns
true if this SedPlot3D's "zAxis" element has been set, otherwise false is returned.
operator=()
SedPlot3D & SedPlot3D::operator= (const SedPlot3D & rhs)
Assignment operator for SedPlot3D.
Parameters
rhs the SedPlot3D object whose values are to be used as the basis of the assignment.
References clone(), and SedPlot::operator=().
removeSurface() [1/2]
SedSurface * SedPlot3D::removeSurface (const std::string & sid)
Removes the SedSurface from this SedPlot3D based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedSurface to remove.
Returns
the SedSurface in this SedPlot3D based on the identifier or NULL if no such SedSurface exists.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(const std::string& sid)
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(unsigned int n)
removeSurface() [2/2]
SedSurface * SedPlot3D::removeSurface (unsigned int n)
Removes the nth SedSurface from this SedPlot3D and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSurface to remove.
Returns
a pointer to the nth SedSurface in this SedPlot3D.
See also
addSurface(const SedSurface* object)
createSurface()
getSurface(const std::string& sid)
getSurface(unsigned int n)
getNumSurfaces()
removeSurface(const std::string& sid)
setZAxis()
int SedPlot3D::setZAxis (const SedAxis * zAxis)
Sets the value of the "zAxis" element of this SedPlot3D.
Parameters
zAxis SedAxis* value of the "zAxis" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedAxis::clone(), and LIBSEDML_OPERATION_SUCCESS.
unsetZAxis()
int SedPlot3D::unsetZAxis ()
Unsets the value of the "zAxis" element of this SedPlot3D.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedPlot3D.h
SedPlot3D.cpp