LIBSEDML API: SedCurve Class Reference
SedCurve Class Reference
#include <SedCurve.h>
Public Member Functions
virtual SedCurve * clone () const
virtual const std::string & getElementName () const
bool getLogY () const
CurveType_t getType () const
std::string getTypeAsString () const
virtual int getTypeCode () const
const std::string & getXErrorLower () const
const std::string & getXErrorUpper () const
const std::string & getYDataReference () const
const std::string & getYErrorLower () const
const std::string & getYErrorUpper () const
virtual bool hasRequiredAttributes () const
bool isSetLogY () const
bool isSetType () const
bool isSetXErrorLower () const
bool isSetXErrorUpper () const
bool isSetYDataReference () const
bool isSetYErrorLower () const
bool isSetYErrorUpper () const
SedCurve & operator= (const SedCurve &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedCurve (const SedCurve &orig)
SedCurve (SedNamespaces *sedmlns)
SedCurve (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setLogY (bool logY)
int setType (const CurveType_t type)
int setType (const std::string &type)
int setXErrorLower (const std::string &xErrorLower)
int setXErrorUpper (const std::string &xErrorUpper)
int setYDataReference (const std::string &yDataReference)
int setYErrorLower (const std::string &yErrorLower)
int setYErrorUpper (const std::string &yErrorUpper)
int unsetLogY ()
int unsetType ()
int unsetXErrorLower ()
int unsetXErrorUpper ()
int unsetYDataReference ()
int unsetYErrorLower ()
int unsetYErrorUpper ()
virtual ~SedCurve ()
Public Member Functions inherited from SedAbstractCurve
bool getLogX () const
int getOrder () const
const std::string & getStyle () const
const std::string & getXDataReference () const
const std::string & getYAxis () const
virtual bool isSedCurve () const
virtual bool isSedShadedArea () const
bool isSetLogX () const
bool isSetOrder () const
bool isSetStyle () const
bool isSetXDataReference () const
bool isSetYAxis () const
SedAbstractCurve & operator= (const SedAbstractCurve &rhs)
SedAbstractCurve (const SedAbstractCurve &orig)
SedAbstractCurve (SedNamespaces *sedmlns)
SedAbstractCurve (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setLogX (bool logX)
int setOrder (int order)
int setStyle (const std::string &style)
int setXDataReference (const std::string &xDataReference)
int setYAxis (const std::string &yAxis)
int unsetLogX ()
int unsetOrder ()
int unsetStyle ()
int unsetXDataReference ()
int unsetYAxis ()
virtual ~SedAbstractCurve ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedCurve class.
Constructor & Destructor Documentation
SedCurve() [1/3]
SedCurve::SedCurve (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedCurve using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedCurve.
version an unsigned int, the SED-ML Version to assign to this SedCurve.
Referenced by clone().
SedCurve() [2/3]
SedCurve::SedCurve (SedNamespaces * sedmlns)
Creates a new SedCurve using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedCurve() [3/3]
SedCurve::SedCurve (const SedCurve & orig)
Copy constructor for SedCurve.
Parameters
orig the SedCurve instance to copy.
~SedCurve()
SedCurve::~SedCurve () virtual
Destructor for SedCurve.
Member Function Documentation
clone()
SedCurve * SedCurve::clone () const virtual
Creates and returns a deep copy of this SedCurve object.
Returns
a (deep) copy of this SedCurve object.
Reimplemented from SedAbstractCurve.
References SedCurve().
getElementName()
const std::string & SedCurve::getElementName () const virtual
Returns the XML element name of this SedCurve object.
For SedCurve, the XML element name is always "curve".
Returns
the name of this element, i.e. "curve".
Reimplemented from SedAbstractCurve.
getLogY()
bool SedCurve::getLogY () const
Returns the value of the "logY" attribute of this SedCurve.
Returns
the value of the "logY" attribute of this SedCurve as a boolean.
References SedBase::getParentSedObject(), SedPlot2D::getRightYAxis(), SedAxis::getType(), SedBase::getTypeCode(), SedBase::getVersion(), SedAbstractCurve::getYAxis(), SedPlot::getYAxis(), isSetLogY(), SedAxis::isSetType(), SEDML_AXISTYPE_LOG10, and SEDML_OUTPUT_PLOT2D.
getType()
CurveType_t SedCurve::getType () const
Returns the value of the "type" attribute of this SedCurve.
Returns
the value of the "type" attribute of this SedCurve as a CurveType_t.
The attribute "type" on a SedCurve object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"points", TODO:add description
"bar", TODO:add description
"barStacked", TODO:add description
"horizontalBar", TODO:add description
"horizontalBarStacked", TODO:add description
The possible values returned by this method are:
@sbmlconstant{SEDML_CURVETYPE_POINTS, CurveType_t}
@sbmlconstant{SEDML_CURVETYPE_BAR, CurveType_t}
@sbmlconstant{SEDML_CURVETYPE_BARSTACKED, CurveType_t}
@sbmlconstant{SEDML_CURVETYPE_HORIZONTALBAR, CurveType_t}
@sbmlconstant{SEDML_CURVETYPE_HORIZONTALBARSTACKED, CurveType_t}
@sbmlconstant{SEDML_CURVETYPE_INVALID, CurveType_t}
getTypeAsString()
std::string SedCurve::getTypeAsString () const
Returns the value of the "type" attribute of this SedCurve.
Returns
the value of the "type" attribute of this SedCurve as a string.
The attribute "type" on a SedCurve object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"points", TODO:add description
"bar", TODO:add description
"barStacked", TODO:add description
"horizontalBar", TODO:add description
"horizontalBarStacked", TODO:add description
The possible values returned by this method are:
"points"
"bar"
"barStacked"
"horizontalBar"
"horizontalBarStacked"
"invalid CurveType value"
References CurveType_toString().
getTypeCode()
int SedCurve::getTypeCode () const virtual
Returns the libSEDML type code for this SedCurve object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_OUTPUT_CURVE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedAbstractCurve.
References SEDML_OUTPUT_CURVE.
getXErrorLower()
const std::string & SedCurve::getXErrorLower () const
Returns the value of the "xErrorLower" attribute of this SedCurve.
Returns
the value of the "xErrorLower" attribute of this SedCurve as a string.
getXErrorUpper()
const std::string & SedCurve::getXErrorUpper () const
Returns the value of the "xErrorUpper" attribute of this SedCurve.
Returns
the value of the "xErrorUpper" attribute of this SedCurve as a string.
getYDataReference()
const std::string & SedCurve::getYDataReference () const
Returns the value of the "yDataReference" attribute of this SedCurve.
Returns
the value of the "yDataReference" attribute of this SedCurve as a string.
getYErrorLower()
const std::string & SedCurve::getYErrorLower () const
Returns the value of the "yErrorLower" attribute of this SedCurve.
Returns
the value of the "yErrorLower" attribute of this SedCurve as a string.
getYErrorUpper()
const std::string & SedCurve::getYErrorUpper () const
Returns the value of the "yErrorUpper" attribute of this SedCurve.
Returns
the value of the "yErrorUpper" attribute of this SedCurve as a string.
hasRequiredAttributes()
bool SedCurve::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedCurve object have been set.
Returns
true to indicate that all the required attributes of this SedCurve have been set, otherwise false is returned.
Note
The required attributes for the SedCurve object are:
"yDataReference"
Reimplemented from SedAbstractCurve.
References SedAbstractCurve::hasRequiredAttributes(), isSetType(), and isSetYDataReference().
isSetLogY()
bool SedCurve::isSetLogY () const
Predicate returning true if this SedCurve's "logY" attribute is set.
Returns
true if this SedCurve's "logY" attribute has been set, otherwise false is returned.
Referenced by getLogY(), and unsetLogY().
isSetType()
bool SedCurve::isSetType () const
Predicate returning true if this SedCurve's "type" attribute is set.
Returns
true if this SedCurve's "type" attribute has been set, otherwise false is returned.
The attribute "type" on a SedCurve object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"points", TODO:add description
"bar", TODO:add description
"barStacked", TODO:add description
"horizontalBar", TODO:add description
"horizontalBarStacked", TODO:add description
References SEDML_CURVETYPE_INVALID.
Referenced by hasRequiredAttributes().
isSetXErrorLower()
bool SedCurve::isSetXErrorLower () const
Predicate returning true if this SedCurve's "xErrorLower" attribute is set.
Returns
true if this SedCurve's "xErrorLower" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetXErrorUpper()
bool SedCurve::isSetXErrorUpper () const
Predicate returning true if this SedCurve's "xErrorUpper" attribute is set.
Returns
true if this SedCurve's "xErrorUpper" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetYDataReference()
bool SedCurve::isSetYDataReference () const
Predicate returning true if this SedCurve's "yDataReference" attribute is set.
Returns
true if this SedCurve's "yDataReference" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetYErrorLower()
bool SedCurve::isSetYErrorLower () const
Predicate returning true if this SedCurve's "yErrorLower" attribute is set.
Returns
true if this SedCurve's "yErrorLower" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetYErrorUpper()
bool SedCurve::isSetYErrorUpper () const
Predicate returning true if this SedCurve's "yErrorUpper" attribute is set.
Returns
true if this SedCurve's "yErrorUpper" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
operator=()
SedCurve & SedCurve::operator= (const SedCurve & rhs)
Assignment operator for SedCurve.
Parameters
rhs the SedCurve object whose values are to be used as the basis of the assignment.
References SedAbstractCurve::operator=().
renameSIdRefs()
void SedCurve::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
Reimplemented from SedAbstractCurve.
References isSetXErrorLower(), isSetXErrorUpper(), isSetYDataReference(), isSetYErrorLower(), isSetYErrorUpper(), setXErrorLower(), setXErrorUpper(), setYDataReference(), setYErrorLower(), and setYErrorUpper().
setLogY()
int SedCurve::setLogY (bool logY)
Sets the value of the "logY" attribute of this SedCurve.
Parameters
logY bool value of the "logY" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setType() [1/2]
int SedCurve::setType (const CurveType_t type)
Sets the value of the "type" attribute of this SedCurve.
Parameters
type intvalue of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedCurve object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"points", TODO:add description
"bar", TODO:add description
"barStacked", TODO:add description
"horizontalBar", TODO:add description
"horizontalBarStacked", TODO:add description
References CurveType_isValid(), LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, and SEDML_CURVETYPE_INVALID.
setType() [2/2]
int SedCurve::setType (const std::string & type)
Sets the value of the "type" attribute of this SedCurve.
Parameters
type std::string& of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedCurve object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"points", TODO:add description
"bar", TODO:add description
"barStacked", TODO:add description
"horizontalBar", TODO:add description
"horizontalBarStacked", TODO:add description
References CurveType_fromString(), LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, and SEDML_CURVETYPE_INVALID.
setXErrorLower()
int SedCurve::setXErrorLower (const std::string & xErrorLower)
Sets the value of the "xErrorLower" attribute of this SedCurve.
Parameters
xErrorLower std::string& value of the "xErrorLower" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setXErrorUpper()
int SedCurve::setXErrorUpper (const std::string & xErrorUpper)
Sets the value of the "xErrorUpper" attribute of this SedCurve.
Parameters
xErrorUpper std::string& value of the "xErrorUpper" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setYDataReference()
int SedCurve::setYDataReference (const std::string & yDataReference)
Sets the value of the "yDataReference" attribute of this SedCurve.
Parameters
yDataReference std::string& value of the "yDataReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setYErrorLower()
int SedCurve::setYErrorLower (const std::string & yErrorLower)
Sets the value of the "yErrorLower" attribute of this SedCurve.
Parameters
yErrorLower std::string& value of the "yErrorLower" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setYErrorUpper()
int SedCurve::setYErrorUpper (const std::string & yErrorUpper)
Sets the value of the "yErrorUpper" attribute of this SedCurve.
Parameters
yErrorUpper std::string& value of the "yErrorUpper" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetLogY()
int SedCurve::unsetLogY ()
Unsets the value of the "logY" attribute of this SedCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetLogY(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetType()
int SedCurve::unsetType ()
Unsets the value of the "type" attribute of this SedCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
The attribute "type" on a SedCurve object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"points", TODO:add description
"bar", TODO:add description
"barStacked", TODO:add description
"horizontalBar", TODO:add description
"horizontalBarStacked", TODO:add description
References LIBSEDML_OPERATION_SUCCESS, and SEDML_CURVETYPE_INVALID.
unsetXErrorLower()
int SedCurve::unsetXErrorLower ()
Unsets the value of the "xErrorLower" attribute of this SedCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetXErrorUpper()
int SedCurve::unsetXErrorUpper ()
Unsets the value of the "xErrorUpper" attribute of this SedCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetYDataReference()
int SedCurve::unsetYDataReference ()
Unsets the value of the "yDataReference" attribute of this SedCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetYErrorLower()
int SedCurve::unsetYErrorLower ()
Unsets the value of the "yErrorLower" attribute of this SedCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetYErrorUpper()
int SedCurve::unsetYErrorUpper ()
Unsets the value of the "yErrorUpper" attribute of this SedCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedCurve.h
SedCurve.cpp