LIBSEDML API: SedVisitor Class Reference
SedVisitor Class Reference
#include <SedVisitor.h>
Public Member Functions
virtual void leave (const SedAbstractCurve &x)
virtual void leave (const SedAbstractTask &x)
virtual void leave (const SedAddXML &x)
virtual void leave (const SedAdjustableParameter &x)
virtual void leave (const SedAlgorithm &x)
virtual void leave (const SedAlgorithmParameter &x)
virtual void leave (const SedAnalysis &x)
virtual void leave (const SedAppliedDimension &x)
virtual void leave (const SedAxis &x)
virtual void leave (const SedBase &x)
virtual void leave (const SedBounds &x)
virtual void leave (const SedChange &x)
virtual void leave (const SedChangeAttribute &x)
virtual void leave (const SedChangeXML &x)
virtual void leave (const SedComputeChange &x)
virtual void leave (const SedCurve &x)
virtual void leave (const SedDataDescription &x)
virtual void leave (const SedDataGenerator &x)
virtual void leave (const SedDataRange &x)
virtual void leave (const SedDataSet &x)
virtual void leave (const SedDataSource &x)
virtual void leave (const SedDocument &x)
virtual void leave (const SedExperimentReference &x)
virtual void leave (const SedFigure &x)
virtual void leave (const SedFill &x)
virtual void leave (const SedFitExperiment &x)
virtual void leave (const SedFitMapping &x)
virtual void leave (const SedFunctionalRange &x)
virtual void leave (const SedLeastSquareObjectiveFunction &x)
virtual void leave (const SedLine &x)
virtual void leave (const SedListOf &x, int type)
virtual void leave (const SedMarker &x)
virtual void leave (const SedModel &x)
virtual void leave (const SedObjective &x)
virtual void leave (const SedOneStep &x)
virtual void leave (const SedOutput &x)
virtual void leave (const SedParameter &x)
virtual void leave (const SedParameterEstimationReport &x)
virtual void leave (const SedParameterEstimationResultPlot &x)
virtual void leave (const SedParameterEstimationTask &x)
virtual void leave (const SedPlot &x)
virtual void leave (const SedPlot2D &x)
virtual void leave (const SedPlot3D &x)
virtual void leave (const SedRange &x)
virtual void leave (const SedRemoveXML &x)
virtual void leave (const SedRepeatedTask &x)
virtual void leave (const SedReport &x)
virtual void leave (const SedSetValue &x)
virtual void leave (const SedShadedArea &x)
virtual void leave (const SedSimulation &x)
virtual void leave (const SedSlice &x)
virtual void leave (const SedSteadyState &x)
virtual void leave (const SedStyle &x)
virtual void leave (const SedSubPlot &x)
virtual void leave (const SedSubTask &x)
virtual void leave (const SedSurface &x)
virtual void leave (const SedTask &x)
virtual void leave (const SedUniformRange &x)
virtual void leave (const SedUniformTimeCourse &x)
virtual void leave (const SedVariable &x)
virtual void leave (const SedVectorRange &x)
virtual void leave (const SedWaterfallPlot &x)
virtual bool visit (const SedAbstractCurve &x)
virtual bool visit (const SedAbstractTask &x)
virtual bool visit (const SedAddXML &x)
virtual bool visit (const SedAdjustableParameter &x)
virtual bool visit (const SedAlgorithm &x)
virtual bool visit (const SedAlgorithmParameter &x)
virtual bool visit (const SedAnalysis &x)
virtual bool visit (const SedAppliedDimension &x)
virtual bool visit (const SedAxis &x)
virtual bool visit (const SedBase &x)
virtual bool visit (const SedBounds &x)
virtual bool visit (const SedChange &x)
virtual bool visit (const SedChangeAttribute &x)
virtual bool visit (const SedChangeXML &x)
virtual bool visit (const SedComputeChange &x)
virtual bool visit (const SedCurve &x)
virtual bool visit (const SedDataDescription &x)
virtual bool visit (const SedDataGenerator &x)
virtual bool visit (const SedDataRange &x)
virtual bool visit (const SedDataSet &x)
virtual bool visit (const SedDataSource &x)
virtual void visit (const SedDocument &x)
virtual bool visit (const SedExperimentReference &x)
virtual bool visit (const SedFigure &x)
virtual bool visit (const SedFill &x)
virtual bool visit (const SedFitExperiment &x)
virtual bool visit (const SedFitMapping &x)
virtual bool visit (const SedFunctionalRange &x)
virtual bool visit (const SedLeastSquareObjectiveFunction &x)
virtual bool visit (const SedLine &x)
virtual void visit (const SedListOf &x, int type)
virtual bool visit (const SedMarker &x)
virtual bool visit (const SedModel &x)
virtual bool visit (const SedObjective &x)
virtual bool visit (const SedOneStep &x)
virtual bool visit (const SedOutput &x)
virtual bool visit (const SedParameter &x)
virtual bool visit (const SedParameterEstimationReport &x)
virtual bool visit (const SedParameterEstimationResultPlot &x)
virtual bool visit (const SedParameterEstimationTask &x)
virtual bool visit (const SedPlot &x)
virtual bool visit (const SedPlot2D &x)
virtual bool visit (const SedPlot3D &x)
virtual bool visit (const SedRange &x)
virtual bool visit (const SedRemoveXML &x)
virtual bool visit (const SedRepeatedTask &x)
virtual bool visit (const SedReport &x)
virtual bool visit (const SedSetValue &x)
virtual bool visit (const SedShadedArea &x)
virtual bool visit (const SedSimulation &x)
virtual bool visit (const SedSlice &x)
virtual bool visit (const SedSteadyState &x)
virtual bool visit (const SedStyle &x)
virtual bool visit (const SedSubPlot &x)
virtual bool visit (const SedSubTask &x)
virtual bool visit (const SedSurface &x)
virtual bool visit (const SedTask &x)
virtual bool visit (const SedUniformRange &x)
virtual bool visit (const SedUniformTimeCourse &x)
virtual bool visit (const SedVariable &x)
virtual bool visit (const SedVectorRange &x)
virtual bool visit (const SedWaterfallPlot &x)
virtual ~SedVisitor ()
Detailed Description
@sbmlbrief{} TODO:Definition of the SedVisitor class.
Constructor & Destructor Documentation
~SedVisitor()
SedVisitor::~SedVisitor () virtual
Destructor method.
Member Function Documentation
leave() [1/62]
void SedVisitor::leave (const SedAbstractCurve & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [2/62]
void SedVisitor::leave (const SedAbstractTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [3/62]
void SedVisitor::leave (const SedAddXML & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [4/62]
void SedVisitor::leave (const SedAdjustableParameter & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [5/62]
void SedVisitor::leave (const SedAlgorithm & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [6/62]
void SedVisitor::leave (const SedAlgorithmParameter & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [7/62]
void SedVisitor::leave (const SedAnalysis & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [8/62]
void SedVisitor::leave (const SedAppliedDimension & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [9/62]
void SedVisitor::leave (const SedAxis & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [10/62]
void SedVisitor::leave (const SedBase & x) virtual
Interface method for using the Visitor Pattern to perform operations on Reaction objects.
Parameters
x the Reaction object to visit.
leave() [11/62]
void SedVisitor::leave (const SedBounds & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [12/62]
void SedVisitor::leave (const SedChange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [13/62]
void SedVisitor::leave (const SedChangeAttribute & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [14/62]
void SedVisitor::leave (const SedChangeXML & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [15/62]
void SedVisitor::leave (const SedComputeChange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [16/62]
void SedVisitor::leave (const SedCurve & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [17/62]
void SedVisitor::leave (const SedDataDescription & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [18/62]
void SedVisitor::leave (const SedDataGenerator & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [19/62]
void SedVisitor::leave (const SedDataRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [20/62]
void SedVisitor::leave (const SedDataSet & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [21/62]
void SedVisitor::leave (const SedDataSource & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [22/62]
void SedVisitor::leave (const SedDocument & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedDocument objects.
Parameters
x the SedDocument object to visit.
leave() [23/62]
void SedVisitor::leave (const SedExperimentReference & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [24/62]
void SedVisitor::leave (const SedFigure & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [25/62]
void SedVisitor::leave (const SedFill & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [26/62]
void SedVisitor::leave (const SedFitExperiment & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [27/62]
void SedVisitor::leave (const SedFitMapping & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [28/62]
void SedVisitor::leave (const SedFunctionalRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [29/62]
void SedVisitor::leave (const SedLeastSquareObjectiveFunction & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [30/62]
void SedVisitor::leave (const SedLine & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [31/62]
void SedVisitor::leave (const SedListOf & x, int type) virtual
Interface method for using the Visitor Pattern to perform operations on SedListOf objects.
Parameters
x the SedListOf object to visit.
type the object type code.
leave() [32/62]
void SedVisitor::leave (const SedMarker & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [33/62]
void SedVisitor::leave (const SedModel & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [34/62]
void SedVisitor::leave (const SedObjective & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [35/62]
void SedVisitor::leave (const SedOneStep & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [36/62]
void SedVisitor::leave (const SedOutput & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [37/62]
void SedVisitor::leave (const SedParameter & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [38/62]
void SedVisitor::leave (const SedParameterEstimationReport & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [39/62]
void SedVisitor::leave (const SedParameterEstimationResultPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [40/62]
void SedVisitor::leave (const SedParameterEstimationTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [41/62]
void SedVisitor::leave (const SedPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [42/62]
void SedVisitor::leave (const SedPlot2D & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [43/62]
void SedVisitor::leave (const SedPlot3D & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [44/62]
void SedVisitor::leave (const SedRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [45/62]
void SedVisitor::leave (const SedRemoveXML & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [46/62]
void SedVisitor::leave (const SedRepeatedTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [47/62]
void SedVisitor::leave (const SedReport & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [48/62]
void SedVisitor::leave (const SedSetValue & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [49/62]
void SedVisitor::leave (const SedShadedArea & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [50/62]
void SedVisitor::leave (const SedSimulation & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [51/62]
void SedVisitor::leave (const SedSlice & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [52/62]
void SedVisitor::leave (const SedSteadyState & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [53/62]
void SedVisitor::leave (const SedStyle & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [54/62]
void SedVisitor::leave (const SedSubPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [55/62]
void SedVisitor::leave (const SedSubTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [56/62]
void SedVisitor::leave (const SedSurface & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [57/62]
void SedVisitor::leave (const SedTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [58/62]
void SedVisitor::leave (const SedUniformRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [59/62]
void SedVisitor::leave (const SedUniformTimeCourse & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [60/62]
void SedVisitor::leave (const SedVariable & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [61/62]
void SedVisitor::leave (const SedVectorRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
leave() [62/62]
void SedVisitor::leave (const SedWaterfallPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to leave.
visit() [1/62]
bool SedVisitor::visit (const SedAbstractCurve & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [2/62]
bool SedVisitor::visit (const SedAbstractTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [3/62]
bool SedVisitor::visit (const SedAddXML & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [4/62]
bool SedVisitor::visit (const SedAdjustableParameter & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [5/62]
bool SedVisitor::visit (const SedAlgorithm & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [6/62]
bool SedVisitor::visit (const SedAlgorithmParameter & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [7/62]
bool SedVisitor::visit (const SedAnalysis & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [8/62]
bool SedVisitor::visit (const SedAppliedDimension & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [9/62]
bool SedVisitor::visit (const SedAxis & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [10/62]
bool SedVisitor::visit (const SedBase & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
visit() [11/62]
bool SedVisitor::visit (const SedBounds & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [12/62]
bool SedVisitor::visit (const SedChange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [13/62]
bool SedVisitor::visit (const SedChangeAttribute & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [14/62]
bool SedVisitor::visit (const SedChangeXML & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [15/62]
bool SedVisitor::visit (const SedComputeChange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [16/62]
bool SedVisitor::visit (const SedCurve & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [17/62]
bool SedVisitor::visit (const SedDataDescription & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [18/62]
bool SedVisitor::visit (const SedDataGenerator & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [19/62]
bool SedVisitor::visit (const SedDataRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [20/62]
bool SedVisitor::visit (const SedDataSet & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [21/62]
bool SedVisitor::visit (const SedDataSource & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [22/62]
void SedVisitor::visit (const SedDocument & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedDocument objects.
Parameters
x the SedDocument object to visit.
Referenced by visit().
visit() [23/62]
bool SedVisitor::visit (const SedExperimentReference & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [24/62]
bool SedVisitor::visit (const SedFigure & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [25/62]
bool SedVisitor::visit (const SedFill & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [26/62]
bool SedVisitor::visit (const SedFitExperiment & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [27/62]
bool SedVisitor::visit (const SedFitMapping & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [28/62]
bool SedVisitor::visit (const SedFunctionalRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [29/62]
bool SedVisitor::visit (const SedLeastSquareObjectiveFunction & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [30/62]
bool SedVisitor::visit (const SedLine & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [31/62]
void SedVisitor::visit (const SedListOf & x, int type) virtual
Interface method for using the Visitor Pattern to perform operations on SedListOf objects.
Parameters
x the SedListOf object to visit.
type the object type code.
References visit().
visit() [32/62]
bool SedVisitor::visit (const SedMarker & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [33/62]
bool SedVisitor::visit (const SedModel & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [34/62]
bool SedVisitor::visit (const SedObjective & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [35/62]
bool SedVisitor::visit (const SedOneStep & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [36/62]
bool SedVisitor::visit (const SedOutput & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [37/62]
bool SedVisitor::visit (const SedParameter & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [38/62]
bool SedVisitor::visit (const SedParameterEstimationReport & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [39/62]
bool SedVisitor::visit (const SedParameterEstimationResultPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [40/62]
bool SedVisitor::visit (const SedParameterEstimationTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [41/62]
bool SedVisitor::visit (const SedPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [42/62]
bool SedVisitor::visit (const SedPlot2D & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [43/62]
bool SedVisitor::visit (const SedPlot3D & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [44/62]
bool SedVisitor::visit (const SedRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [45/62]
bool SedVisitor::visit (const SedRemoveXML & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [46/62]
bool SedVisitor::visit (const SedRepeatedTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [47/62]
bool SedVisitor::visit (const SedReport & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [48/62]
bool SedVisitor::visit (const SedSetValue & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [49/62]
bool SedVisitor::visit (const SedShadedArea & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [50/62]
bool SedVisitor::visit (const SedSimulation & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [51/62]
bool SedVisitor::visit (const SedSlice & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [52/62]
bool SedVisitor::visit (const SedSteadyState & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [53/62]
bool SedVisitor::visit (const SedStyle & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [54/62]
bool SedVisitor::visit (const SedSubPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [55/62]
bool SedVisitor::visit (const SedSubTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [56/62]
bool SedVisitor::visit (const SedSurface & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [57/62]
bool SedVisitor::visit (const SedTask & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [58/62]
bool SedVisitor::visit (const SedUniformRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [59/62]
bool SedVisitor::visit (const SedUniformTimeCourse & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [60/62]
bool SedVisitor::visit (const SedVariable & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [61/62]
bool SedVisitor::visit (const SedVectorRange & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
visit() [62/62]
bool SedVisitor::visit (const SedWaterfallPlot & x) virtual
Interface method for using the Visitor Pattern to perform operations on SedBase objects.
Parameters
x the SedBase object to visit.
References visit().
The documentation for this class was generated from the following files:
SedVisitor.h
SedVisitor.cpp