LIBSEDML API: SedVariable Class Reference
SedVariable Class Reference
#include <SedVariable.h>
Public Member Functions
int addAppliedDimension (const SedAppliedDimension *sad)
virtual SedVariable * clone () const
SedAppliedDimension * createAppliedDimension ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedAppliedDimension * getAppliedDimension (unsigned int n)
const SedAppliedDimension * getAppliedDimension (unsigned int n) const
SedAppliedDimension * getAppliedDimensionByDimensionTarget (const std::string &sid)
const SedAppliedDimension * getAppliedDimensionByDimensionTarget (const std::string &sid) const
SedAppliedDimension * getAppliedDimensionByTarget (const std::string &sid)
const SedAppliedDimension * getAppliedDimensionByTarget (const std::string &sid) const
const std::string & getDimensionTerm () const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfAppliedDimensions * getListOfAppliedDimensions ()
const SedListOfAppliedDimensions * getListOfAppliedDimensions () const
const std::string & getModelReference () const
unsigned int getNumAppliedDimensions () const
const std::string & getSymbol () const
const std::string & getSymbol2 () const
const std::string & getTarget () const
const std::string & getTarget2 () const
const std::string & getTaskReference () const
const std::string & getTerm () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetDimensionTerm () const
bool isSetModelReference () const
bool isSetSymbol () const
bool isSetSymbol2 () const
bool isSetTarget () const
bool isSetTarget2 () const
bool isSetTaskReference () const
bool isSetTerm () const
SedVariable & operator= (const SedVariable &rhs)
SedAppliedDimension * removeAppliedDimension (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedVariable (const SedVariable &orig)
SedVariable (SedNamespaces *sedmlns)
SedVariable (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setDimensionTerm (const std::string &dimensionTerm)
int setModelReference (const std::string &modelReference)
int setSymbol (const std::string &symbol)
int setSymbol2 (const std::string &symbol2)
int setTarget (const std::string &target)
int setTarget2 (const std::string &target2)
int setTaskReference (const std::string &taskReference)
int setTerm (const std::string &term)
int unsetDimensionTerm ()
int unsetModelReference ()
int unsetSymbol ()
int unsetSymbol2 ()
int unsetTarget ()
int unsetTarget2 ()
int unsetTaskReference ()
int unsetTerm ()
virtual ~SedVariable ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedVariable class.
Constructor & Destructor Documentation
SedVariable() [1/3]
SedVariable::SedVariable (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedVariable using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedVariable.
version an unsigned int, the SED-ML Version to assign to this SedVariable.
Referenced by clone().
SedVariable() [2/3]
SedVariable::SedVariable (SedNamespaces * sedmlns)
Creates a new SedVariable using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedVariable() [3/3]
SedVariable::SedVariable (const SedVariable & orig)
Copy constructor for SedVariable.
Parameters
orig the SedVariable instance to copy.
~SedVariable()
SedVariable::~SedVariable () virtual
Destructor for SedVariable.
Member Function Documentation
addAppliedDimension()
int SedVariable::addAppliedDimension (const SedAppliedDimension * sad)
Adds a copy of the given SedAppliedDimension to this SedVariable.
Parameters
sad the SedAppliedDimension object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createAppliedDimension()
getAppliedDimension(const std::string& sid)
getAppliedDimension(unsigned int n)
getNumAppliedDimensions()
removeAppliedDimension(const std::string& sid)
removeAppliedDimension(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedAppliedDimension::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedVariable * SedVariable::clone () const virtual
Creates and returns a deep copy of this SedVariable object.
Returns
a (deep) copy of this SedVariable object.
Implements SedBase.
References SedVariable().
createAppliedDimension()
SedAppliedDimension * SedVariable::createAppliedDimension ()
Creates a new SedAppliedDimension object, adds it to this SedVariable object and returns the SedAppliedDimension object created.
Returns
a new SedAppliedDimension object instance.
See also
addAppliedDimension(const SedAppliedDimension* object)
getAppliedDimension(const std::string& sid)
getAppliedDimension(unsigned int n)
getNumAppliedDimensions()
removeAppliedDimension(const std::string& sid)
removeAppliedDimension(unsigned int n)
getAllElements()
List * SedVariable::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getAppliedDimension() [1/2]
SedAppliedDimension * SedVariable::getAppliedDimension (unsigned int n)
Get a SedAppliedDimension from the SedVariable.
Parameters
n an unsigned int representing the index of the SedAppliedDimension to retrieve.
Returns
the nth SedAppliedDimension in the SedListOfAppliedDimensions within this SedVariable or NULL if no such object exists.
See also
addAppliedDimension(const SedAppliedDimension* object)
createAppliedDimension()
getAppliedDimension(const std::string& sid)
getNumAppliedDimensions()
removeAppliedDimension(const std::string& sid)
removeAppliedDimension(unsigned int n)
getAppliedDimension() [2/2]
const SedAppliedDimension * SedVariable::getAppliedDimension (unsigned int n) const
Get a SedAppliedDimension from the SedVariable.
Parameters
n an unsigned int representing the index of the SedAppliedDimension to retrieve.
Returns
the nth SedAppliedDimension in the SedListOfAppliedDimensions within this SedVariable or NULL if no such object exists.
See also
addAppliedDimension(const SedAppliedDimension* object)
createAppliedDimension()
getAppliedDimension(const std::string& sid)
getNumAppliedDimensions()
removeAppliedDimension(const std::string& sid)
removeAppliedDimension(unsigned int n)
getAppliedDimensionByDimensionTarget() [1/2]
SedAppliedDimension * SedVariable::getAppliedDimensionByDimensionTarget (const std::string & sid)
Get a SedAppliedDimension from the SedVariable based on the DimensionTarget to which it refers.
Parameters
sid a string representing the "dimensionTarget" attribute of the SedAppliedDimension object to retrieve.
Returns
the first SedAppliedDimension in this SedVariable based on the given dimensionTarget attribute or NULL if no such SedAppliedDimension exists.
getAppliedDimensionByDimensionTarget() [2/2]
const SedAppliedDimension * SedVariable::getAppliedDimensionByDimensionTarget (const std::string & sid) const
Get a SedAppliedDimension from the SedVariable based on the DimensionTarget to which it refers.
Parameters
sid a string representing the "dimensionTarget" attribute of the SedAppliedDimension object to retrieve.
Returns
the first SedAppliedDimension in this SedVariable based on the given dimensionTarget attribute or NULL if no such SedAppliedDimension exists.
getAppliedDimensionByTarget() [1/2]
SedAppliedDimension * SedVariable::getAppliedDimensionByTarget (const std::string & sid)
Get a SedAppliedDimension from the SedVariable based on the Target to which it refers.
Parameters
sid a string representing the "target" attribute of the SedAppliedDimension object to retrieve.
Returns
the first SedAppliedDimension in this SedVariable based on the given target attribute or NULL if no such SedAppliedDimension exists.
getAppliedDimensionByTarget() [2/2]
const SedAppliedDimension * SedVariable::getAppliedDimensionByTarget (const std::string & sid) const
Get a SedAppliedDimension from the SedVariable based on the Target to which it refers.
Parameters
sid a string representing the "target" attribute of the SedAppliedDimension object to retrieve.
Returns
the first SedAppliedDimension in this SedVariable based on the given target attribute or NULL if no such SedAppliedDimension exists.
getDimensionTerm()
const std::string & SedVariable::getDimensionTerm () const
Returns the value of the "dimensionTerm" attribute of this SedVariable.
Returns
the value of the "dimensionTerm" attribute of this SedVariable as a string.
getElementBySId()
SedBase * SedVariable::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedVariable::getElementName () const virtual
Returns the XML element name of this SedVariable object.
For SedVariable, the XML element name is always "variable".
Returns
the name of this element, i.e. "variable".
Implements SedBase.
getListOfAppliedDimensions() [1/2]
SedListOfAppliedDimensions * SedVariable::getListOfAppliedDimensions ()
Returns the SedListOfAppliedDimensions from this SedVariable.
Returns
the SedListOfAppliedDimensions from this SedVariable.
See also
addAppliedDimension(const SedAppliedDimension* object)
createAppliedDimension()
getAppliedDimension(const std::string& sid)
getAppliedDimension(unsigned int n)
getNumAppliedDimensions()
removeAppliedDimension(const std::string& sid)
removeAppliedDimension(unsigned int n)
getListOfAppliedDimensions() [2/2]
const SedListOfAppliedDimensions * SedVariable::getListOfAppliedDimensions () const
Returns the SedListOfAppliedDimensions from this SedVariable.
Returns
the SedListOfAppliedDimensions from this SedVariable.
See also
addAppliedDimension(const SedAppliedDimension* object)
createAppliedDimension()
getAppliedDimension(const std::string& sid)
getAppliedDimension(unsigned int n)
getNumAppliedDimensions()
removeAppliedDimension(const std::string& sid)
removeAppliedDimension(unsigned int n)
getModelReference()
const std::string & SedVariable::getModelReference () const
Returns the value of the "modelReference" attribute of this SedVariable.
Returns
the value of the "modelReference" attribute of this SedVariable as a string.
getNumAppliedDimensions()
unsigned int SedVariable::getNumAppliedDimensions () const
Get the number of SedAppliedDimension objects in this SedVariable.
Returns
the number of SedAppliedDimension objects in this SedVariable.
See also
addAppliedDimension(const SedAppliedDimension* object)
createAppliedDimension()
getAppliedDimension(const std::string& sid)
getAppliedDimension(unsigned int n)
removeAppliedDimension(const std::string& sid)
removeAppliedDimension(unsigned int n)
getSymbol()
const std::string & SedVariable::getSymbol () const
Returns the value of the "symbol" attribute of this SedVariable.
Returns
the value of the "symbol" attribute of this SedVariable as a string.
getSymbol2()
const std::string & SedVariable::getSymbol2 () const
Returns the value of the "symbol2" attribute of this SedVariable.
Returns
the value of the "symbol2" attribute of this SedVariable as a string.
getTarget()
const std::string & SedVariable::getTarget () const
Returns the value of the "target" attribute of this SedVariable.
Returns
the value of the "target" attribute of this SedVariable as a string.
getTarget2()
const std::string & SedVariable::getTarget2 () const
Returns the value of the "target2" attribute of this SedVariable.
Returns
the value of the "target2" attribute of this SedVariable as a string.
getTaskReference()
const std::string & SedVariable::getTaskReference () const
Returns the value of the "taskReference" attribute of this SedVariable.
Returns
the value of the "taskReference" attribute of this SedVariable as a string.
getTerm()
const std::string & SedVariable::getTerm () const
Returns the value of the "term" attribute of this SedVariable.
Returns
the value of the "term" attribute of this SedVariable as a string.
getTypeCode()
int SedVariable::getTypeCode () const virtual
Returns the libSEDML type code for this SedVariable object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_VARIABLE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_VARIABLE.
hasRequiredAttributes()
bool SedVariable::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedVariable object have been set.
Returns
true to indicate that all the required attributes of this SedVariable have been set, otherwise false is returned.
Note
The required attributes for the SedVariable object are:
"id"
References SedBase::isSetId().
Referenced by SedComputeChange::addVariable(), SedDataGenerator::addVariable(), SedFunctionalRange::addVariable(), SedListOfVariables::addVariable(), and SedSetValue::addVariable().
isSetDimensionTerm()
bool SedVariable::isSetDimensionTerm () const
Predicate returning true if this SedVariable's "dimensionTerm" attribute is set.
Returns
true if this SedVariable's "dimensionTerm" attribute has been set, otherwise false is returned.
isSetModelReference()
bool SedVariable::isSetModelReference () const
Predicate returning true if this SedVariable's "modelReference" attribute is set.
Returns
true if this SedVariable's "modelReference" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetSymbol()
bool SedVariable::isSetSymbol () const
Predicate returning true if this SedVariable's "symbol" attribute is set.
Returns
true if this SedVariable's "symbol" attribute has been set, otherwise false is returned.
isSetSymbol2()
bool SedVariable::isSetSymbol2 () const
Predicate returning true if this SedVariable's "symbol2" attribute is set.
Returns
true if this SedVariable's "symbol2" attribute has been set, otherwise false is returned.
isSetTarget()
bool SedVariable::isSetTarget () const
Predicate returning true if this SedVariable's "target" attribute is set.
Returns
true if this SedVariable's "target" attribute has been set, otherwise false is returned.
isSetTarget2()
bool SedVariable::isSetTarget2 () const
Predicate returning true if this SedVariable's "target2" attribute is set.
Returns
true if this SedVariable's "target2" attribute has been set, otherwise false is returned.
isSetTaskReference()
bool SedVariable::isSetTaskReference () const
Predicate returning true if this SedVariable's "taskReference" attribute is set.
Returns
true if this SedVariable's "taskReference" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetTerm()
bool SedVariable::isSetTerm () const
Predicate returning true if this SedVariable's "term" attribute is set.
Returns
true if this SedVariable's "term" attribute has been set, otherwise false is returned.
operator=()
SedVariable & SedVariable::operator= (const SedVariable & rhs)
Assignment operator for SedVariable.
Parameters
rhs the SedVariable object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
removeAppliedDimension()
SedAppliedDimension * SedVariable::removeAppliedDimension (unsigned int n)
Removes the nth SedAppliedDimension from this SedVariable and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAppliedDimension to remove.
Returns
a pointer to the nth SedAppliedDimension in this SedVariable.
See also
addAppliedDimension(const SedAppliedDimension* object)
createAppliedDimension()
getAppliedDimension(const std::string& sid)
getAppliedDimension(unsigned int n)
getNumAppliedDimensions()
removeAppliedDimension(const std::string& sid)
renameSIdRefs()
void SedVariable::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetModelReference(), isSetTaskReference(), setModelReference(), and setTaskReference().
setDimensionTerm()
int SedVariable::setDimensionTerm (const std::string & dimensionTerm)
Sets the value of the "dimensionTerm" attribute of this SedVariable.
Parameters
dimensionTerm std::string& value of the "dimensionTerm" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with dimensionTerm = NULL or an empty string is equivalent to calling unsetDimensionTerm().
References LIBSEDML_OPERATION_SUCCESS.
setModelReference()
int SedVariable::setModelReference (const std::string & modelReference)
Sets the value of the "modelReference" attribute of this SedVariable.
Parameters
modelReference std::string& value of the "modelReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setSymbol()
int SedVariable::setSymbol (const std::string & symbol)
Sets the value of the "symbol" attribute of this SedVariable.
Parameters
symbol std::string& value of the "symbol" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with symbol = NULL or an empty string is equivalent to calling unsetSymbol().
References LIBSEDML_OPERATION_SUCCESS.
setSymbol2()
int SedVariable::setSymbol2 (const std::string & symbol2)
Sets the value of the "symbol2" attribute of this SedVariable.
Parameters
symbol2 std::string& value of the "symbol2" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with symbol2 = NULL or an empty string is equivalent to calling unsetSymbol2().
References LIBSEDML_OPERATION_SUCCESS.
setTarget()
int SedVariable::setTarget (const std::string & target)
Sets the value of the "target" attribute of this SedVariable.
Parameters
target std::string& value of the "target" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with target = NULL or an empty string is equivalent to calling unsetTarget().
References LIBSEDML_OPERATION_SUCCESS.
setTarget2()
int SedVariable::setTarget2 (const std::string & target2)
Sets the value of the "target2" attribute of this SedVariable.
Parameters
target2 std::string& value of the "target2" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with target2 = NULL or an empty string is equivalent to calling unsetTarget2().
References LIBSEDML_OPERATION_SUCCESS.
setTaskReference()
int SedVariable::setTaskReference (const std::string & taskReference)
Sets the value of the "taskReference" attribute of this SedVariable.
Parameters
taskReference std::string& value of the "taskReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setTerm()
int SedVariable::setTerm (const std::string & term)
Sets the value of the "term" attribute of this SedVariable.
Parameters
term std::string& value of the "term" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with term = NULL or an empty string is equivalent to calling unsetTerm().
References LIBSEDML_OPERATION_SUCCESS.
unsetDimensionTerm()
int SedVariable::unsetDimensionTerm ()
Unsets the value of the "dimensionTerm" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetModelReference()
int SedVariable::unsetModelReference ()
Unsets the value of the "modelReference" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetSymbol()
int SedVariable::unsetSymbol ()
Unsets the value of the "symbol" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetSymbol2()
int SedVariable::unsetSymbol2 ()
Unsets the value of the "symbol2" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTarget()
int SedVariable::unsetTarget ()
Unsets the value of the "target" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTarget2()
int SedVariable::unsetTarget2 ()
Unsets the value of the "target2" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTaskReference()
int SedVariable::unsetTaskReference ()
Unsets the value of the "taskReference" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTerm()
int SedVariable::unsetTerm ()
Unsets the value of the "term" attribute of this SedVariable.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedVariable.h
SedVariable.cpp