LIBSEDML API: SedSubPlot Class Reference
SedSubPlot Class Reference
#include <SedSubPlot.h>
Public Member Functions
virtual SedSubPlot * clone () const
int getCol () const
int getColSpan () const
virtual const std::string & getElementName () const
const std::string & getPlot () const
int getRow () const
int getRowSpan () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetCol () const
bool isSetColSpan () const
bool isSetPlot () const
bool isSetRow () const
bool isSetRowSpan () const
SedSubPlot & operator= (const SedSubPlot &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedSubPlot (const SedSubPlot &orig)
SedSubPlot (SedNamespaces *sedmlns)
SedSubPlot (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setCol (int col)
int setColSpan (int colSpan)
int setPlot (const std::string &plot)
int setRow (int row)
int setRowSpan (int rowSpan)
int unsetCol ()
int unsetColSpan ()
int unsetPlot ()
int unsetRow ()
int unsetRowSpan ()
virtual ~SedSubPlot ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedSubPlot class.
Constructor & Destructor Documentation
SedSubPlot() [1/3]
SedSubPlot::SedSubPlot (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedSubPlot using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedSubPlot.
version an unsigned int, the SED-ML Version to assign to this SedSubPlot.
Referenced by clone().
SedSubPlot() [2/3]
SedSubPlot::SedSubPlot (SedNamespaces * sedmlns)
Creates a new SedSubPlot using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedSubPlot() [3/3]
SedSubPlot::SedSubPlot (const SedSubPlot & orig)
Copy constructor for SedSubPlot.
Parameters
orig the SedSubPlot instance to copy.
~SedSubPlot()
SedSubPlot::~SedSubPlot () virtual
Destructor for SedSubPlot.
Member Function Documentation
clone()
SedSubPlot * SedSubPlot::clone () const virtual
Creates and returns a deep copy of this SedSubPlot object.
Returns
a (deep) copy of this SedSubPlot object.
Implements SedBase.
References SedSubPlot().
getCol()
int SedSubPlot::getCol () const
Returns the value of the "col" attribute of this SedSubPlot.
Returns
the value of the "col" attribute of this SedSubPlot as a integer.
getColSpan()
int SedSubPlot::getColSpan () const
Returns the value of the "colSpan" attribute of this SedSubPlot.
Returns
the value of the "colSpan" attribute of this SedSubPlot as a integer.
getElementName()
const std::string & SedSubPlot::getElementName () const virtual
Returns the XML element name of this SedSubPlot object.
For SedSubPlot, the XML element name is always "subPlot".
Returns
the name of this element, i.e. "subPlot".
Implements SedBase.
getPlot()
const std::string & SedSubPlot::getPlot () const
Returns the value of the "plot" attribute of this SedSubPlot.
Returns
the value of the "plot" attribute of this SedSubPlot as a string.
getRow()
int SedSubPlot::getRow () const
Returns the value of the "row" attribute of this SedSubPlot.
Returns
the value of the "row" attribute of this SedSubPlot as a integer.
getRowSpan()
int SedSubPlot::getRowSpan () const
Returns the value of the "rowSpan" attribute of this SedSubPlot.
Returns
the value of the "rowSpan" attribute of this SedSubPlot as a integer.
getTypeCode()
int SedSubPlot::getTypeCode () const virtual
Returns the libSEDML type code for this SedSubPlot object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SUBPLOT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_SUBPLOT.
hasRequiredAttributes()
bool SedSubPlot::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedSubPlot object have been set.
Returns
true to indicate that all the required attributes of this SedSubPlot have been set, otherwise false is returned.
Note
The required attributes for the SedSubPlot object are:
"plot"
"row"
"col"
References isSetCol(), isSetPlot(), and isSetRow().
Referenced by SedFigure::addSubPlot(), and SedListOfSubPlots::addSubPlot().
isSetCol()
bool SedSubPlot::isSetCol () const
Predicate returning true if this SedSubPlot's "col" attribute is set.
Returns
true if this SedSubPlot's "col" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
isSetColSpan()
bool SedSubPlot::isSetColSpan () const
Predicate returning true if this SedSubPlot's "colSpan" attribute is set.
Returns
true if this SedSubPlot's "colSpan" attribute has been set, otherwise false is returned.
isSetPlot()
bool SedSubPlot::isSetPlot () const
Predicate returning true if this SedSubPlot's "plot" attribute is set.
Returns
true if this SedSubPlot's "plot" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetRow()
bool SedSubPlot::isSetRow () const
Predicate returning true if this SedSubPlot's "row" attribute is set.
Returns
true if this SedSubPlot's "row" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
isSetRowSpan()
bool SedSubPlot::isSetRowSpan () const
Predicate returning true if this SedSubPlot's "rowSpan" attribute is set.
Returns
true if this SedSubPlot's "rowSpan" attribute has been set, otherwise false is returned.
operator=()
SedSubPlot & SedSubPlot::operator= (const SedSubPlot & rhs)
Assignment operator for SedSubPlot.
Parameters
rhs the SedSubPlot object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
renameSIdRefs()
void SedSubPlot::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetPlot(), and setPlot().
setCol()
int SedSubPlot::setCol (int col)
Sets the value of the "col" attribute of this SedSubPlot.
Parameters
col int value of the "col" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setColSpan()
int SedSubPlot::setColSpan (int colSpan)
Sets the value of the "colSpan" attribute of this SedSubPlot.
Parameters
colSpan int value of the "colSpan" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setPlot()
int SedSubPlot::setPlot (const std::string & plot)
Sets the value of the "plot" attribute of this SedSubPlot.
Parameters
plot std::string& value of the "plot" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setRow()
int SedSubPlot::setRow (int row)
Sets the value of the "row" attribute of this SedSubPlot.
Parameters
row int value of the "row" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setRowSpan()
int SedSubPlot::setRowSpan (int rowSpan)
Sets the value of the "rowSpan" attribute of this SedSubPlot.
Parameters
rowSpan int value of the "rowSpan" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetCol()
int SedSubPlot::unsetCol ()
Unsets the value of the "col" attribute of this SedSubPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetColSpan()
int SedSubPlot::unsetColSpan ()
Unsets the value of the "colSpan" attribute of this SedSubPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetPlot()
int SedSubPlot::unsetPlot ()
Unsets the value of the "plot" attribute of this SedSubPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetRow()
int SedSubPlot::unsetRow ()
Unsets the value of the "row" attribute of this SedSubPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetRowSpan()
int SedSubPlot::unsetRowSpan ()
Unsets the value of the "rowSpan" attribute of this SedSubPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
The documentation for this class was generated from the following files:
SedSubPlot.h
SedSubPlot.cpp