LIBSEDML API: SedSubTask Class Reference
SedSubTask Class Reference
#include <SedSubTask.h>
Public Member Functions
int addTaskChange (const SedSetValue *ssv)
virtual SedSubTask * clone () const
SedSetValue * createTaskChange ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfSetValues * getListOfTaskChanges ()
const SedListOfSetValues * getListOfTaskChanges () const
unsigned int getNumTaskChanges () const
int getOrder () const
const std::string & getTask () const
SedSetValue * getTaskChange (const std::string &id)
SedSetValue * getTaskChange (unsigned int n)
const SedSetValue * getTaskChange (unsigned int n) const
SedSetValue * getTaskChangeByModelReference (const std::string &sid)
const SedSetValue * getTaskChangeByModelReference (const std::string &sid) const
SedSetValue * getTaskChangeByRange (const std::string &sid)
const SedSetValue * getTaskChangeByRange (const std::string &sid) const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetOrder () const
bool isSetTask () const
SedSubTask & operator= (const SedSubTask &rhs)
SedSetValue * removeTaskChange (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedSubTask (const SedSubTask &orig)
SedSubTask (SedNamespaces *sedmlns)
SedSubTask (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setOrder (int order)
int setTask (const std::string &task)
int unsetOrder ()
int unsetTask ()
virtual ~SedSubTask ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedSubTask class.
Constructor & Destructor Documentation
SedSubTask() [1/3]
SedSubTask::SedSubTask (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedSubTask using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedSubTask.
version an unsigned int, the SED-ML Version to assign to this SedSubTask.
Referenced by clone().
SedSubTask() [2/3]
SedSubTask::SedSubTask (SedNamespaces * sedmlns)
Creates a new SedSubTask using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedSubTask() [3/3]
SedSubTask::SedSubTask (const SedSubTask & orig)
Copy constructor for SedSubTask.
Parameters
orig the SedSubTask instance to copy.
~SedSubTask()
SedSubTask::~SedSubTask () virtual
Destructor for SedSubTask.
Member Function Documentation
addTaskChange()
int SedSubTask::addTaskChange (const SedSetValue * ssv)
Adds a copy of the given SedSetValue to this SedRepeatedTask.
Parameters
ssv the SedSetValue object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedSetValue::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedSubTask * SedSubTask::clone () const virtual
Creates and returns a deep copy of this SedSubTask object.
Returns
a (deep) copy of this SedSubTask object.
Implements SedBase.
References SedSubTask().
createTaskChange()
SedSetValue * SedSubTask::createTaskChange ()
Creates a new SedSetValue object, adds it to this SedRepeatedTask object and returns the SedSetValue object created.
Returns
a new SedSetValue object instance.
See also
addTaskChange(const SedSetValue* object)
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
References SedBase::getLevel(), and SedBase::getVersion().
getAllElements()
List * SedSubTask::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getElementBySId()
SedBase * SedSubTask::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedSubTask::getElementName () const virtual
Returns the XML element name of this SedSubTask object.
For SedSubTask, the XML element name is always "subTask".
Returns
the name of this element, i.e. "subTask".
Implements SedBase.
getListOfTaskChanges() [1/2]
SedListOfSetValues * SedSubTask::getListOfTaskChanges ()
Returns the SedListOfSetValues from this SedRepeatedTask.
Returns
the SedListOfSetValues from this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getListOfTaskChanges() [2/2]
const SedListOfSetValues * SedSubTask::getListOfTaskChanges () const
Returns the SedListOfSetValues from this SedRepeatedTask.
Returns
the SedListOfSetValues from this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getNumTaskChanges()
unsigned int SedSubTask::getNumTaskChanges () const
Get the number of SedSetValue objects in this SedRepeatedTask.
Returns
the number of SedSetValue objects in this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getOrder()
int SedSubTask::getOrder () const
Returns the value of the "order" attribute of this SedSubTask.
Returns
the value of the "order" attribute of this SedSubTask as a integer.
Referenced by SubTaskOrderComparator::operator()().
getTask()
const std::string & SedSubTask::getTask () const
Returns the value of the "task" attribute of this SedSubTask.
Returns
the value of the "task" attribute of this SedSubTask as a string.
getTaskChange() [1/3]
SedSetValue * SedSubTask::getTaskChange (const std::string & id)
Get a SedSetValue from the SedRepeatedTask.
Parameters
id the id of the SedSetValue to retrieve.
Returns
the SedSetValue in the SedListOfSetValues within this SedRepeatedTask or NULL if no such object exists.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getTaskChange() [2/3]
SedSetValue * SedSubTask::getTaskChange (unsigned int n)
Get a SedSetValue from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedSetValue to retrieve.
Returns
the nth SedSetValue in the SedListOfSetValues within this SedRepeatedTask or NULL if no such object exists.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getTaskChange() [3/3]
const SedSetValue * SedSubTask::getTaskChange (unsigned int n) const
Get a SedSetValue from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedSetValue to retrieve.
Returns
the nth SedSetValue in the SedListOfSetValues within this SedRepeatedTask or NULL if no such object exists.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getTaskChangeByModelReference() [1/2]
SedSetValue * SedSubTask::getTaskChangeByModelReference (const std::string & sid)
Get a SedSetValue from the SedRepeatedTask based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given modelReference attribute or NULL if no such SedSetValue exists.
getTaskChangeByModelReference() [2/2]
const SedSetValue * SedSubTask::getTaskChangeByModelReference (const std::string & sid) const
Get a SedSetValue from the SedRepeatedTask based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given modelReference attribute or NULL if no such SedSetValue exists.
getTaskChangeByRange() [1/2]
SedSetValue * SedSubTask::getTaskChangeByRange (const std::string & sid)
Get a SedSetValue from the SedRepeatedTask based on the Range to which it refers.
Parameters
sid a string representing the "range" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given range attribute or NULL if no such SedSetValue exists.
getTaskChangeByRange() [2/2]
const SedSetValue * SedSubTask::getTaskChangeByRange (const std::string & sid) const
Get a SedSetValue from the SedRepeatedTask based on the Range to which it refers.
Parameters
sid a string representing the "range" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given range attribute or NULL if no such SedSetValue exists.
getTypeCode()
int SedSubTask::getTypeCode () const virtual
Returns the libSEDML type code for this SedSubTask object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_TASK_SUBTASK, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_TASK_SUBTASK.
hasRequiredAttributes()
bool SedSubTask::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedSubTask object have been set.
Returns
true to indicate that all the required attributes of this SedSubTask have been set, otherwise false is returned.
Note
The required attributes for the SedSubTask object are:
"order"
"task"
References isSetOrder(), and isSetTask().
Referenced by SedListOfSubTasks::addSubTask(), and SedRepeatedTask::addSubTask().
isSetOrder()
bool SedSubTask::isSetOrder () const
Predicate returning true if this SedSubTask's "order" attribute is set.
Returns
true if this SedSubTask's "order" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and SubTaskOrderComparator::operator()().
isSetTask()
bool SedSubTask::isSetTask () const
Predicate returning true if this SedSubTask's "task" attribute is set.
Returns
true if this SedSubTask's "task" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
operator=()
SedSubTask & SedSubTask::operator= (const SedSubTask & rhs)
Assignment operator for SedSubTask.
Parameters
rhs the SedSubTask object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
removeTaskChange()
SedSetValue * SedSubTask::removeTaskChange (unsigned int n)
Removes the nth SedSetValue from this SedRepeatedTask and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSetValue to remove.
Returns
a pointer to the nth SedSetValue in this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
renameSIdRefs()
void SedSubTask::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetTask(), and setTask().
setOrder()
int SedSubTask::setOrder (int order)
Sets the value of the "order" attribute of this SedSubTask.
Parameters
order int value of the "order" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setTask()
int SedSubTask::setTask (const std::string & task)
Sets the value of the "task" attribute of this SedSubTask.
Parameters
task std::string& value of the "task" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetOrder()
int SedSubTask::unsetOrder ()
Unsets the value of the "order" attribute of this SedSubTask.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetTask()
int SedSubTask::unsetTask ()
Unsets the value of the "task" attribute of this SedSubTask.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedSubTask.h
SedSubTask.cpp