LIBSEDML API: SedSetValue Class Reference
SedSetValue Class Reference
#include <SedSetValue.h>
Public Member Functions
int addParameter (const SedParameter *sp)
int addVariable (const SedVariable *sv)
virtual SedSetValue * clone () const
SedParameter * createParameter ()
SedVariable * createVariable ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfParameters * getListOfParameters ()
const SedListOfParameters * getListOfParameters () const
SedListOfVariables * getListOfVariables ()
const SedListOfVariables * getListOfVariables () const
ASTNode * getMath ()
const ASTNode * getMath () const
const std::string & getModelReference () const
unsigned int getNumParameters () const
unsigned int getNumVariables () const
SedParameter * getParameter (const std::string &sid)
const SedParameter * getParameter (const std::string &sid) const
SedParameter * getParameter (unsigned int n)
const SedParameter * getParameter (unsigned int n) const
const std::string & getRange () const
const std::string & getSymbol () const
const std::string & getTarget () const
virtual int getTypeCode () const
SedVariable * getVariable (const std::string &sid)
const SedVariable * getVariable (const std::string &sid) const
SedVariable * getVariable (unsigned int n)
const SedVariable * getVariable (unsigned int n) const
SedVariable * getVariableByModelReference (const std::string &sid)
const SedVariable * getVariableByModelReference (const std::string &sid) const
SedVariable * getVariableByTaskReference (const std::string &sid)
const SedVariable * getVariableByTaskReference (const std::string &sid) const
virtual bool hasRequiredAttributes () const
bool isSetMath () const
bool isSetModelReference () const
bool isSetRange () const
bool isSetSymbol () const
bool isSetTarget () const
SedSetValue & operator= (const SedSetValue &rhs)
SedParameter * removeParameter (const std::string &sid)
SedParameter * removeParameter (unsigned int n)
SedVariable * removeVariable (const std::string &sid)
SedVariable * removeVariable (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedSetValue (const SedSetValue &orig)
SedSetValue (SedNamespaces *sedmlns)
SedSetValue (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setMath (const ASTNode *math)
int setModelReference (const std::string &modelReference)
int setRange (const std::string &range)
int setSymbol (const std::string &symbol)
int setTarget (const std::string &target)
int unsetMath ()
int unsetModelReference ()
int unsetRange ()
int unsetSymbol ()
int unsetTarget ()
virtual ~SedSetValue ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedSetValue class.
Constructor & Destructor Documentation
SedSetValue() [1/3]
SedSetValue::SedSetValue (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedSetValue using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedSetValue.
version an unsigned int, the SED-ML Version to assign to this SedSetValue.
Referenced by clone().
SedSetValue() [2/3]
SedSetValue::SedSetValue (SedNamespaces * sedmlns)
Creates a new SedSetValue using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedSetValue() [3/3]
SedSetValue::SedSetValue (const SedSetValue & orig)
Copy constructor for SedSetValue.
Parameters
orig the SedSetValue instance to copy.
~SedSetValue()
SedSetValue::~SedSetValue () virtual
Destructor for SedSetValue.
Member Function Documentation
addParameter()
int SedSetValue::addParameter (const SedParameter * sp)
Adds a copy of the given SedParameter to this SedSetValue.
Parameters
sp the SedParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedParameter::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addVariable()
int SedSetValue::addVariable (const SedVariable * sv)
Adds a copy of the given SedVariable to this SedSetValue.
Parameters
sv the SedVariable object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedVariable::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedSetValue * SedSetValue::clone () const virtual
Creates and returns a deep copy of this SedSetValue object.
Returns
a (deep) copy of this SedSetValue object.
Implements SedBase.
References SedSetValue().
createParameter()
SedParameter * SedSetValue::createParameter ()
Creates a new SedParameter object, adds it to this SedSetValue object and returns the SedParameter object created.
Returns
a new SedParameter object instance.
See also
addParameter(const SedParameter* object)
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
createVariable()
SedVariable * SedSetValue::createVariable ()
Creates a new SedVariable object, adds it to this SedSetValue object and returns the SedVariable object created.
Returns
a new SedVariable object instance.
See also
addVariable(const SedVariable* object)
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getAllElements()
List * SedSetValue::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getElementBySId()
SedBase * SedSetValue::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedSetValue::getElementName () const virtual
Returns the XML element name of this SedSetValue object.
For SedSetValue, the XML element name is always "setValue".
Returns
the name of this element, i.e. "setValue".
Implements SedBase.
getListOfParameters() [1/2]
SedListOfParameters * SedSetValue::getListOfParameters ()
Returns the SedListOfParameters from this SedSetValue.
Returns
the SedListOfParameters from this SedSetValue.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getListOfParameters() [2/2]
const SedListOfParameters * SedSetValue::getListOfParameters () const
Returns the SedListOfParameters from this SedSetValue.
Returns
the SedListOfParameters from this SedSetValue.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getListOfVariables() [1/2]
SedListOfVariables * SedSetValue::getListOfVariables ()
Returns the SedListOfVariables from this SedSetValue.
Returns
the SedListOfVariables from this SedSetValue.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getListOfVariables() [2/2]
const SedListOfVariables * SedSetValue::getListOfVariables () const
Returns the SedListOfVariables from this SedSetValue.
Returns
the SedListOfVariables from this SedSetValue.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getMath() [1/2]
ASTNode * SedSetValue::getMath ()
Returns the value of the "math" element of this SedSetValue.
Returns
the value of the "math" element of this SedSetValue as a LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode*.
getMath() [2/2]
const ASTNode * SedSetValue::getMath () const
Returns the value of the "math" element of this SedSetValue.
Returns
the value of the "math" element of this SedSetValue as a LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode*.
getModelReference()
const std::string & SedSetValue::getModelReference () const
Returns the value of the "modelReference" attribute of this SedSetValue.
Returns
the value of the "modelReference" attribute of this SedSetValue as a string.
getNumParameters()
unsigned int SedSetValue::getNumParameters () const
Get the number of SedParameter objects in this SedSetValue.
Returns
the number of SedParameter objects in this SedSetValue.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getNumVariables()
unsigned int SedSetValue::getNumVariables () const
Get the number of SedVariable objects in this SedSetValue.
Returns
the number of SedVariable objects in this SedSetValue.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getParameter() [1/4]
SedParameter * SedSetValue::getParameter (const std::string & sid)
Get a SedParameter from the SedSetValue based on its identifier.
Parameters
sid a string representing the identifier of the SedParameter to retrieve.
Returns
the SedParameter in the SedListOfParameters within this SedSetValue with the given sid or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [2/4]
const SedParameter * SedSetValue::getParameter (const std::string & sid) const
Get a SedParameter from the SedSetValue based on its identifier.
Parameters
sid a string representing the identifier of the SedParameter to retrieve.
Returns
the SedParameter in the SedListOfParameters within this SedSetValue with the given sid or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [3/4]
SedParameter * SedSetValue::getParameter (unsigned int n)
Get a SedParameter from the SedSetValue.
Parameters
n an unsigned int representing the index of the SedParameter to retrieve.
Returns
the nth SedParameter in the SedListOfParameters within this SedSetValue or NULL if no such object exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [4/4]
const SedParameter * SedSetValue::getParameter (unsigned int n) const
Get a SedParameter from the SedSetValue.
Parameters
n an unsigned int representing the index of the SedParameter to retrieve.
Returns
the nth SedParameter in the SedListOfParameters within this SedSetValue or NULL if no such object exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getRange()
const std::string & SedSetValue::getRange () const
Returns the value of the "range" attribute of this SedSetValue.
Returns
the value of the "range" attribute of this SedSetValue as a string.
getSymbol()
const std::string & SedSetValue::getSymbol () const
Returns the value of the "symbol" attribute of this SedSetValue.
Returns
the value of the "symbol" attribute of this SedSetValue as a string.
getTarget()
const std::string & SedSetValue::getTarget () const
Returns the value of the "target" attribute of this SedSetValue.
Returns
the value of the "target" attribute of this SedSetValue as a string.
getTypeCode()
int SedSetValue::getTypeCode () const virtual
Returns the libSEDML type code for this SedSetValue object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_TASK_SETVALUE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_TASK_SETVALUE.
getVariable() [1/4]
SedVariable * SedSetValue::getVariable (const std::string & sid)
Get a SedVariable from the SedSetValue based on its identifier.
Parameters
sid a string representing the identifier of the SedVariable to retrieve.
Returns
the SedVariable in the SedListOfVariables within this SedSetValue with the given sid or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [2/4]
const SedVariable * SedSetValue::getVariable (const std::string & sid) const
Get a SedVariable from the SedSetValue based on its identifier.
Parameters
sid a string representing the identifier of the SedVariable to retrieve.
Returns
the SedVariable in the SedListOfVariables within this SedSetValue with the given sid or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [3/4]
SedVariable * SedSetValue::getVariable (unsigned int n)
Get a SedVariable from the SedSetValue.
Parameters
n an unsigned int representing the index of the SedVariable to retrieve.
Returns
the nth SedVariable in the SedListOfVariables within this SedSetValue or NULL if no such object exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [4/4]
const SedVariable * SedSetValue::getVariable (unsigned int n) const
Get a SedVariable from the SedSetValue.
Parameters
n an unsigned int representing the index of the SedVariable to retrieve.
Returns
the nth SedVariable in the SedListOfVariables within this SedSetValue or NULL if no such object exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariableByModelReference() [1/2]
SedVariable * SedSetValue::getVariableByModelReference (const std::string & sid)
Get a SedVariable from the SedSetValue based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedSetValue based on the given modelReference attribute or NULL if no such SedVariable exists.
getVariableByModelReference() [2/2]
const SedVariable * SedSetValue::getVariableByModelReference (const std::string & sid) const
Get a SedVariable from the SedSetValue based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedSetValue based on the given modelReference attribute or NULL if no such SedVariable exists.
getVariableByTaskReference() [1/2]
SedVariable * SedSetValue::getVariableByTaskReference (const std::string & sid)
Get a SedVariable from the SedSetValue based on the TaskReference to which it refers.
Parameters
sid a string representing the "taskReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedSetValue based on the given taskReference attribute or NULL if no such SedVariable exists.
getVariableByTaskReference() [2/2]
const SedVariable * SedSetValue::getVariableByTaskReference (const std::string & sid) const
Get a SedVariable from the SedSetValue based on the TaskReference to which it refers.
Parameters
sid a string representing the "taskReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedSetValue based on the given taskReference attribute or NULL if no such SedVariable exists.
hasRequiredAttributes()
bool SedSetValue::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedSetValue object have been set.
Returns
true to indicate that all the required attributes of this SedSetValue have been set, otherwise false is returned.
Note
The required attributes for the SedSetValue object are:
"modelReference"
References isSetModelReference().
Referenced by SedListOfSetValues::addTaskChange(), SedRepeatedTask::addTaskChange(), and SedSubTask::addTaskChange().
isSetMath()
bool SedSetValue::isSetMath () const
Predicate returning true if this SedSetValue's "math" element is set.
Returns
true if this SedSetValue's "math" element has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetModelReference()
bool SedSetValue::isSetModelReference () const
Predicate returning true if this SedSetValue's "modelReference" attribute is set.
Returns
true if this SedSetValue's "modelReference" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetRange()
bool SedSetValue::isSetRange () const
Predicate returning true if this SedSetValue's "range" attribute is set.
Returns
true if this SedSetValue's "range" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetSymbol()
bool SedSetValue::isSetSymbol () const
Predicate returning true if this SedSetValue's "symbol" attribute is set.
Returns
true if this SedSetValue's "symbol" attribute has been set, otherwise false is returned.
isSetTarget()
bool SedSetValue::isSetTarget () const
Predicate returning true if this SedSetValue's "target" attribute is set.
Returns
true if this SedSetValue's "target" attribute has been set, otherwise false is returned.
operator=()
SedSetValue & SedSetValue::operator= (const SedSetValue & rhs)
Assignment operator for SedSetValue.
Parameters
rhs the SedSetValue object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
removeParameter() [1/2]
SedParameter * SedSetValue::removeParameter (const std::string & sid)
Removes the SedParameter from this SedSetValue based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedParameter to remove.
Returns
the SedParameter in this SedSetValue based on the identifier or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(unsigned int n)
removeParameter() [2/2]
SedParameter * SedSetValue::removeParameter (unsigned int n)
Removes the nth SedParameter from this SedSetValue and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedParameter to remove.
Returns
a pointer to the nth SedParameter in this SedSetValue.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeVariable() [1/2]
SedVariable * SedSetValue::removeVariable (const std::string & sid)
Removes the SedVariable from this SedSetValue based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedVariable to remove.
Returns
the SedVariable in this SedSetValue based on the identifier or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(unsigned int n)
removeVariable() [2/2]
SedVariable * SedSetValue::removeVariable (unsigned int n)
Removes the nth SedVariable from this SedSetValue and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedVariable to remove.
Returns
a pointer to the nth SedVariable in this SedSetValue.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
renameSIdRefs()
void SedSetValue::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetMath(), isSetModelReference(), isSetRange(), setModelReference(), and setRange().
setMath()
int SedSetValue::setMath (const ASTNode * math)
Sets the value of the "math" element of this SedSetValue.
Parameters
math LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode* value of the "math" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_OBJECT, and LIBSEDML_OPERATION_SUCCESS.
setModelReference()
int SedSetValue::setModelReference (const std::string & modelReference)
Sets the value of the "modelReference" attribute of this SedSetValue.
Parameters
modelReference std::string& value of the "modelReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setRange()
int SedSetValue::setRange (const std::string & range)
Sets the value of the "range" attribute of this SedSetValue.
Parameters
range std::string& value of the "range" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setSymbol()
int SedSetValue::setSymbol (const std::string & symbol)
Sets the value of the "symbol" attribute of this SedSetValue.
Parameters
symbol std::string& value of the "symbol" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with symbol = NULL or an empty string is equivalent to calling unsetSymbol().
References LIBSEDML_OPERATION_SUCCESS.
setTarget()
int SedSetValue::setTarget (const std::string & target)
Sets the value of the "target" attribute of this SedSetValue.
Parameters
target std::string& value of the "target" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with target = NULL or an empty string is equivalent to calling unsetTarget().
References LIBSEDML_OPERATION_SUCCESS.
unsetMath()
int SedSetValue::unsetMath ()
Unsets the value of the "math" element of this SedSetValue.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetModelReference()
int SedSetValue::unsetModelReference ()
Unsets the value of the "modelReference" attribute of this SedSetValue.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetRange()
int SedSetValue::unsetRange ()
Unsets the value of the "range" attribute of this SedSetValue.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetSymbol()
int SedSetValue::unsetSymbol ()
Unsets the value of the "symbol" attribute of this SedSetValue.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTarget()
int SedSetValue::unsetTarget ()
Unsets the value of the "target" attribute of this SedSetValue.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedSetValue.h
SedSetValue.cpp