LIBSEDML API: SedFunctionalRange Class Reference
SedFunctionalRange Class Reference
#include <SedFunctionalRange.h>
Public Member Functions
int addParameter (const SedParameter *sp)
int addVariable (const SedVariable *sv)
virtual SedFunctionalRange * clone () const
SedParameter * createParameter ()
SedVariable * createVariable ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfParameters * getListOfParameters ()
const SedListOfParameters * getListOfParameters () const
SedListOfVariables * getListOfVariables ()
const SedListOfVariables * getListOfVariables () const
ASTNode * getMath ()
const ASTNode * getMath () const
unsigned int getNumParameters () const
unsigned int getNumVariables () const
SedParameter * getParameter (const std::string &sid)
const SedParameter * getParameter (const std::string &sid) const
SedParameter * getParameter (unsigned int n)
const SedParameter * getParameter (unsigned int n) const
const std::string & getRange () const
virtual int getTypeCode () const
SedVariable * getVariable (const std::string &sid)
const SedVariable * getVariable (const std::string &sid) const
SedVariable * getVariable (unsigned int n)
const SedVariable * getVariable (unsigned int n) const
SedVariable * getVariableByModelReference (const std::string &sid)
const SedVariable * getVariableByModelReference (const std::string &sid) const
SedVariable * getVariableByTaskReference (const std::string &sid)
const SedVariable * getVariableByTaskReference (const std::string &sid) const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetMath () const
bool isSetRange () const
SedFunctionalRange & operator= (const SedFunctionalRange &rhs)
SedParameter * removeParameter (const std::string &sid)
SedParameter * removeParameter (unsigned int n)
SedVariable * removeVariable (const std::string &sid)
SedVariable * removeVariable (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedFunctionalRange (const SedFunctionalRange &orig)
SedFunctionalRange (SedNamespaces *sedmlns)
SedFunctionalRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setMath (const ASTNode *math)
int setRange (const std::string &range)
int unsetMath ()
int unsetRange ()
virtual ~SedFunctionalRange ()
Public Member Functions inherited from SedRange
virtual bool isSedDataRange () const
virtual bool isSedFunctionalRange () const
virtual bool isSedUniformRange () const
virtual bool isSedVectorRange () const
SedRange & operator= (const SedRange &rhs)
SedRange (const SedRange &orig)
SedRange (SedNamespaces *sedmlns)
SedRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedRange ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedFunctionalRange class.
Constructor & Destructor Documentation
SedFunctionalRange() [1/3]
SedFunctionalRange::SedFunctionalRange (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedFunctionalRange using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedFunctionalRange.
version an unsigned int, the SED-ML Version to assign to this SedFunctionalRange.
Referenced by clone().
SedFunctionalRange() [2/3]
SedFunctionalRange::SedFunctionalRange (SedNamespaces * sedmlns)
Creates a new SedFunctionalRange using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedFunctionalRange() [3/3]
SedFunctionalRange::SedFunctionalRange (const SedFunctionalRange & orig)
Copy constructor for SedFunctionalRange.
Parameters
orig the SedFunctionalRange instance to copy.
~SedFunctionalRange()
SedFunctionalRange::~SedFunctionalRange () virtual
Destructor for SedFunctionalRange.
Member Function Documentation
addParameter()
int SedFunctionalRange::addParameter (const SedParameter * sp)
Adds a copy of the given SedParameter to this SedFunctionalRange.
Parameters
sp the SedParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedParameter::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addVariable()
int SedFunctionalRange::addVariable (const SedVariable * sv)
Adds a copy of the given SedVariable to this SedFunctionalRange.
Parameters
sv the SedVariable object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedVariable::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedFunctionalRange * SedFunctionalRange::clone () const virtual
Creates and returns a deep copy of this SedFunctionalRange object.
Returns
a (deep) copy of this SedFunctionalRange object.
Reimplemented from SedRange.
References SedFunctionalRange().
createParameter()
SedParameter * SedFunctionalRange::createParameter ()
Creates a new SedParameter object, adds it to this SedFunctionalRange object and returns the SedParameter object created.
Returns
a new SedParameter object instance.
See also
addParameter(const SedParameter* object)
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
createVariable()
SedVariable * SedFunctionalRange::createVariable ()
Creates a new SedVariable object, adds it to this SedFunctionalRange object and returns the SedVariable object created.
Returns
a new SedVariable object instance.
See also
addVariable(const SedVariable* object)
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getAllElements()
List * SedFunctionalRange::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getElementBySId()
SedBase * SedFunctionalRange::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedFunctionalRange::getElementName () const virtual
Returns the XML element name of this SedFunctionalRange object.
For SedFunctionalRange, the XML element name is always "functionalRange".
Returns
the name of this element, i.e. "functionalRange".
Reimplemented from SedRange.
getListOfParameters() [1/2]
SedListOfParameters * SedFunctionalRange::getListOfParameters ()
Returns the SedListOfParameters from this SedFunctionalRange.
Returns
the SedListOfParameters from this SedFunctionalRange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getListOfParameters() [2/2]
const SedListOfParameters * SedFunctionalRange::getListOfParameters () const
Returns the SedListOfParameters from this SedFunctionalRange.
Returns
the SedListOfParameters from this SedFunctionalRange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getListOfVariables() [1/2]
SedListOfVariables * SedFunctionalRange::getListOfVariables ()
Returns the SedListOfVariables from this SedFunctionalRange.
Returns
the SedListOfVariables from this SedFunctionalRange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getListOfVariables() [2/2]
const SedListOfVariables * SedFunctionalRange::getListOfVariables () const
Returns the SedListOfVariables from this SedFunctionalRange.
Returns
the SedListOfVariables from this SedFunctionalRange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getMath() [1/2]
ASTNode * SedFunctionalRange::getMath ()
Returns the value of the "math" element of this SedFunctionalRange.
Returns
the value of the "math" element of this SedFunctionalRange as a LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode*.
getMath() [2/2]
const ASTNode * SedFunctionalRange::getMath () const
Returns the value of the "math" element of this SedFunctionalRange.
Returns
the value of the "math" element of this SedFunctionalRange as a LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode*.
getNumParameters()
unsigned int SedFunctionalRange::getNumParameters () const
Get the number of SedParameter objects in this SedFunctionalRange.
Returns
the number of SedParameter objects in this SedFunctionalRange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getNumVariables()
unsigned int SedFunctionalRange::getNumVariables () const
Get the number of SedVariable objects in this SedFunctionalRange.
Returns
the number of SedVariable objects in this SedFunctionalRange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getParameter() [1/4]
SedParameter * SedFunctionalRange::getParameter (const std::string & sid)
Get a SedParameter from the SedFunctionalRange based on its identifier.
Parameters
sid a string representing the identifier of the SedParameter to retrieve.
Returns
the SedParameter in the SedListOfParameters within this SedFunctionalRange with the given sid or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [2/4]
const SedParameter * SedFunctionalRange::getParameter (const std::string & sid) const
Get a SedParameter from the SedFunctionalRange based on its identifier.
Parameters
sid a string representing the identifier of the SedParameter to retrieve.
Returns
the SedParameter in the SedListOfParameters within this SedFunctionalRange with the given sid or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [3/4]
SedParameter * SedFunctionalRange::getParameter (unsigned int n)
Get a SedParameter from the SedFunctionalRange.
Parameters
n an unsigned int representing the index of the SedParameter to retrieve.
Returns
the nth SedParameter in the SedListOfParameters within this SedFunctionalRange or NULL if no such object exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [4/4]
const SedParameter * SedFunctionalRange::getParameter (unsigned int n) const
Get a SedParameter from the SedFunctionalRange.
Parameters
n an unsigned int representing the index of the SedParameter to retrieve.
Returns
the nth SedParameter in the SedListOfParameters within this SedFunctionalRange or NULL if no such object exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getRange()
const std::string & SedFunctionalRange::getRange () const
Returns the value of the "range" attribute of this SedFunctionalRange.
Returns
the value of the "range" attribute of this SedFunctionalRange as a string.
getTypeCode()
int SedFunctionalRange::getTypeCode () const virtual
Returns the libSEDML type code for this SedFunctionalRange object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_RANGE_FUNCTIONALRANGE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedRange.
References SEDML_RANGE_FUNCTIONALRANGE.
getVariable() [1/4]
SedVariable * SedFunctionalRange::getVariable (const std::string & sid)
Get a SedVariable from the SedFunctionalRange based on its identifier.
Parameters
sid a string representing the identifier of the SedVariable to retrieve.
Returns
the SedVariable in the SedListOfVariables within this SedFunctionalRange with the given sid or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [2/4]
const SedVariable * SedFunctionalRange::getVariable (const std::string & sid) const
Get a SedVariable from the SedFunctionalRange based on its identifier.
Parameters
sid a string representing the identifier of the SedVariable to retrieve.
Returns
the SedVariable in the SedListOfVariables within this SedFunctionalRange with the given sid or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [3/4]
SedVariable * SedFunctionalRange::getVariable (unsigned int n)
Get a SedVariable from the SedFunctionalRange.
Parameters
n an unsigned int representing the index of the SedVariable to retrieve.
Returns
the nth SedVariable in the SedListOfVariables within this SedFunctionalRange or NULL if no such object exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [4/4]
const SedVariable * SedFunctionalRange::getVariable (unsigned int n) const
Get a SedVariable from the SedFunctionalRange.
Parameters
n an unsigned int representing the index of the SedVariable to retrieve.
Returns
the nth SedVariable in the SedListOfVariables within this SedFunctionalRange or NULL if no such object exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariableByModelReference() [1/2]
SedVariable * SedFunctionalRange::getVariableByModelReference (const std::string & sid)
Get a SedVariable from the SedFunctionalRange based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedFunctionalRange based on the given modelReference attribute or NULL if no such SedVariable exists.
getVariableByModelReference() [2/2]
const SedVariable * SedFunctionalRange::getVariableByModelReference (const std::string & sid) const
Get a SedVariable from the SedFunctionalRange based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedFunctionalRange based on the given modelReference attribute or NULL if no such SedVariable exists.
getVariableByTaskReference() [1/2]
SedVariable * SedFunctionalRange::getVariableByTaskReference (const std::string & sid)
Get a SedVariable from the SedFunctionalRange based on the TaskReference to which it refers.
Parameters
sid a string representing the "taskReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedFunctionalRange based on the given taskReference attribute or NULL if no such SedVariable exists.
getVariableByTaskReference() [2/2]
const SedVariable * SedFunctionalRange::getVariableByTaskReference (const std::string & sid) const
Get a SedVariable from the SedFunctionalRange based on the TaskReference to which it refers.
Parameters
sid a string representing the "taskReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedFunctionalRange based on the given taskReference attribute or NULL if no such SedVariable exists.
hasRequiredAttributes()
bool SedFunctionalRange::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedFunctionalRange object have been set.
Returns
true to indicate that all the required attributes of this SedFunctionalRange have been set, otherwise false is returned.
Note
The required attributes for the SedFunctionalRange object are:
"range"
Reimplemented from SedRange.
References SedRange::hasRequiredAttributes(), and isSetRange().
hasRequiredElements()
bool SedFunctionalRange::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedFunctionalRange object have been set.
Returns
true to indicate that all the required elements of this SedFunctionalRange have been set, otherwise false is returned.
Note
The required elements for the SedFunctionalRange object are:
isSetMath()
bool SedFunctionalRange::isSetMath () const
Predicate returning true if this SedFunctionalRange's "math" element is set.
Returns
true if this SedFunctionalRange's "math" element has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetRange()
bool SedFunctionalRange::isSetRange () const
Predicate returning true if this SedFunctionalRange's "range" attribute is set.
Returns
true if this SedFunctionalRange's "range" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
operator=()
SedFunctionalRange & SedFunctionalRange::operator= (const SedFunctionalRange & rhs)
Assignment operator for SedFunctionalRange.
Parameters
rhs the SedFunctionalRange object whose values are to be used as the basis of the assignment.
References SedRange::operator=().
removeParameter() [1/2]
SedParameter * SedFunctionalRange::removeParameter (const std::string & sid)
Removes the SedParameter from this SedFunctionalRange based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedParameter to remove.
Returns
the SedParameter in this SedFunctionalRange based on the identifier or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(unsigned int n)
removeParameter() [2/2]
SedParameter * SedFunctionalRange::removeParameter (unsigned int n)
Removes the nth SedParameter from this SedFunctionalRange and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedParameter to remove.
Returns
a pointer to the nth SedParameter in this SedFunctionalRange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeVariable() [1/2]
SedVariable * SedFunctionalRange::removeVariable (const std::string & sid)
Removes the SedVariable from this SedFunctionalRange based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedVariable to remove.
Returns
the SedVariable in this SedFunctionalRange based on the identifier or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(unsigned int n)
removeVariable() [2/2]
SedVariable * SedFunctionalRange::removeVariable (unsigned int n)
Removes the nth SedVariable from this SedFunctionalRange and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedVariable to remove.
Returns
a pointer to the nth SedVariable in this SedFunctionalRange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
renameSIdRefs()
void SedFunctionalRange::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetMath(), isSetRange(), and setRange().
setMath()
int SedFunctionalRange::setMath (const ASTNode * math)
Sets the value of the "math" element of this SedFunctionalRange.
Parameters
math LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode* value of the "math" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_OBJECT, and LIBSEDML_OPERATION_SUCCESS.
setRange()
int SedFunctionalRange::setRange (const std::string & range)
Sets the value of the "range" attribute of this SedFunctionalRange.
Parameters
range std::string& value of the "range" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetMath()
int SedFunctionalRange::unsetMath ()
Unsets the value of the "math" element of this SedFunctionalRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetRange()
int SedFunctionalRange::unsetRange ()
Unsets the value of the "range" attribute of this SedFunctionalRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedFunctionalRange.h
SedFunctionalRange.cpp