LIBSEDML API: SedPlot Class Reference
SedPlot Class Reference
#include <SedPlot.h>
Public Member Functions
virtual SedPlot * clone () const
SedAxis * createXAxis ()
SedAxis * createYAxis ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
double getHeight () const
bool getLegend () const
virtual int getTypeCode () const
double getWidth () const
SedAxis * getXAxis ()
const SedAxis * getXAxis () const
SedAxis * getYAxis ()
const SedAxis * getYAxis () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetHeight () const
bool isSetLegend () const
bool isSetWidth () const
bool isSetXAxis () const
bool isSetYAxis () const
SedPlot & operator= (const SedPlot &rhs)
SedPlot (const SedPlot &orig)
SedPlot (SedNamespaces *sedmlns)
SedPlot (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setHeight (double height)
int setLegend (bool legend)
int setWidth (double width)
int setXAxis (const SedAxis *xAxis)
int setYAxis (const SedAxis *yAxis)
int unsetHeight ()
int unsetLegend ()
int unsetWidth ()
int unsetXAxis ()
int unsetYAxis ()
virtual ~SedPlot ()
Public Member Functions inherited from SedOutput
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedPlot class.
Constructor & Destructor Documentation
SedPlot() [1/3]
SedPlot::SedPlot (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedPlot using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedPlot.
version an unsigned int, the SED-ML Version to assign to this SedPlot.
Referenced by clone().
SedPlot() [2/3]
SedPlot::SedPlot (SedNamespaces * sedmlns)
Creates a new SedPlot using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedPlot() [3/3]
SedPlot::SedPlot (const SedPlot & orig)
Copy constructor for SedPlot.
Parameters
orig the SedPlot instance to copy.
References clone().
~SedPlot()
SedPlot::~SedPlot () virtual
Destructor for SedPlot.
Member Function Documentation
clone()
SedPlot * SedPlot::clone () const virtual
Creates and returns a deep copy of this SedPlot object.
Returns
a (deep) copy of this SedPlot object.
Reimplemented from SedOutput.
Reimplemented in SedWaterfallPlot, SedPlot3D, SedPlot2D, and SedParameterEstimationResultPlot.
References SedPlot().
Referenced by operator=(), and SedPlot().
createXAxis()
SedAxis * SedPlot::createXAxis ()
Creates a new SedAxis object, adds it to this SedPlot object and returns the SedAxis object created.
Returns
a new SedAxis object instance.
createYAxis()
SedAxis * SedPlot::createYAxis ()
Creates a new SedAxis object, adds it to this SedPlot object and returns the SedAxis object created.
Returns
a new SedAxis object instance.
getAllElements()
List * SedPlot::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
Reimplemented in SedPlot3D, and SedPlot2D.
References SED_ADD_FILTERED_POINTER.
getElementBySId()
SedBase * SedPlot::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
Reimplemented in SedPlot3D, and SedPlot2D.
References SedBase::getElementBySId().
getElementName()
const std::string & SedPlot::getElementName () const virtual
Returns the XML element name of this SedPlot object.
For SedPlot, the XML element name is always "plot".
Returns
the name of this element, i.e. "plot".
Reimplemented from SedOutput.
Reimplemented in SedWaterfallPlot, SedPlot3D, SedPlot2D, and SedParameterEstimationResultPlot.
getHeight()
double SedPlot::getHeight () const
Returns the value of the "height" attribute of this SedPlot.
Returns
the value of the "height" attribute of this SedPlot as a double.
getLegend()
bool SedPlot::getLegend () const
Returns the value of the "legend" attribute of this SedPlot.
Returns
the value of the "legend" attribute of this SedPlot as a boolean.
getTypeCode()
int SedPlot::getTypeCode () const virtual
Returns the libSEDML type code for this SedPlot object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_OUTPUT_PLOT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedOutput.
Reimplemented in SedWaterfallPlot, SedPlot3D, SedPlot2D, and SedParameterEstimationResultPlot.
References SEDML_OUTPUT_PLOT.
getWidth()
double SedPlot::getWidth () const
Returns the value of the "width" attribute of this SedPlot.
Returns
the value of the "width" attribute of this SedPlot as a double.
getXAxis() [1/2]
SedAxis * SedPlot::getXAxis ()
Returns the value of the "xAxis" element of this SedPlot.
Returns
the value of the "xAxis" element of this SedPlot as a SedAxis*.
getXAxis() [2/2]
const SedAxis * SedPlot::getXAxis () const
Returns the value of the "xAxis" element of this SedPlot.
Returns
the value of the "xAxis" element of this SedPlot as a SedAxis*.
Referenced by SedAbstractCurve::getLogX(), and SedSurface::getLogX().
getYAxis() [1/2]
SedAxis * SedPlot::getYAxis ()
Returns the value of the "yAxis" element of this SedPlot.
Returns
the value of the "yAxis" element of this SedPlot as a SedAxis*.
getYAxis() [2/2]
const SedAxis * SedPlot::getYAxis () const
Returns the value of the "yAxis" element of this SedPlot.
Returns
the value of the "yAxis" element of this SedPlot as a SedAxis*.
Referenced by SedCurve::getLogY(), and SedSurface::getLogY().
hasRequiredAttributes()
bool SedPlot::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedPlot object have been set.
Returns
true to indicate that all the required attributes of this SedPlot have been set, otherwise false is returned.
Reimplemented from SedOutput.
Reimplemented in SedWaterfallPlot, SedPlot3D, SedPlot2D, and SedParameterEstimationResultPlot.
References SedOutput::hasRequiredAttributes().
Referenced by SedParameterEstimationResultPlot::hasRequiredAttributes(), SedPlot2D::hasRequiredAttributes(), SedPlot3D::hasRequiredAttributes(), and SedWaterfallPlot::hasRequiredAttributes().
hasRequiredElements()
bool SedPlot::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedPlot object have been set.
Returns
true to indicate that all the required elements of this SedPlot have been set, otherwise false is returned.
Note
The required elements for the SedPlot object are:
Reimplemented in SedPlot3D, and SedPlot2D.
Referenced by SedPlot2D::hasRequiredElements(), and SedPlot3D::hasRequiredElements().
isSetHeight()
bool SedPlot::isSetHeight () const
Predicate returning true if this SedPlot's "height" attribute is set.
Returns
true if this SedPlot's "height" attribute has been set, otherwise false is returned.
Referenced by unsetHeight().
isSetLegend()
bool SedPlot::isSetLegend () const
Predicate returning true if this SedPlot's "legend" attribute is set.
Returns
true if this SedPlot's "legend" attribute has been set, otherwise false is returned.
Referenced by unsetLegend().
isSetWidth()
bool SedPlot::isSetWidth () const
Predicate returning true if this SedPlot's "width" attribute is set.
Returns
true if this SedPlot's "width" attribute has been set, otherwise false is returned.
Referenced by unsetWidth().
isSetXAxis()
bool SedPlot::isSetXAxis () const
Predicate returning true if this SedPlot's "xAxis" element is set.
Returns
true if this SedPlot's "xAxis" element has been set, otherwise false is returned.
isSetYAxis()
bool SedPlot::isSetYAxis () const
Predicate returning true if this SedPlot's "yAxis" element is set.
Returns
true if this SedPlot's "yAxis" element has been set, otherwise false is returned.
operator=()
SedPlot & SedPlot::operator= (const SedPlot & rhs)
Assignment operator for SedPlot.
Parameters
rhs the SedPlot object whose values are to be used as the basis of the assignment.
References clone(), and SedOutput::operator=().
Referenced by SedParameterEstimationResultPlot::operator=(), SedPlot2D::operator=(), SedPlot3D::operator=(), and SedWaterfallPlot::operator=().
setHeight()
int SedPlot::setHeight (double height)
Sets the value of the "height" attribute of this SedPlot.
Parameters
height double value of the "height" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setLegend()
int SedPlot::setLegend (bool legend)
Sets the value of the "legend" attribute of this SedPlot.
Parameters
legend bool value of the "legend" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setWidth()
int SedPlot::setWidth (double width)
Sets the value of the "width" attribute of this SedPlot.
Parameters
width double value of the "width" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setXAxis()
int SedPlot::setXAxis (const SedAxis * xAxis)
Sets the value of the "xAxis" element of this SedPlot.
Parameters
xAxis SedAxis* value of the "xAxis" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedAxis::clone(), and LIBSEDML_OPERATION_SUCCESS.
setYAxis()
int SedPlot::setYAxis (const SedAxis * yAxis)
Sets the value of the "yAxis" element of this SedPlot.
Parameters
yAxis SedAxis* value of the "yAxis" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedAxis::clone(), and LIBSEDML_OPERATION_SUCCESS.
unsetHeight()
int SedPlot::unsetHeight ()
Unsets the value of the "height" attribute of this SedPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetHeight(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetLegend()
int SedPlot::unsetLegend ()
Unsets the value of the "legend" attribute of this SedPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetLegend(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetWidth()
int SedPlot::unsetWidth ()
Unsets the value of the "width" attribute of this SedPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetWidth(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetXAxis()
int SedPlot::unsetXAxis ()
Unsets the value of the "xAxis" element of this SedPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetYAxis()
int SedPlot::unsetYAxis ()
Unsets the value of the "yAxis" element of this SedPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedPlot.h
SedPlot.cpp