LIBSEDML API: SedListOfStyles Class Reference
SedListOfStyles Class Reference
#include <SedListOfStyles.h>
Public Member Functions
int addStyle (const SedStyle *ss)
virtual SedListOfStyles * clone () const
SedStyle * createStyle ()
virtual SedStyle * get (const std::string &sid)
virtual const SedStyle * get (const std::string &sid) const
virtual SedStyle * get (unsigned int n)
virtual const SedStyle * get (unsigned int n) const
SedStyle * getByBaseStyle (const std::string &sid)
const SedStyle * getByBaseStyle (const std::string &sid) const
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
unsigned int getNumStyles () const
virtual int getTypeCode () const
SedListOfStyles & operator= (const SedListOfStyles &rhs)
virtual SedStyle * remove (const std::string &sid)
virtual SedStyle * remove (unsigned int n)
SedListOfStyles (const SedListOfStyles &orig)
SedListOfStyles (SedNamespaces *sedMLns)
SedListOfStyles (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedListOfStyles ()
Public Member Functions inherited from SedListOf
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedListOfStyles class.
Constructor & Destructor Documentation
SedListOfStyles() [1/3]
SedListOfStyles::SedListOfStyles (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOfStyles using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedListOfStyles.
version an unsigned int, the SED-ML Version to assign to this SedListOfStyles.
Referenced by clone().
SedListOfStyles() [2/3]
SedListOfStyles::SedListOfStyles (SedNamespaces * sedMLns)
Creates a new SedListOfStyles using the given SedNamespaces object sedMLns.
Parameters
sedMLns the SedNamespaces object.
References SedNamespaces::getURI().
SedListOfStyles() [3/3]
SedListOfStyles::SedListOfStyles (const SedListOfStyles & orig)
Copy constructor for SedListOfStyles.
Parameters
orig the SedListOfStyles instance to copy.
~SedListOfStyles()
SedListOfStyles::~SedListOfStyles () virtual
Destructor for SedListOfStyles.
Member Function Documentation
addStyle()
int SedListOfStyles::addStyle (const SedStyle * ss)
Adds a copy of the given SedStyle to this SedListOfStyles.
Parameters
ss the SedStyle object to add.
@sedMLconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedMLconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedMLconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedMLconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedMLconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedMLconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedMLconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createStyle()
get(const std::string& sid)
get(unsigned int n)
getNumStyles()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::append(), SedBase::getLevel(), SedBase::getVersion(), SedStyle::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedListOfStyles * SedListOfStyles::clone () const virtual
Creates and returns a deep copy of this SedListOfStyles object.
Returns
a (deep) copy of this SedListOfStyles object.
Reimplemented from SedListOf.
References SedListOfStyles().
createStyle()
SedStyle * SedListOfStyles::createStyle ()
Creates a new SedStyle object, adds it to this SedListOfStyles object and returns the SedStyle object created.
Returns
a new SedStyle object instance.
See also
addStyle(const SedStyle* object)
get(const std::string& sid)
get(unsigned int n)
getNumStyles()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
get() [1/4]
SedStyle * SedListOfStyles::get (const std::string & sid) virtual
Get a SedStyle from the SedListOfStyles based on its identifier.
Parameters
sid a string representing the identifier of the SedStyle to retrieve.
Returns
the SedStyle in this SedListOfStyles with the given sid or NULL if no such SedStyle exists.
See also
addStyle(const SedStyle* object)
createStyle()
get(unsigned int n)
getNumStyles()
remove(const std::string& sid)
remove(unsigned int n)
References get().
get() [2/4]
const SedStyle * SedListOfStyles::get (const std::string & sid) const virtual
Get a SedStyle from the SedListOfStyles based on its identifier.
Parameters
sid a string representing the identifier of the SedStyle to retrieve.
Returns
the SedStyle in this SedListOfStyles with the given sid or NULL if no such SedStyle exists.
See also
addStyle(const SedStyle* object)
createStyle()
get(unsigned int n)
getNumStyles()
remove(const std::string& sid)
remove(unsigned int n)
get() [3/4]
SedStyle * SedListOfStyles::get (unsigned int n) virtual
Get a SedStyle from the SedListOfStyles.
Parameters
n an unsigned int representing the index of the SedStyle to retrieve.
Returns
the nth SedStyle in this SedListOfStyles or NULL if no such object exists.
See also
addStyle(const SedStyle* object)
createStyle()
get(const std::string& sid)
getNumStyles()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
Referenced by get().
get() [4/4]
const SedStyle * SedListOfStyles::get (unsigned int n) const virtual
Get a SedStyle from the SedListOfStyles.
Parameters
n an unsigned int representing the index of the SedStyle to retrieve.
Returns
the nth SedStyle in this SedListOfStyles or NULL if no such object exists.
See also
addStyle(const SedStyle* object)
createStyle()
get(const std::string& sid)
getNumStyles()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
getByBaseStyle() [1/2]
SedStyle * SedListOfStyles::getByBaseStyle (const std::string & sid)
Get a SedStyle from the SedListOfStyles based on the BaseStyle to which it refers.
Parameters
sid a string representing the "baseStyle" attribute of the SedStyle object to retrieve.
Returns
the first SedStyle in this SedListOfStyles based on the given baseStyle attribute or NULL if no such SedStyle exists.
References getByBaseStyle().
getByBaseStyle() [2/2]
const SedStyle * SedListOfStyles::getByBaseStyle (const std::string & sid) const
Get a SedStyle from the SedListOfStyles based on the BaseStyle to which it refers.
Parameters
sid a string representing the "baseStyle" attribute of the SedStyle object to retrieve.
Returns
the first SedStyle in this SedListOfStyles based on the given baseStyle attribute or NULL if no such SedStyle exists.
Referenced by getByBaseStyle().
getElementName()
const std::string & SedListOfStyles::getElementName () const virtual
Returns the XML element name of this SedListOfStyles object.
For SedListOfStyles, the XML element name is always "listOfStyles".
Returns
the name of this element, i.e. "listOfStyles".
Reimplemented from SedListOf.
getItemTypeCode()
int SedListOfStyles::getItemTypeCode () const virtual
Returns the libSEDML type code for the SED-ML objects contained in this SedListOfStyles object.
Returns
the SED-ML typecode for the objects contained in this SedListOfStyles: @sedmlconstant{SEDML_STYLE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedListOf.
References SEDML_STYLE.
getNumStyles()
unsigned int SedListOfStyles::getNumStyles () const
Get the number of SedStyle objects in this SedListOfStyles.
Returns
the number of SedStyle objects in this SedListOfStyles.
See also
addStyle(const SedStyle* object)
createStyle()
get(const std::string& sid)
get(unsigned int n)
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::size().
getTypeCode()
int SedListOfStyles::getTypeCode () const virtual
Returns the libSEDML type code for this SedListOfStyles object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Reimplemented from SedListOf.
References SEDML_LIST_OF.
operator=()
SedListOfStyles & SedListOfStyles::operator= (const SedListOfStyles & rhs)
Assignment operator for SedListOfStyles.
Parameters
rhs the SedListOfStyles object whose values are to be used as the basis of the assignment.
References SedListOf::operator=().
remove() [1/2]
SedStyle * SedListOfStyles::remove (const std::string & sid) virtual
Removes the SedStyle from this SedListOfStyles based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedStyle to remove.
Returns
the SedStyle in this SedListOfStyles based on the identifier or NULL if no such SedStyle exists.
See also
addStyle(const SedStyle* object)
createStyle()
get(const std::string& sid)
get(unsigned int n)
getNumStyles()
remove(unsigned int n)
remove() [2/2]
SedStyle * SedListOfStyles::remove (unsigned int n) virtual
Removes the nth SedStyle from this SedListOfStyles and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedStyle to remove.
Returns
a pointer to the nth SedStyle in this SedListOfStyles.
See also
addStyle(const SedStyle* object)
createStyle()
get(const std::string& sid)
get(unsigned int n)
getNumStyles()
remove(const std::string& sid)
Reimplemented from SedListOf.
References SedListOf::remove().
The documentation for this class was generated from the following files:
SedListOfStyles.h
SedListOfStyles.cpp