LIBSEDML API: SedDocument Class Reference
SedDocument Class Reference
#include <SedDocument.h>
Public Member Functions
int addAlgorithmParameter (const SedAlgorithmParameter *sap)
int addDataDescription (const SedDataDescription *sdd)
int addDataGenerator (const SedDataGenerator *sdg)
int addModel (const SedModel *sm)
int addOutput (const SedOutput *so)
int addSimulation (const SedSimulation *ss)
int addStyle (const SedStyle *ss)
int addTask (const SedAbstractTask *sat)
virtual SedDocument * clone () const
SedAlgorithmParameter * createAlgorithmParameter ()
SedAnalysis * createAnalysis ()
SedDataDescription * createDataDescription ()
SedDataGenerator * createDataGenerator ()
SedFigure * createFigure ()
SedModel * createModel ()
SedOneStep * createOneStep ()
SedParameterEstimationResultPlot * createParameterEstimationResultPlot ()
SedParameterEstimationTask * createParameterEstimationTask ()
SedPlot2D * createPlot2D ()
SedPlot3D * createPlot3D ()
SedRepeatedTask * createRepeatedTask ()
SedReport * createReport ()
SedSteadyState * createSteadyState ()
SedStyle * createStyle ()
SedTask * createTask ()
SedUniformTimeCourse * createUniformTimeCourse ()
SedAlgorithmParameter * getAlgorithmParameter (const std::string &id)
const SedAlgorithmParameter * getAlgorithmParameter (const std::string &id) const
SedAlgorithmParameter * getAlgorithmParameter (unsigned int n)
const SedAlgorithmParameter * getAlgorithmParameter (unsigned int n) const
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedDataDescription * getDataDescription (const std::string &sid)
const SedDataDescription * getDataDescription (const std::string &sid) const
SedDataDescription * getDataDescription (unsigned int n)
const SedDataDescription * getDataDescription (unsigned int n) const
SedDataGenerator * getDataGenerator (const std::string &sid)
const SedDataGenerator * getDataGenerator (const std::string &sid) const
SedDataGenerator * getDataGenerator (unsigned int n)
const SedDataGenerator * getDataGenerator (unsigned int n) const
SedStyle getEffectiveStyle (const std::string &sid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedError * getError (unsigned int n)
const SedError * getError (unsigned int n) const
SedErrorLog * getErrorLog ()
const SedErrorLog * getErrorLog () const
unsigned int getLevel () const
SedListOfAlgorithmParameters * getListOfAlgorithmParameters ()
const SedListOfAlgorithmParameters * getListOfAlgorithmParameters () const
SedListOfDataDescriptions * getListOfDataDescriptions ()
const SedListOfDataDescriptions * getListOfDataDescriptions () const
SedListOfDataGenerators * getListOfDataGenerators ()
const SedListOfDataGenerators * getListOfDataGenerators () const
SedListOfModels * getListOfModels ()
const SedListOfModels * getListOfModels () const
SedListOfOutputs * getListOfOutputs ()
const SedListOfOutputs * getListOfOutputs () const
SedListOfSimulations * getListOfSimulations ()
const SedListOfSimulations * getListOfSimulations () const
SedListOfStyles * getListOfStyles ()
const SedListOfStyles * getListOfStyles () const
SedListOfTasks * getListOfTasks ()
const SedListOfTasks * getListOfTasks () const
SedModel * getModel (const std::string &sid)
const SedModel * getModel (const std::string &sid) const
SedModel * getModel (unsigned int n)
const SedModel * getModel (unsigned int n) const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
unsigned int getNumAlgorithmParameters () const
unsigned int getNumDataDescriptions () const
unsigned int getNumDataGenerators () const
unsigned int getNumErrors () const
unsigned int getNumErrors (unsigned int severity) const
unsigned int getNumModels () const
unsigned int getNumOutputs () const
unsigned int getNumSimulations () const
unsigned int getNumStyles () const
unsigned int getNumTasks () const
SedOutput * getOutput (const std::string &sid)
const SedOutput * getOutput (const std::string &sid) const
SedOutput * getOutput (unsigned int n)
const SedOutput * getOutput (unsigned int n) const
SedSimulation * getSimulation (const std::string &sid)
const SedSimulation * getSimulation (const std::string &sid) const
SedSimulation * getSimulation (unsigned int n)
const SedSimulation * getSimulation (unsigned int n) const
SedStyle * getStyle (const std::string &sid)
const SedStyle * getStyle (const std::string &sid) const
SedStyle * getStyle (unsigned int n)
const SedStyle * getStyle (unsigned int n) const
SedStyle * getStyleByBaseStyle (const std::string &sid)
const SedStyle * getStyleByBaseStyle (const std::string &sid) const
SedAbstractTask * getTask (const std::string &sid)
const SedAbstractTask * getTask (const std::string &sid) const
SedAbstractTask * getTask (unsigned int n)
const SedAbstractTask * getTask (unsigned int n) const
virtual int getTypeCode () const
unsigned int getVersion () const
virtual bool hasRequiredAttributes () const
bool isSetLevel () const
bool isSetVersion () const
SedDocument & operator= (const SedDocument &rhs)
SedAlgorithmParameter * removeAlgorithmParameter (const std::string &id)
SedAlgorithmParameter * removeAlgorithmParameter (unsigned int n)
SedDataDescription * removeDataDescription (const std::string &sid)
SedDataDescription * removeDataDescription (unsigned int n)
SedDataGenerator * removeDataGenerator (const std::string &sid)
SedDataGenerator * removeDataGenerator (unsigned int n)
SedModel * removeModel (const std::string &sid)
SedModel * removeModel (unsigned int n)
SedOutput * removeOutput (const std::string &sid)
SedOutput * removeOutput (unsigned int n)
SedSimulation * removeSimulation (const std::string &sid)
SedSimulation * removeSimulation (unsigned int n)
SedStyle * removeStyle (const std::string &sid)
SedStyle * removeStyle (unsigned int n)
SedAbstractTask * removeTask (const std::string &sid)
SedAbstractTask * removeTask (unsigned int n)
SedDocument (const SedDocument &orig)
SedDocument (SedNamespaces *sedmlns)
SedDocument (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setLevel (unsigned int level)
int setVersion (unsigned int version)
void sortOrderedObjects ()
int unsetLevel ()
int unsetVersion ()
virtual ~SedDocument ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedDocument class.
Constructor & Destructor Documentation
SedDocument() [1/3]
SedDocument::SedDocument (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedDocument using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedDocument.
version an unsigned int, the SED-ML Version to assign to this SedDocument.
Referenced by clone().
SedDocument() [2/3]
SedDocument::SedDocument (SedNamespaces * sedmlns)
Creates a new SedDocument using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedDocument() [3/3]
SedDocument::SedDocument (const SedDocument & orig)
Copy constructor for SedDocument.
Parameters
orig the SedDocument instance to copy.
~SedDocument()
SedDocument::~SedDocument () virtual
Destructor for SedDocument.
Member Function Documentation
addAlgorithmParameter()
int SedDocument::addAlgorithmParameter (const SedAlgorithmParameter * sap)
Adds a copy of the given SedAlgorithmParameter to this SedDocument.
Parameters
sap the SedAlgorithmParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
References SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedAlgorithmParameter::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addDataDescription()
int SedDocument::addDataDescription (const SedDataDescription * sdd)
Adds a copy of the given SedDataDescription to this SedDocument.
Parameters
sdd the SedDataDescription object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createDataDescription()
getDataDescription(const std::string& sid)
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedDataDescription::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addDataGenerator()
int SedDocument::addDataGenerator (const SedDataGenerator * sdg)
Adds a copy of the given SedDataGenerator to this SedDocument.
Parameters
sdg the SedDataGenerator object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createDataGenerator()
getDataGenerator(const std::string& sid)
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedDataGenerator::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addModel()
int SedDocument::addModel (const SedModel * sm)
Adds a copy of the given SedModel to this SedDocument.
Parameters
sm the SedModel object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createModel()
getModel(const std::string& sid)
getModel(unsigned int n)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedModel::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addOutput()
int SedDocument::addOutput (const SedOutput * so)
Adds a copy of the given SedOutput to this SedDocument.
Parameters
so the SedOutput object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createOutput()
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedOutput::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addSimulation()
int SedDocument::addSimulation (const SedSimulation * ss)
Adds a copy of the given SedSimulation to this SedDocument.
Parameters
ss the SedSimulation object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createSimulation()
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedSimulation::hasRequiredAttributes(), SedSimulation::hasRequiredElements(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addStyle()
int SedDocument::addStyle (const SedStyle * ss)
Adds a copy of the given SedStyle to this SedDocument.
Parameters
ss the SedStyle object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createStyle()
getStyle(const std::string& sid)
getStyle(unsigned int n)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedStyle::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addTask()
int SedDocument::addTask (const SedAbstractTask * sat)
Adds a copy of the given SedAbstractTask to this SedDocument.
Parameters
sat the SedAbstractTask object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createTask()
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), getLevel(), SedBase::getVersion(), getVersion(), SedAbstractTask::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedDocument * SedDocument::clone () const virtual
Creates and returns a deep copy of this SedDocument object.
Returns
a (deep) copy of this SedDocument object.
Implements SedBase.
References SedDocument().
createAlgorithmParameter()
SedAlgorithmParameter * SedDocument::createAlgorithmParameter ()
Creates a new SedAlgorithmParameter object, adds it to this SedDocument object and returns the SedAlgorithmParameter object created.
Returns
a new SedAlgorithmParameter object instance.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
References getLevel(), and getVersion().
createAnalysis()
SedAnalysis * SedDocument::createAnalysis ()
Creates a new SedAnalysis object, adds it to this SedDocument object and returns the SedAnalysis object created.
Returns
a new SedAnalysis object instance.
See also
addSimulation(const SedSimulation* object)
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
createDataDescription()
SedDataDescription * SedDocument::createDataDescription ()
Creates a new SedDataDescription object, adds it to this SedDocument object and returns the SedDataDescription object created.
Returns
a new SedDataDescription object instance.
See also
addDataDescription(const SedDataDescription* object)
getDataDescription(const std::string& sid)
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
createDataGenerator()
SedDataGenerator * SedDocument::createDataGenerator ()
Creates a new SedDataGenerator object, adds it to this SedDocument object and returns the SedDataGenerator object created.
Returns
a new SedDataGenerator object instance.
See also
addDataGenerator(const SedDataGenerator* object)
getDataGenerator(const std::string& sid)
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
createFigure()
SedFigure * SedDocument::createFigure ()
Creates a new SedFigure object, adds it to this SedDocument object and returns the SedFigure object created.
Returns
a new SedFigure object instance.
See also
addOutput(const SedOutput* object)
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
createModel()
SedModel * SedDocument::createModel ()
Creates a new SedModel object, adds it to this SedDocument object and returns the SedModel object created.
Returns
a new SedModel object instance.
See also
addModel(const SedModel* object)
getModel(const std::string& sid)
getModel(unsigned int n)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
createOneStep()
SedOneStep * SedDocument::createOneStep ()
Creates a new SedOneStep object, adds it to this SedDocument object and returns the SedOneStep object created.
Returns
a new SedOneStep object instance.
See also
addSimulation(const SedSimulation* object)
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
createParameterEstimationResultPlot()
SedParameterEstimationResultPlot * SedDocument::createParameterEstimationResultPlot ()
Creates a new SedParameterEstimationResultPlot object, adds it to this SedDocument object and returns the SedParameterEstimationResultPlot object created.
Returns
a new SedParameterEstimationResultPlot object instance.
See also
addOutput(const SedOutput* object)
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
createParameterEstimationTask()
SedParameterEstimationTask * SedDocument::createParameterEstimationTask ()
Creates a new SedParameterEstimationTask object, adds it to this SedDocument object and returns the SedParameterEstimationTask object created.
Returns
a new SedParameterEstimationTask object instance.
See also
addTask(const SedAbstractTask* object)
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
createPlot2D()
SedPlot2D * SedDocument::createPlot2D ()
Creates a new SedPlot2D object, adds it to this SedDocument object and returns the SedPlot2D object created.
Returns
a new SedPlot2D object instance.
See also
addOutput(const SedOutput* object)
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
createPlot3D()
SedPlot3D * SedDocument::createPlot3D ()
Creates a new SedPlot3D object, adds it to this SedDocument object and returns the SedPlot3D object created.
Returns
a new SedPlot3D object instance.
See also
addOutput(const SedOutput* object)
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
createRepeatedTask()
SedRepeatedTask * SedDocument::createRepeatedTask ()
Creates a new SedRepeatedTask object, adds it to this SedDocument object and returns the SedRepeatedTask object created.
Returns
a new SedRepeatedTask object instance.
See also
addTask(const SedAbstractTask* object)
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
createReport()
SedReport * SedDocument::createReport ()
Creates a new SedReport object, adds it to this SedDocument object and returns the SedReport object created.
Returns
a new SedReport object instance.
See also
addOutput(const SedOutput* object)
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
createSteadyState()
SedSteadyState * SedDocument::createSteadyState ()
Creates a new SedSteadyState object, adds it to this SedDocument object and returns the SedSteadyState object created.
Returns
a new SedSteadyState object instance.
See also
addSimulation(const SedSimulation* object)
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
createStyle()
SedStyle * SedDocument::createStyle ()
Creates a new SedStyle object, adds it to this SedDocument object and returns the SedStyle object created.
Returns
a new SedStyle object instance.
See also
addStyle(const SedStyle* object)
getStyle(const std::string& sid)
getStyle(unsigned int n)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
createTask()
SedTask * SedDocument::createTask ()
Creates a new SedTask object, adds it to this SedDocument object and returns the SedTask object created.
Returns
a new SedTask object instance.
See also
addTask(const SedAbstractTask* object)
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
createUniformTimeCourse()
SedUniformTimeCourse * SedDocument::createUniformTimeCourse ()
Creates a new SedUniformTimeCourse object, adds it to this SedDocument object and returns the SedUniformTimeCourse object created.
Returns
a new SedUniformTimeCourse object instance.
See also
addSimulation(const SedSimulation* object)
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getAlgorithmParameter() [1/4]
SedAlgorithmParameter * SedDocument::getAlgorithmParameter (const std::string & id)
Get a SedAlgorithmParameter from the SedDocument.
Parameters
id id of the SedAlgorithmParameter to retrieve.
Returns
the SedAlgorithmParameter in the SedListOfAlgorithmParameters within this SedDocument or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAlgorithmParameter() [2/4]
const SedAlgorithmParameter * SedDocument::getAlgorithmParameter (const std::string & id) const
Get a SedAlgorithmParameter from the SedDocument.
Parameters
id id of the SedAlgorithmParameter to retrieve.
Returns
the SedAlgorithmParameter in the SedListOfAlgorithmParameters within this SedDocument or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAlgorithmParameter() [3/4]
SedAlgorithmParameter * SedDocument::getAlgorithmParameter (unsigned int n)
Get a SedAlgorithmParameter from the SedDocument.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in the SedListOfAlgorithmParameters within this SedDocument or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAlgorithmParameter() [4/4]
const SedAlgorithmParameter * SedDocument::getAlgorithmParameter (unsigned int n) const
Get a SedAlgorithmParameter from the SedDocument.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in the SedListOfAlgorithmParameters within this SedDocument or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAllElements()
List * SedDocument::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getDataDescription() [1/4]
SedDataDescription * SedDocument::getDataDescription (const std::string & sid)
Get a SedDataDescription from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedDataDescription to retrieve.
Returns
the SedDataDescription in the SedListOfDataDescriptions within this SedDocument with the given sid or NULL if no such SedDataDescription exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
getDataDescription() [2/4]
const SedDataDescription * SedDocument::getDataDescription (const std::string & sid) const
Get a SedDataDescription from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedDataDescription to retrieve.
Returns
the SedDataDescription in the SedListOfDataDescriptions within this SedDocument with the given sid or NULL if no such SedDataDescription exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
getDataDescription() [3/4]
SedDataDescription * SedDocument::getDataDescription (unsigned int n)
Get a SedDataDescription from the SedDocument.
Parameters
n an unsigned int representing the index of the SedDataDescription to retrieve.
Returns
the nth SedDataDescription in the SedListOfDataDescriptions within this SedDocument or NULL if no such object exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(const std::string& sid)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
getDataDescription() [4/4]
const SedDataDescription * SedDocument::getDataDescription (unsigned int n) const
Get a SedDataDescription from the SedDocument.
Parameters
n an unsigned int representing the index of the SedDataDescription to retrieve.
Returns
the nth SedDataDescription in the SedListOfDataDescriptions within this SedDocument or NULL if no such object exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(const std::string& sid)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
getDataGenerator() [1/4]
SedDataGenerator * SedDocument::getDataGenerator (const std::string & sid)
Get a SedDataGenerator from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedDataGenerator to retrieve.
Returns
the SedDataGenerator in the SedListOfDataGenerators within this SedDocument with the given sid or NULL if no such SedDataGenerator exists.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
getDataGenerator() [2/4]
const SedDataGenerator * SedDocument::getDataGenerator (const std::string & sid) const
Get a SedDataGenerator from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedDataGenerator to retrieve.
Returns
the SedDataGenerator in the SedListOfDataGenerators within this SedDocument with the given sid or NULL if no such SedDataGenerator exists.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
getDataGenerator() [3/4]
SedDataGenerator * SedDocument::getDataGenerator (unsigned int n)
Get a SedDataGenerator from the SedDocument.
Parameters
n an unsigned int representing the index of the SedDataGenerator to retrieve.
Returns
the nth SedDataGenerator in the SedListOfDataGenerators within this SedDocument or NULL if no such object exists.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(const std::string& sid)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
getDataGenerator() [4/4]
const SedDataGenerator * SedDocument::getDataGenerator (unsigned int n) const
Get a SedDataGenerator from the SedDocument.
Parameters
n an unsigned int representing the index of the SedDataGenerator to retrieve.
Returns
the nth SedDataGenerator in the SedListOfDataGenerators within this SedDocument or NULL if no such object exists.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(const std::string& sid)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
getEffectiveStyle()
SedStyle SedDocument::getEffectiveStyle (const std::string & sid) const
Get the effecive SedStyle from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedStyle to retrieve.
Returns
a new SedStyle based on the SedStyle in the SedListOfStyles, but changed so that any referenced styles are applied.
References SedStyle::getBaseStyle(), SedFill::getColor(), SedLine::getColor(), SedMarker::getFill(), SedStyle::getFillStyle(), SedBase::getId(), SedMarker::getLineColor(), SedStyle::getLineStyle(), SedMarker::getLineThickness(), SedStyle::getMarkerStyle(), SedBase::getName(), SedMarker::getSize(), SedLine::getThickness(), SedLine::getType(), SedMarker::getType(), SedStyle::isSetBaseStyle(), SedFill::isSetColor(), SedLine::isSetColor(), SedMarker::isSetFill(), SedStyle::isSetFillStyle(), SedMarker::isSetLineColor(), SedStyle::isSetLineStyle(), SedMarker::isSetLineThickness(), SedStyle::isSetMarkerStyle(), SedMarker::isSetSize(), SedLine::isSetThickness(), SedLine::isSetType(), SedMarker::isSetType(), SedFill::setColor(), SedLine::setColor(), SedMarker::setFill(), SedStyle::setFillStyle(), SedBase::setId(), SedMarker::setLineColor(), SedStyle::setLineStyle(), SedMarker::setLineThickness(), SedStyle::setMarkerStyle(), SedBase::setName(), SedMarker::setSize(), SedLine::setThickness(), SedLine::setType(), SedMarker::setType(), and SedStyle::unsetBaseStyle().
getElementBySId()
SedBase * SedDocument::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedDocument::getElementName () const virtual
Returns the XML element name of this SedDocument object.
For SedDocument, the XML element name is always "sedML".
Returns
the name of this element, i.e. "sedML".
Implements SedBase.
getError() [1/2]
SedError * SedDocument::getError (unsigned int n)
Get a SedError from the SedDocument.
Parameters
n an unsigned int representing the index of the SedError to retrieve.
Returns
the nth SedError within this SedDocument or NULL if no such object exists.
See also
getNumErrors()
getError() [2/2]
const SedError * SedDocument::getError (unsigned int n) const
Get a SedError from the SedDocument.
Parameters
n an unsigned int representing the index of the SedError to retrieve.
Returns
the nth SedError within this SedDocument or NULL if no such object exists.
See also
getNumErrors()
getErrorLog() [1/2]
SedErrorLog * SedDocument::getErrorLog ()
Returns the value of the "SedErrorLog" element of this SedDocument.
Returns
the value of the "SedErrorLog" element of this SedDocument as a SedErrorLog*.
getErrorLog() [2/2]
const SedErrorLog * SedDocument::getErrorLog () const
Returns the value of the "SedErrorLog" element of this SedDocument.
Returns
the value of the "SedErrorLog" element of this SedDocument as a SedErrorLog*.
Referenced by getNumErrors().
getLevel()
unsigned int SedDocument::getLevel () const
Returns the value of the "level" attribute of this SedDocument.
Returns
the value of the "level" attribute of this SedDocument as a unsigned integer.
Referenced by addAlgorithmParameter(), addDataDescription(), addDataGenerator(), addModel(), addOutput(), addSimulation(), addStyle(), addTask(), and createAlgorithmParameter().
getListOfAlgorithmParameters() [1/2]
SedListOfAlgorithmParameters * SedDocument::getListOfAlgorithmParameters ()
Returns the SedListOfAlgorithmParameters from this SedDocument.
Returns
the SedListOfAlgorithmParameters from this SedDocument.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getListOfAlgorithmParameters() [2/2]
const SedListOfAlgorithmParameters * SedDocument::getListOfAlgorithmParameters () const
Returns the SedListOfAlgorithmParameters from this SedDocument.
Returns
the SedListOfAlgorithmParameters from this SedDocument.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getListOfDataDescriptions() [1/2]
SedListOfDataDescriptions * SedDocument::getListOfDataDescriptions ()
Returns the SedListOfDataDescriptions from this SedDocument.
Returns
the SedListOfDataDescriptions from this SedDocument.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(const std::string& sid)
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
getListOfDataDescriptions() [2/2]
const SedListOfDataDescriptions * SedDocument::getListOfDataDescriptions () const
Returns the SedListOfDataDescriptions from this SedDocument.
Returns
the SedListOfDataDescriptions from this SedDocument.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(const std::string& sid)
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
getListOfDataGenerators() [1/2]
SedListOfDataGenerators * SedDocument::getListOfDataGenerators ()
Returns the SedListOfDataGenerators from this SedDocument.
Returns
the SedListOfDataGenerators from this SedDocument.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(const std::string& sid)
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
getListOfDataGenerators() [2/2]
const SedListOfDataGenerators * SedDocument::getListOfDataGenerators () const
Returns the SedListOfDataGenerators from this SedDocument.
Returns
the SedListOfDataGenerators from this SedDocument.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(const std::string& sid)
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
getListOfModels() [1/2]
SedListOfModels * SedDocument::getListOfModels ()
Returns the SedListOfModels from this SedDocument.
Returns
the SedListOfModels from this SedDocument.
See also
addModel(const SedModel* object)
createModel()
getModel(const std::string& sid)
getModel(unsigned int n)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
getListOfModels() [2/2]
const SedListOfModels * SedDocument::getListOfModels () const
Returns the SedListOfModels from this SedDocument.
Returns
the SedListOfModels from this SedDocument.
See also
addModel(const SedModel* object)
createModel()
getModel(const std::string& sid)
getModel(unsigned int n)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
getListOfOutputs() [1/2]
SedListOfOutputs * SedDocument::getListOfOutputs ()
Returns the SedListOfOutputs from this SedDocument.
Returns
the SedListOfOutputs from this SedDocument.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
getListOfOutputs() [2/2]
const SedListOfOutputs * SedDocument::getListOfOutputs () const
Returns the SedListOfOutputs from this SedDocument.
Returns
the SedListOfOutputs from this SedDocument.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
getListOfSimulations() [1/2]
SedListOfSimulations * SedDocument::getListOfSimulations ()
Returns the SedListOfSimulations from this SedDocument.
Returns
the SedListOfSimulations from this SedDocument.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getListOfSimulations() [2/2]
const SedListOfSimulations * SedDocument::getListOfSimulations () const
Returns the SedListOfSimulations from this SedDocument.
Returns
the SedListOfSimulations from this SedDocument.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getListOfStyles() [1/2]
SedListOfStyles * SedDocument::getListOfStyles ()
Returns the SedListOfStyles from this SedDocument.
Returns
the SedListOfStyles from this SedDocument.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(const std::string& sid)
getStyle(unsigned int n)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
getListOfStyles() [2/2]
const SedListOfStyles * SedDocument::getListOfStyles () const
Returns the SedListOfStyles from this SedDocument.
Returns
the SedListOfStyles from this SedDocument.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(const std::string& sid)
getStyle(unsigned int n)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
getListOfTasks() [1/2]
SedListOfTasks * SedDocument::getListOfTasks ()
Returns the SedListOfTasks from this SedDocument.
Returns
the SedListOfTasks from this SedDocument.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
getListOfTasks() [2/2]
const SedListOfTasks * SedDocument::getListOfTasks () const
Returns the SedListOfTasks from this SedDocument.
Returns
the SedListOfTasks from this SedDocument.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
getModel() [1/4]
SedModel * SedDocument::getModel (const std::string & sid)
Get a SedModel from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedModel to retrieve.
Returns
the SedModel in the SedListOfModels within this SedDocument with the given sid or NULL if no such SedModel exists.
See also
addModel(const SedModel* object)
createModel()
getModel(unsigned int n)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
getModel() [2/4]
const SedModel * SedDocument::getModel (const std::string & sid) const
Get a SedModel from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedModel to retrieve.
Returns
the SedModel in the SedListOfModels within this SedDocument with the given sid or NULL if no such SedModel exists.
See also
addModel(const SedModel* object)
createModel()
getModel(unsigned int n)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
getModel() [3/4]
SedModel * SedDocument::getModel (unsigned int n)
Get a SedModel from the SedDocument.
Parameters
n an unsigned int representing the index of the SedModel to retrieve.
Returns
the nth SedModel in the SedListOfModels within this SedDocument or NULL if no such object exists.
See also
addModel(const SedModel* object)
createModel()
getModel(const std::string& sid)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
getModel() [4/4]
const SedModel * SedDocument::getModel (unsigned int n) const
Get a SedModel from the SedDocument.
Parameters
n an unsigned int representing the index of the SedModel to retrieve.
Returns
the nth SedModel in the SedListOfModels within this SedDocument or NULL if no such object exists.
See also
addModel(const SedModel* object)
createModel()
getModel(const std::string& sid)
getNumModels()
removeModel(const std::string& sid)
removeModel(unsigned int n)
getNamespaces() [1/2]
XMLNamespaces * SedDocument::getNamespaces () virtual
Returns the value of the "Namespaces" element of this SedDocument.
Returns
the value of the "Namespaces" element of this SedDocument as a LIBSBML_CPP_NAMESPACE_QUALIFIER XMLNamespaces*.
Reimplemented from SedBase.
getNamespaces() [2/2]
const XMLNamespaces * SedDocument::getNamespaces () const virtual
Returns the value of the "Namespaces" element of this SedDocument.
Returns
the value of the "Namespaces" element of this SedDocument as a LIBSBML_CPP_NAMESPACE_QUALIFIER XMLNamespaces*.
Reimplemented from SedBase.
Referenced by SedBase::appendAnnotation(), SedBase::appendNotes(), SedBase::replaceTopLevelAnnotationElement(), SedBase::setAnnotation(), and SedBase::setNotes().
getNumAlgorithmParameters()
unsigned int SedDocument::getNumAlgorithmParameters () const
Get the number of SedAlgorithmParameter objects in this SedDocument.
Returns
the number of SedAlgorithmParameter objects in this SedDocument.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getNumDataDescriptions()
unsigned int SedDocument::getNumDataDescriptions () const
Get the number of SedDataDescription objects in this SedDocument.
Returns
the number of SedDataDescription objects in this SedDocument.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(const std::string& sid)
getDataDescription(unsigned int n)
removeDataDescription(const std::string& sid)
removeDataDescription(unsigned int n)
getNumDataGenerators()
unsigned int SedDocument::getNumDataGenerators () const
Get the number of SedDataGenerator objects in this SedDocument.
Returns
the number of SedDataGenerator objects in this SedDocument.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(const std::string& sid)
getDataGenerator(unsigned int n)
removeDataGenerator(const std::string& sid)
removeDataGenerator(unsigned int n)
getNumErrors() [1/2]
unsigned int SedDocument::getNumErrors () const
Get the number of SedError objects in this SedDocument.
Returns
the number of SedError objects in this SedDocument.
See also
getError(unsigned int n)
getNumErrors() [2/2]
unsigned int SedDocument::getNumErrors (unsigned int severity) const
Get the number of SedError objects in this SedDocument with the given severity.
Parameters
severity the severity of the SedError to return.
Returns
the number of SedError objects in this SedDocument.
See also
getError(unsigned int n)
References getErrorLog(), and SedErrorLog::getNumFailsWithSeverity().
getNumModels()
unsigned int SedDocument::getNumModels () const
Get the number of SedModel objects in this SedDocument.
Returns
the number of SedModel objects in this SedDocument.
See also
addModel(const SedModel* object)
createModel()
getModel(const std::string& sid)
getModel(unsigned int n)
removeModel(const std::string& sid)
removeModel(unsigned int n)
getNumOutputs()
unsigned int SedDocument::getNumOutputs () const
Get the number of SedOutput objects in this SedDocument.
Returns
the number of SedOutput objects in this SedDocument.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(const std::string& sid)
getOutput(unsigned int n)
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
getNumSimulations()
unsigned int SedDocument::getNumSimulations () const
Get the number of SedSimulation objects in this SedDocument.
Returns
the number of SedSimulation objects in this SedDocument.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getNumStyles()
unsigned int SedDocument::getNumStyles () const
Get the number of SedStyle objects in this SedDocument.
Returns
the number of SedStyle objects in this SedDocument.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(const std::string& sid)
getStyle(unsigned int n)
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
getNumTasks()
unsigned int SedDocument::getNumTasks () const
Get the number of SedAbstractTask objects in this SedDocument.
Returns
the number of SedAbstractTask objects in this SedDocument.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(const std::string& sid)
getTask(unsigned int n)
removeTask(const std::string& sid)
removeTask(unsigned int n)
getOutput() [1/4]
SedOutput * SedDocument::getOutput (const std::string & sid)
Get a SedOutput from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedOutput to retrieve.
Returns
the SedOutput in the SedListOfOutputs within this SedDocument with the given sid or NULL if no such SedOutput exists.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
getOutput() [2/4]
const SedOutput * SedDocument::getOutput (const std::string & sid) const
Get a SedOutput from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedOutput to retrieve.
Returns
the SedOutput in the SedListOfOutputs within this SedDocument with the given sid or NULL if no such SedOutput exists.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
getOutput() [3/4]
SedOutput * SedDocument::getOutput (unsigned int n)
Get a SedOutput from the SedDocument.
Parameters
n an unsigned int representing the index of the SedOutput to retrieve.
Returns
the nth SedOutput in the SedListOfOutputs within this SedDocument or NULL if no such object exists.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(const std::string& sid)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
getOutput() [4/4]
const SedOutput * SedDocument::getOutput (unsigned int n) const
Get a SedOutput from the SedDocument.
Parameters
n an unsigned int representing the index of the SedOutput to retrieve.
Returns
the nth SedOutput in the SedListOfOutputs within this SedDocument or NULL if no such object exists.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(const std::string& sid)
getNumOutputs()
removeOutput(const std::string& sid)
removeOutput(unsigned int n)
getSimulation() [1/4]
SedSimulation * SedDocument::getSimulation (const std::string & sid)
Get a SedSimulation from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedSimulation to retrieve.
Returns
the SedSimulation in the SedListOfSimulations within this SedDocument with the given sid or NULL if no such SedSimulation exists.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getSimulation() [2/4]
const SedSimulation * SedDocument::getSimulation (const std::string & sid) const
Get a SedSimulation from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedSimulation to retrieve.
Returns
the SedSimulation in the SedListOfSimulations within this SedDocument with the given sid or NULL if no such SedSimulation exists.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getSimulation() [3/4]
SedSimulation * SedDocument::getSimulation (unsigned int n)
Get a SedSimulation from the SedDocument.
Parameters
n an unsigned int representing the index of the SedSimulation to retrieve.
Returns
the nth SedSimulation in the SedListOfSimulations within this SedDocument or NULL if no such object exists.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(const std::string& sid)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getSimulation() [4/4]
const SedSimulation * SedDocument::getSimulation (unsigned int n) const
Get a SedSimulation from the SedDocument.
Parameters
n an unsigned int representing the index of the SedSimulation to retrieve.
Returns
the nth SedSimulation in the SedListOfSimulations within this SedDocument or NULL if no such object exists.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(const std::string& sid)
getNumSimulations()
removeSimulation(const std::string& sid)
removeSimulation(unsigned int n)
getStyle() [1/4]
SedStyle * SedDocument::getStyle (const std::string & sid)
Get a SedStyle from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedStyle to retrieve.
Returns
the SedStyle in the SedListOfStyles within this SedDocument with the given sid or NULL if no such SedStyle exists.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(unsigned int n)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
getStyle() [2/4]
const SedStyle * SedDocument::getStyle (const std::string & sid) const
Get a SedStyle from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedStyle to retrieve.
Returns
the SedStyle in the SedListOfStyles within this SedDocument with the given sid or NULL if no such SedStyle exists.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(unsigned int n)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
getStyle() [3/4]
SedStyle * SedDocument::getStyle (unsigned int n)
Get a SedStyle from the SedDocument.
Parameters
n an unsigned int representing the index of the SedStyle to retrieve.
Returns
the nth SedStyle in the SedListOfStyles within this SedDocument or NULL if no such object exists.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(const std::string& sid)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
getStyle() [4/4]
const SedStyle * SedDocument::getStyle (unsigned int n) const
Get a SedStyle from the SedDocument.
Parameters
n an unsigned int representing the index of the SedStyle to retrieve.
Returns
the nth SedStyle in the SedListOfStyles within this SedDocument or NULL if no such object exists.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(const std::string& sid)
getNumStyles()
removeStyle(const std::string& sid)
removeStyle(unsigned int n)
getStyleByBaseStyle() [1/2]
SedStyle * SedDocument::getStyleByBaseStyle (const std::string & sid)
Get a SedStyle from the SedDocument based on the BaseStyle to which it refers.
Parameters
sid a string representing the "baseStyle" attribute of the SedStyle object to retrieve.
Returns
the first SedStyle in this SedDocument based on the given baseStyle attribute or NULL if no such SedStyle exists.
getStyleByBaseStyle() [2/2]
const SedStyle * SedDocument::getStyleByBaseStyle (const std::string & sid) const
Get a SedStyle from the SedDocument based on the BaseStyle to which it refers.
Parameters
sid a string representing the "baseStyle" attribute of the SedStyle object to retrieve.
Returns
the first SedStyle in this SedDocument based on the given baseStyle attribute or NULL if no such SedStyle exists.
getTask() [1/4]
SedAbstractTask * SedDocument::getTask (const std::string & sid)
Get a SedAbstractTask from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedAbstractTask to retrieve.
Returns
the SedAbstractTask in the SedListOfTasks within this SedDocument with the given sid or NULL if no such SedAbstractTask exists.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
getTask() [2/4]
const SedAbstractTask * SedDocument::getTask (const std::string & sid) const
Get a SedAbstractTask from the SedDocument based on its identifier.
Parameters
sid a string representing the identifier of the SedAbstractTask to retrieve.
Returns
the SedAbstractTask in the SedListOfTasks within this SedDocument with the given sid or NULL if no such SedAbstractTask exists.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
getTask() [3/4]
SedAbstractTask * SedDocument::getTask (unsigned int n)
Get a SedAbstractTask from the SedDocument.
Parameters
n an unsigned int representing the index of the SedAbstractTask to retrieve.
Returns
the nth SedAbstractTask in the SedListOfTasks within this SedDocument or NULL if no such object exists.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(const std::string& sid)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
getTask() [4/4]
const SedAbstractTask * SedDocument::getTask (unsigned int n) const
Get a SedAbstractTask from the SedDocument.
Parameters
n an unsigned int representing the index of the SedAbstractTask to retrieve.
Returns
the nth SedAbstractTask in the SedListOfTasks within this SedDocument or NULL if no such object exists.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(const std::string& sid)
getNumTasks()
removeTask(const std::string& sid)
removeTask(unsigned int n)
getTypeCode()
int SedDocument::getTypeCode () const virtual
Returns the libSEDML type code for this SedDocument object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_DOCUMENT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_DOCUMENT.
getVersion()
unsigned int SedDocument::getVersion () const
Returns the value of the "version" attribute of this SedDocument.
Returns
the value of the "version" attribute of this SedDocument as a unsigned integer.
Referenced by addAlgorithmParameter(), addDataDescription(), addDataGenerator(), addModel(), addOutput(), addSimulation(), addStyle(), addTask(), and createAlgorithmParameter().
hasRequiredAttributes()
bool SedDocument::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedDocument object have been set.
Returns
true to indicate that all the required attributes of this SedDocument have been set, otherwise false is returned.
Note
The required attributes for the SedDocument object are:
"level"
"version"
References isSetLevel(), and isSetVersion().
isSetLevel()
bool SedDocument::isSetLevel () const
Predicate returning true if this SedDocument's "level" attribute is set.
Returns
true if this SedDocument's "level" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
isSetVersion()
bool SedDocument::isSetVersion () const
Predicate returning true if this SedDocument's "version" attribute is set.
Returns
true if this SedDocument's "version" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedDocument & SedDocument::operator= (const SedDocument & rhs)
Assignment operator for SedDocument.
Parameters
rhs the SedDocument object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
removeAlgorithmParameter() [1/2]
SedAlgorithmParameter * SedDocument::removeAlgorithmParameter (const std::string & id)
Removes the SedAlgorithmParameter with the given id from this SedAlgorithm and returns a pointer to it.
Parameters
id a string representing the id of the SedAlgorithmParameter to remove.
Returns
a pointer to the nth SedAlgorithmParameter in this SedAlgorithm.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter() [2/2]
SedAlgorithmParameter * SedDocument::removeAlgorithmParameter (unsigned int n)
Removes the nth SedAlgorithmParameter from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to remove.
Returns
a pointer to the nth SedAlgorithmParameter in this SedDocument.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeDataDescription() [1/2]
SedDataDescription * SedDocument::removeDataDescription (const std::string & sid)
Removes the SedDataDescription from this SedDocument based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedDataDescription to remove.
Returns
the SedDataDescription in this SedDocument based on the identifier or NULL if no such SedDataDescription exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(const std::string& sid)
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(unsigned int n)
removeDataDescription() [2/2]
SedDataDescription * SedDocument::removeDataDescription (unsigned int n)
Removes the nth SedDataDescription from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedDataDescription to remove.
Returns
a pointer to the nth SedDataDescription in this SedDocument.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
getDataDescription(const std::string& sid)
getDataDescription(unsigned int n)
getNumDataDescriptions()
removeDataDescription(const std::string& sid)
removeDataGenerator() [1/2]
SedDataGenerator * SedDocument::removeDataGenerator (const std::string & sid)
Removes the SedDataGenerator from this SedDocument based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedDataGenerator to remove.
Returns
the SedDataGenerator in this SedDocument based on the identifier or NULL if no such SedDataGenerator exists.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(const std::string& sid)
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(unsigned int n)
removeDataGenerator() [2/2]
SedDataGenerator * SedDocument::removeDataGenerator (unsigned int n)
Removes the nth SedDataGenerator from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedDataGenerator to remove.
Returns
a pointer to the nth SedDataGenerator in this SedDocument.
See also
addDataGenerator(const SedDataGenerator* object)
createDataGenerator()
getDataGenerator(const std::string& sid)
getDataGenerator(unsigned int n)
getNumDataGenerators()
removeDataGenerator(const std::string& sid)
removeModel() [1/2]
SedModel * SedDocument::removeModel (const std::string & sid)
Removes the SedModel from this SedDocument based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedModel to remove.
Returns
the SedModel in this SedDocument based on the identifier or NULL if no such SedModel exists.
See also
addModel(const SedModel* object)
createModel()
getModel(const std::string& sid)
getModel(unsigned int n)
getNumModels()
removeModel(unsigned int n)
removeModel() [2/2]
SedModel * SedDocument::removeModel (unsigned int n)
Removes the nth SedModel from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedModel to remove.
Returns
a pointer to the nth SedModel in this SedDocument.
See also
addModel(const SedModel* object)
createModel()
getModel(const std::string& sid)
getModel(unsigned int n)
getNumModels()
removeModel(const std::string& sid)
removeOutput() [1/2]
SedOutput * SedDocument::removeOutput (const std::string & sid)
Removes the SedOutput from this SedDocument based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedOutput to remove.
Returns
the SedOutput in this SedDocument based on the identifier or NULL if no such SedOutput exists.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(unsigned int n)
removeOutput() [2/2]
SedOutput * SedDocument::removeOutput (unsigned int n)
Removes the nth SedOutput from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedOutput to remove.
Returns
a pointer to the nth SedOutput in this SedDocument.
See also
addOutput(const SedOutput* object)
createOutput()
getOutput(const std::string& sid)
getOutput(unsigned int n)
getNumOutputs()
removeOutput(const std::string& sid)
removeSimulation() [1/2]
SedSimulation * SedDocument::removeSimulation (const std::string & sid)
Removes the SedSimulation from this SedDocument based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedSimulation to remove.
Returns
the SedSimulation in this SedDocument based on the identifier or NULL if no such SedSimulation exists.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(unsigned int n)
removeSimulation() [2/2]
SedSimulation * SedDocument::removeSimulation (unsigned int n)
Removes the nth SedSimulation from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSimulation to remove.
Returns
a pointer to the nth SedSimulation in this SedDocument.
See also
addSimulation(const SedSimulation* object)
createSimulation()
getSimulation(const std::string& sid)
getSimulation(unsigned int n)
getNumSimulations()
removeSimulation(const std::string& sid)
removeStyle() [1/2]
SedStyle * SedDocument::removeStyle (const std::string & sid)
Removes the SedStyle from this SedDocument based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedStyle to remove.
Returns
the SedStyle in this SedDocument based on the identifier or NULL if no such SedStyle exists.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(const std::string& sid)
getStyle(unsigned int n)
getNumStyles()
removeStyle(unsigned int n)
removeStyle() [2/2]
SedStyle * SedDocument::removeStyle (unsigned int n)
Removes the nth SedStyle from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedStyle to remove.
Returns
a pointer to the nth SedStyle in this SedDocument.
See also
addStyle(const SedStyle* object)
createStyle()
getStyle(const std::string& sid)
getStyle(unsigned int n)
getNumStyles()
removeStyle(const std::string& sid)
removeTask() [1/2]
SedAbstractTask * SedDocument::removeTask (const std::string & sid)
Removes the SedAbstractTask from this SedDocument based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedAbstractTask to remove.
Returns
the SedAbstractTask in this SedDocument based on the identifier or NULL if no such SedAbstractTask exists.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(unsigned int n)
removeTask() [2/2]
SedAbstractTask * SedDocument::removeTask (unsigned int n)
Removes the nth SedAbstractTask from this SedDocument and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAbstractTask to remove.
Returns
a pointer to the nth SedAbstractTask in this SedDocument.
See also
addTask(const SedAbstractTask* object)
createTask()
getTask(const std::string& sid)
getTask(unsigned int n)
getNumTasks()
removeTask(const std::string& sid)
setLevel()
int SedDocument::setLevel (unsigned int level)
Sets the value of the "level" attribute of this SedDocument.
Parameters
level unsigned int value of the "level" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setVersion()
int SedDocument::setVersion (unsigned int version)
Sets the value of the "version" attribute of this SedDocument.
Parameters
version unsigned int value of the "version" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
sortOrderedObjects()
void SedDocument::sortOrderedObjects ()
Sort any SubTasks or Curves in the document according to their 'order' attributes.
References SedPlot2D::getListOfCurves(), SedRepeatedTask::getListOfSubTasks(), SedPlot3D::getListOfSurfaces(), SedAbstractTask::getTypeCode(), SedOutput::getTypeCode(), SEDML_OUTPUT_PLOT2D, SEDML_OUTPUT_PLOT3D, SEDML_TASK_REPEATEDTASK, SedListOfCurves::sort(), SedListOfSubTasks::sort(), and SedListOfSurfaces::sort().
unsetLevel()
int SedDocument::unsetLevel ()
Unsets the value of the "level" attribute of this SedDocument.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetVersion()
int SedDocument::unsetVersion ()
Unsets the value of the "version" attribute of this SedDocument.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
The documentation for this class was generated from the following files:
SedDocument.h
SedDocument.cpp