LIBSEDML API: SedAppliedDimension Class Reference
SedAppliedDimension Class Reference
#include <SedAppliedDimension.h>
Public Member Functions
virtual SedAppliedDimension * clone () const
const std::string & getDimensionTarget () const
virtual const std::string & getElementName () const
const std::string & getTarget () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetDimensionTarget () const
bool isSetTarget () const
SedAppliedDimension & operator= (const SedAppliedDimension &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedAppliedDimension (const SedAppliedDimension &orig)
SedAppliedDimension (SedNamespaces *sedmlns)
SedAppliedDimension (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setDimensionTarget (const std::string &dimensionTarget)
int setTarget (const std::string &target)
int unsetDimensionTarget ()
int unsetTarget ()
virtual ~SedAppliedDimension ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAppliedDimension class.
Constructor & Destructor Documentation
SedAppliedDimension() [1/3]
SedAppliedDimension::SedAppliedDimension (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAppliedDimension using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAppliedDimension.
version an unsigned int, the SED-ML Version to assign to this SedAppliedDimension.
Referenced by clone().
SedAppliedDimension() [2/3]
SedAppliedDimension::SedAppliedDimension (SedNamespaces * sedmlns)
Creates a new SedAppliedDimension using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedAppliedDimension() [3/3]
SedAppliedDimension::SedAppliedDimension (const SedAppliedDimension & orig)
Copy constructor for SedAppliedDimension.
Parameters
orig the SedAppliedDimension instance to copy.
~SedAppliedDimension()
SedAppliedDimension::~SedAppliedDimension () virtual
Destructor for SedAppliedDimension.
Member Function Documentation
clone()
SedAppliedDimension * SedAppliedDimension::clone () const virtual
Creates and returns a deep copy of this SedAppliedDimension object.
Returns
a (deep) copy of this SedAppliedDimension object.
Implements SedBase.
References SedAppliedDimension().
getDimensionTarget()
const std::string & SedAppliedDimension::getDimensionTarget () const
Returns the value of the "dimensionTarget" attribute of this SedAppliedDimension.
Returns
the value of the "dimensionTarget" attribute of this SedAppliedDimension as a string.
getElementName()
const std::string & SedAppliedDimension::getElementName () const virtual
Returns the XML element name of this SedAppliedDimension object.
For SedAppliedDimension, the XML element name is always "appliedDimension".
Returns
the name of this element, i.e. "appliedDimension".
Implements SedBase.
getTarget()
const std::string & SedAppliedDimension::getTarget () const
Returns the value of the "target" attribute of this SedAppliedDimension.
Returns
the value of the "target" attribute of this SedAppliedDimension as a string.
getTypeCode()
int SedAppliedDimension::getTypeCode () const virtual
Returns the libSEDML type code for this SedAppliedDimension object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_APPLIEDDIMENSION, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_APPLIEDDIMENSION.
hasRequiredAttributes()
bool SedAppliedDimension::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAppliedDimension object have been set.
Returns
true to indicate that all the required attributes of this SedAppliedDimension have been set, otherwise false is returned.
Referenced by SedVariable::addAppliedDimension(), and SedListOfAppliedDimensions::addAppliedDimension().
isSetDimensionTarget()
bool SedAppliedDimension::isSetDimensionTarget () const
Predicate returning true if this SedAppliedDimension's "dimensionTarget" attribute is set.
Returns
true if this SedAppliedDimension's "dimensionTarget" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetTarget()
bool SedAppliedDimension::isSetTarget () const
Predicate returning true if this SedAppliedDimension's "target" attribute is set.
Returns
true if this SedAppliedDimension's "target" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
operator=()
SedAppliedDimension & SedAppliedDimension::operator= (const SedAppliedDimension & rhs)
Assignment operator for SedAppliedDimension.
Parameters
rhs the SedAppliedDimension object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
renameSIdRefs()
void SedAppliedDimension::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetDimensionTarget(), isSetTarget(), setDimensionTarget(), and setTarget().
setDimensionTarget()
int SedAppliedDimension::setDimensionTarget (const std::string & dimensionTarget)
Sets the value of the "dimensionTarget" attribute of this SedAppliedDimension.
Parameters
dimensionTarget std::string& value of the "dimensionTarget" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setTarget()
int SedAppliedDimension::setTarget (const std::string & target)
Sets the value of the "target" attribute of this SedAppliedDimension.
Parameters
target std::string& value of the "target" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetDimensionTarget()
int SedAppliedDimension::unsetDimensionTarget ()
Unsets the value of the "dimensionTarget" attribute of this SedAppliedDimension.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTarget()
int SedAppliedDimension::unsetTarget ()
Unsets the value of the "target" attribute of this SedAppliedDimension.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedAppliedDimension.h
SedAppliedDimension.cpp