LIBSEDML API: SedShadedArea Class Reference
SedShadedArea Class Reference
#include <SedShadedArea.h>
Public Member Functions
virtual SedShadedArea * clone () const
virtual const std::string & getElementName () const
virtual int getTypeCode () const
const std::string & getYDataReferenceFrom () const
const std::string & getYDataReferenceTo () const
virtual bool hasRequiredAttributes () const
bool isSetYDataReferenceFrom () const
bool isSetYDataReferenceTo () const
SedShadedArea & operator= (const SedShadedArea &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedShadedArea (const SedShadedArea &orig)
SedShadedArea (SedNamespaces *sedmlns)
SedShadedArea (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setYDataReferenceFrom (const std::string &yDataReferenceFrom)
int setYDataReferenceTo (const std::string &yDataReferenceTo)
int unsetYDataReferenceFrom ()
int unsetYDataReferenceTo ()
virtual ~SedShadedArea ()
Public Member Functions inherited from SedAbstractCurve
bool getLogX () const
int getOrder () const
const std::string & getStyle () const
const std::string & getXDataReference () const
const std::string & getYAxis () const
virtual bool isSedCurve () const
virtual bool isSedShadedArea () const
bool isSetLogX () const
bool isSetOrder () const
bool isSetStyle () const
bool isSetXDataReference () const
bool isSetYAxis () const
SedAbstractCurve & operator= (const SedAbstractCurve &rhs)
SedAbstractCurve (const SedAbstractCurve &orig)
SedAbstractCurve (SedNamespaces *sedmlns)
SedAbstractCurve (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setLogX (bool logX)
int setOrder (int order)
int setStyle (const std::string &style)
int setXDataReference (const std::string &xDataReference)
int setYAxis (const std::string &yAxis)
int unsetLogX ()
int unsetOrder ()
int unsetStyle ()
int unsetXDataReference ()
int unsetYAxis ()
virtual ~SedAbstractCurve ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedShadedArea class.
Constructor & Destructor Documentation
SedShadedArea() [1/3]
SedShadedArea::SedShadedArea (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedShadedArea using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedShadedArea.
version an unsigned int, the SED-ML Version to assign to this SedShadedArea.
Referenced by clone().
SedShadedArea() [2/3]
SedShadedArea::SedShadedArea (SedNamespaces * sedmlns)
Creates a new SedShadedArea using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedShadedArea() [3/3]
SedShadedArea::SedShadedArea (const SedShadedArea & orig)
Copy constructor for SedShadedArea.
Parameters
orig the SedShadedArea instance to copy.
~SedShadedArea()
SedShadedArea::~SedShadedArea () virtual
Destructor for SedShadedArea.
Member Function Documentation
clone()
SedShadedArea * SedShadedArea::clone () const virtual
Creates and returns a deep copy of this SedShadedArea object.
Returns
a (deep) copy of this SedShadedArea object.
Reimplemented from SedAbstractCurve.
References SedShadedArea().
getElementName()
const std::string & SedShadedArea::getElementName () const virtual
Returns the XML element name of this SedShadedArea object.
For SedShadedArea, the XML element name is always "shadedArea".
Returns
the name of this element, i.e. "shadedArea".
Reimplemented from SedAbstractCurve.
getTypeCode()
int SedShadedArea::getTypeCode () const virtual
Returns the libSEDML type code for this SedShadedArea object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SHADEDAREA, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedAbstractCurve.
References SEDML_SHADEDAREA.
getYDataReferenceFrom()
const std::string & SedShadedArea::getYDataReferenceFrom () const
Returns the value of the "yDataReferenceFrom" attribute of this SedShadedArea.
Returns
the value of the "yDataReferenceFrom" attribute of this SedShadedArea as a string.
getYDataReferenceTo()
const std::string & SedShadedArea::getYDataReferenceTo () const
Returns the value of the "yDataReferenceTo" attribute of this SedShadedArea.
Returns
the value of the "yDataReferenceTo" attribute of this SedShadedArea as a string.
hasRequiredAttributes()
bool SedShadedArea::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedShadedArea object have been set.
Returns
true to indicate that all the required attributes of this SedShadedArea have been set, otherwise false is returned.
Note
The required attributes for the SedShadedArea object are:
"yDataReferenceFrom"
"yDataReferenceTo"
Reimplemented from SedAbstractCurve.
References SedAbstractCurve::hasRequiredAttributes(), isSetYDataReferenceFrom(), and isSetYDataReferenceTo().
isSetYDataReferenceFrom()
bool SedShadedArea::isSetYDataReferenceFrom () const
Predicate returning true if this SedShadedArea's "yDataReferenceFrom" attribute is set.
Returns
true if this SedShadedArea's "yDataReferenceFrom" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetYDataReferenceTo()
bool SedShadedArea::isSetYDataReferenceTo () const
Predicate returning true if this SedShadedArea's "yDataReferenceTo" attribute is set.
Returns
true if this SedShadedArea's "yDataReferenceTo" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
operator=()
SedShadedArea & SedShadedArea::operator= (const SedShadedArea & rhs)
Assignment operator for SedShadedArea.
Parameters
rhs the SedShadedArea object whose values are to be used as the basis of the assignment.
References SedAbstractCurve::operator=().
renameSIdRefs()
void SedShadedArea::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
Reimplemented from SedAbstractCurve.
References isSetYDataReferenceFrom(), isSetYDataReferenceTo(), setYDataReferenceFrom(), and setYDataReferenceTo().
setYDataReferenceFrom()
int SedShadedArea::setYDataReferenceFrom (const std::string & yDataReferenceFrom)
Sets the value of the "yDataReferenceFrom" attribute of this SedShadedArea.
Parameters
yDataReferenceFrom std::string& value of the "yDataReferenceFrom" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setYDataReferenceTo()
int SedShadedArea::setYDataReferenceTo (const std::string & yDataReferenceTo)
Sets the value of the "yDataReferenceTo" attribute of this SedShadedArea.
Parameters
yDataReferenceTo std::string& value of the "yDataReferenceTo" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetYDataReferenceFrom()
int SedShadedArea::unsetYDataReferenceFrom ()
Unsets the value of the "yDataReferenceFrom" attribute of this SedShadedArea.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetYDataReferenceTo()
int SedShadedArea::unsetYDataReferenceTo ()
Unsets the value of the "yDataReferenceTo" attribute of this SedShadedArea.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedShadedArea.h
SedShadedArea.cpp