LIBSEDML API: SedAbstractTask Class Reference
SedAbstractTask Class Reference
#include <SedAbstractTask.h>
Public Member Functions
virtual SedAbstractTask * clone () const
virtual const std::string & getElementName () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool isSedParameterEstimationTask () const
virtual bool isSedRepeatedTask () const
virtual bool isSedTask () const
SedAbstractTask & operator= (const SedAbstractTask &rhs)
SedAbstractTask (const SedAbstractTask &orig)
SedAbstractTask (SedNamespaces *sedmlns)
SedAbstractTask (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedAbstractTask ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAbstractTask class.
Constructor & Destructor Documentation
SedAbstractTask() [1/3]
SedAbstractTask::SedAbstractTask (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAbstractTask using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAbstractTask.
version an unsigned int, the SED-ML Version to assign to this SedAbstractTask.
Referenced by clone().
SedAbstractTask() [2/3]
SedAbstractTask::SedAbstractTask (SedNamespaces * sedmlns)
Creates a new SedAbstractTask using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedAbstractTask() [3/3]
SedAbstractTask::SedAbstractTask (const SedAbstractTask & orig)
Copy constructor for SedAbstractTask.
Parameters
orig the SedAbstractTask instance to copy.
~SedAbstractTask()
SedAbstractTask::~SedAbstractTask () virtual
Destructor for SedAbstractTask.
Member Function Documentation
clone()
SedAbstractTask * SedAbstractTask::clone () const virtual
Creates and returns a deep copy of this SedAbstractTask object.
Returns
a (deep) copy of this SedAbstractTask object.
Implements SedBase.
Reimplemented in SedTask, SedRepeatedTask, and SedParameterEstimationTask.
References SedAbstractTask().
getElementName()
const std::string & SedAbstractTask::getElementName () const virtual
Returns the XML element name of this SedAbstractTask object.
For SedAbstractTask, the XML element name is always "task".
Returns
the name of this element, i.e. "task".
Implements SedBase.
Reimplemented in SedTask, SedRepeatedTask, and SedParameterEstimationTask.
getTypeCode()
int SedAbstractTask::getTypeCode () const virtual
Returns the libSEDML type code for this SedAbstractTask object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SEDML_ABSTRACTTASK, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
Reimplemented in SedTask, SedRepeatedTask, and SedParameterEstimationTask.
References SEDML_SEDML_ABSTRACTTASK.
Referenced by SedDocument::sortOrderedObjects().
hasRequiredAttributes()
bool SedAbstractTask::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAbstractTask object have been set.
Returns
true to indicate that all the required attributes of this SedAbstractTask have been set, otherwise false is returned.
Note
The required attributes for the SedAbstractTask object are:
"id"
Reimplemented in SedTask, SedRepeatedTask, and SedParameterEstimationTask.
References SedBase::isSetId().
Referenced by SedListOfTasks::addAbstractTask(), SedDocument::addTask(), SedParameterEstimationTask::hasRequiredAttributes(), SedRepeatedTask::hasRequiredAttributes(), and SedTask::hasRequiredAttributes().
isSedParameterEstimationTask()
bool SedAbstractTask::isSedParameterEstimationTask () const virtual
Predicate returning true if this abstract "SedAbstractTask" is of type SedParameterEstimationTask
Returns
true if this abstract "SedAbstractTask" is of type SedParameterEstimationTask, false otherwise
isSedRepeatedTask()
bool SedAbstractTask::isSedRepeatedTask () const virtual
Predicate returning true if this abstract "SedAbstractTask" is of type SedRepeatedTask
Returns
true if this abstract "SedAbstractTask" is of type SedRepeatedTask, false otherwise
isSedTask()
bool SedAbstractTask::isSedTask () const virtual
Predicate returning true if this abstract "SedAbstractTask" is of type SedTask
Returns
true if this abstract "SedAbstractTask" is of type SedTask, false otherwise
operator=()
SedAbstractTask & SedAbstractTask::operator= (const SedAbstractTask & rhs)
Assignment operator for SedAbstractTask.
Parameters
rhs the SedAbstractTask object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
Referenced by SedParameterEstimationTask::operator=(), SedRepeatedTask::operator=(), and SedTask::operator=().
The documentation for this class was generated from the following files:
SedAbstractTask.h
SedAbstractTask.cpp