LIBSEDML API: SedFitMapping Class Reference
SedFitMapping Class Reference
#include <SedFitMapping.h>
Public Member Functions
virtual SedFitMapping * clone () const
const std::string & getDataSource () const
virtual const std::string & getElementName () const
const std::string & getPointWeight () const
const std::string & getTarget () const
MappingType_t getType () const
std::string getTypeAsString () const
virtual int getTypeCode () const
double getWeight () const
virtual bool hasRequiredAttributes () const
bool isSetDataSource () const
bool isSetPointWeight () const
bool isSetTarget () const
bool isSetType () const
bool isSetWeight () const
SedFitMapping & operator= (const SedFitMapping &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedFitMapping (const SedFitMapping &orig)
SedFitMapping (SedNamespaces *sedmlns)
SedFitMapping (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setDataSource (const std::string &dataSource)
int setPointWeight (const std::string &pointWeight)
int setTarget (const std::string &target)
int setType (const MappingType_t type)
int setType (const std::string &type)
int setWeight (double weight)
int unsetDataSource ()
int unsetPointWeight ()
int unsetTarget ()
int unsetType ()
int unsetWeight ()
virtual ~SedFitMapping ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedFitMapping class.
Constructor & Destructor Documentation
SedFitMapping() [1/3]
SedFitMapping::SedFitMapping (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedFitMapping using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedFitMapping.
version an unsigned int, the SED-ML Version to assign to this SedFitMapping.
Referenced by clone().
SedFitMapping() [2/3]
SedFitMapping::SedFitMapping (SedNamespaces * sedmlns)
Creates a new SedFitMapping using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedFitMapping() [3/3]
SedFitMapping::SedFitMapping (const SedFitMapping & orig)
Copy constructor for SedFitMapping.
Parameters
orig the SedFitMapping instance to copy.
~SedFitMapping()
SedFitMapping::~SedFitMapping () virtual
Destructor for SedFitMapping.
Member Function Documentation
clone()
SedFitMapping * SedFitMapping::clone () const virtual
Creates and returns a deep copy of this SedFitMapping object.
Returns
a (deep) copy of this SedFitMapping object.
Implements SedBase.
References SedFitMapping().
getDataSource()
const std::string & SedFitMapping::getDataSource () const
Returns the value of the "dataSource" attribute of this SedFitMapping.
Returns
the value of the "dataSource" attribute of this SedFitMapping as a string.
getElementName()
const std::string & SedFitMapping::getElementName () const virtual
Returns the XML element name of this SedFitMapping object.
For SedFitMapping, the XML element name is always "fitMapping".
Returns
the name of this element, i.e. "fitMapping".
Implements SedBase.
getPointWeight()
const std::string & SedFitMapping::getPointWeight () const
Returns the value of the "pointWeight" attribute of this SedFitMapping.
Returns
the value of the "pointWeight" attribute of this SedFitMapping as a string.
getTarget()
const std::string & SedFitMapping::getTarget () const
Returns the value of the "target" attribute of this SedFitMapping.
Returns
the value of the "target" attribute of this SedFitMapping as a string.
getType()
MappingType_t SedFitMapping::getType () const
Returns the value of the "type" attribute of this SedFitMapping.
Returns
the value of the "type" attribute of this SedFitMapping as a MappingType_t.
The attribute "type" on a SedFitMapping object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"time", TODO:add description
"experimentalCondition", TODO:add description
"observable", TODO:add description
The possible values returned by this method are:
@sbmlconstant{SEDML_MAPPINGTYPE_TIME, MappingType_t}
@sbmlconstant{SEDML_MAPPINGTYPE_EXPERIMENTALCONDITION, MappingType_t}
@sbmlconstant{SEDML_MAPPINGTYPE_OBSERVABLE, MappingType_t}
@sbmlconstant{SEDML_MAPPINGTYPE_INVALID, MappingType_t}
getTypeAsString()
std::string SedFitMapping::getTypeAsString () const
Returns the value of the "type" attribute of this SedFitMapping.
Returns
the value of the "type" attribute of this SedFitMapping as a string.
The attribute "type" on a SedFitMapping object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"time", TODO:add description
"experimentalCondition", TODO:add description
"observable", TODO:add description
The possible values returned by this method are:
"time"
"experimentalCondition"
"observable"
"invalid MappingType value"
References MappingType_toString().
getTypeCode()
int SedFitMapping::getTypeCode () const virtual
Returns the libSEDML type code for this SedFitMapping object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_FITMAPPING, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_FITMAPPING.
getWeight()
double SedFitMapping::getWeight () const
Returns the value of the "weight" attribute of this SedFitMapping.
Returns
the value of the "weight" attribute of this SedFitMapping as a double.
hasRequiredAttributes()
bool SedFitMapping::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedFitMapping object have been set.
Returns
true to indicate that all the required attributes of this SedFitMapping have been set, otherwise false is returned.
Note
The required attributes for the SedFitMapping object are:
"dataSource"
"target"
"type"
References isSetDataSource(), isSetTarget(), and isSetType().
Referenced by SedFitExperiment::addFitMapping(), and SedListOfFitMappings::addFitMapping().
isSetDataSource()
bool SedFitMapping::isSetDataSource () const
Predicate returning true if this SedFitMapping's "dataSource" attribute is set.
Returns
true if this SedFitMapping's "dataSource" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetPointWeight()
bool SedFitMapping::isSetPointWeight () const
Predicate returning true if this SedFitMapping's "pointWeight" attribute is set.
Returns
true if this SedFitMapping's "pointWeight" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetTarget()
bool SedFitMapping::isSetTarget () const
Predicate returning true if this SedFitMapping's "target" attribute is set.
Returns
true if this SedFitMapping's "target" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetType()
bool SedFitMapping::isSetType () const
Predicate returning true if this SedFitMapping's "type" attribute is set.
Returns
true if this SedFitMapping's "type" attribute has been set, otherwise false is returned.
The attribute "type" on a SedFitMapping object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"time", TODO:add description
"experimentalCondition", TODO:add description
"observable", TODO:add description
References SEDML_MAPPINGTYPE_INVALID.
Referenced by hasRequiredAttributes().
isSetWeight()
bool SedFitMapping::isSetWeight () const
Predicate returning true if this SedFitMapping's "weight" attribute is set.
Returns
true if this SedFitMapping's "weight" attribute has been set, otherwise false is returned.
Referenced by unsetWeight().
operator=()
SedFitMapping & SedFitMapping::operator= (const SedFitMapping & rhs)
Assignment operator for SedFitMapping.
Parameters
rhs the SedFitMapping object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
renameSIdRefs()
void SedFitMapping::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetDataSource(), isSetPointWeight(), isSetTarget(), setDataSource(), setPointWeight(), and setTarget().
setDataSource()
int SedFitMapping::setDataSource (const std::string & dataSource)
Sets the value of the "dataSource" attribute of this SedFitMapping.
Parameters
dataSource std::string& value of the "dataSource" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setPointWeight()
int SedFitMapping::setPointWeight (const std::string & pointWeight)
Sets the value of the "pointWeight" attribute of this SedFitMapping.
Parameters
pointWeight std::string& value of the "pointWeight" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setTarget()
int SedFitMapping::setTarget (const std::string & target)
Sets the value of the "target" attribute of this SedFitMapping.
Parameters
target std::string& value of the "target" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setType() [1/2]
int SedFitMapping::setType (const MappingType_t type)
Sets the value of the "type" attribute of this SedFitMapping.
Parameters
type intvalue of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedFitMapping object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"time", TODO:add description
"experimentalCondition", TODO:add description
"observable", TODO:add description
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, MappingType_isValid(), and SEDML_MAPPINGTYPE_INVALID.
setType() [2/2]
int SedFitMapping::setType (const std::string & type)
Sets the value of the "type" attribute of this SedFitMapping.
Parameters
type std::string& of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedFitMapping object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"time", TODO:add description
"experimentalCondition", TODO:add description
"observable", TODO:add description
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, MappingType_fromString(), and SEDML_MAPPINGTYPE_INVALID.
setWeight()
int SedFitMapping::setWeight (double weight)
Sets the value of the "weight" attribute of this SedFitMapping.
Parameters
weight double value of the "weight" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetDataSource()
int SedFitMapping::unsetDataSource ()
Unsets the value of the "dataSource" attribute of this SedFitMapping.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetPointWeight()
int SedFitMapping::unsetPointWeight ()
Unsets the value of the "pointWeight" attribute of this SedFitMapping.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTarget()
int SedFitMapping::unsetTarget ()
Unsets the value of the "target" attribute of this SedFitMapping.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetType()
int SedFitMapping::unsetType ()
Unsets the value of the "type" attribute of this SedFitMapping.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
The attribute "type" on a SedFitMapping object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"time", TODO:add description
"experimentalCondition", TODO:add description
"observable", TODO:add description
References LIBSEDML_OPERATION_SUCCESS, and SEDML_MAPPINGTYPE_INVALID.
unsetWeight()
int SedFitMapping::unsetWeight ()
Unsets the value of the "weight" attribute of this SedFitMapping.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetWeight(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedFitMapping.h
SedFitMapping.cpp