LIBSEDML API: SedBase Class Reference
SedBase Class Reference abstract
#include <SedBase.h>
Public Member Functions
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual SedBase * clone () const =0
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const std::string & getElementName () const =0
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
virtual int getTypeCode () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Protected Member Functions
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{} TODO:Definition of the SedBase class.
Constructor & Destructor Documentation
~SedBase()
SedBase::~SedBase () virtual
Destroys this object.
Member Function Documentation
appendAnnotation() [1/2]
int SedBase::appendAnnotation (const std::string & annotation) virtual
Appends the given annotation to the "annotation" subelement of this object.
Whereas the SedBase "notes" subelement is a container for content to be shown directly to humans, the "annotation" element is a container for optional software-generated content not meant to be shown to humans. Every object derived from SedBase can have its own value for "annotation". The element's content type is XML type "any", allowing essentially arbitrary well-formed XML data content.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
Unlike SedBase::setAnnotation(const XMLNode* annotation) or SedBase::setAnnotation(const std::string& annotation), this method allows other annotations to be preserved when an application adds its own data.
Parameters
annotation an XML string that is to be copied and appended to the content of the "annotation" subelement of this object
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_OPERATION_FAILED
See also
getAnnotationString()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
unsetAnnotation()
References appendAnnotation(), SedDocument::getNamespaces(), getSedDocument(), and LIBSEDML_OPERATION_FAILED.
appendAnnotation() [2/2]
int SedBase::appendAnnotation (const XMLNode * annotation) virtual
Appends the given annotation to the "annotation" subelement of this object.
Whereas the SedBase "notes" subelement is a container for content to be shown directly to humans, the "annotation" element is a container for optional software-generated content not meant to be shown to humans. Every object derived from SedBase can have its own value for "annotation". The element's content type is XML type "any", allowing essentially arbitrary well-formed XML data content.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
Unlike SedBase::setAnnotation(const XMLNode* annotation) or SedBase::setAnnotation(const std::string& annotation), this method allows other annotations to be preserved when an application adds its own data.
Parameters
annotation an XML structure that is to be copied and appended to the content of the "annotation" subelement of this object
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_OPERATION_FAILED
See also
getAnnotationString()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
References LIBSEDML_DUPLICATE_ANNOTATION_NS, LIBSEDML_OPERATION_FAILED, LIBSEDML_OPERATION_SUCCESS, and setAnnotation().
Referenced by appendAnnotation(), and replaceTopLevelAnnotationElement().
appendNotes() [1/2]
int SedBase::appendNotes (const std::string & notes)
Appends the given notes to the "notes" subelement of this object.
The content of the parameter notes is copied.
The optional SED-ML element named "notes", present on every major SED-ML component type, is intended as a place for storing optional information intended to be seen by humans. An example use of the "notes" element would be to contain formatted user comments about the model element in which the "notes" element is enclosed. Every object derived directly or indirectly from type SedBase can have a separate value for "notes", allowing users considerable freedom when adding comments to their models.
The format of "notes" elements must be XHTML 1.0. To help verify the formatting of "notes" content, libSEDML provides the static utility method SyntaxChecker::hasExpectedXHTMLSyntax(); however, readers are urged to consult the appropriate SED-ML specification document for the Level and Version of their model for more in-depth explanations. The SED-ML Level 2 and 3 specifications have considerable detail about how "notes" element content must be structured.
Parameters
notes an XML string that is to appended to the content of the "notes" subelement of this object
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_INVALID_OBJECT
LIBSEDML_OPERATION_FAILED
See also
getNotesString()
isSetNotes()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes, bool addXHTMLMarkup)
appendNotes(const XMLNode* notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
References appendNotes(), SedDocument::getNamespaces(), getSedDocument(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
appendNotes() [2/2]
int SedBase::appendNotes (const XMLNode * notes)
Appends the given notes to the "notes" subelement of this object.
The content of notes is copied.
The optional SED-ML element named "notes", present on every major SED-ML component type, is intended as a place for storing optional information intended to be seen by humans. An example use of the "notes" element would be to contain formatted user comments about the model element in which the "notes" element is enclosed. Every object derived directly or indirectly from type SedBase can have a separate value for "notes", allowing users considerable freedom when adding comments to their models.
The format of "notes" elements must be XHTML 1.0. To help verify the formatting of "notes" content, libSEDML provides the static utility method SyntaxChecker::hasExpectedXHTMLSyntax(); however, readers are urged to consult the appropriate SED-ML specification document for the Level and Version of their model for more in-depth explanations. The SED-ML Level 2 and 3 specifications have considerable detail about how "notes" element content must be structured.
Parameters
notes an XML node structure that is to appended to the content of the "notes" subelement of this object
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_INVALID_OBJECT
LIBSEDML_OPERATION_FAILED
See also
getNotesString()
isSetNotes()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes, bool addXHTMLMarkup)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
References getLevel(), getVersion(), LIBSEDML_INVALID_OBJECT, LIBSEDML_OPERATION_FAILED, LIBSEDML_OPERATION_SUCCESS, and setNotes().
Referenced by appendNotes().
clone()
virtual SedBase* SedBase::clone () const pure virtual
Creates and returns a deep copy of this SedBase object.
Returns
the (deep) copy of this SedBase object.
Implemented in SedWaterfallPlot, SedVectorRange, SedVariable, SedUniformTimeCourse, SedUniformRange, SedTask, SedSurface, SedSubTask, SedSubPlot, SedStyle, SedSteadyState, SedSlice, SedSimulation, SedShadedArea, SedSetValue, SedReport, SedRepeatedTask, SedRemoveXML, SedRange, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationTask, SedParameterEstimationResultPlot, SedParameterEstimationReport, SedParameter, SedOutput, SedOneStep, SedObjective, SedModel, SedMarker, SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, SedListOfAdjustableParameters, SedListOf, SedLine, SedLeastSquareObjectiveFunction, SedFunctionalRange, SedFitMapping, SedFitExperiment, SedFill, SedFigure, SedExperimentReference, SedDocument, SedDataSource, SedDataSet, SedDataRange, SedDataGenerator, SedDataDescription, SedCurve, SedComputeChange, SedChangeXML, SedChangeAttribute, SedChange, SedBounds, SedAxis, SedAppliedDimension, SedAnalysis, SedAlgorithmParameter, SedAlgorithm, SedAdjustableParameter, SedAddXML, SedAbstractTask, and SedAbstractCurve.
Referenced by SedListOf::append(), SedListOf::appendFrom(), SedListOf::insert(), and Clone::operator()().
getAllElements()
List * SedBase::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Returns
a pointer to a List of pointers to all children objects.
Reimplemented in SedVariable, SedSubTask, SedStyle, SedSimulation, SedSetValue, SedReport, SedRepeatedTask, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationTask, SedModel, SedListOf, SedFunctionalRange, SedFitExperiment, SedFigure, SedDocument, SedDataSource, SedDataGenerator, SedDataDescription, SedComputeChange, SedAlgorithmParameter, SedAlgorithm, and SedAdjustableParameter.
Referenced by SedListOf::getAllElements().
getAncestorOfType() [1/2]
SedBase * SedBase::getAncestorOfType (int type)
Returns the first ancestor object that has the given SED-ML type code.
This method searches the tree of objects that are parents of this object, and returns the first one that has the given SED-ML type code from the given pkgName.
Parameters
type the SED-ML type code of the object sought
Returns
the ancestor SED-ML object of this SED-ML object that corresponds to the given SED-ML object type code, or NULL if no ancestor exists.
References getParentSedObject(), getSedDocument(), getTypeCode(), and SEDML_DOCUMENT.
getAncestorOfType() [2/2]
const SedBase * SedBase::getAncestorOfType (int type) const
Returns the first ancestor object that has the given SED-ML type code.
This method searches the tree of objects that are parents of this object, and returns the first one that has the given SED-ML type code from the given pkgName.
Parameters
type the SED-ML type code of the object sought
Returns
the ancestor SED-ML object of this SED-ML object that corresponds to the given SED-ML object type code, or NULL if no ancestor exists.
References getParentSedObject(), getSedDocument(), getTypeCode(), and SEDML_DOCUMENT.
getAnnotation() [1/2]
XMLNode * SedBase::getAnnotation ()
Returns the content of the "annotation" subelement of this object as a tree of XMLNode objects.
The annotations returned by this method will be in XML form. LibSEDML provides an object model and related interfaces for certain specific kinds of annotations, namely model history information and RDF content. See the ModelHistory, CVTerm and RDFAnnotationParser classes for more information about the facilities available.
Returns
the annotation of this SED-ML object as a tree of XMLNode objects.
See also
getAnnotationString()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
Referenced by getAnnotation(), and getAnnotationString().
getAnnotation() [2/2]
const XMLNode * SedBase::getAnnotation () const
Returns the content of the "annotation" subelement of this object as a tree of XMLNode objects.
The annotations returned by this method will be in XML form. LibSEDML provides an object model and related interfaces for certain specific kinds of annotations, namely model history information and RDF content. See the ModelHistory, CVTerm and RDFAnnotationParser classes for more information about the facilities available.
Returns
the annotation of this SED-ML object as a tree of XMLNode objects.
See also
getAnnotationString()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
References getAnnotation().
getAnnotationString() [1/2]
std::string SedBase::getAnnotationString ()
Returns the content of the "annotation" subelement of this object as a character string.
The annotations returned by this method will be in string form. See the method getAnnotation() for a version that returns annotations in XML form.
Returns
the annotation of this SED-ML object as a character string.
See also
getAnnotation()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
References getAnnotation().
getAnnotationString() [2/2]
std::string SedBase::getAnnotationString () const
Returns the content of the "annotation" subelement of this object as a character string.
The annotations returned by this method will be in string form. See the method getAnnotation() for a version that returns annotations in XML form.
Returns
the annotation of this SED-ML object as a character string.
See also
getAnnotation()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
References getAnnotation().
getColumn()
unsigned int SedBase::getColumn () const
Returns the column number on which this object first appears in the XML representation of the SED-ML document, or '0' if the object was created, not read from a file.
Returns
the column number of this SED-ML object, or '0' if no such value.
Note
The column number for each construct in an SED-ML model is set upon reading the model. The accuracy of the column number depends on the correctness of the XML representation of the model, and on the particular XML parser library being used. The former limitation relates to the following problem: if the model is actually invalid XML, then the parser may not be able to interpret the data correctly and consequently may not be able to establish the real column number. The latter limitation is simply that different parsers seem to have their own accuracy limitations, and out of all the parsers supported by libSEDML, none have been 100% accurate in all situations. (At this time, libSEDML supports the use of libxml2, Expat and Xerces.)
See also
getLine()
getElementByMetaId() [1/2]
SedBase * SedBase::getElementByMetaId (const std::string & metaid) virtual
Returns the first child element it can find with a specific "metaid" attribute value, or NULL if no such object is found.
Parameters
metaid string representing the "metaid" attribute value of the object to find.
Returns
pointer to the first element found with the given meta-identifier.
Reimplemented in SedListOf.
Referenced by SedListOf::getElementByMetaId().
getElementByMetaId() [2/2]
const SedBase * SedBase::getElementByMetaId (const std::string & metaid) const virtual
Returns the first child element it can find with a specific "metaid" attribute value, or NULL if no such object is found.
Parameters
metaid string representing the "metaid" attribute value of the object to find.
Returns
pointer to the first element found with the given meta-identifier.
getElementBySId() [1/2]
SedBase * SedBase::getElementBySId (const std::string & id) virtual
Returns the first child element it can find with a specific "id" attribute value, or NULL if no such object is found.
Parameters
id string representing the "id" attribute value of the object to find.
Returns
pointer to the first element found with the given identifier.
Reimplemented in SedVariable, SedSubTask, SedStyle, SedSimulation, SedSetValue, SedReport, SedRepeatedTask, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationTask, SedModel, SedListOf, SedFunctionalRange, SedFitExperiment, SedFigure, SedDocument, SedDataSource, SedDataGenerator, SedDataDescription, SedComputeChange, SedAlgorithmParameter, SedAlgorithm, and SedAdjustableParameter.
Referenced by SedAdjustableParameter::getElementBySId(), SedAlgorithm::getElementBySId(), SedAlgorithmParameter::getElementBySId(), SedComputeChange::getElementBySId(), SedDataDescription::getElementBySId(), SedDataGenerator::getElementBySId(), SedDataSource::getElementBySId(), SedDocument::getElementBySId(), SedFigure::getElementBySId(), SedFitExperiment::getElementBySId(), SedFunctionalRange::getElementBySId(), SedListOf::getElementBySId(), SedModel::getElementBySId(), SedParameterEstimationTask::getElementBySId(), SedPlot::getElementBySId(), SedPlot2D::getElementBySId(), SedPlot3D::getElementBySId(), SedRepeatedTask::getElementBySId(), SedReport::getElementBySId(), SedSetValue::getElementBySId(), SedSimulation::getElementBySId(), SedStyle::getElementBySId(), SedSubTask::getElementBySId(), and SedVariable::getElementBySId().
getElementBySId() [2/2]
const SedBase * SedBase::getElementBySId (const std::string & metaid) const virtual
Returns the first child element it can find with a specific "id" attribute value, or NULL if no such object is found.
Parameters
id string representing the "id" attribute value of the object to find.
Returns
pointer to the first element found with the given identifier.
getElementName()
virtual const std::string& SedBase::getElementName () const pure virtual
Returns the XML element name of this object.
This is overridden by subclasses to return a string appropriate to the SED-ML component. For example, Model defines it as returning "model", CompartmentType defines it as returning "compartmentType", and so on.
Implemented in SedWaterfallPlot, SedVectorRange, SedVariable, SedUniformTimeCourse, SedUniformRange, SedTask, SedSurface, SedSubTask, SedSubPlot, SedStyle, SedSteadyState, SedSlice, SedSimulation, SedShadedArea, SedSetValue, SedReport, SedRepeatedTask, SedRemoveXML, SedRange, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationTask, SedParameterEstimationResultPlot, SedParameterEstimationReport, SedParameter, SedOutput, SedOneStep, SedObjective, SedModel, SedMarker, SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, SedListOfAdjustableParameters, SedListOf, SedLine, SedLeastSquareObjectiveFunction, SedFunctionalRange, SedFitMapping, SedFitExperiment, SedFill, SedFigure, SedExperimentReference, SedDocument, SedDataSource, SedDataSet, SedDataRange, SedDataGenerator, SedDataDescription, SedCurve, SedComputeChange, SedChangeXML, SedChangeAttribute, SedChange, SedBounds, SedAxis, SedAppliedDimension, SedAnalysis, SedAlgorithmParameter, SedAlgorithm, SedAdjustableParameter, SedAddXML, SedAbstractTask, and SedAbstractCurve.
Referenced by GetDowncastSwigType().
getElementNamespaces()
const XMLNamespaces * SedBase::getElementNamespaces () const virtual
Returns a list of the XML Namespaces declared on this object.
Returns
the XML Namespaces associated with this SED-ML object, or NULL in certain very usual circumstances where a namespace is not set.
See also
getLevel()
getVersion()
getErrorLog()
SedErrorLog* SedBase::getErrorLog ()
Returns the SedErrorLog used to log errors while reading and validating SED-ML.
Returns
the SedErrorLog used to log errors while reading and validating SED-ML.
getHasBeenDeleted()
bool SedBase::getHasBeenDeleted () const protected
getId()
const string & SedBase::getId () const virtual
References getLevel(), and getVersion().
Referenced by SedPlot2D::addCurve(), SedDocument::addDataDescription(), SedDocument::addDataGenerator(), SedReport::addDataSet(), SedDataDescription::addDataSource(), SedParameterEstimationTask::addFitExperiment(), SedDocument::addModel(), SedDocument::addOutput(), SedComputeChange::addParameter(), SedDataGenerator::addParameter(), SedFunctionalRange::addParameter(), SedSetValue::addParameter(), SedRepeatedTask::addRange(), SedDocument::addSimulation(), SedDocument::addStyle(), SedPlot3D::addSurface(), SedDocument::addTask(), SedComputeChange::addVariable(), SedDataGenerator::addVariable(), SedFunctionalRange::addVariable(), SedSetValue::addVariable(), SedDocument::getEffectiveStyle(), SedListOf::getElementBySId(), and isSetId().
getLevel()
unsigned int SedBase::getLevel () const
Returns the SED-ML Level of the SedDocument object containing this object.
Returns
the SED-ML level of this SED-ML object.
See also
getVersion()
getNamespaces()
getPackageVersion()
References LIBSEDML_CPP_NAMESPACE::SEDML_DEFAULT_LEVEL.
Referenced by SedListOfTasks::addAbstractTask(), SedListOfAdjustableParameters::addAdjustableParameter(), SedParameterEstimationTask::addAdjustableParameter(), SedAlgorithm::addAlgorithmParameter(), SedDocument::addAlgorithmParameter(), SedListOfAlgorithmParameters::addAlgorithmParameter(), SedAlgorithmParameter::addAlgorithmParameter(), SedVariable::addAppliedDimension(), SedListOfAppliedDimensions::addAppliedDimension(), SedListOfChanges::addChange(), SedModel::addChange(), SedListOfCurves::addCurve(), SedPlot2D::addCurve(), SedDocument::addDataDescription(), SedListOfDataDescriptions::addDataDescription(), SedDocument::addDataGenerator(), SedListOfDataGenerators::addDataGenerator(), SedListOfDataSets::addDataSet(), SedReport::addDataSet(), SedDataDescription::addDataSource(), SedListOfDataSources::addDataSource(), SedAdjustableParameter::addExperimentReference(), SedListOfExperimentReferences::addExperimentReference(), SedListOfFitExperiments::addFitExperiment(), SedParameterEstimationTask::addFitExperiment(), SedFitExperiment::addFitMapping(), SedListOfFitMappings::addFitMapping(), SedDocument::addModel(), SedListOfModels::addModel(), SedDocument::addOutput(), SedListOfOutputs::addOutput(), SedComputeChange::addParameter(), SedDataGenerator::addParameter(), SedFunctionalRange::addParameter(), SedListOfParameters::addParameter(), SedSetValue::addParameter(), SedListOfRanges::addRange(), SedRepeatedTask::addRange(), SedDocument::addSimulation(), SedListOfSimulations::addSimulation(), SedDataSource::addSlice(), SedListOfSlices::addSlice(), SedDocument::addStyle(), SedListOfStyles::addStyle(), SedFigure::addSubPlot(), SedListOfSubPlots::addSubPlot(), SedListOfSubTasks::addSubTask(), SedRepeatedTask::addSubTask(), SedListOfSurfaces::addSurface(), SedPlot3D::addSurface(), SedDocument::addTask(), SedListOfSetValues::addTaskChange(), SedRepeatedTask::addTaskChange(), SedSubTask::addTaskChange(), SedComputeChange::addVariable(), SedDataGenerator::addVariable(), SedFunctionalRange::addVariable(), SedListOfVariables::addVariable(), SedSetValue::addVariable(), appendNotes(), SedSubTask::createTaskChange(), getId(), getName(), SedComputeChange::getSymbol(), SedComputeChange::isSetSymbol(), SedRepeatedTask::setConcatenate(), setId(), setName(), and SedComputeChange::setSymbol().
getLine()
unsigned int SedBase::getLine () const
Returns the line number on which this object first appears in the XML representation of the SED-ML document, or '0' if the object was created, not read from a file.
Returns
the line number of this SED-ML object, or '0' if no such value.
Note
The line number for each construct in an SED-ML model is set upon reading the model. The accuracy of the line number depends on the correctness of the XML representation of the model, and on the particular XML parser library being used. The former limitation relates to the following problem: if the model is actually invalid XML, then the parser may not be able to interpret the data correctly and consequently may not be able to establish the real line number. The latter limitation is simply that different parsers seem to have their own accuracy limitations, and out of all the parsers supported by libSEDML, none have been 100% accurate in all situations. (At this time, libSEDML supports the use of libxml2, Expat and Xerces.)
See also
getColumn()
getMetaId() [1/2]
string & SedBase::getMetaId ()
Returns the value of the "metaid" attribute of this object.
Returns
the meta-identifier of this SED-ML object, as a string.
See also
isSetMetaId()
setMetaId(const std::string& metaid)
getMetaId() [2/2]
const string & SedBase::getMetaId () const
Returns the value of the "metaid" attribute of this object.
Returns
the meta-identifier of this SED-ML object.
See also
isSetMetaId()
setMetaId(const std::string& metaid)
Referenced by SedListOf::getElementByMetaId().
getName()
const std::string & SedBase::getName () const virtual
Returns
the value of the "name" attribute (or an empty string).
Note
The "name" attribute was added to the SedBase class in Level 1 version 4, and its presence here does not indicate whether the attribute was allowed on any given class in previous levels or versions. LibSEDML will return an empty string if the attribute was not allowed on the current level/version of the class.
References getLevel(), and getVersion().
Referenced by SedDocument::getEffectiveStyle(), and isSetName().
getNamespaces() [1/2]
XMLNamespaces * SedBase::getNamespaces () virtual
Returns a list of the XML Namespaces declared on the SED-ML document owning this object.
The SedNamespaces object encapsulates SED-ML Level/Version/namespaces information. It is used to communicate the SED-ML Level, Version, and (in Level 3) packages used in addition to SED-ML Level 3 Core.
Returns
the XML Namespaces associated with this SED-ML object, or NULL in certain very usual circumstances where a namespace is not set.
See also
getLevel()
getVersion()
Reimplemented in SedDocument.
getNamespaces() [2/2]
const XMLNamespaces * SedBase::getNamespaces () const virtual
Returns a list of the XML Namespaces declared on the SED-ML document owning this object.
The SedNamespaces object encapsulates SED-ML Level/Version/namespaces information. It is used to communicate the SED-ML Level, Version, and (in Level 3) packages used in addition to SED-ML Level 3 Core.
Returns
the XML Namespaces associated with this SED-ML object, or NULL in certain very usual circumstances where a namespace is not set.
See also
getLevel()
getVersion()
Reimplemented in SedDocument.
Referenced by hasValidLevelVersionNamespaceCombination().
getNotes() [1/2]
XMLNode * SedBase::getNotes ()
Returns the content of the "notes" subelement of this object as a tree of XMLNode objects.
The "notes" element content returned by this method will be in XML form, but libSEDML does not provide an object model specifically for the content of notes. Callers will need to traverse the XML tree structure using the facilities available on XMLNode and related objects. For an alternative method of accessing the notes, see getNotesString().
Returns
the content of the "notes" subelement of this SED-ML object as a tree structure composed of XMLNode objects.
See also
getNotesString()
isSetNotes()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
Referenced by operator=().
getNotes() [2/2]
const XMLNode * SedBase::getNotes () const
Returns the content of the "notes" subelement of this object as a tree of XMLNode objects.
The "notes" element content returned by this method will be in XML form, but libSEDML does not provide an object model specifically for the content of notes. Callers will need to traverse the XML tree structure using the facilities available on XMLNode and related objects. For an alternative method of accessing the notes, see getNotesString().
Returns
the content of the "notes" subelement of this SED-ML object as a tree structure composed of XMLNode objects.
See also
getNotesString()
isSetNotes()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
getNotesString() [1/2]
std::string SedBase::getNotesString ()
Returns the content of the "notes" subelement of this object as a string.
For an alternative method of accessing the notes, see getNotes(), which returns the content as an XMLNode tree structure. Depending on an application's needs, one or the other method may be more convenient.
Returns
the content of the "notes" subelement of this SED-ML object as a string.
See also
getNotes()
isSetNotes()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
getNotesString() [2/2]
std::string SedBase::getNotesString () const
Returns the content of the "notes" subelement of this object as a string.
For an alternative method of accessing the notes, see getNotes(), which returns the content as an XMLNode tree structure. Depending on an application's needs, one or the other method may be more convenient.
Returns
the content of the "notes" subelement of this SED-ML object as a string.
See also
getNotes()
isSetNotes()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
getParentSedObject() [1/2]
SedBase * SedBase::getParentSedObject ()
Returns the parent SED-ML object containing this object.
This returns the immediately-containing object. This method is convenient when holding an object nested inside other objects in an SED-ML model.
Returns
the parent SED-ML object of this SED-ML object.
See also
getSedDocument()
getModel()
Referenced by getAncestorOfType(), SedAbstractCurve::getLogX(), SedSurface::getLogX(), SedCurve::getLogY(), SedSurface::getLogY(), SedSurface::getLogZ(), and removeFromParentAndDelete().
getParentSedObject() [2/2]
const SedBase * SedBase::getParentSedObject () const
Returns the parent SED-ML object containing this object.
This returns the immediately-containing object. This method is convenient when holding an object nested inside other objects in an SED-ML model.
Returns
the parent SED-ML object of this SED-ML object.
See also
getSedDocument()
getModel()
getSedDocument() [1/2]
SedDocument * SedBase::getSedDocument ()
Returns the SedDocument object containing this object instance.
This method allows the caller to obtain the SedDocument for the current object.
Returns
the parent SedDocument object of this SED-ML object.
See also
getParentSedObject()
getModel()
getSedDocument() [2/2]
const SedDocument * SedBase::getSedDocument () const
Returns the SedDocument object containing this object instance.
This method allows the caller to obtain the SedDocument for the current object.
Returns
the parent SedDocument object of this SED-ML object.
See also
getParentSedObject()
getModel()
Referenced by appendAnnotation(), appendNotes(), getAncestorOfType(), replaceTopLevelAnnotationElement(), setAnnotation(), and setNotes().
getTypeCode()
int SedBase::getTypeCode () const virtual
Returns the libSEDML type code for this object.
Returns
the SED-ML object type code of this SED-ML object, or @sedmlconstant{SEDML_UNKNOWN, SedTypeCode_t} (the default). The latter is possible because subclasses of SedBase are not required to implement this method to return a type code.
See also
getPackageName()
getElementName()
Reimplemented in SedWaterfallPlot, SedVectorRange, SedVariable, SedUniformTimeCourse, SedUniformRange, SedTask, SedSurface, SedSubTask, SedSubPlot, SedStyle, SedSteadyState, SedSlice, SedSimulation, SedShadedArea, SedSetValue, SedReport, SedRepeatedTask, SedRemoveXML, SedRange, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationTask, SedParameterEstimationResultPlot, SedParameterEstimationReport, SedParameter, SedOutput, SedOneStep, SedObjective, SedModel, SedMarker, SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, SedListOfAdjustableParameters, SedListOf, SedLine, SedLeastSquareObjectiveFunction, SedFunctionalRange, SedFitMapping, SedFitExperiment, SedFill, SedFigure, SedExperimentReference, SedDocument, SedDataSource, SedDataSet, SedDataRange, SedDataGenerator, SedDataDescription, SedCurve, SedComputeChange, SedChangeXML, SedChangeAttribute, SedChange, SedBounds, SedAxis, SedAppliedDimension, SedAnalysis, SedAlgorithmParameter, SedAlgorithm, SedAdjustableParameter, SedAddXML, SedAbstractTask, and SedAbstractCurve.
References SEDML_UNKNOWN.
Referenced by getAncestorOfType(), GetDowncastSwigType(), SedAbstractCurve::getLogX(), SedSurface::getLogX(), SedCurve::getLogY(), SedSurface::getLogY(), SedSurface::getLogZ(), and hasValidLevelVersionNamespaceCombination().
getUserData()
void * SedBase::getUserData () const
Returns the user data that has been previously set via setUserData().
The user data associated with an SBML object can be used by an application developer to attach custom information to that object in the model. In case of a deep copy, this data will passed as-is. The data attribute will never be interpreted by libSBML.
Returns
the user data of this node, or NULL if no user data has been set.
getVersion()
unsigned int SedBase::getVersion () const
Returns the Version within the SED-ML Level of the SedDocument object containing this object.
Returns
the SED-ML version of this SED-ML object.
See also
getLevel()
getNamespaces()
References LIBSEDML_CPP_NAMESPACE::SEDML_DEFAULT_VERSION.
Referenced by SedListOfTasks::addAbstractTask(), SedListOfAdjustableParameters::addAdjustableParameter(), SedParameterEstimationTask::addAdjustableParameter(), SedAlgorithm::addAlgorithmParameter(), SedDocument::addAlgorithmParameter(), SedListOfAlgorithmParameters::addAlgorithmParameter(), SedAlgorithmParameter::addAlgorithmParameter(), SedVariable::addAppliedDimension(), SedListOfAppliedDimensions::addAppliedDimension(), SedListOfChanges::addChange(), SedModel::addChange(), SedListOfCurves::addCurve(), SedPlot2D::addCurve(), SedDocument::addDataDescription(), SedListOfDataDescriptions::addDataDescription(), SedDocument::addDataGenerator(), SedListOfDataGenerators::addDataGenerator(), SedListOfDataSets::addDataSet(), SedReport::addDataSet(), SedDataDescription::addDataSource(), SedListOfDataSources::addDataSource(), SedAdjustableParameter::addExperimentReference(), SedListOfExperimentReferences::addExperimentReference(), SedListOfFitExperiments::addFitExperiment(), SedParameterEstimationTask::addFitExperiment(), SedFitExperiment::addFitMapping(), SedListOfFitMappings::addFitMapping(), SedDocument::addModel(), SedListOfModels::addModel(), SedDocument::addOutput(), SedListOfOutputs::addOutput(), SedComputeChange::addParameter(), SedDataGenerator::addParameter(), SedFunctionalRange::addParameter(), SedListOfParameters::addParameter(), SedSetValue::addParameter(), SedListOfRanges::addRange(), SedRepeatedTask::addRange(), SedDocument::addSimulation(), SedListOfSimulations::addSimulation(), SedDataSource::addSlice(), SedListOfSlices::addSlice(), SedDocument::addStyle(), SedListOfStyles::addStyle(), SedFigure::addSubPlot(), SedListOfSubPlots::addSubPlot(), SedListOfSubTasks::addSubTask(), SedRepeatedTask::addSubTask(), SedListOfSurfaces::addSurface(), SedPlot3D::addSurface(), SedDocument::addTask(), SedListOfSetValues::addTaskChange(), SedRepeatedTask::addTaskChange(), SedSubTask::addTaskChange(), SedComputeChange::addVariable(), SedDataGenerator::addVariable(), SedFunctionalRange::addVariable(), SedListOfVariables::addVariable(), SedSetValue::addVariable(), appendNotes(), SedSubTask::createTaskChange(), getId(), SedAbstractCurve::getLogX(), SedSurface::getLogX(), SedCurve::getLogY(), SedSurface::getLogY(), SedSurface::getLogZ(), getName(), SedComputeChange::getSymbol(), SedComputeChange::isSetSymbol(), SedRepeatedTask::setConcatenate(), setId(), setName(), and SedComputeChange::setSymbol().
hasValidLevelVersionNamespaceCombination()
bool SedBase::hasValidLevelVersionNamespaceCombination ()
Predicate returning true if this object's level/version and namespace values correspond to a valid SED-ML specification.
Returns
true if the level, version and namespace values of this SED-ML object correspond to a valid set of values, false otherwise.
References getNamespaces(), and getTypeCode().
Referenced by SedListOf::SedListOf().
isSetAnnotation()
bool SedBase::isSetAnnotation () const
Predicate returning true if this object's "annotation" subelement exists and has content.
Whereas the SedBase "notes" subelement is a container for content to be shown directly to humans, the "annotation" element is a container for optional software-generated content not meant to be shown to humans. Every object derived from SedBase can have its own value for "annotation". The element's content type is XML type "any", allowing essentially arbitrary well-formed XML data content.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
Returns
true if a "annotation" subelement exists, false otherwise.
See also
getAnnotation()
getAnnotationString()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
isSetId()
bool SedBase::isSetId () const virtual
Predicate returning true if this object's "id" attribute is set.
Returns
true if the "id" attribute of this SED-ML object is set, false otherwise.
See also
getId()
References getId().
Referenced by SedPlot2D::addCurve(), SedDocument::addDataDescription(), SedDocument::addDataGenerator(), SedReport::addDataSet(), SedDataDescription::addDataSource(), SedParameterEstimationTask::addFitExperiment(), SedDocument::addModel(), SedDocument::addOutput(), SedComputeChange::addParameter(), SedDataGenerator::addParameter(), SedFunctionalRange::addParameter(), SedSetValue::addParameter(), SedRepeatedTask::addRange(), SedDocument::addSimulation(), SedDocument::addStyle(), SedPlot3D::addSurface(), SedDocument::addTask(), SedComputeChange::addVariable(), SedDataGenerator::addVariable(), SedFunctionalRange::addVariable(), SedSetValue::addVariable(), SedAbstractTask::hasRequiredAttributes(), SedDataDescription::hasRequiredAttributes(), SedDataGenerator::hasRequiredAttributes(), SedDataSet::hasRequiredAttributes(), SedDataSource::hasRequiredAttributes(), SedModel::hasRequiredAttributes(), SedParameter::hasRequiredAttributes(), SedRange::hasRequiredAttributes(), SedSimulation::hasRequiredAttributes(), SedStyle::hasRequiredAttributes(), and SedVariable::hasRequiredAttributes().
isSetMetaId()
bool SedBase::isSetMetaId () const
Predicate returning true if this object's "metaid" attribute is set.
Returns
true if the "metaid" attribute of this SED-ML object is set, false otherwise.
See also
getMetaId()
setMetaId(const std::string& metaid)
isSetName()
bool SedBase::isSetName () const virtual
Predicate returning true if this element's "name" attribute is set.
Returns
true if this element's "name" attribute has been set, otherwise false is returned.
References getName().
Referenced by SedAlgorithm::setKisaoID(), and SedAlgorithmParameter::setKisaoID().
isSetNotes()
bool SedBase::isSetNotes () const
Predicate returning true if this object's "notes" subelement exists and has content.
The optional SED-ML element named "notes", present on every major SED-ML component type, is intended as a place for storing optional information intended to be seen by humans. An example use of the "notes" element would be to contain formatted user comments about the model element in which the "notes" element is enclosed. Every object derived directly or indirectly from type SedBase can have a separate value for "notes", allowing users considerable freedom when adding comments to their models.
The format of "notes" elements must be XHTML 1.0. To help verify the formatting of "notes" content, libSEDML provides the static utility method SyntaxChecker::hasExpectedXHTMLSyntax(); however, readers are urged to consult the appropriate SED-ML specification document for the Level and Version of their model for more in-depth explanations. The SED-ML Level 2 and 3 specifications have considerable detail about how "notes" element content must be structured.
Returns
true if a "notes" subelement exists, false otherwise.
See also
getNotes()
getNotesString()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
isSetUserData()
bool SedBase::isSetUserData () const
Predicate returning true or false depending on whether the user data of this element has been set.
The user data associated with an SBML object can be used by an application developer to attach custom information to that object in the model. In case of a deep copy, this data will passed as-is. The data attribute will never be interpreted by libSBML.
Returns
boolean, true if this object's user data has been set, false otherwise.
matchesRequiredSedNamespacesForAddition() [1/2]
bool SedBase::matchesRequiredSedNamespacesForAddition (const SedBase * sb)
Returns true if this object's set of XML namespaces are a subset of the given object's XML namespaces.
Parameters
sb an object to compare with respect to namespaces
Returns
boolean, true if this object's collection of namespaces is a subset of sb's, false otherwise.
Referenced by SedListOfTasks::addAbstractTask(), SedListOfAdjustableParameters::addAdjustableParameter(), SedParameterEstimationTask::addAdjustableParameter(), SedAlgorithm::addAlgorithmParameter(), SedDocument::addAlgorithmParameter(), SedListOfAlgorithmParameters::addAlgorithmParameter(), SedAlgorithmParameter::addAlgorithmParameter(), SedVariable::addAppliedDimension(), SedListOfAppliedDimensions::addAppliedDimension(), SedListOfChanges::addChange(), SedModel::addChange(), SedListOfCurves::addCurve(), SedPlot2D::addCurve(), SedDocument::addDataDescription(), SedListOfDataDescriptions::addDataDescription(), SedDocument::addDataGenerator(), SedListOfDataGenerators::addDataGenerator(), SedListOfDataSets::addDataSet(), SedReport::addDataSet(), SedDataDescription::addDataSource(), SedListOfDataSources::addDataSource(), SedAdjustableParameter::addExperimentReference(), SedListOfExperimentReferences::addExperimentReference(), SedListOfFitExperiments::addFitExperiment(), SedParameterEstimationTask::addFitExperiment(), SedFitExperiment::addFitMapping(), SedListOfFitMappings::addFitMapping(), SedDocument::addModel(), SedListOfModels::addModel(), SedDocument::addOutput(), SedListOfOutputs::addOutput(), SedComputeChange::addParameter(), SedDataGenerator::addParameter(), SedFunctionalRange::addParameter(), SedListOfParameters::addParameter(), SedSetValue::addParameter(), SedListOfRanges::addRange(), SedRepeatedTask::addRange(), SedDocument::addSimulation(), SedListOfSimulations::addSimulation(), SedDataSource::addSlice(), SedListOfSlices::addSlice(), SedDocument::addStyle(), SedListOfStyles::addStyle(), SedFigure::addSubPlot(), SedListOfSubPlots::addSubPlot(), SedListOfSubTasks::addSubTask(), SedRepeatedTask::addSubTask(), SedListOfSurfaces::addSurface(), SedPlot3D::addSurface(), SedDocument::addTask(), SedListOfSetValues::addTaskChange(), SedRepeatedTask::addTaskChange(), SedSubTask::addTaskChange(), SedComputeChange::addVariable(), SedDataGenerator::addVariable(), SedFunctionalRange::addVariable(), SedListOfVariables::addVariable(), and SedSetValue::addVariable().
matchesRequiredSedNamespacesForAddition() [2/2]
bool SedBase::matchesRequiredSedNamespacesForAddition (const SedBase * sb) const
Returns true if this object's set of XML namespaces are a subset of the given object's XML namespaces.
Parameters
sb an object to compare with respect to namespaces
Returns
boolean, true if this object's collection of namespaces is a subset of sb's, false otherwise.
matchesSedNamespaces() [1/2]
bool SedBase::matchesSedNamespaces (const SedBase * sb)
Returns true if this object's set of XML namespaces are the same as the given object's XML namespaces.
Parameters
sb an object to compare with respect to namespaces
Returns
boolean, true if this object's collection of namespaces is the same as sb's, false otherwise.
matchesSedNamespaces() [2/2]
bool SedBase::matchesSedNamespaces (const SedBase * sb) const
Returns true if this object's set of XML namespaces are the same as the given object's XML namespaces.
Parameters
sb an object to compare with respect to namespaces
Returns
boolean, true if this object's collection of namespaces is the same as sb's, false otherwise.
operator=()
SedBase & SedBase::operator= (const SedBase & rhs)
Assignment operator for SedBase.
Parameters
rhs The object whose values are used as the basis of the assignment.
References getNotes().
Referenced by SedAbstractCurve::operator=(), SedAbstractTask::operator=(), SedAdjustableParameter::operator=(), SedAlgorithm::operator=(), SedAlgorithmParameter::operator=(), SedAppliedDimension::operator=(), SedAxis::operator=(), SedBounds::operator=(), SedChange::operator=(), SedDataDescription::operator=(), SedDataGenerator::operator=(), SedDataSet::operator=(), SedDataSource::operator=(), SedDocument::operator=(), SedExperimentReference::operator=(), SedFill::operator=(), SedFitExperiment::operator=(), SedFitMapping::operator=(), SedLine::operator=(), SedListOf::operator=(), SedMarker::operator=(), SedModel::operator=(), SedObjective::operator=(), SedOutput::operator=(), SedParameter::operator=(), SedRange::operator=(), SedSetValue::operator=(), SedSimulation::operator=(), SedSlice::operator=(), SedStyle::operator=(), SedSubPlot::operator=(), SedSubTask::operator=(), SedSurface::operator=(), and SedVariable::operator=().
removeFromParentAndDelete()
int SedBase::removeFromParentAndDelete () virtual
Removes this object from its parent.
If the parent was storing this object as a pointer, it is deleted. If not, it is simply cleared (as in SedListOf objects). This is a pure virtual method, as every SedBase element has different parents, and therefore different methods of removing itself. Will fail (and not delete itself) if it has no parent object. This function is designed to be overridden, but for all objects whose parent is of the class SedListOf, the default implementation will work.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
Reimplemented in SedListOf.
References SedListOf::get(), getParentSedObject(), LIBSEDML_OPERATION_FAILED, LIBSEDML_OPERATION_SUCCESS, SedListOf::remove(), and SedListOf::size().
removeTopLevelAnnotationElement()
int SedBase::removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI = "")
Removes the top-level element within the "annotation" subelement of this SED-ML object with the given name and optional URI.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
Calling this method allows a particular annotation element to be removed whilst the remaining annotations remain intact.
Parameters
elementName a string representing the name of the top level annotation element that is to be removed
elementURI an optional string that is used to check both the name and URI of the top level element to be removed
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_OPERATION_FAILED
LIBSEDML_ANNOTATION_NAME_NOT_FOUND
LIBSEDML_ANNOTATION_NS_NOT_FOUND
See also
replaceTopLevelAnnotationElement(const XMLNode *)
replaceTopLevelAnnotationElement(const std::string&)
References LIBSEDML_ANNOTATION_NAME_NOT_FOUND, LIBSEDML_ANNOTATION_NS_NOT_FOUND, LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
Referenced by replaceTopLevelAnnotationElement().
replaceTopLevelAnnotationElement() [1/2]
int SedBase::replaceTopLevelAnnotationElement (const std::string & annotation)
Replaces the given top-level element within the "annotation" subelement of this SED-ML object and with the annotation element supplied.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
This method determines the name of the element to be replaced from the annotation argument. Functionally it is equivalent to calling removeTopLevelAnnotationElement(name); appendAnnotation(annotation_with_name); with the exception that the placement of the annotation element remains the same.
Parameters
annotation string representing the replacement top level annotation
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_OPERATION_FAILED
LIBSEDML_INVALID_OBJECT
See also
removeTopLevelAnnotationElement(const std::string elementName, const std::string elementURI)
replaceTopLevelAnnotationElement(const XMLNode*)
References SedDocument::getNamespaces(), getSedDocument(), LIBSEDML_OPERATION_FAILED, and replaceTopLevelAnnotationElement().
replaceTopLevelAnnotationElement() [2/2]
int SedBase::replaceTopLevelAnnotationElement (const XMLNode * annotation)
Replaces the given top-level element within the "annotation" subelement of this SED-ML object and with the annotation element supplied.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
This method determines the name of the element to be replaced from the annotation argument. Functionally it is equivalent to calling removeTopLevelAnnotationElement(name); appendAnnotation(annotation_with_name); with the exception that the placement of the annotation element remains the same.
Parameters
annotation XMLNode representing the replacement top level annotation
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_OPERATION_FAILED
LIBSEDML_INVALID_OBJECT
See also
removeTopLevelAnnotationElement(const std::string elementName, const std::string elementURI)
replaceTopLevelAnnotationElement(const std::string&)
References appendAnnotation(), LIBSEDML_INVALID_OBJECT, LIBSEDML_OPERATION_FAILED, LIBSEDML_OPERATION_SUCCESS, and removeTopLevelAnnotationElement().
Referenced by replaceTopLevelAnnotationElement().
setAnnotation() [1/2]
int SedBase::setAnnotation (const std::string & annotation) virtual
Sets the value of the "annotation" subelement of this SED-ML object.
The content of annotation is copied, and any previous content of this object's "annotation" subelement is deleted.
Whereas the SedBase "notes" subelement is a container for content to be shown directly to humans, the "annotation" element is a container for optional software-generated content not meant to be shown to humans. Every object derived from SedBase can have its own value for "annotation". The element's content type is XML type "any", allowing essentially arbitrary well-formed XML data content.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
Call this method will result in any existing content of the "annotation" subelement to be discarded. Unless you have taken steps to first copy and reconstitute any existing annotations into the annotation that is about to be assigned, it is likely that performing such wholesale replacement is unfriendly towards other software applications whose annotations are discarded. An alternative may be to use SedBase::appendAnnotation(const XMLNode* annotation) or SedBase::appendAnnotation(const std::string& annotation).
Parameters
annotation an XML string that is to be used as the content of the "annotation" subelement of this object
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_OPERATION_FAILED
See also
getAnnotationString()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
References SedDocument::getNamespaces(), getSedDocument(), LIBSEDML_OPERATION_FAILED, LIBSEDML_OPERATION_SUCCESS, setAnnotation(), and unsetAnnotation().
setAnnotation() [2/2]
int SedBase::setAnnotation (XMLNode * annotation) virtual
Sets the value of the "annotation" subelement of this SED-ML object.
The content of annotation is copied, and any previous content of this object's "annotation" subelement is deleted.
Whereas the SedBase "notes" subelement is a container for content to be shown directly to humans, the "annotation" element is a container for optional software-generated content not meant to be shown to humans. Every object derived from SedBase can have its own value for "annotation". The element's content type is XML type "any", allowing essentially arbitrary well-formed XML data content.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
Call this method will result in any existing content of the "annotation" subelement to be discarded. Unless you have taken steps to first copy and reconstitute any existing annotations into the annotation that is about to be assigned, it is likely that performing such wholesale replacement is unfriendly towards other software applications whose annotations are discarded. An alternative may be to use SedBase::appendAnnotation(const XMLNode* annotation) or SedBase::appendAnnotation(const std::string& annotation).
Parameters
annotation an XML structure that is to be used as the new content of the "annotation" subelement of this object
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
See also
getAnnotationString()
isSetAnnotation()
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
unsetAnnotation()
References LIBSEDML_OPERATION_SUCCESS.
Referenced by appendAnnotation(), setAnnotation(), and unsetAnnotation().
setElementText()
void SedBase::setElementText (const std::string & text) protected virtual
When overridden allows SedBase elements to use the text included in between the elements tags. The default implementation does nothing.
Parameters
text the text string found between the element tags.
setId()
int SedBase::setId (const std::string & sid) virtual
Sets the value of the "id" attribute of this SED-ML object.
References getLevel(), getVersion(), LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, and LIBSEDML_UNEXPECTED_ATTRIBUTE.
Referenced by SedDocument::getEffectiveStyle().
setMetaId()
int SedBase::setMetaId (const std::string & metaid)
Sets the value of the meta-identifier attribute of this object.
The string metaid is copied.
Parameters
metaid the identifier string to use as the value of the "metaid" attribute
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_UNEXPECTED_ATTRIBUTE, OperationReturnValues_t}
See also
getMetaId()
isSetMetaId()
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
setName()
int SedBase::setName (const std::string & name) virtual
Sets the value of the "name" attribute of this element.
Parameters
name std::string& value of the "name" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with name = NULL or an empty string is equivalent to calling unsetName().
References getLevel(), getVersion(), LIBSEDML_OPERATION_SUCCESS, and LIBSEDML_UNEXPECTED_ATTRIBUTE.
Referenced by SedDocument::getEffectiveStyle(), SedAlgorithm::setKisaoID(), and SedAlgorithmParameter::setKisaoID().
setNamespaces()
int SedBase::setNamespaces (XMLNamespaces * xmlns)
Sets the namespaces relevant of this SED-ML object.
The content of xmlns is copied, and this object's existing namespace content is deleted.
The SedNamespaces object encapsulates SED-ML Level/Version/namespaces information. It is used to communicate the SED-ML Level, Version, and (in Level 3) packages used in addition to SED-ML Level 3 Core.
Parameters
xmlns the namespaces to set
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setNotes() [1/2]
int SedBase::setNotes (const std::string & notes, bool addXHTMLMarkup = false)
Sets the value of the "notes" subelement of this SED-ML object to a copy of the string notes.
The content of notes is copied, and any existing content of this object's "notes" subelement is deleted.
The optional SED-ML element named "notes", present on every major SED-ML component type, is intended as a place for storing optional information intended to be seen by humans. An example use of the "notes" element would be to contain formatted user comments about the model element in which the "notes" element is enclosed. Every object derived directly or indirectly from type SedBase can have a separate value for "notes", allowing users considerable freedom when adding comments to their models.
The format of "notes" elements must be XHTML 1.0. To help verify the formatting of "notes" content, libSEDML provides the static utility method SyntaxChecker::hasExpectedXHTMLSyntax(); however, readers are urged to consult the appropriate SED-ML specification document for the Level and Version of their model for more in-depth explanations. The SED-ML Level 2 and 3 specifications have considerable detail about how "notes" element content must be structured.
Parameters
notes an XML string that is to be used as the content of the "notes" subelement of this object
addXHTMLMarkup a boolean indicating whether to wrap the contents of the notes argument with XHTML paragraph (<p>) tags. This is appropriate when the string in notes does not already containg the appropriate XHTML markup.
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_INVALID_OBJECT
LIBSEDML_OPERATION_FAILED
See also
getNotesString()
isSetNotes()
setNotes(const XMLNode* notes)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
References SedDocument::getNamespaces(), getSedDocument(), LIBSEDML_OPERATION_FAILED, setNotes(), and unsetNotes().
setNotes() [2/2]
int SedBase::setNotes (const XMLNode * notes)
Sets the value of the "notes" subelement of this SED-ML object.
The content of notes is copied, and any existing content of this object's "notes" subelement is deleted.
The optional SED-ML element named "notes", present on every major SED-ML component type, is intended as a place for storing optional information intended to be seen by humans. An example use of the "notes" element would be to contain formatted user comments about the model element in which the "notes" element is enclosed. Every object derived directly or indirectly from type SedBase can have a separate value for "notes", allowing users considerable freedom when adding comments to their models.
The format of "notes" elements must be XHTML 1.0. To help verify the formatting of "notes" content, libSEDML provides the static utility method SyntaxChecker::hasExpectedXHTMLSyntax(); however, readers are urged to consult the appropriate SED-ML specification document for the Level and Version of their model for more in-depth explanations. The SED-ML Level 2 and 3 specifications have considerable detail about how "notes" element content must be structured.
Parameters
notes an XML structure that is to be used as the content of the "notes" subelement of this object
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
LIBSEDML_INVALID_OBJECT
See also
getNotesString()
isSetNotes()
setNotes(const std::string& notes, bool addXHTMLMarkup)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
unsetNotes()
SyntaxChecker::hasExpectedXHTMLSyntax()
References LIBSEDML_INVALID_OBJECT, LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
Referenced by appendNotes(), and setNotes().
setUserData()
int SedBase::setUserData (void * userData)
Sets the user data of this element.
The user data associated with an SBML object can be used by an application developer to attach custom information to that object in the model. In case of a deep copy, this data will passed as-is. The data attribute will never be interpreted by libSBML.
Parameters
userData specifies the new user data.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
toSed()
char * SedBase::toSed ()
Returns a string consisting of a partial SED-ML corresponding to just this object.
Returns
the partial SED-ML that describes this SED-ML object.
Warning
This is primarily provided for testing and debugging purposes. It may be removed in a future version of libSEDML.
unsetAnnotation()
int SedBase::unsetAnnotation ()
Unsets the value of the "annotation" subelement of this SED-ML object.
Whereas the SedBase "notes" subelement is a container for content to be shown directly to humans, the "annotation" element is a container for optional software-generated content not meant to be shown to humans. Every object derived from SedBase can have its own value for "annotation". The element's content type is XML type "any", allowing essentially arbitrary well-formed XML data content.
SED-ML places a few restrictions on the organization of the content of annotations; these are intended to help software tools read and write the data as well as help reduce conflicts between annotations added by different tools. Please see the SED-ML specifications for more details.
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
See also
getAnnotation()
getAnnotationString()
isSetAnnotation()
setAnnotation(const XMLNode* annotation)
setAnnotation(const std::string& annotation)
appendAnnotation(const XMLNode* annotation)
appendAnnotation(const std::string& annotation)
References setAnnotation().
Referenced by SedListOf::removeFromParentAndDelete(), and setAnnotation().
unsetId()
int SedBase::unsetId () virtual
Unsets the value of the "id" attribute of this SED-ML object.
References LIBSEDML_OPERATION_SUCCESS.
unsetMetaId()
int SedBase::unsetMetaId ()
Unsets the value of the "metaid" attribute of this SED-ML object.
References LIBSEDML_OPERATION_SUCCESS.
Referenced by SedListOf::removeFromParentAndDelete().
unsetName()
int SedBase::unsetName () virtual
Unsets the value of the "name" attribute of this SedSurface.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetNotes()
int SedBase::unsetNotes ()
Unsets the value of the "notes" subelement of this SED-ML object.
The optional SED-ML element named "notes", present on every major SED-ML component type, is intended as a place for storing optional information intended to be seen by humans. An example use of the "notes" element would be to contain formatted user comments about the model element in which the "notes" element is enclosed. Every object derived directly or indirectly from type SedBase can have a separate value for "notes", allowing users considerable freedom when adding comments to their models.
The format of "notes" elements must be XHTML 1.0. To help verify the formatting of "notes" content, libSEDML provides the static utility method SyntaxChecker::hasExpectedXHTMLSyntax(); however, readers are urged to consult the appropriate SED-ML specification document for the Level and Version of their model for more in-depth explanations. The SED-ML Level 2 and 3 specifications have considerable detail about how "notes" element content must be structured.
Returns
integer value indicating success/failure of the function. The possible values returned by this function are:
LIBSEDML_OPERATION_SUCCESS
See also
getNotesString()
isSetNotes()
setNotes(const XMLNode* notes)
setNotes(const std::string& notes, bool addXHTMLMarkup)
appendNotes(const XMLNode* notes)
appendNotes(const std::string& notes)
SyntaxChecker::hasExpectedXHTMLSyntax()
References LIBSEDML_OPERATION_SUCCESS.
Referenced by SedListOf::removeFromParentAndDelete(), and setNotes().
unsetUserData()
int SedBase::unsetUserData ()
Unsets the user data of this element.
The user data associated with an SBML object can be used by an application developer to attach custom information to that object in the model. In case of a deep copy, this data will passed as-is. The data attribute will never be interpreted by libSBML.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedBase.h
SedBase.cpp