LIBSEDML API: SedFigure Class Reference
SedFigure Class Reference
#include <SedFigure.h>
Public Member Functions
int addSubPlot (const SedSubPlot *ssp)
virtual SedFigure * clone () const
SedSubPlot * createSubPlot ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfSubPlots * getListOfSubPlots ()
const SedListOfSubPlots * getListOfSubPlots () const
int getNumCols () const
int getNumRows () const
unsigned int getNumSubPlots () const
SedSubPlot * getSubPlot (unsigned int n)
const SedSubPlot * getSubPlot (unsigned int n) const
SedSubPlot * getSubPlotByPlot (const std::string &sid)
const SedSubPlot * getSubPlotByPlot (const std::string &sid) const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetNumCols () const
bool isSetNumRows () const
SedFigure & operator= (const SedFigure &rhs)
SedSubPlot * removeSubPlot (unsigned int n)
SedFigure (const SedFigure &orig)
SedFigure (SedNamespaces *sedmlns)
SedFigure (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setNumCols (int numCols)
int setNumRows (int numRows)
int unsetNumCols ()
int unsetNumRows ()
virtual ~SedFigure ()
Public Member Functions inherited from SedOutput
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedFigure class.
Constructor & Destructor Documentation
SedFigure() [1/3]
SedFigure::SedFigure (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedFigure using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedFigure.
version an unsigned int, the SED-ML Version to assign to this SedFigure.
Referenced by clone().
SedFigure() [2/3]
SedFigure::SedFigure (SedNamespaces * sedmlns)
Creates a new SedFigure using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedFigure() [3/3]
SedFigure::SedFigure (const SedFigure & orig)
Copy constructor for SedFigure.
Parameters
orig the SedFigure instance to copy.
~SedFigure()
SedFigure::~SedFigure () virtual
Destructor for SedFigure.
Member Function Documentation
addSubPlot()
int SedFigure::addSubPlot (const SedSubPlot * ssp)
Adds a copy of the given SedSubPlot to this SedFigure.
Parameters
ssp the SedSubPlot object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createSubPlot()
getSubPlot(const std::string& sid)
getSubPlot(unsigned int n)
getNumSubPlots()
removeSubPlot(const std::string& sid)
removeSubPlot(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedSubPlot::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedFigure * SedFigure::clone () const virtual
Creates and returns a deep copy of this SedFigure object.
Returns
a (deep) copy of this SedFigure object.
Reimplemented from SedOutput.
References SedFigure().
createSubPlot()
SedSubPlot * SedFigure::createSubPlot ()
Creates a new SedSubPlot object, adds it to this SedFigure object and returns the SedSubPlot object created.
Returns
a new SedSubPlot object instance.
See also
addSubPlot(const SedSubPlot* object)
getSubPlot(const std::string& sid)
getSubPlot(unsigned int n)
getNumSubPlots()
removeSubPlot(const std::string& sid)
removeSubPlot(unsigned int n)
getAllElements()
List * SedFigure::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getElementBySId()
SedBase * SedFigure::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedFigure::getElementName () const virtual
Returns the XML element name of this SedFigure object.
For SedFigure, the XML element name is always "figure".
Returns
the name of this element, i.e. "figure".
Reimplemented from SedOutput.
getListOfSubPlots() [1/2]
SedListOfSubPlots * SedFigure::getListOfSubPlots ()
Returns the SedListOfSubPlots from this SedFigure.
Returns
the SedListOfSubPlots from this SedFigure.
See also
addSubPlot(const SedSubPlot* object)
createSubPlot()
getSubPlot(const std::string& sid)
getSubPlot(unsigned int n)
getNumSubPlots()
removeSubPlot(const std::string& sid)
removeSubPlot(unsigned int n)
getListOfSubPlots() [2/2]
const SedListOfSubPlots * SedFigure::getListOfSubPlots () const
Returns the SedListOfSubPlots from this SedFigure.
Returns
the SedListOfSubPlots from this SedFigure.
See also
addSubPlot(const SedSubPlot* object)
createSubPlot()
getSubPlot(const std::string& sid)
getSubPlot(unsigned int n)
getNumSubPlots()
removeSubPlot(const std::string& sid)
removeSubPlot(unsigned int n)
getNumCols()
int SedFigure::getNumCols () const
Returns the value of the "numCols" attribute of this SedFigure.
Returns
the value of the "numCols" attribute of this SedFigure as a integer.
getNumRows()
int SedFigure::getNumRows () const
Returns the value of the "numRows" attribute of this SedFigure.
Returns
the value of the "numRows" attribute of this SedFigure as a integer.
getNumSubPlots()
unsigned int SedFigure::getNumSubPlots () const
Get the number of SedSubPlot objects in this SedFigure.
Returns
the number of SedSubPlot objects in this SedFigure.
See also
addSubPlot(const SedSubPlot* object)
createSubPlot()
getSubPlot(const std::string& sid)
getSubPlot(unsigned int n)
removeSubPlot(const std::string& sid)
removeSubPlot(unsigned int n)
getSubPlot() [1/2]
SedSubPlot * SedFigure::getSubPlot (unsigned int n)
Get a SedSubPlot from the SedFigure.
Parameters
n an unsigned int representing the index of the SedSubPlot to retrieve.
Returns
the nth SedSubPlot in the SedListOfSubPlots within this SedFigure or NULL if no such object exists.
See also
addSubPlot(const SedSubPlot* object)
createSubPlot()
getSubPlot(const std::string& sid)
getNumSubPlots()
removeSubPlot(const std::string& sid)
removeSubPlot(unsigned int n)
getSubPlot() [2/2]
const SedSubPlot * SedFigure::getSubPlot (unsigned int n) const
Get a SedSubPlot from the SedFigure.
Parameters
n an unsigned int representing the index of the SedSubPlot to retrieve.
Returns
the nth SedSubPlot in the SedListOfSubPlots within this SedFigure or NULL if no such object exists.
See also
addSubPlot(const SedSubPlot* object)
createSubPlot()
getSubPlot(const std::string& sid)
getNumSubPlots()
removeSubPlot(const std::string& sid)
removeSubPlot(unsigned int n)
getSubPlotByPlot() [1/2]
SedSubPlot * SedFigure::getSubPlotByPlot (const std::string & sid)
Get a SedSubPlot from the SedFigure based on the Plot to which it refers.
Parameters
sid a string representing the "plot" attribute of the SedSubPlot object to retrieve.
Returns
the first SedSubPlot in this SedFigure based on the given plot attribute or NULL if no such SedSubPlot exists.
getSubPlotByPlot() [2/2]
const SedSubPlot * SedFigure::getSubPlotByPlot (const std::string & sid) const
Get a SedSubPlot from the SedFigure based on the Plot to which it refers.
Parameters
sid a string representing the "plot" attribute of the SedSubPlot object to retrieve.
Returns
the first SedSubPlot in this SedFigure based on the given plot attribute or NULL if no such SedSubPlot exists.
getTypeCode()
int SedFigure::getTypeCode () const virtual
Returns the libSEDML type code for this SedFigure object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_FIGURE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedOutput.
References SEDML_FIGURE.
hasRequiredAttributes()
bool SedFigure::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedFigure object have been set.
Returns
true to indicate that all the required attributes of this SedFigure have been set, otherwise false is returned.
Reimplemented from SedOutput.
References SedOutput::hasRequiredAttributes().
hasRequiredElements()
bool SedFigure::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedFigure object have been set.
Returns
true to indicate that all the required elements of this SedFigure have been set, otherwise false is returned.
Note
The required elements for the SedFigure object are:
isSetNumCols()
bool SedFigure::isSetNumCols () const
Predicate returning true if this SedFigure's "numCols" attribute is set.
Returns
true if this SedFigure's "numCols" attribute has been set, otherwise false is returned.
isSetNumRows()
bool SedFigure::isSetNumRows () const
Predicate returning true if this SedFigure's "numRows" attribute is set.
Returns
true if this SedFigure's "numRows" attribute has been set, otherwise false is returned.
operator=()
SedFigure & SedFigure::operator= (const SedFigure & rhs)
Assignment operator for SedFigure.
Parameters
rhs the SedFigure object whose values are to be used as the basis of the assignment.
References SedOutput::operator=().
removeSubPlot()
SedSubPlot * SedFigure::removeSubPlot (unsigned int n)
Removes the nth SedSubPlot from this SedFigure and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSubPlot to remove.
Returns
a pointer to the nth SedSubPlot in this SedFigure.
See also
addSubPlot(const SedSubPlot* object)
createSubPlot()
getSubPlot(const std::string& sid)
getSubPlot(unsigned int n)
getNumSubPlots()
removeSubPlot(const std::string& sid)
setNumCols()
int SedFigure::setNumCols (int numCols)
Sets the value of the "numCols" attribute of this SedFigure.
Parameters
numCols int value of the "numCols" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setNumRows()
int SedFigure::setNumRows (int numRows)
Sets the value of the "numRows" attribute of this SedFigure.
Parameters
numRows int value of the "numRows" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetNumCols()
int SedFigure::unsetNumCols ()
Unsets the value of the "numCols" attribute of this SedFigure.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetNumRows()
int SedFigure::unsetNumRows ()
Unsets the value of the "numRows" attribute of this SedFigure.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
The documentation for this class was generated from the following files:
SedFigure.h
SedFigure.cpp