LIBSEDML API: SedPlot2D Class Reference
SedPlot2D Class Reference
#include <SedPlot2D.h>
Public Member Functions
int addCurve (const SedAbstractCurve *sac)
virtual SedPlot2D * clone () const
SedCurve * createCurve ()
SedAxis * createRightYAxis ()
SedShadedArea * createShadedArea ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedAbstractCurve * getCurve (const std::string &sid)
const SedAbstractCurve * getCurve (const std::string &sid) const
SedAbstractCurve * getCurve (unsigned int n)
const SedAbstractCurve * getCurve (unsigned int n) const
SedAbstractCurve * getCurveByStyle (const std::string &sid)
const SedAbstractCurve * getCurveByStyle (const std::string &sid) const
SedAbstractCurve * getCurveByXDataReference (const std::string &sid)
const SedAbstractCurve * getCurveByXDataReference (const std::string &sid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfCurves * getListOfCurves ()
const SedListOfCurves * getListOfCurves () const
unsigned int getNumCurves () const
SedAxis * getRightYAxis ()
const SedAxis * getRightYAxis () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetRightYAxis () const
SedPlot2D & operator= (const SedPlot2D &rhs)
SedAbstractCurve * removeCurve (const std::string &sid)
SedAbstractCurve * removeCurve (unsigned int n)
SedPlot2D (const SedPlot2D &orig)
SedPlot2D (SedNamespaces *sedmlns)
SedPlot2D (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setRightYAxis (const SedAxis *rightYAxis)
int unsetRightYAxis ()
virtual ~SedPlot2D ()
Public Member Functions inherited from SedPlot
SedAxis * createXAxis ()
SedAxis * createYAxis ()
double getHeight () const
bool getLegend () const
double getWidth () const
SedAxis * getXAxis ()
const SedAxis * getXAxis () const
SedAxis * getYAxis ()
const SedAxis * getYAxis () const
bool isSetHeight () const
bool isSetLegend () const
bool isSetWidth () const
bool isSetXAxis () const
bool isSetYAxis () const
SedPlot & operator= (const SedPlot &rhs)
SedPlot (const SedPlot &orig)
SedPlot (SedNamespaces *sedmlns)
SedPlot (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setHeight (double height)
int setLegend (bool legend)
int setWidth (double width)
int setXAxis (const SedAxis *xAxis)
int setYAxis (const SedAxis *yAxis)
int unsetHeight ()
int unsetLegend ()
int unsetWidth ()
int unsetXAxis ()
int unsetYAxis ()
virtual ~SedPlot ()
Public Member Functions inherited from SedOutput
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedPlot2D class.
Constructor & Destructor Documentation
SedPlot2D() [1/3]
SedPlot2D::SedPlot2D (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedPlot2D using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedPlot2D.
version an unsigned int, the SED-ML Version to assign to this SedPlot2D.
Referenced by clone().
SedPlot2D() [2/3]
SedPlot2D::SedPlot2D (SedNamespaces * sedmlns)
Creates a new SedPlot2D using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedPlot2D() [3/3]
SedPlot2D::SedPlot2D (const SedPlot2D & orig)
Copy constructor for SedPlot2D.
Parameters
orig the SedPlot2D instance to copy.
References clone().
~SedPlot2D()
SedPlot2D::~SedPlot2D () virtual
Destructor for SedPlot2D.
Member Function Documentation
addCurve()
int SedPlot2D::addCurve (const SedAbstractCurve * sac)
Adds a copy of the given SedAbstractCurve to this SedPlot2D.
Parameters
sac the SedAbstractCurve object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createCurve()
getCurve(const std::string& sid)
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedAbstractCurve::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedPlot2D * SedPlot2D::clone () const virtual
Creates and returns a deep copy of this SedPlot2D object.
Returns
a (deep) copy of this SedPlot2D object.
Reimplemented from SedPlot.
References SedPlot2D().
Referenced by operator=(), and SedPlot2D().
createCurve()
SedCurve * SedPlot2D::createCurve ()
Creates a new SedCurve object, adds it to this SedPlot2D object and returns the SedCurve object created.
Returns
a new SedCurve object instance.
See also
addCurve(const SedAbstractCurve* object)
getCurve(const std::string& sid)
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
createRightYAxis()
SedAxis * SedPlot2D::createRightYAxis ()
Creates a new SedAxis object, adds it to this SedPlot2D object and returns the SedAxis object created.
Returns
a new SedAxis object instance.
createShadedArea()
SedShadedArea * SedPlot2D::createShadedArea ()
Creates a new SedShadedArea object, adds it to this SedPlot2D object and returns the SedShadedArea object created.
Returns
a new SedShadedArea object instance.
See also
addCurve(const SedAbstractCurve* object)
getCurve(const std::string& sid)
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
getAllElements()
List * SedPlot2D::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedPlot.
References SED_ADD_FILTERED_LIST, and SED_ADD_FILTERED_POINTER.
getCurve() [1/4]
SedAbstractCurve * SedPlot2D::getCurve (const std::string & sid)
Get a SedAbstractCurve from the SedPlot2D based on its identifier.
Parameters
sid a string representing the identifier of the SedAbstractCurve to retrieve.
Returns
the SedAbstractCurve in the SedListOfCurves within this SedPlot2D with the given sid or NULL if no such SedAbstractCurve exists.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
getCurve() [2/4]
const SedAbstractCurve * SedPlot2D::getCurve (const std::string & sid) const
Get a SedAbstractCurve from the SedPlot2D based on its identifier.
Parameters
sid a string representing the identifier of the SedAbstractCurve to retrieve.
Returns
the SedAbstractCurve in the SedListOfCurves within this SedPlot2D with the given sid or NULL if no such SedAbstractCurve exists.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
getCurve() [3/4]
SedAbstractCurve * SedPlot2D::getCurve (unsigned int n)
Get a SedAbstractCurve from the SedPlot2D.
Parameters
n an unsigned int representing the index of the SedAbstractCurve to retrieve.
Returns
the nth SedAbstractCurve in the SedListOfCurves within this SedPlot2D or NULL if no such object exists.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(const std::string& sid)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
getCurve() [4/4]
const SedAbstractCurve * SedPlot2D::getCurve (unsigned int n) const
Get a SedAbstractCurve from the SedPlot2D.
Parameters
n an unsigned int representing the index of the SedAbstractCurve to retrieve.
Returns
the nth SedAbstractCurve in the SedListOfCurves within this SedPlot2D or NULL if no such object exists.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(const std::string& sid)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
getCurveByStyle() [1/2]
SedAbstractCurve * SedPlot2D::getCurveByStyle (const std::string & sid)
Get a SedAbstractCurve from the SedPlot2D based on the Style to which it refers.
Parameters
sid a string representing the "style" attribute of the SedAbstractCurve object to retrieve.
Returns
the first SedAbstractCurve in this SedPlot2D based on the given style attribute or NULL if no such SedAbstractCurve exists.
getCurveByStyle() [2/2]
const SedAbstractCurve * SedPlot2D::getCurveByStyle (const std::string & sid) const
Get a SedAbstractCurve from the SedPlot2D based on the Style to which it refers.
Parameters
sid a string representing the "style" attribute of the SedAbstractCurve object to retrieve.
Returns
the first SedAbstractCurve in this SedPlot2D based on the given style attribute or NULL if no such SedAbstractCurve exists.
getCurveByXDataReference() [1/2]
SedAbstractCurve * SedPlot2D::getCurveByXDataReference (const std::string & sid)
Get a SedAbstractCurve from the SedPlot2D based on the XDataReference to which it refers.
Parameters
sid a string representing the "xDataReference" attribute of the SedAbstractCurve object to retrieve.
Returns
the first SedAbstractCurve in this SedPlot2D based on the given xDataReference attribute or NULL if no such SedAbstractCurve exists.
getCurveByXDataReference() [2/2]
const SedAbstractCurve * SedPlot2D::getCurveByXDataReference (const std::string & sid) const
Get a SedAbstractCurve from the SedPlot2D based on the XDataReference to which it refers.
Parameters
sid a string representing the "xDataReference" attribute of the SedAbstractCurve object to retrieve.
Returns
the first SedAbstractCurve in this SedPlot2D based on the given xDataReference attribute or NULL if no such SedAbstractCurve exists.
getElementBySId()
SedBase * SedPlot2D::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedPlot.
References SedBase::getElementBySId().
getElementName()
const std::string & SedPlot2D::getElementName () const virtual
Returns the XML element name of this SedPlot2D object.
For SedPlot2D, the XML element name is always "plot2D".
Returns
the name of this element, i.e. "plot2D".
Reimplemented from SedPlot.
getListOfCurves() [1/2]
SedListOfCurves * SedPlot2D::getListOfCurves ()
Returns the SedListOfCurves from this SedPlot2D.
Returns
the SedListOfCurves from this SedPlot2D.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(const std::string& sid)
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
getListOfCurves() [2/2]
const SedListOfCurves * SedPlot2D::getListOfCurves () const
Returns the SedListOfCurves from this SedPlot2D.
Returns
the SedListOfCurves from this SedPlot2D.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(const std::string& sid)
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
Referenced by SedDocument::sortOrderedObjects().
getNumCurves()
unsigned int SedPlot2D::getNumCurves () const
Get the number of SedAbstractCurve objects in this SedPlot2D.
Returns
the number of SedAbstractCurve objects in this SedPlot2D.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(const std::string& sid)
getCurve(unsigned int n)
removeCurve(const std::string& sid)
removeCurve(unsigned int n)
getRightYAxis() [1/2]
SedAxis * SedPlot2D::getRightYAxis ()
Returns the value of the "rightYAxis" element of this SedPlot2D.
Returns
the value of the "rightYAxis" element of this SedPlot2D as a SedAxis*.
getRightYAxis() [2/2]
const SedAxis * SedPlot2D::getRightYAxis () const
Returns the value of the "rightYAxis" element of this SedPlot2D.
Returns
the value of the "rightYAxis" element of this SedPlot2D as a SedAxis*.
Referenced by SedCurve::getLogY().
getTypeCode()
int SedPlot2D::getTypeCode () const virtual
Returns the libSEDML type code for this SedPlot2D object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_OUTPUT_PLOT2D, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedPlot.
References SEDML_OUTPUT_PLOT2D.
hasRequiredAttributes()
bool SedPlot2D::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedPlot2D object have been set.
Returns
true to indicate that all the required attributes of this SedPlot2D have been set, otherwise false is returned.
Reimplemented from SedPlot.
References SedPlot::hasRequiredAttributes().
hasRequiredElements()
bool SedPlot2D::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedPlot2D object have been set.
Returns
true to indicate that all the required elements of this SedPlot2D have been set, otherwise false is returned.
Note
The required elements for the SedPlot2D object are:
Reimplemented from SedPlot.
References SedPlot::hasRequiredElements().
isSetRightYAxis()
bool SedPlot2D::isSetRightYAxis () const
Predicate returning true if this SedPlot2D's "rightYAxis" element is set.
Returns
true if this SedPlot2D's "rightYAxis" element has been set, otherwise false is returned.
operator=()
SedPlot2D & SedPlot2D::operator= (const SedPlot2D & rhs)
Assignment operator for SedPlot2D.
Parameters
rhs the SedPlot2D object whose values are to be used as the basis of the assignment.
References clone(), and SedPlot::operator=().
removeCurve() [1/2]
SedAbstractCurve * SedPlot2D::removeCurve (const std::string & sid)
Removes the SedAbstractCurve from this SedPlot2D based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedAbstractCurve to remove.
Returns
the SedAbstractCurve in this SedPlot2D based on the identifier or NULL if no such SedAbstractCurve exists.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(const std::string& sid)
getCurve(unsigned int n)
getNumCurves()
removeCurve(unsigned int n)
removeCurve() [2/2]
SedAbstractCurve * SedPlot2D::removeCurve (unsigned int n)
Removes the nth SedAbstractCurve from this SedPlot2D and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAbstractCurve to remove.
Returns
a pointer to the nth SedAbstractCurve in this SedPlot2D.
See also
addCurve(const SedAbstractCurve* object)
createCurve()
getCurve(const std::string& sid)
getCurve(unsigned int n)
getNumCurves()
removeCurve(const std::string& sid)
setRightYAxis()
int SedPlot2D::setRightYAxis (const SedAxis * rightYAxis)
Sets the value of the "rightYAxis" element of this SedPlot2D.
Parameters
rightYAxis SedAxis* value of the "rightYAxis" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedAxis::clone(), and LIBSEDML_OPERATION_SUCCESS.
unsetRightYAxis()
int SedPlot2D::unsetRightYAxis ()
Unsets the value of the "rightYAxis" element of this SedPlot2D.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedPlot2D.h
SedPlot2D.cpp