/**
 * @file    libsedml-config.h
 * @brief   Decides whether to include Unix or Windows configuration variables.
 * @author  Ben Bornstein
 * 
 * <!--------------------------------------------------------------------------
 * This file is part of libSEDML.  Please visit http://sed-ml.org for more
 * information about SEDML, and the latest version of libSEDML.
 *
 * Copyright (C) 2009-2013 jointly by the following organizations: 
 *     1. California Institute of Technology, Pasadena, CA, USA
 *     2. EMBL European Bioinformatics Institute (EBML-EBI), Hinxton, UK
 *  
 * Copyright (C) 2006-2008 by the California Institute of Technology,
 *     Pasadena, CA, USA 
 *  
 * Copyright (C) 2002-2005 jointly by the following organizations: 
 *     1. California Institute of Technology, Pasadena, CA, USA
 *     2. Japan Science and Technology Agency, Japan
 * 
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation.  A copy of the license agreement is provided
 * in the file named "LICENSE.txt" included with this software distribution and
 * also available online as http://sedml.org/software/libsedml/license.html
 * ------------------------------------------------------------------------ -->
 *
 * Some explanations about this file are warranted.  This file includes
 * one of the following (depending on operating system and compiler):
 * 
 * - <tt>libsedml-config-unix.h</tt>
 * - <tt>libsedml-config-win.h</tt>
 * 
 * On Linux, MacOS X, Cygwin, etc., <tt>libsedml-config-unix.h</tt> and
 * <tt>libsedml-package.h</tt> are generated from
 * <tt>libsedml-config-unix.h.in</tt> and <tt>libsedml-package.h.in</tt>,
 * respectively, by the @c configure script at the top level of the libSEDML
 * distribution.
 * 
 * On Windows, we cannot rely on <tt>libsedml-config-win.h</tt> being
 * generated by @c configure, since most developers will not be able to run
 * @c configure in that environment.  Instead, both
 * <tt>libsedml-config-win.h</tt> and <tt>libsedml-package.h</tt> (which see)
 * are stored in the source repository and must be updated by the libSEDML
 * developers as necessary.  The file <tt>libsedml-config-win.h</tt> should
 * rarely, if ever, need to be updated, while <tt>libsedml-package.h</tt>
 * should require minor updates prior to each libsedml release.  This is
 * admittedly not an ideal and fool-proof arrangement; however, at this
 * time it is the best we have been able to find under the circumstances.
 * 
 * Finally, <tt>libsedml-config.h</tt>, <tt>libsedml-package.h</tt>,
 * <tt>libsedml-config-unix.h</tt>, and (for consistency)
 * <tt>libsedml-config-win.h</tt> are all installed by @c "make install".
 */

#ifndef LIBSEDML_CONFIG_H
#define LIBSEDML_CONFIG_H 1

#include <sedml/common/libsedml-namespace.h>

#include <sedml/common/libsedml-config-common.h>

#include <sedml/common/libsedml-version.h>


#endif  /* LIBSEDML_CONFIG_H */

