LIBSEDML API: SedFitExperiment Class Reference
SedFitExperiment Class Reference
#include <SedFitExperiment.h>
Public Member Functions
int addFitMapping (const SedFitMapping *sfm)
virtual SedFitExperiment * clone () const
SedAlgorithm * createAlgorithm ()
SedFitMapping * createFitMapping ()
SedAlgorithm * getAlgorithm ()
const SedAlgorithm * getAlgorithm () const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedFitMapping * getFitMapping (unsigned int n)
const SedFitMapping * getFitMapping (unsigned int n) const
SedFitMapping * getFitMappingByDataSource (const std::string &sid)
const SedFitMapping * getFitMappingByDataSource (const std::string &sid) const
SedFitMapping * getFitMappingByPointWeight (const std::string &sid)
const SedFitMapping * getFitMappingByPointWeight (const std::string &sid) const
SedFitMapping * getFitMappingByTarget (const std::string &sid)
const SedFitMapping * getFitMappingByTarget (const std::string &sid) const
SedListOfFitMappings * getListOfFitMappings ()
const SedListOfFitMappings * getListOfFitMappings () const
unsigned int getNumFitMappings () const
ExperimentType_t getType () const
std::string getTypeAsString () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetAlgorithm () const
bool isSetType () const
SedFitExperiment & operator= (const SedFitExperiment &rhs)
SedFitMapping * removeFitMapping (unsigned int n)
SedFitExperiment (const SedFitExperiment &orig)
SedFitExperiment (SedNamespaces *sedmlns)
SedFitExperiment (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setAlgorithm (const SedAlgorithm *algorithm)
int setType (const ExperimentType_t type)
int setType (const std::string &type)
int unsetAlgorithm ()
int unsetType ()
virtual ~SedFitExperiment ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedFitExperiment class.
Constructor & Destructor Documentation
SedFitExperiment() [1/3]
SedFitExperiment::SedFitExperiment (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedFitExperiment using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedFitExperiment.
version an unsigned int, the SED-ML Version to assign to this SedFitExperiment.
Referenced by clone().
SedFitExperiment() [2/3]
SedFitExperiment::SedFitExperiment (SedNamespaces * sedmlns)
Creates a new SedFitExperiment using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedFitExperiment() [3/3]
SedFitExperiment::SedFitExperiment (const SedFitExperiment & orig)
Copy constructor for SedFitExperiment.
Parameters
orig the SedFitExperiment instance to copy.
References clone().
~SedFitExperiment()
SedFitExperiment::~SedFitExperiment () virtual
Destructor for SedFitExperiment.
Member Function Documentation
addFitMapping()
int SedFitExperiment::addFitMapping (const SedFitMapping * sfm)
Adds a copy of the given SedFitMapping to this SedFitExperiment.
Parameters
sfm the SedFitMapping object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createFitMapping()
getFitMapping(const std::string& sid)
getFitMapping(unsigned int n)
getNumFitMappings()
removeFitMapping(const std::string& sid)
removeFitMapping(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedFitMapping::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedFitExperiment * SedFitExperiment::clone () const virtual
Creates and returns a deep copy of this SedFitExperiment object.
Returns
a (deep) copy of this SedFitExperiment object.
Implements SedBase.
References SedFitExperiment().
Referenced by operator=(), and SedFitExperiment().
createAlgorithm()
SedAlgorithm * SedFitExperiment::createAlgorithm ()
Creates a new SedAlgorithm object, adds it to this SedFitExperiment object and returns the SedAlgorithm object created.
Returns
a new SedAlgorithm object instance.
createFitMapping()
SedFitMapping * SedFitExperiment::createFitMapping ()
Creates a new SedFitMapping object, adds it to this SedFitExperiment object and returns the SedFitMapping object created.
Returns
a new SedFitMapping object instance.
See also
addFitMapping(const SedFitMapping* object)
getFitMapping(const std::string& sid)
getFitMapping(unsigned int n)
getNumFitMappings()
removeFitMapping(const std::string& sid)
removeFitMapping(unsigned int n)
getAlgorithm() [1/2]
SedAlgorithm * SedFitExperiment::getAlgorithm ()
Returns the value of the "algorithm" element of this SedFitExperiment.
Returns
the value of the "algorithm" element of this SedFitExperiment as a SedAlgorithm*.
getAlgorithm() [2/2]
const SedAlgorithm * SedFitExperiment::getAlgorithm () const
Returns the value of the "algorithm" element of this SedFitExperiment.
Returns
the value of the "algorithm" element of this SedFitExperiment as a SedAlgorithm*.
getAllElements()
List * SedFitExperiment::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST, and SED_ADD_FILTERED_POINTER.
getElementBySId()
SedBase * SedFitExperiment::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedFitExperiment::getElementName () const virtual
Returns the XML element name of this SedFitExperiment object.
For SedFitExperiment, the XML element name is always "fitExperiment".
Returns
the name of this element, i.e. "fitExperiment".
Implements SedBase.
getFitMapping() [1/2]
SedFitMapping * SedFitExperiment::getFitMapping (unsigned int n)
Get a SedFitMapping from the SedFitExperiment.
Parameters
n an unsigned int representing the index of the SedFitMapping to retrieve.
Returns
the nth SedFitMapping in the SedListOfFitMappings within this SedFitExperiment or NULL if no such object exists.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
getFitMapping(const std::string& sid)
getNumFitMappings()
removeFitMapping(const std::string& sid)
removeFitMapping(unsigned int n)
getFitMapping() [2/2]
const SedFitMapping * SedFitExperiment::getFitMapping (unsigned int n) const
Get a SedFitMapping from the SedFitExperiment.
Parameters
n an unsigned int representing the index of the SedFitMapping to retrieve.
Returns
the nth SedFitMapping in the SedListOfFitMappings within this SedFitExperiment or NULL if no such object exists.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
getFitMapping(const std::string& sid)
getNumFitMappings()
removeFitMapping(const std::string& sid)
removeFitMapping(unsigned int n)
getFitMappingByDataSource() [1/2]
SedFitMapping * SedFitExperiment::getFitMappingByDataSource (const std::string & sid)
Get a SedFitMapping from the SedFitExperiment based on the DataSource to which it refers.
Parameters
sid a string representing the "dataSource" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedFitExperiment based on the given dataSource attribute or NULL if no such SedFitMapping exists.
getFitMappingByDataSource() [2/2]
const SedFitMapping * SedFitExperiment::getFitMappingByDataSource (const std::string & sid) const
Get a SedFitMapping from the SedFitExperiment based on the DataSource to which it refers.
Parameters
sid a string representing the "dataSource" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedFitExperiment based on the given dataSource attribute or NULL if no such SedFitMapping exists.
getFitMappingByPointWeight() [1/2]
SedFitMapping * SedFitExperiment::getFitMappingByPointWeight (const std::string & sid)
Get a SedFitMapping from the SedFitExperiment based on the PointWeight to which it refers.
Parameters
sid a string representing the "pointWeight" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedFitExperiment based on the given pointWeight attribute or NULL if no such SedFitMapping exists.
getFitMappingByPointWeight() [2/2]
const SedFitMapping * SedFitExperiment::getFitMappingByPointWeight (const std::string & sid) const
Get a SedFitMapping from the SedFitExperiment based on the PointWeight to which it refers.
Parameters
sid a string representing the "pointWeight" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedFitExperiment based on the given pointWeight attribute or NULL if no such SedFitMapping exists.
getFitMappingByTarget() [1/2]
SedFitMapping * SedFitExperiment::getFitMappingByTarget (const std::string & sid)
Get a SedFitMapping from the SedFitExperiment based on the Target to which it refers.
Parameters
sid a string representing the "target" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedFitExperiment based on the given target attribute or NULL if no such SedFitMapping exists.
getFitMappingByTarget() [2/2]
const SedFitMapping * SedFitExperiment::getFitMappingByTarget (const std::string & sid) const
Get a SedFitMapping from the SedFitExperiment based on the Target to which it refers.
Parameters
sid a string representing the "target" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedFitExperiment based on the given target attribute or NULL if no such SedFitMapping exists.
getListOfFitMappings() [1/2]
SedListOfFitMappings * SedFitExperiment::getListOfFitMappings ()
Returns the SedListOfFitMappings from this SedFitExperiment.
Returns
the SedListOfFitMappings from this SedFitExperiment.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
getFitMapping(const std::string& sid)
getFitMapping(unsigned int n)
getNumFitMappings()
removeFitMapping(const std::string& sid)
removeFitMapping(unsigned int n)
getListOfFitMappings() [2/2]
const SedListOfFitMappings * SedFitExperiment::getListOfFitMappings () const
Returns the SedListOfFitMappings from this SedFitExperiment.
Returns
the SedListOfFitMappings from this SedFitExperiment.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
getFitMapping(const std::string& sid)
getFitMapping(unsigned int n)
getNumFitMappings()
removeFitMapping(const std::string& sid)
removeFitMapping(unsigned int n)
getNumFitMappings()
unsigned int SedFitExperiment::getNumFitMappings () const
Get the number of SedFitMapping objects in this SedFitExperiment.
Returns
the number of SedFitMapping objects in this SedFitExperiment.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
getFitMapping(const std::string& sid)
getFitMapping(unsigned int n)
removeFitMapping(const std::string& sid)
removeFitMapping(unsigned int n)
getType()
ExperimentType_t SedFitExperiment::getType () const
Returns the value of the "type" attribute of this SedFitExperiment.
Returns
the value of the "type" attribute of this SedFitExperiment as a ExperimentType_t.
The attribute "type" on a SedFitExperiment object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"SteadyState", TODO:add description
"TimeCourse", TODO:add description
The possible values returned by this method are:
@sbmlconstant{SEDML_EXPERIMENTTYPE_STEADYSTATE, ExperimentType_t}
@sbmlconstant{SEDML_EXPERIMENTTYPE_TIMECOURSE, ExperimentType_t}
@sbmlconstant{SEDML_EXPERIMENTTYPE_INVALID, ExperimentType_t}
getTypeAsString()
std::string SedFitExperiment::getTypeAsString () const
Returns the value of the "type" attribute of this SedFitExperiment.
Returns
the value of the "type" attribute of this SedFitExperiment as a string.
The attribute "type" on a SedFitExperiment object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"SteadyState", TODO:add description
"TimeCourse", TODO:add description
The possible values returned by this method are:
"SteadyState"
"TimeCourse"
"invalid ExperimentType value"
References ExperimentType_toString().
getTypeCode()
int SedFitExperiment::getTypeCode () const virtual
Returns the libSEDML type code for this SedFitExperiment object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_FIT_EXPERIMENT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_FIT_EXPERIMENT.
hasRequiredAttributes()
bool SedFitExperiment::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedFitExperiment object have been set.
Returns
true to indicate that all the required attributes of this SedFitExperiment have been set, otherwise false is returned.
Referenced by SedListOfFitExperiments::addFitExperiment(), and SedParameterEstimationTask::addFitExperiment().
isSetAlgorithm()
bool SedFitExperiment::isSetAlgorithm () const
Predicate returning true if this SedFitExperiment's "algorithm" element is set.
Returns
true if this SedFitExperiment's "algorithm" element has been set, otherwise false is returned.
isSetType()
bool SedFitExperiment::isSetType () const
Predicate returning true if this SedFitExperiment's "type" attribute is set.
Returns
true if this SedFitExperiment's "type" attribute has been set, otherwise false is returned.
The attribute "type" on a SedFitExperiment object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"SteadyState", TODO:add description
"TimeCourse", TODO:add description
References SEDML_EXPERIMENTTYPE_INVALID.
operator=()
SedFitExperiment & SedFitExperiment::operator= (const SedFitExperiment & rhs)
Assignment operator for SedFitExperiment.
Parameters
rhs the SedFitExperiment object whose values are to be used as the basis of the assignment.
References clone(), and SedBase::operator=().
removeFitMapping()
SedFitMapping * SedFitExperiment::removeFitMapping (unsigned int n)
Removes the nth SedFitMapping from this SedFitExperiment and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedFitMapping to remove.
Returns
a pointer to the nth SedFitMapping in this SedFitExperiment.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
getFitMapping(const std::string& sid)
getFitMapping(unsigned int n)
getNumFitMappings()
removeFitMapping(const std::string& sid)
setAlgorithm()
int SedFitExperiment::setAlgorithm (const SedAlgorithm * algorithm)
Sets the value of the "algorithm" element of this SedFitExperiment.
Parameters
algorithm SedAlgorithm* value of the "algorithm" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedAlgorithm::clone(), and LIBSEDML_OPERATION_SUCCESS.
setType() [1/2]
int SedFitExperiment::setType (const ExperimentType_t type)
Sets the value of the "type" attribute of this SedFitExperiment.
Parameters
type intvalue of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedFitExperiment object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"SteadyState", TODO:add description
"TimeCourse", TODO:add description
References ExperimentType_isValid(), LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, and SEDML_EXPERIMENTTYPE_INVALID.
setType() [2/2]
int SedFitExperiment::setType (const std::string & type)
Sets the value of the "type" attribute of this SedFitExperiment.
Parameters
type std::string& of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedFitExperiment object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"SteadyState", TODO:add description
"TimeCourse", TODO:add description
References ExperimentType_fromString(), LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, and SEDML_EXPERIMENTTYPE_INVALID.
unsetAlgorithm()
int SedFitExperiment::unsetAlgorithm ()
Unsets the value of the "algorithm" element of this SedFitExperiment.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetType()
int SedFitExperiment::unsetType ()
Unsets the value of the "type" attribute of this SedFitExperiment.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
The attribute "type" on a SedFitExperiment object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"SteadyState", TODO:add description
"TimeCourse", TODO:add description
References LIBSEDML_OPERATION_SUCCESS, and SEDML_EXPERIMENTTYPE_INVALID.
The documentation for this class was generated from the following files:
SedFitExperiment.h
SedFitExperiment.cpp