LIBSEDML API: SedAxis Class Reference
SedAxis Class Reference
#include <SedAxis.h>
Public Member Functions
virtual SedAxis * clone () const
virtual const std::string & getElementName () const
bool getGrid () const
double getMax () const
double getMin () const
bool getReverse () const
const std::string & getStyle () const
AxisType_t getType () const
std::string getTypeAsString () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetGrid () const
bool isSetMax () const
bool isSetMin () const
bool isSetReverse () const
bool isSetStyle () const
bool isSetType () const
SedAxis & operator= (const SedAxis &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedAxis (const SedAxis &orig)
SedAxis (SedNamespaces *sedmlns)
SedAxis (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setGrid (bool grid)
int setMax (double max)
int setMin (double min)
int setReverse (bool reverse)
int setStyle (const std::string &style)
int setType (const AxisType_t type)
int setType (const std::string &type)
int unsetGrid ()
int unsetMax ()
int unsetMin ()
int unsetReverse ()
int unsetStyle ()
int unsetType ()
virtual ~SedAxis ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAxis class.
Constructor & Destructor Documentation
SedAxis() [1/3]
SedAxis::SedAxis (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAxis using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAxis.
version an unsigned int, the SED-ML Version to assign to this SedAxis.
Referenced by clone().
SedAxis() [2/3]
SedAxis::SedAxis (SedNamespaces * sedmlns)
Creates a new SedAxis using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedAxis() [3/3]
SedAxis::SedAxis (const SedAxis & orig)
Copy constructor for SedAxis.
Parameters
orig the SedAxis instance to copy.
~SedAxis()
SedAxis::~SedAxis () virtual
Destructor for SedAxis.
Member Function Documentation
clone()
SedAxis * SedAxis::clone () const virtual
Creates and returns a deep copy of this SedAxis object.
Returns
a (deep) copy of this SedAxis object.
Implements SedBase.
References SedAxis().
Referenced by SedPlot2D::setRightYAxis(), SedPlot::setXAxis(), SedPlot::setYAxis(), and SedPlot3D::setZAxis().
getElementName()
const std::string & SedAxis::getElementName () const virtual
Returns the XML element name of this SedAxis object.
For SedAxis, the XML element name is always "axis".
Returns
the name of this element, i.e. "axis".
Implements SedBase.
getGrid()
bool SedAxis::getGrid () const
Returns the value of the "grid" attribute of this SedAxis.
Returns
the value of the "grid" attribute of this SedAxis as a boolean.
getMax()
double SedAxis::getMax () const
Returns the value of the "max" attribute of this SedAxis.
Returns
the value of the "max" attribute of this SedAxis as a double.
getMin()
double SedAxis::getMin () const
Returns the value of the "min" attribute of this SedAxis.
Returns
the value of the "min" attribute of this SedAxis as a double.
getReverse()
bool SedAxis::getReverse () const
Returns the value of the "reverse" attribute of this SedAxis.
Returns
the value of the "reverse" attribute of this SedAxis as a boolean.
getStyle()
const std::string & SedAxis::getStyle () const
Returns the value of the "style" attribute of this SedAxis.
Returns
the value of the "style" attribute of this SedAxis as a string.
getType()
AxisType_t SedAxis::getType () const
Returns the value of the "type" attribute of this SedAxis.
Returns
the value of the "type" attribute of this SedAxis as a AxisType_t.
The attribute "type" on a SedAxis object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"linear", TODO:add description
"log10", TODO:add description
The possible values returned by this method are:
@sbmlconstant{SEDML_AXISTYPE_LINEAR, AxisType_t}
@sbmlconstant{SEDML_AXISTYPE_LOG10, AxisType_t}
@sbmlconstant{SEDML_AXISTYPE_INVALID, AxisType_t}
Referenced by SedAbstractCurve::getLogX(), SedSurface::getLogX(), SedCurve::getLogY(), SedSurface::getLogY(), and SedSurface::getLogZ().
getTypeAsString()
std::string SedAxis::getTypeAsString () const
Returns the value of the "type" attribute of this SedAxis.
Returns
the value of the "type" attribute of this SedAxis as a string.
The attribute "type" on a SedAxis object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"linear", TODO:add description
"log10", TODO:add description
The possible values returned by this method are:
"linear"
"log10"
"invalid AxisType value"
References AxisType_toString().
getTypeCode()
int SedAxis::getTypeCode () const virtual
Returns the libSEDML type code for this SedAxis object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_AXIS, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_AXIS.
hasRequiredAttributes()
bool SedAxis::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAxis object have been set.
Returns
true to indicate that all the required attributes of this SedAxis have been set, otherwise false is returned.
Note
The required attributes for the SedAxis object are:
"type"
References isSetType().
isSetGrid()
bool SedAxis::isSetGrid () const
Predicate returning true if this SedAxis's "grid" attribute is set.
Returns
true if this SedAxis's "grid" attribute has been set, otherwise false is returned.
Referenced by unsetGrid().
isSetMax()
bool SedAxis::isSetMax () const
Predicate returning true if this SedAxis's "max" attribute is set.
Returns
true if this SedAxis's "max" attribute has been set, otherwise false is returned.
Referenced by unsetMax().
isSetMin()
bool SedAxis::isSetMin () const
Predicate returning true if this SedAxis's "min" attribute is set.
Returns
true if this SedAxis's "min" attribute has been set, otherwise false is returned.
Referenced by unsetMin().
isSetReverse()
bool SedAxis::isSetReverse () const
Predicate returning true if this SedAxis's "reverse" attribute is set.
Returns
true if this SedAxis's "reverse" attribute has been set, otherwise false is returned.
Referenced by unsetReverse().
isSetStyle()
bool SedAxis::isSetStyle () const
Predicate returning true if this SedAxis's "style" attribute is set.
Returns
true if this SedAxis's "style" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetType()
bool SedAxis::isSetType () const
Predicate returning true if this SedAxis's "type" attribute is set.
Returns
true if this SedAxis's "type" attribute has been set, otherwise false is returned.
The attribute "type" on a SedAxis object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"linear", TODO:add description
"log10", TODO:add description
References SEDML_AXISTYPE_INVALID.
Referenced by SedAbstractCurve::getLogX(), SedSurface::getLogX(), SedCurve::getLogY(), SedSurface::getLogY(), SedSurface::getLogZ(), and hasRequiredAttributes().
operator=()
SedAxis & SedAxis::operator= (const SedAxis & rhs)
Assignment operator for SedAxis.
Parameters
rhs the SedAxis object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
renameSIdRefs()
void SedAxis::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetStyle(), and setStyle().
setGrid()
int SedAxis::setGrid (bool grid)
Sets the value of the "grid" attribute of this SedAxis.
Parameters
grid bool value of the "grid" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setMax()
int SedAxis::setMax (double max)
Sets the value of the "max" attribute of this SedAxis.
Parameters
max double value of the "max" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setMin()
int SedAxis::setMin (double min)
Sets the value of the "min" attribute of this SedAxis.
Parameters
min double value of the "min" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setReverse()
int SedAxis::setReverse (bool reverse)
Sets the value of the "reverse" attribute of this SedAxis.
Parameters
reverse bool value of the "reverse" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setStyle()
int SedAxis::setStyle (const std::string & style)
Sets the value of the "style" attribute of this SedAxis.
Parameters
style std::string& value of the "style" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setType() [1/2]
int SedAxis::setType (const AxisType_t type)
Sets the value of the "type" attribute of this SedAxis.
Parameters
type intvalue of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedAxis object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"linear", TODO:add description
"log10", TODO:add description
References AxisType_isValid(), LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, and SEDML_AXISTYPE_INVALID.
setType() [2/2]
int SedAxis::setType (const std::string & type)
Sets the value of the "type" attribute of this SedAxis.
Parameters
type std::string& of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedAxis object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"linear", TODO:add description
"log10", TODO:add description
References AxisType_fromString(), LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, and SEDML_AXISTYPE_INVALID.
unsetGrid()
int SedAxis::unsetGrid ()
Unsets the value of the "grid" attribute of this SedAxis.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetGrid(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetMax()
int SedAxis::unsetMax ()
Unsets the value of the "max" attribute of this SedAxis.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetMax(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetMin()
int SedAxis::unsetMin ()
Unsets the value of the "min" attribute of this SedAxis.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetMin(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetReverse()
int SedAxis::unsetReverse ()
Unsets the value of the "reverse" attribute of this SedAxis.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetReverse(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetStyle()
int SedAxis::unsetStyle ()
Unsets the value of the "style" attribute of this SedAxis.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetType()
int SedAxis::unsetType ()
Unsets the value of the "type" attribute of this SedAxis.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
The attribute "type" on a SedAxis object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"linear", TODO:add description
"log10", TODO:add description
References LIBSEDML_OPERATION_SUCCESS, and SEDML_AXISTYPE_INVALID.
The documentation for this class was generated from the following files:
SedAxis.h
SedAxis.cpp