LIBSEDML API: SedOutput Class Reference
SedOutput Class Reference
#include <SedOutput.h>
Public Member Functions
virtual SedOutput * clone () const
virtual const std::string & getElementName () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedOutput class.
Constructor & Destructor Documentation
SedOutput() [1/3]
SedOutput::SedOutput (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedOutput using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedOutput.
version an unsigned int, the SED-ML Version to assign to this SedOutput.
Referenced by clone().
SedOutput() [2/3]
SedOutput::SedOutput (SedNamespaces * sedmlns)
Creates a new SedOutput using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedOutput() [3/3]
SedOutput::SedOutput (const SedOutput & orig)
Copy constructor for SedOutput.
Parameters
orig the SedOutput instance to copy.
~SedOutput()
SedOutput::~SedOutput () virtual
Destructor for SedOutput.
Member Function Documentation
clone()
SedOutput * SedOutput::clone () const virtual
Creates and returns a deep copy of this SedOutput object.
Returns
a (deep) copy of this SedOutput object.
Implements SedBase.
Reimplemented in SedWaterfallPlot, SedReport, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationResultPlot, SedParameterEstimationReport, and SedFigure.
References SedOutput().
getElementName()
const std::string & SedOutput::getElementName () const virtual
Returns the XML element name of this SedOutput object.
For SedOutput, the XML element name is always "output".
Returns
the name of this element, i.e. "output".
Implements SedBase.
Reimplemented in SedWaterfallPlot, SedReport, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationResultPlot, SedParameterEstimationReport, and SedFigure.
getTypeCode()
int SedOutput::getTypeCode () const virtual
Returns the libSEDML type code for this SedOutput object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_OUTPUT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
Reimplemented in SedWaterfallPlot, SedReport, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationResultPlot, SedParameterEstimationReport, and SedFigure.
References SEDML_OUTPUT.
Referenced by SedDocument::sortOrderedObjects().
hasRequiredAttributes()
bool SedOutput::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedOutput object have been set.
Returns
true to indicate that all the required attributes of this SedOutput have been set, otherwise false is returned.
Reimplemented in SedWaterfallPlot, SedReport, SedPlot3D, SedPlot2D, SedPlot, SedParameterEstimationResultPlot, SedParameterEstimationReport, and SedFigure.
Referenced by SedDocument::addOutput(), SedListOfOutputs::addOutput(), SedFigure::hasRequiredAttributes(), SedParameterEstimationReport::hasRequiredAttributes(), SedPlot::hasRequiredAttributes(), and SedReport::hasRequiredAttributes().
isSedFigure()
bool SedOutput::isSedFigure () const virtual
Predicate returning true if this abstract "SedOutput" is of type SedFigure
Returns
true if this abstract "SedOutput" is of type SedFigure, false otherwise
isSedParameterEstimationResultPlot()
bool SedOutput::isSedParameterEstimationResultPlot () const virtual
Predicate returning true if this abstract "SedOutput" is of type SedParameterEstimationResultPlot
Returns
true if this abstract "SedOutput" is of type SedParameterEstimationResultPlot, false otherwise
isSedPlot2D()
bool SedOutput::isSedPlot2D () const virtual
Predicate returning true if this abstract "SedOutput" is of type SedPlot2D
Returns
true if this abstract "SedOutput" is of type SedPlot2D, false otherwise
isSedPlot3D()
bool SedOutput::isSedPlot3D () const virtual
Predicate returning true if this abstract "SedOutput" is of type SedPlot3D
Returns
true if this abstract "SedOutput" is of type SedPlot3D, false otherwise
isSedReport()
bool SedOutput::isSedReport () const virtual
Predicate returning true if this abstract "SedOutput" is of type SedReport
Returns
true if this abstract "SedOutput" is of type SedReport, false otherwise
operator=()
SedOutput & SedOutput::operator= (const SedOutput & rhs)
Assignment operator for SedOutput.
Parameters
rhs the SedOutput object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
Referenced by SedFigure::operator=(), SedParameterEstimationReport::operator=(), SedPlot::operator=(), and SedReport::operator=().
The documentation for this class was generated from the following files:
SedOutput.h
SedOutput.cpp