LIBSEDML API: SedmlEnumerations.cpp File Reference
SedmlEnumerations.cpp File Reference
Implementation of SedmlEnumerations.
#include <string>
#include <sedml/common/SedmlEnumerations.h>
Functions
AxisType_t AxisType_fromString (const char *code)
int AxisType_isValid (AxisType_t at)
int AxisType_isValidString (const char *code)
const char * AxisType_toString (AxisType_t at)
CurveType_t CurveType_fromString (const char *code)
int CurveType_isValid (CurveType_t ct)
int CurveType_isValidString (const char *code)
const char * CurveType_toString (CurveType_t ct)
ExperimentType_t ExperimentType_fromString (const char *code)
int ExperimentType_isValid (ExperimentType_t et)
int ExperimentType_isValidString (const char *code)
const char * ExperimentType_toString (ExperimentType_t et)
LineType_t LineType_fromString (const char *code)
int LineType_isValid (LineType_t lt)
int LineType_isValidString (const char *code)
const char * LineType_toString (LineType_t lt)
MappingType_t MappingType_fromString (const char *code)
int MappingType_isValid (MappingType_t mt)
int MappingType_isValidString (const char *code)
const char * MappingType_toString (MappingType_t mt)
MarkerType_t MarkerType_fromString (const char *code)
int MarkerType_isValid (MarkerType_t mt)
int MarkerType_isValidString (const char *code)
const char * MarkerType_toString (MarkerType_t mt)
ScaleType_t ScaleType_fromString (const char *code)
int ScaleType_isValid (ScaleType_t st)
int ScaleType_isValidString (const char *code)
const char * ScaleType_toString (ScaleType_t st)
SurfaceType_t SurfaceType_fromString (const char *code)
int SurfaceType_isValid (SurfaceType_t st)
int SurfaceType_isValidString (const char *code)
const char * SurfaceType_toString (SurfaceType_t st)
Detailed Description
Implementation of SedmlEnumerations.
Author
DEVISER
Function Documentation
AxisType_fromString()
AxisType_t AxisType_fromString (const char * code)
Returns the AxisType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_AXISTYPE_INVALID, AxisType_t} if there is no such match.
Parameters
code the string to convert to a AxisType_t.
Returns
the corresponding AxisType_t or @sbmlconstant{SEDML_AXISTYPE_INVALID, AxisType_t} if no match is found.
Note
The matching is case-sensitive: "linear" will return @sbmlconstant{SEDML_AXISTYPE_LINEAR, AxisType_t}, but "Linear" will return @sbmlconstant{SEDML_AXISTYPE_INVALID, AxisType_t}.
Referenced by AxisType_isValidString(), and SedAxis::setType().
AxisType_isValid()
int AxisType_isValid (AxisType_t at)
Predicate returning 1 (true) or 0 (false) depending on whether the given AxisType_t is valid.
Parameters
at the AxisType_t enumeration to query.
Returns
1 (true) if the AxisType_t is @sbmlconstant{SEDML_AXISTYPE_LINEAR, AxisType_t}, or @sbmlconstant{SEDML_AXISTYPE_LOG10, AxisType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_AXISTYPE_INVALID, AxisType_t}).
References SEDML_AXISTYPE_INVALID, and SEDML_AXISTYPE_LINEAR.
Referenced by AxisType_isValidString(), and SedAxis::setType().
AxisType_isValidString()
int AxisType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid AxisType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "linear", "log10", or "invalid AxisType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "linear" will return 1 (true), but "Linear" will return 0 (false).
References AxisType_fromString(), and AxisType_isValid().
AxisType_toString()
const char* AxisType_toString (AxisType_t at)
Returns the string version of the provided AxisType_t enumeration.
Parameters
at the AxisType_t enumeration value to convert.
Returns
A string corresponding to the given type: "linear", "log10", "invalid AxisType value", or NULL if the value is @sbmlconstant{SEDML_AXISTYPE_INVALID, AxisType_t} or another invalid enumeration value.
References SEDML_AXISTYPE_INVALID, and SEDML_AXISTYPE_LINEAR.
Referenced by SedAxis::getTypeAsString(), and SedAxis_getTypeAsString().
CurveType_fromString()
CurveType_t CurveType_fromString (const char * code)
Returns the CurveType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_CURVETYPE_INVALID, CurveType_t} if there is no such match.
Parameters
code the string to convert to a CurveType_t.
Returns
the corresponding CurveType_t or @sbmlconstant{SEDML_CURVETYPE_INVALID, CurveType_t} if no match is found.
Note
The matching is case-sensitive: "points" will return @sbmlconstant{SEDML_CURVETYPE_POINTS, CurveType_t}, but "Points" will return @sbmlconstant{SEDML_CURVETYPE_INVALID, CurveType_t}.
Referenced by CurveType_isValidString(), and SedCurve::setType().
CurveType_isValid()
int CurveType_isValid (CurveType_t ct)
Predicate returning 1 (true) or 0 (false) depending on whether the given CurveType_t is valid.
Parameters
ct the CurveType_t enumeration to query.
Returns
1 (true) if the CurveType_t is @sbmlconstant{SEDML_CURVETYPE_POINTS, CurveType_t}, @sbmlconstant{SEDML_CURVETYPE_BAR, CurveType_t}, @sbmlconstant{SEDML_CURVETYPE_BARSTACKED, CurveType_t}, @sbmlconstant{SEDML_CURVETYPE_HORIZONTALBAR, CurveType_t}, or @sbmlconstant{SEDML_CURVETYPE_HORIZONTALBARSTACKED, CurveType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_CURVETYPE_INVALID, CurveType_t}).
References SEDML_CURVETYPE_INVALID, and SEDML_CURVETYPE_POINTS.
Referenced by CurveType_isValidString(), and SedCurve::setType().
CurveType_isValidString()
int CurveType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid CurveType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "points", "bar", "barStacked", "horizontalBar", "horizontalBarStacked", or "invalid CurveType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "points" will return 1 (true), but "Points" will return 0 (false).
References CurveType_fromString(), and CurveType_isValid().
CurveType_toString()
const char* CurveType_toString (CurveType_t ct)
Returns the string version of the provided CurveType_t enumeration.
Parameters
ct the CurveType_t enumeration value to convert.
Returns
A string corresponding to the given type: "points", "bar", "barStacked", "horizontalBar", "horizontalBarStacked", "invalid CurveType value", or NULL if the value is @sbmlconstant{SEDML_CURVETYPE_INVALID, CurveType_t} or another invalid enumeration value.
References SEDML_CURVETYPE_INVALID, and SEDML_CURVETYPE_POINTS.
Referenced by SedCurve::getTypeAsString(), and SedCurve_getTypeAsString().
ExperimentType_fromString()
ExperimentType_t ExperimentType_fromString (const char * code)
Returns the ExperimentType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_EXPERIMENTTYPE_INVALID, ExperimentType_t} if there is no such match.
Parameters
code the string to convert to a ExperimentType_t.
Returns
the corresponding ExperimentType_t or @sbmlconstant{SEDML_EXPERIMENTTYPE_INVALID, ExperimentType_t} if no match is found.
Note
The matching is case-sensitive: "steadyState" will return @sbmlconstant{SEDML_EXPERIMENTTYPE_STEADYSTATE, ExperimentType_t}, but "SteadyState" will return @sbmlconstant{SEDML_EXPERIMENTTYPE_INVALID, ExperimentType_t}.
Referenced by ExperimentType_isValidString(), and SedFitExperiment::setType().
ExperimentType_isValid()
int ExperimentType_isValid (ExperimentType_t et)
Predicate returning 1 (true) or 0 (false) depending on whether the given ExperimentType_t is valid.
Parameters
et the ExperimentType_t enumeration to query.
Returns
1 (true) if the ExperimentType_t is @sbmlconstant{SEDML_EXPERIMENTTYPE_STEADYSTATE, ExperimentType_t}, or @sbmlconstant{SEDML_EXPERIMENTTYPE_TIMECOURSE, ExperimentType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_EXPERIMENTTYPE_INVALID, ExperimentType_t}).
References SEDML_EXPERIMENTTYPE_INVALID, and SEDML_EXPERIMENTTYPE_STEADYSTATE.
Referenced by ExperimentType_isValidString(), and SedFitExperiment::setType().
ExperimentType_isValidString()
int ExperimentType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid ExperimentType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "steadyState", "timeCourse", or "invalid ExperimentType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "steadyState" will return 1 (true), but "SteadyState" will return 0 (false).
References ExperimentType_fromString(), and ExperimentType_isValid().
ExperimentType_toString()
const char* ExperimentType_toString (ExperimentType_t et)
Returns the string version of the provided ExperimentType_t enumeration.
Parameters
et the ExperimentType_t enumeration value to convert.
Returns
A string corresponding to the given type: "steadyState", "timeCourse", "invalid ExperimentType value", or NULL if the value is @sbmlconstant{SEDML_EXPERIMENTTYPE_INVALID, ExperimentType_t} or another invalid enumeration value.
References SEDML_EXPERIMENTTYPE_INVALID, and SEDML_EXPERIMENTTYPE_STEADYSTATE.
Referenced by SedFitExperiment::getTypeAsString(), and SedFitExperiment_getTypeAsString().
LineType_fromString()
LineType_t LineType_fromString (const char * code)
Returns the LineType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_LINETYPE_INVALID, LineType_t} if there is no such match.
Parameters
code the string to convert to a LineType_t.
Returns
the corresponding LineType_t or @sbmlconstant{SEDML_LINETYPE_INVALID, LineType_t} if no match is found.
Note
The matching is case-sensitive: "none" will return @sbmlconstant{SEDML_LINETYPE_NONE, LineType_t}, but "None" will return @sbmlconstant{SEDML_LINETYPE_INVALID, LineType_t}.
Referenced by LineType_isValidString(), and SedLine::setType().
LineType_isValid()
int LineType_isValid (LineType_t lt)
Predicate returning 1 (true) or 0 (false) depending on whether the given LineType_t is valid.
Parameters
lt the LineType_t enumeration to query.
Returns
1 (true) if the LineType_t is @sbmlconstant{SEDML_LINETYPE_NONE, LineType_t}, @sbmlconstant{SEDML_LINETYPE_SOLID, LineType_t}, @sbmlconstant{SEDML_LINETYPE_DASH, LineType_t}, @sbmlconstant{SEDML_LINETYPE_DOT, LineType_t}, @sbmlconstant{SEDML_LINETYPE_DASHDOT, LineType_t}, or @sbmlconstant{SEDML_LINETYPE_DASHDOTDOT, LineType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_LINETYPE_INVALID, LineType_t}).
References SEDML_LINETYPE_INVALID, and SEDML_LINETYPE_NONE.
Referenced by LineType_isValidString(), and SedLine::setType().
LineType_isValidString()
int LineType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid LineType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "none", "solid", "dash", "dot", "dashDot", "dashDotDot", or "invalid LineType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "none" will return 1 (true), but "None" will return 0 (false).
References LineType_fromString(), and LineType_isValid().
LineType_toString()
const char* LineType_toString (LineType_t lt)
Returns the string version of the provided LineType_t enumeration.
Parameters
lt the LineType_t enumeration value to convert.
Returns
A string corresponding to the given type: "none", "solid", "dash", "dot", "dashDot", "dashDotDot", "invalid LineType value", or NULL if the value is @sbmlconstant{SEDML_LINETYPE_INVALID, LineType_t} or another invalid enumeration value.
References SEDML_LINETYPE_INVALID, and SEDML_LINETYPE_NONE.
Referenced by SedLine::getTypeAsString(), and SedLine_getTypeAsString().
MappingType_fromString()
MappingType_t MappingType_fromString (const char * code)
Returns the MappingType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_MAPPINGTYPE_INVALID, MappingType_t} if there is no such match.
Parameters
code the string to convert to a MappingType_t.
Returns
the corresponding MappingType_t or @sbmlconstant{SEDML_MAPPINGTYPE_INVALID, MappingType_t} if no match is found.
Note
The matching is case-sensitive: "time" will return @sbmlconstant{SEDML_MAPPINGTYPE_TIME, MappingType_t}, but "Time" will return @sbmlconstant{SEDML_MAPPINGTYPE_INVALID, MappingType_t}.
Referenced by MappingType_isValidString(), and SedFitMapping::setType().
MappingType_isValid()
int MappingType_isValid (MappingType_t mt)
Predicate returning 1 (true) or 0 (false) depending on whether the given MappingType_t is valid.
Parameters
mt the MappingType_t enumeration to query.
Returns
1 (true) if the MappingType_t is @sbmlconstant{SEDML_MAPPINGTYPE_TIME, MappingType_t}, @sbmlconstant{SEDML_MAPPINGTYPE_EXPERIMENTALCONDITION, MappingType_t}, or @sbmlconstant{SEDML_MAPPINGTYPE_OBSERVABLE, MappingType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_MAPPINGTYPE_INVALID, MappingType_t}).
References SEDML_MAPPINGTYPE_INVALID, and SEDML_MAPPINGTYPE_TIME.
Referenced by MappingType_isValidString(), and SedFitMapping::setType().
MappingType_isValidString()
int MappingType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid MappingType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "time", "experimentalCondition", "observable", or "invalid MappingType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "time" will return 1 (true), but "Time" will return 0 (false).
References MappingType_fromString(), and MappingType_isValid().
MappingType_toString()
const char* MappingType_toString (MappingType_t mt)
Returns the string version of the provided MappingType_t enumeration.
Parameters
mt the MappingType_t enumeration value to convert.
Returns
A string corresponding to the given type: "time", "experimentalCondition", "observable", "invalid MappingType value", or NULL if the value is @sbmlconstant{SEDML_MAPPINGTYPE_INVALID, MappingType_t} or another invalid enumeration value.
References SEDML_MAPPINGTYPE_INVALID, and SEDML_MAPPINGTYPE_TIME.
Referenced by SedFitMapping::getTypeAsString(), and SedFitMapping_getTypeAsString().
MarkerType_fromString()
MarkerType_t MarkerType_fromString (const char * code)
Returns the MarkerType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_MARKERTYPE_INVALID, MarkerType_t} if there is no such match.
Parameters
code the string to convert to a MarkerType_t.
Returns
the corresponding MarkerType_t or @sbmlconstant{SEDML_MARKERTYPE_INVALID, MarkerType_t} if no match is found.
Note
The matching is case-sensitive: "none" will return @sbmlconstant{SEDML_MARKERTYPE_NONE, MarkerType_t}, but "None" will return @sbmlconstant{SEDML_MARKERTYPE_INVALID, MarkerType_t}.
Referenced by MarkerType_isValidString(), and SedMarker::setType().
MarkerType_isValid()
int MarkerType_isValid (MarkerType_t mt)
Predicate returning 1 (true) or 0 (false) depending on whether the given MarkerType_t is valid.
Parameters
mt the MarkerType_t enumeration to query.
Returns
1 (true) if the MarkerType_t is @sbmlconstant{SEDML_MARKERTYPE_NONE, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_SQUARE, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_CIRCLE, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_DIAMOND, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_XCROSS, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_PLUS, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_STAR, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_TRIANGLEUP, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_TRIANGLEDOWN, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_TRIANGLELEFT, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_TRIANGLERIGHT, MarkerType_t}, @sbmlconstant{SEDML_MARKERTYPE_HDASH, MarkerType_t}, or @sbmlconstant{SEDML_MARKERTYPE_VDASH, MarkerType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_MARKERTYPE_INVALID, MarkerType_t}).
References SEDML_MARKERTYPE_INVALID, and SEDML_MARKERTYPE_NONE.
Referenced by MarkerType_isValidString(), and SedMarker::setType().
MarkerType_isValidString()
int MarkerType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid MarkerType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "none", "square", "circle", "diamond", "xCross", "plus", "star", "triangleUp", "triangleDown", "triangleLeft", "triangleRight", "hDash", "vDash", or "invalid MarkerType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "none" will return 1 (true), but "None" will return 0 (false).
References MarkerType_fromString(), and MarkerType_isValid().
MarkerType_toString()
const char* MarkerType_toString (MarkerType_t mt)
Returns the string version of the provided MarkerType_t enumeration.
Parameters
mt the MarkerType_t enumeration value to convert.
Returns
A string corresponding to the given type: "none", "square", "circle", "diamond", "xCross", "plus", "star", "triangleUp", "triangleDown", "triangleLeft", "triangleRight", "hDash", "vDash", "invalid MarkerType value", or NULL if the value is @sbmlconstant{SEDML_MARKERTYPE_INVALID, MarkerType_t} or another invalid enumeration value.
References SEDML_MARKERTYPE_INVALID, and SEDML_MARKERTYPE_NONE.
Referenced by SedMarker::getTypeAsString(), and SedMarker_getTypeAsString().
ScaleType_fromString()
ScaleType_t ScaleType_fromString (const char * code)
Returns the ScaleType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_SCALETYPE_INVALID, ScaleType_t} if there is no such match.
Parameters
code the string to convert to a ScaleType_t.
Returns
the corresponding ScaleType_t or @sbmlconstant{SEDML_SCALETYPE_INVALID, ScaleType_t} if no match is found.
Note
The matching is case-sensitive: "linear" will return @sbmlconstant{SEDML_SCALETYPE_LINEAR, ScaleType_t}, but "Linear" will return @sbmlconstant{SEDML_SCALETYPE_INVALID, ScaleType_t}.
Referenced by ScaleType_isValidString(), and SedBounds::setScale().
ScaleType_isValid()
int ScaleType_isValid (ScaleType_t st)
Predicate returning 1 (true) or 0 (false) depending on whether the given ScaleType_t is valid.
Parameters
st the ScaleType_t enumeration to query.
Returns
1 (true) if the ScaleType_t is @sbmlconstant{SEDML_SCALETYPE_LINEAR, ScaleType_t}, @sbmlconstant{SEDML_SCALETYPE_LOG, ScaleType_t}, or @sbmlconstant{SEDML_SCALETYPE_LOG10, ScaleType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_SCALETYPE_INVALID, ScaleType_t}).
References SEDML_SCALETYPE_INVALID, and SEDML_SCALETYPE_LINEAR.
Referenced by ScaleType_isValidString(), and SedBounds::setScale().
ScaleType_isValidString()
int ScaleType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid ScaleType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "linear", "log", "log10", or "invalid ScaleType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "linear" will return 1 (true), but "Linear" will return 0 (false).
References ScaleType_fromString(), and ScaleType_isValid().
ScaleType_toString()
const char* ScaleType_toString (ScaleType_t st)
Returns the string version of the provided ScaleType_t enumeration.
Parameters
st the ScaleType_t enumeration value to convert.
Returns
A string corresponding to the given type: "linear", "log", "log10", "invalid ScaleType value", or NULL if the value is @sbmlconstant{SEDML_SCALETYPE_INVALID, ScaleType_t} or another invalid enumeration value.
References SEDML_SCALETYPE_INVALID, and SEDML_SCALETYPE_LINEAR.
Referenced by SedBounds::getScaleAsString(), and SedBounds_getScaleAsString().
SurfaceType_fromString()
SurfaceType_t SurfaceType_fromString (const char * code)
Returns the SurfaceType_t enumeration corresponding to the given string or @sbmlconstant{SEDML_SURFACETYPE_INVALID, SurfaceType_t} if there is no such match.
Parameters
code the string to convert to a SurfaceType_t.
Returns
the corresponding SurfaceType_t or @sbmlconstant{SEDML_SURFACETYPE_INVALID, SurfaceType_t} if no match is found.
Note
The matching is case-sensitive: "parametricCurve" will return @sbmlconstant{SEDML_SURFACETYPE_PARAMETRICCURVE, SurfaceType_t}, but "ParametricCurve" will return @sbmlconstant{SEDML_SURFACETYPE_INVALID, SurfaceType_t}.
Referenced by SedSurface::setType(), and SurfaceType_isValidString().
SurfaceType_isValid()
int SurfaceType_isValid (SurfaceType_t st)
Predicate returning 1 (true) or 0 (false) depending on whether the given SurfaceType_t is valid.
Parameters
st the SurfaceType_t enumeration to query.
Returns
1 (true) if the SurfaceType_t is @sbmlconstant{SEDML_SURFACETYPE_PARAMETRICCURVE, SurfaceType_t}, @sbmlconstant{SEDML_SURFACETYPE_SURFACEMESH, SurfaceType_t}, @sbmlconstant{SEDML_SURFACETYPE_SURFACECONTOUR, SurfaceType_t}, @sbmlconstant{SEDML_SURFACETYPE_CONTOUR, SurfaceType_t}, @sbmlconstant{SEDML_SURFACETYPE_HEATMAP, SurfaceType_t}, @sbmlconstant{SEDML_SURFACETYPE_STACKEDCURVES, SurfaceType_t}, or @sbmlconstant{SEDML_SURFACETYPE_BAR, SurfaceType_t}; 0 (false) otherwise (including @sbmlconstant{SEDML_SURFACETYPE_INVALID, SurfaceType_t}).
References SEDML_SURFACETYPE_INVALID, and SEDML_SURFACETYPE_PARAMETRICCURVE.
Referenced by SedSurface::setType(), and SurfaceType_isValidString().
SurfaceType_isValidString()
int SurfaceType_isValidString (const char * code)
Predicate returning 1 (true) or 0 (false) depending on whether the given string is a valid SurfaceType_t.
Parameters
code the string to query.
Returns
1 (true) if the string is "parametricCurve", "surfaceMesh", "surfaceContour", "contour", "heatMap", "stackedCurves", "bar", or "invalid SurfaceType value"; 0 (false) otherwise.
Note
The matching is case-sensitive: "parametricCurve" will return 1 (true), but "ParametricCurve" will return 0 (false).
References SurfaceType_fromString(), and SurfaceType_isValid().
SurfaceType_toString()
const char* SurfaceType_toString (SurfaceType_t st)
Returns the string version of the provided SurfaceType_t enumeration.
Parameters
st the SurfaceType_t enumeration value to convert.
Returns
A string corresponding to the given type: "parametricCurve", "surfaceMesh", "surfaceContour", "contour", "heatMap", "stackedCurves", "bar", "invalid SurfaceType value", or NULL if the value is @sbmlconstant{SEDML_SURFACETYPE_INVALID, SurfaceType_t} or another invalid enumeration value.
References SEDML_SURFACETYPE_INVALID, and SEDML_SURFACETYPE_PARAMETRICCURVE.
Referenced by SedSurface::getTypeAsString(), and SedSurface_getTypeAsString().