LIBSEDML API: SedListOf Class Reference
SedListOf Class Reference
#include <SedListOf.h>
Public Member Functions
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual SedListOf * clone () const
virtual SedBase * get (unsigned int n)
virtual const SedBase * get (unsigned int n) const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
virtual int getTypeCode () const
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual SedBase * remove (unsigned int n)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{} TODO:Definition of the SedListOf class.
Constructor & Destructor Documentation
SedListOf() [1/3]
SedListOf::SedListOf (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOf object.
Parameters
level the SED-ML Level; if not assigned, defaults to the value of SEDML_DEFAULT_LEVEL.
version the Version within the SED-ML Level; if not assigned, defaults to the value of SEDML_DEFAULT_VERSION.
References SedBase::hasValidLevelVersionNamespaceCombination().
Referenced by clone().
SedListOf() [2/3]
SedListOf::SedListOf (SedNamespaces * sedmlns)
Creates a new SedListOf with a given SedNamespaces object.
Parameters
sedmlns the set of SED-ML namespaces that this SedListOf should contain.
References SedBase::hasValidLevelVersionNamespaceCombination().
~SedListOf()
SedListOf::~SedListOf () virtual
Destroys this SedListOf and the items inside it.
SedListOf() [3/3]
SedListOf::SedListOf (const SedListOf & orig)
Copy constructor; creates a copy of this SedListOf.
Parameters
orig the SedListOf instance to copy.
References size().
Member Function Documentation
append()
int SedListOf::append (const SedBase * item)
Adds an item to the end of this SedListOf's list of items.
This method makes a clone of the item handed to it. This means that when the SedListOf object is destroyed, the original items will not be destroyed. For a method with an alternative ownership behavior, see the SedListOf::appendAndOwn() method.
Parameters
item the item to be added to the list.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
See also
appendAndOwn(SedBase* disownedItem)
appendFrom(const SedListOf* list)
References appendAndOwn(), clone(), SedBase::clone(), and LIBSEDML_OPERATION_SUCCESS.
Referenced by SedListOfTasks::addAbstractTask(), SedListOfAdjustableParameters::addAdjustableParameter(), SedListOfAlgorithmParameters::addAlgorithmParameter(), SedListOfAppliedDimensions::addAppliedDimension(), SedListOfChanges::addChange(), SedListOfCurves::addCurve(), SedListOfDataDescriptions::addDataDescription(), SedListOfDataGenerators::addDataGenerator(), SedListOfDataSets::addDataSet(), SedListOfDataSources::addDataSource(), SedListOfExperimentReferences::addExperimentReference(), SedListOfFitExperiments::addFitExperiment(), SedListOfFitMappings::addFitMapping(), SedListOfModels::addModel(), SedListOfOutputs::addOutput(), SedListOfParameters::addParameter(), SedListOfRanges::addRange(), SedListOfSimulations::addSimulation(), SedListOfSlices::addSlice(), SedListOfStyles::addStyle(), SedListOfSubPlots::addSubPlot(), SedListOfSubTasks::addSubTask(), SedListOfSurfaces::addSurface(), SedListOfSetValues::addTaskChange(), and SedListOfVariables::addVariable().
appendAndOwn()
int SedListOf::appendAndOwn (SedBase * disownedItem)
Adds an item to the end of this SedListOf's list of items.
This method does not clone the disownedItem handed to it; instead, it assumes ownership of it. This means that when the SedListOf is destroyed, the item will be destroyed along with it. For a method with an alternative ownership behavior, see the SedListOf::append(SedBase* item) method.
Parameters
disownedItem the item to be added to the list.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
See also
append(const SedBase* item)
appendFrom(const SedListOf* list)
References getItemTypeCode(), LIBSEDML_INVALID_OBJECT, LIBSEDML_OPERATION_SUCCESS, and SEDML_UNKNOWN.
Referenced by append(), appendFrom(), SedListOfChanges::createAddXML(), SedListOfAdjustableParameters::createAdjustableParameter(), SedListOfAlgorithmParameters::createAlgorithmParameter(), SedListOfSimulations::createAnalysis(), SedListOfAppliedDimensions::createAppliedDimension(), SedListOfChanges::createChangeAttribute(), SedListOfChanges::createChangeXML(), SedListOfChanges::createComputeChange(), SedListOfCurves::createCurve(), SedListOfDataDescriptions::createDataDescription(), SedListOfDataGenerators::createDataGenerator(), SedListOfRanges::createDataRange(), SedListOfDataSets::createDataSet(), SedListOfDataSources::createDataSource(), SedListOfExperimentReferences::createExperimentReference(), SedListOfOutputs::createFigure(), SedListOfFitExperiments::createFitExperiment(), SedListOfFitMappings::createFitMapping(), SedListOfRanges::createFunctionalRange(), SedListOfModels::createModel(), SedListOfSimulations::createOneStep(), SedListOfParameters::createParameter(), SedListOfOutputs::createParameterEstimationResultPlot(), SedListOfTasks::createParameterEstimationTask(), SedListOfOutputs::createPlot2D(), SedListOfOutputs::createPlot3D(), SedListOfChanges::createRemoveXML(), SedListOfTasks::createRepeatedTask(), SedListOfOutputs::createReport(), SedListOfSetValues::createSetValue(), SedListOfCurves::createShadedArea(), SedListOfSlices::createSlice(), SedListOfSimulations::createSteadyState(), SedListOfStyles::createStyle(), SedListOfSubPlots::createSubPlot(), SedListOfSubTasks::createSubTask(), SedListOfSurfaces::createSurface(), SedListOfTasks::createTask(), SedListOfRanges::createUniformRange(), SedListOfSimulations::createUniformTimeCourse(), SedListOfVariables::createVariable(), and SedListOfRanges::createVectorRange().
appendFrom()
int SedListOf::appendFrom (const SedListOf * list) virtual
Adds a clone of a list of items to this SedListOf's list.
Note that because this clones the objects handed to it, the original items will not be destroyed when this SedListOf object is destroyed.
Parameters
list a list of items to be added.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
See also
append(const SedBase* item)
appendAndOwn(SedBase* disownedItem)
References appendAndOwn(), SedBase::clone(), get(), getItemTypeCode(), LIBSEDML_INVALID_OBJECT, LIBSEDML_OPERATION_SUCCESS, and size().
clear()
void SedListOf::clear (bool doDelete = true)
Removes all items in this SedListOf object.
If parameter doDelete is true (default), all items in this SedListOf object are deleted and cleared, and thus the caller doesn't have to delete those items. Otherwise, all items are cleared only from this SedListOf object; the caller is still responsible for deleting the actual items. (In the latter case, callers are advised to store pointers to all items elsewhere before calling this function.)
Parameters
doDelete if true (default), all items are deleted and cleared. Otherwise, all items are just cleared and not deleted.
Referenced by removeFromParentAndDelete().
clone()
SedListOf * SedListOf::clone () const virtual
Creates and returns a deep copy of this SedListOf object.
Returns
the (deep) copy of this SedListOf object.
Implements SedBase.
Reimplemented in SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, and SedListOfAdjustableParameters.
References SedListOf().
Referenced by append().
get() [1/2]
SedBase * SedListOf::get (unsigned int n) virtual
Get an item from the list.
Parameters
n the index number of the item to get.
Returns
the nth item in this SedListOf items, or a null pointer if the index number n refers to a nonexistent position in this list.
See also
size()
Reimplemented in SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, and SedListOfAdjustableParameters.
References get().
get() [2/2]
const SedBase * SedListOf::get (unsigned int n) const virtual
Get an item from the list.
Parameters
n the index number of the item to get.
Returns
the nth item in this SedListOf items, or a null pointer if the index number n refers to a nonexistent position in this list.
See also
size()
Reimplemented in SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, and SedListOfAdjustableParameters.
Referenced by appendFrom(), get(), SedListOfAdjustableParameters::get(), SedListOfAlgorithmParameters::get(), SedListOfAppliedDimensions::get(), SedListOfChanges::get(), SedListOfCurves::get(), SedListOfDataDescriptions::get(), SedListOfDataGenerators::get(), SedListOfDataSets::get(), SedListOfDataSources::get(), SedListOfExperimentReferences::get(), SedListOfFitExperiments::get(), SedListOfFitMappings::get(), SedListOfModels::get(), SedListOfOutputs::get(), SedListOfParameters::get(), SedListOfRanges::get(), SedListOfSetValues::get(), SedListOfSimulations::get(), SedListOfSlices::get(), SedListOfStyles::get(), SedListOfSubPlots::get(), SedListOfSubTasks::get(), SedListOfSurfaces::get(), SedListOfTasks::get(), SedListOfVariables::get(), getAllElements(), getElementByMetaId(), getElementBySId(), remove(), and SedBase::removeFromParentAndDelete().
getAllElements()
List * SedListOf::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects.
The values returned include all children of the objects in this SedListOf list, nested to an arbitrary depth.
Returns
a List of pointers to all child objects.
Reimplemented from SedBase.
References SedElementFilter::filter(), get(), SedBase::getAllElements(), and size().
getElementByMetaId()
SedBase * SedListOf::getElementByMetaId (const std::string & metaid) virtual
Returns the first child element found with the given meta-identifier.
Parameters
metaid string representing the "metaid" attribute of the object to find.
Returns
the first element found with the given metaid, or NULL if no such object is found.
Reimplemented from SedBase.
References get(), SedBase::getElementByMetaId(), SedBase::getMetaId(), and size().
getElementBySId()
SedBase * SedListOf::getElementBySId (const std::string & id) virtual
Returns the first child element it can find with a specific "id" attribute value, or NULL if no such object is found.
Parameters
id string representing the "id" attribute value of the object to find.
Returns
pointer to the first element found with the given identifier.
Reimplemented from SedBase.
References get(), SedBase::getElementBySId(), SedBase::getId(), and size().
getElementName()
const string & SedListOf::getElementName () const virtual
Returns the XML element name of this object, which for SedListOf, is always "listOf".
Returns
the XML name of this element.
Implements SedBase.
Reimplemented in SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, and SedListOfAdjustableParameters.
getItemTypeCode()
int SedListOf::getItemTypeCode () const virtual
Get the type code of the objects contained in this SedListOf.
Classes that inherit from the SedListOf class should override this method to return the SED-ML type code for the objects contained in this SedListOf. If they do not, this method will return @sedmlconstant{SEDML_UNKNOWN, SedTypeCode_t}
Returns
The SedListOf base class contains no SED-ML objects, and therefore this method returns @sedmlconstant{SEDML_UNKNOWN, SedTypeCode_t}.
See also
getElementName()
getPackageName()
Reimplemented in SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, and SedListOfAdjustableParameters.
References SEDML_UNKNOWN.
Referenced by appendAndOwn(), appendFrom(), and insertAndOwn().
getTypeCode()
int SedListOf::getTypeCode () const virtual
Returns the libSEDML type code for this object, namely, @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t} (default).
Note
The various SedListOf classes mostly differ from each other in what they contain. Hence, one must call getItemTypeCode() to fully determine the class of this SED-ML object.
See also
getItemTypeCode()
getElementName()
Reimplemented from SedBase.
Reimplemented in SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, and SedListOfAdjustableParameters.
References SEDML_LIST_OF.
insert()
int SedListOf::insert (int location, const SedBase * item)
Inserts an item at a given position in this SedListOf's list of items.
This variant of the method makes a clone of the item handed to it. This means that when the SedListOf is destroyed, the original item will not be destroyed.
Parameters
location the location in the list where to insert the item.
item the item to be inserted to the list.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
See also
insertAndOwn(int location, SedBase* item)
References SedBase::clone(), and insertAndOwn().
insertAndOwn()
int SedListOf::insertAndOwn (int location, SedBase * disownedItem)
Inserts an item at a given position in this SedListOf's list of items.
This variant of the method does not make a clone of the disownedItem handed to it. This means that when the SedListOf is destroyed, the original item will be destroyed.
Parameters
location the location where to insert the item
disownedItem the item to be inserted to the list
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
See also
insert(int location, const SedBase* item)
References getItemTypeCode(), LIBSEDML_INVALID_OBJECT, LIBSEDML_OPERATION_SUCCESS, and SEDML_UNKNOWN.
Referenced by insert().
operator=()
SedListOf & SedListOf::operator= (const SedListOf & rhs)
Assignment operator for SedListOf.
References SedBase::operator=(), and size().
Referenced by SedListOfAdjustableParameters::operator=(), SedListOfAlgorithmParameters::operator=(), SedListOfAppliedDimensions::operator=(), SedListOfChanges::operator=(), SedListOfCurves::operator=(), SedListOfDataDescriptions::operator=(), SedListOfDataGenerators::operator=(), SedListOfDataSets::operator=(), SedListOfDataSources::operator=(), SedListOfExperimentReferences::operator=(), SedListOfFitExperiments::operator=(), SedListOfFitMappings::operator=(), SedListOfModels::operator=(), SedListOfOutputs::operator=(), SedListOfParameters::operator=(), SedListOfRanges::operator=(), SedListOfSetValues::operator=(), SedListOfSimulations::operator=(), SedListOfSlices::operator=(), SedListOfStyles::operator=(), SedListOfSubPlots::operator=(), SedListOfSubTasks::operator=(), SedListOfSurfaces::operator=(), SedListOfTasks::operator=(), and SedListOfVariables::operator=().
remove()
SedBase * SedListOf::remove (unsigned int n) virtual
Removes the nth item from this SedListOf list of items and returns it.
The caller owns the returned item and is responsible for deleting it.
Parameters
n the index of the item to remove
See also
size()
Reimplemented in SedListOfVariables, SedListOfTasks, SedListOfSurfaces, SedListOfSubTasks, SedListOfSubPlots, SedListOfStyles, SedListOfSlices, SedListOfSimulations, SedListOfSetValues, SedListOfRanges, SedListOfParameters, SedListOfOutputs, SedListOfModels, SedListOfFitMappings, SedListOfFitExperiments, SedListOfExperimentReferences, SedListOfDataSources, SedListOfDataSets, SedListOfDataGenerators, SedListOfDataDescriptions, SedListOfCurves, SedListOfChanges, SedListOfAppliedDimensions, SedListOfAlgorithmParameters, and SedListOfAdjustableParameters.
References get().
Referenced by SedListOfAdjustableParameters::remove(), SedListOfAlgorithmParameters::remove(), SedListOfAppliedDimensions::remove(), SedListOfChanges::remove(), SedListOfCurves::remove(), SedListOfDataDescriptions::remove(), SedListOfDataGenerators::remove(), SedListOfDataSets::remove(), SedListOfDataSources::remove(), SedListOfExperimentReferences::remove(), SedListOfFitExperiments::remove(), SedListOfFitMappings::remove(), SedListOfModels::remove(), SedListOfOutputs::remove(), SedListOfParameters::remove(), SedListOfRanges::remove(), SedListOfSetValues::remove(), SedListOfSimulations::remove(), SedListOfSlices::remove(), SedListOfStyles::remove(), SedListOfSubPlots::remove(), SedListOfSubTasks::remove(), SedListOfSurfaces::remove(), SedListOfTasks::remove(), SedListOfVariables::remove(), and SedBase::removeFromParentAndDelete().
removeFromParentAndDelete()
int SedListOf::removeFromParentAndDelete () virtual
Removes all items in this SedListOf object and deletes its properties too.
This performs a call to clear() with an argument of true (thus removing all the child objects in the list), followed by calls to various libSEDML unsetFoo methods to delete everything else: CVTerm objects, model history objects, etc.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Reimplemented from SedBase.
References clear(), LIBSEDML_OPERATION_SUCCESS, SedBase::unsetAnnotation(), SedBase::unsetMetaId(), and SedBase::unsetNotes().
size()
unsigned int SedListOf::size () const
Returns number of items in this SedListOf list.
Returns
the number of items in this SedListOf items.
Referenced by appendFrom(), fixNegativeIndex(), getAllElements(), getElementByMetaId(), getElementBySId(), SedListOfTasks::getNumAbstractTasks(), SedListOfAdjustableParameters::getNumAdjustableParameters(), SedListOfAlgorithmParameters::getNumAlgorithmParameters(), SedListOfAppliedDimensions::getNumAppliedDimensions(), SedListOfChanges::getNumChanges(), SedListOfCurves::getNumCurves(), SedListOfDataDescriptions::getNumDataDescriptions(), SedListOfDataGenerators::getNumDataGenerators(), SedListOfDataSets::getNumDataSets(), SedListOfDataSources::getNumDataSources(), SedListOfExperimentReferences::getNumExperimentReferences(), SedListOfFitExperiments::getNumFitExperiments(), SedListOfFitMappings::getNumFitMappings(), SedListOfModels::getNumModels(), SedListOfOutputs::getNumOutputs(), SedListOfParameters::getNumParameters(), SedListOfRanges::getNumRanges(), SedListOfSimulations::getNumSimulations(), SedListOfSlices::getNumSlices(), SedListOfStyles::getNumStyles(), SedListOfSubPlots::getNumSubPlots(), SedListOfSubTasks::getNumSubTasks(), SedListOfSurfaces::getNumSurfaces(), SedListOfSetValues::getNumTaskChanges(), SedListOfVariables::getNumVariables(), operator=(), SedBase::removeFromParentAndDelete(), and SedListOf().
The documentation for this class was generated from the following files:
SedListOf.h
SedListOf.cpp