LIBSEDML API: SedChange Class Reference
SedChange Class Reference
#include <SedChange.h>
Public Member Functions
virtual SedChange * clone () const
virtual const std::string & getElementName () const
const std::string & getTarget () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool isSedAddXML () const
virtual bool isSedChangeAttribute () const
virtual bool isSedChangeXML () const
virtual bool isSedComputeChange () const
virtual bool isSedRemoveXML () const
bool isSetTarget () const
SedChange & operator= (const SedChange &rhs)
SedChange (const SedChange &orig)
SedChange (SedNamespaces *sedmlns)
SedChange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setTarget (const std::string &target)
int unsetTarget ()
virtual ~SedChange ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Static Protected Member Functions
static std::string _trim (const std::string &text)
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedChange class.
Constructor & Destructor Documentation
SedChange() [1/3]
SedChange::SedChange (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedChange using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedChange.
version an unsigned int, the SED-ML Version to assign to this SedChange.
Referenced by clone().
SedChange() [2/3]
SedChange::SedChange (SedNamespaces * sedmlns)
Creates a new SedChange using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedChange() [3/3]
SedChange::SedChange (const SedChange & orig)
Copy constructor for SedChange.
Parameters
orig the SedChange instance to copy.
~SedChange()
SedChange::~SedChange () virtual
Destructor for SedChange.
Member Function Documentation
_trim()
static std::string SedChange::_trim (const std::string & text) static protected
clone()
SedChange * SedChange::clone () const virtual
Creates and returns a deep copy of this SedChange object.
Returns
a (deep) copy of this SedChange object.
Implements SedBase.
Reimplemented in SedRemoveXML, SedComputeChange, SedChangeXML, SedChangeAttribute, and SedAddXML.
References SedChange().
getElementName()
const std::string & SedChange::getElementName () const virtual
Returns the XML element name of this SedChange object.
For SedChange, the XML element name is always "change".
Returns
the name of this element, i.e. "change".
Implements SedBase.
Reimplemented in SedRemoveXML, SedComputeChange, SedChangeXML, SedChangeAttribute, and SedAddXML.
getTarget()
const std::string & SedChange::getTarget () const
Returns the value of the "target" attribute of this SedChange.
Returns
the value of the "target" attribute of this SedChange as a string.
getTypeCode()
int SedChange::getTypeCode () const virtual
Returns the libSEDML type code for this SedChange object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_CHANGE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
Reimplemented in SedRemoveXML, SedComputeChange, SedChangeXML, SedChangeAttribute, and SedAddXML.
References SEDML_CHANGE.
hasRequiredAttributes()
bool SedChange::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedChange object have been set.
Returns
true to indicate that all the required attributes of this SedChange have been set, otherwise false is returned.
Note
The required attributes for the SedChange object are:
"target"
Reimplemented in SedRemoveXML, SedComputeChange, SedChangeXML, SedChangeAttribute, and SedAddXML.
References isSetTarget().
Referenced by SedListOfChanges::addChange(), SedModel::addChange(), SedAddXML::hasRequiredAttributes(), SedChangeAttribute::hasRequiredAttributes(), SedChangeXML::hasRequiredAttributes(), SedComputeChange::hasRequiredAttributes(), and SedRemoveXML::hasRequiredAttributes().
isSedAddXML()
bool SedChange::isSedAddXML () const virtual
Predicate returning true if this abstract "SedChange" is of type SedAddXML
Returns
true if this abstract "SedChange" is of type SedAddXML, false otherwise
isSedChangeAttribute()
bool SedChange::isSedChangeAttribute () const virtual
Predicate returning true if this abstract "SedChange" is of type SedChangeAttribute
Returns
true if this abstract "SedChange" is of type SedChangeAttribute, false otherwise
isSedChangeXML()
bool SedChange::isSedChangeXML () const virtual
Predicate returning true if this abstract "SedChange" is of type SedChangeXML
Returns
true if this abstract "SedChange" is of type SedChangeXML, false otherwise
isSedComputeChange()
bool SedChange::isSedComputeChange () const virtual
Predicate returning true if this abstract "SedChange" is of type SedComputeChange
Returns
true if this abstract "SedChange" is of type SedComputeChange, false otherwise
isSedRemoveXML()
bool SedChange::isSedRemoveXML () const virtual
Predicate returning true if this abstract "SedChange" is of type SedRemoveXML
Returns
true if this abstract "SedChange" is of type SedRemoveXML, false otherwise
isSetTarget()
bool SedChange::isSetTarget () const
Predicate returning true if this SedChange's "target" attribute is set.
Returns
true if this SedChange's "target" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedChange & SedChange::operator= (const SedChange & rhs)
Assignment operator for SedChange.
Parameters
rhs the SedChange object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
Referenced by SedAddXML::operator=(), SedChangeAttribute::operator=(), SedChangeXML::operator=(), SedComputeChange::operator=(), and SedRemoveXML::operator=().
setTarget()
int SedChange::setTarget (const std::string & target)
Sets the value of the "target" attribute of this SedChange.
Parameters
target std::string& value of the "target" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with target = NULL or an empty string is equivalent to calling unsetTarget().
References LIBSEDML_OPERATION_SUCCESS.
unsetTarget()
int SedChange::unsetTarget ()
Unsets the value of the "target" attribute of this SedChange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedChange.h
SedChange.cpp