LIBSEDML API: SedListOfAlgorithmParameters Class Reference
SedListOfAlgorithmParameters Class Reference
#include <SedListOfAlgorithmParameters.h>
Public Member Functions
int addAlgorithmParameter (const SedAlgorithmParameter *sap)
virtual SedListOfAlgorithmParameters * clone () const
SedAlgorithmParameter * createAlgorithmParameter ()
virtual SedAlgorithmParameter * get (const std::string &sid)
virtual const SedAlgorithmParameter * get (const std::string &sid) const
virtual SedAlgorithmParameter * get (unsigned int n)
virtual const SedAlgorithmParameter * get (unsigned int n) const
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
unsigned int getNumAlgorithmParameters () const
virtual int getTypeCode () const
SedListOfAlgorithmParameters & operator= (const SedListOfAlgorithmParameters &rhs)
virtual SedAlgorithmParameter * remove (const std::string &sid)
virtual SedAlgorithmParameter * remove (unsigned int n)
SedListOfAlgorithmParameters (const SedListOfAlgorithmParameters &orig)
SedListOfAlgorithmParameters (SedNamespaces *sedmlns)
SedListOfAlgorithmParameters (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedListOfAlgorithmParameters ()
Public Member Functions inherited from SedListOf
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedListOfAlgorithmParameters class.
Constructor & Destructor Documentation
SedListOfAlgorithmParameters() [1/3]
SedListOfAlgorithmParameters::SedListOfAlgorithmParameters (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOfAlgorithmParameters using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedListOfAlgorithmParameters.
version an unsigned int, the SED-ML Version to assign to this SedListOfAlgorithmParameters.
Referenced by clone().
SedListOfAlgorithmParameters() [2/3]
SedListOfAlgorithmParameters::SedListOfAlgorithmParameters (SedNamespaces * sedmlns)
Creates a new SedListOfAlgorithmParameters using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedListOfAlgorithmParameters() [3/3]
SedListOfAlgorithmParameters::SedListOfAlgorithmParameters (const SedListOfAlgorithmParameters & orig)
Copy constructor for SedListOfAlgorithmParameters.
Parameters
orig the SedListOfAlgorithmParameters instance to copy.
~SedListOfAlgorithmParameters()
SedListOfAlgorithmParameters::~SedListOfAlgorithmParameters () virtual
Destructor for SedListOfAlgorithmParameters.
Member Function Documentation
addAlgorithmParameter()
int SedListOfAlgorithmParameters::addAlgorithmParameter (const SedAlgorithmParameter * sap)
Adds a copy of the given SedAlgorithmParameter to this SedListOfAlgorithmParameters.
Parameters
sap the SedAlgorithmParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createAlgorithmParameter()
get(const std::string& sid)
get(unsigned int n)
getNumAlgorithmParameters()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::append(), SedBase::getLevel(), SedBase::getVersion(), SedAlgorithmParameter::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedListOfAlgorithmParameters * SedListOfAlgorithmParameters::clone () const virtual
Creates and returns a deep copy of this SedListOfAlgorithmParameters object.
Returns
a (deep) copy of this SedListOfAlgorithmParameters object.
Reimplemented from SedListOf.
References SedListOfAlgorithmParameters().
createAlgorithmParameter()
SedAlgorithmParameter * SedListOfAlgorithmParameters::createAlgorithmParameter ()
Creates a new SedAlgorithmParameter object, adds it to this SedListOfAlgorithmParameters object and returns the SedAlgorithmParameter object created.
Returns
a new SedAlgorithmParameter object instance.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
get(const std::string& sid)
get(unsigned int n)
getNumAlgorithmParameters()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
get() [1/4]
SedAlgorithmParameter * SedListOfAlgorithmParameters::get (const std::string & sid) virtual
Get a SedAlgorithmParameter from the SedListOfAlgorithmParameters based on its identifier.
Parameters
sid a string representing the identifier of the SedAlgorithmParameter to retrieve.
Returns
the SedAlgorithmParameter in this SedListOfAlgorithmParameters with the given sid or NULL if no such SedAlgorithmParameter exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
get(unsigned int n)
getNumAlgorithmParameters()
remove(const std::string& sid)
remove(unsigned int n)
References get().
get() [2/4]
const SedAlgorithmParameter * SedListOfAlgorithmParameters::get (const std::string & sid) const virtual
Get a SedAlgorithmParameter from the SedListOfAlgorithmParameters based on its identifier.
Parameters
sid a string representing the identifier of the SedAlgorithmParameter to retrieve.
Returns
the SedAlgorithmParameter in this SedListOfAlgorithmParameters with the given sid or NULL if no such SedAlgorithmParameter exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
get(unsigned int n)
getNumAlgorithmParameters()
remove(const std::string& sid)
remove(unsigned int n)
get() [3/4]
SedAlgorithmParameter * SedListOfAlgorithmParameters::get (unsigned int n) virtual
Get a SedAlgorithmParameter from the SedListOfAlgorithmParameters.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in this SedListOfAlgorithmParameters or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
get(const std::string& sid)
getNumAlgorithmParameters()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
Referenced by get().
get() [4/4]
const SedAlgorithmParameter * SedListOfAlgorithmParameters::get (unsigned int n) const virtual
Get a SedAlgorithmParameter from the SedListOfAlgorithmParameters.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in this SedListOfAlgorithmParameters or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
get(const std::string& sid)
getNumAlgorithmParameters()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
getElementName()
const std::string & SedListOfAlgorithmParameters::getElementName () const virtual
Returns the XML element name of this SedListOfAlgorithmParameters object.
For SedListOfAlgorithmParameters, the XML element name is always "listOfAlgorithmParameters".
Returns
the name of this element, i.e. "listOfAlgorithmParameters".
Reimplemented from SedListOf.
getItemTypeCode()
int SedListOfAlgorithmParameters::getItemTypeCode () const virtual
Returns the libSEDML type code for the SED-ML objects contained in this SedListOfAlgorithmParameters object.
Returns
the SED-ML typecode for the objects contained in this SedListOfAlgorithmParameters: @sedmlconstant{SEDML_SIMULATION_ALGORITHM_PARAMETER, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedListOf.
References SEDML_SIMULATION_ALGORITHM_PARAMETER.
getNumAlgorithmParameters()
unsigned int SedListOfAlgorithmParameters::getNumAlgorithmParameters () const
Get the number of SedAlgorithmParameter objects in this SedListOfAlgorithmParameters.
Returns
the number of SedAlgorithmParameter objects in this SedListOfAlgorithmParameters.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
get(const std::string& sid)
get(unsigned int n)
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::size().
getTypeCode()
int SedListOfAlgorithmParameters::getTypeCode () const virtual
Returns the libSEDML type code for this SedListOfAlgorithmParameters object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Reimplemented from SedListOf.
References SEDML_LIST_OF.
operator=()
SedListOfAlgorithmParameters & SedListOfAlgorithmParameters::operator= (const SedListOfAlgorithmParameters & rhs)
Assignment operator for SedListOfAlgorithmParameters.
Parameters
rhs the SedListOfAlgorithmParameters object whose values are to be used as the basis of the assignment.
References SedListOf::operator=().
remove() [1/2]
SedAlgorithmParameter * SedListOfAlgorithmParameters::remove (const std::string & sid) virtual
Removes the SedAlgorithmParameter from this SedListOfAlgorithmParameters based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedAlgorithmParameter to remove.
Returns
the SedAlgorithmParameter in this SedListOfAlgorithmParameters based on the identifier or NULL if no such SedAlgorithmParameter exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
get(const std::string& sid)
get(unsigned int n)
getNumAlgorithmParameters()
remove(unsigned int n)
remove() [2/2]
SedAlgorithmParameter * SedListOfAlgorithmParameters::remove (unsigned int n) virtual
Removes the nth SedAlgorithmParameter from this SedListOfAlgorithmParameters and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to remove.
Returns
a pointer to the nth SedAlgorithmParameter in this SedListOfAlgorithmParameters.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
get(const std::string& sid)
get(unsigned int n)
getNumAlgorithmParameters()
remove(const std::string& sid)
Reimplemented from SedListOf.
References SedListOf::remove().
The documentation for this class was generated from the following files:
SedListOfAlgorithmParameters.h
SedListOfAlgorithmParameters.cpp