LIBSEDML API: SedParameterEstimationTask Class Reference
SedParameterEstimationTask Class Reference
#include <SedParameterEstimationTask.h>
Public Member Functions
int addAdjustableParameter (const SedAdjustableParameter *sap)
int addFitExperiment (const SedFitExperiment *sfe)
virtual SedParameterEstimationTask * clone () const
SedAdjustableParameter * createAdjustableParameter ()
SedAlgorithm * createAlgorithm ()
SedFitExperiment * createFitExperiment ()
SedLeastSquareObjectiveFunction * createLeastSquareObjectiveFunction ()
SedAdjustableParameter * getAdjustableParameter (unsigned int n)
const SedAdjustableParameter * getAdjustableParameter (unsigned int n) const
SedAdjustableParameter * getAdjustableParameterByModelReference (const std::string &sid)
const SedAdjustableParameter * getAdjustableParameterByModelReference (const std::string &sid) const
SedAlgorithm * getAlgorithm ()
const SedAlgorithm * getAlgorithm () const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedFitExperiment * getFitExperiment (const std::string &sid)
const SedFitExperiment * getFitExperiment (const std::string &sid) const
SedFitExperiment * getFitExperiment (unsigned int n)
const SedFitExperiment * getFitExperiment (unsigned int n) const
SedListOfAdjustableParameters * getListOfAdjustableParameters ()
const SedListOfAdjustableParameters * getListOfAdjustableParameters () const
SedListOfFitExperiments * getListOfFitExperiments ()
const SedListOfFitExperiments * getListOfFitExperiments () const
unsigned int getNumAdjustableParameters () const
unsigned int getNumFitExperiments () const
SedObjective * getObjective ()
const SedObjective * getObjective () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetAlgorithm () const
bool isSetObjective () const
SedParameterEstimationTask & operator= (const SedParameterEstimationTask &rhs)
SedAdjustableParameter * removeAdjustableParameter (unsigned int n)
SedFitExperiment * removeFitExperiment (const std::string &sid)
SedFitExperiment * removeFitExperiment (unsigned int n)
SedParameterEstimationTask (const SedParameterEstimationTask &orig)
SedParameterEstimationTask (SedNamespaces *sedmlns)
SedParameterEstimationTask (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setAlgorithm (const SedAlgorithm *algorithm)
int setObjective (const SedObjective *objective)
int unsetAlgorithm ()
int unsetObjective ()
virtual ~SedParameterEstimationTask ()
Public Member Functions inherited from SedAbstractTask
virtual bool isSedParameterEstimationTask () const
virtual bool isSedRepeatedTask () const
virtual bool isSedTask () const
SedAbstractTask & operator= (const SedAbstractTask &rhs)
SedAbstractTask (const SedAbstractTask &orig)
SedAbstractTask (SedNamespaces *sedmlns)
SedAbstractTask (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedAbstractTask ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedParameterEstimationTask class.
Constructor & Destructor Documentation
SedParameterEstimationTask() [1/3]
SedParameterEstimationTask::SedParameterEstimationTask (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedParameterEstimationTask using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedParameterEstimationTask.
version an unsigned int, the SED-ML Version to assign to this SedParameterEstimationTask.
Referenced by clone().
SedParameterEstimationTask() [2/3]
SedParameterEstimationTask::SedParameterEstimationTask (SedNamespaces * sedmlns)
Creates a new SedParameterEstimationTask using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedParameterEstimationTask() [3/3]
SedParameterEstimationTask::SedParameterEstimationTask (const SedParameterEstimationTask & orig)
Copy constructor for SedParameterEstimationTask.
Parameters
orig the SedParameterEstimationTask instance to copy.
References clone().
~SedParameterEstimationTask()
SedParameterEstimationTask::~SedParameterEstimationTask () virtual
Destructor for SedParameterEstimationTask.
Member Function Documentation
addAdjustableParameter()
int SedParameterEstimationTask::addAdjustableParameter (const SedAdjustableParameter * sap)
Adds a copy of the given SedAdjustableParameter to this SedParameterEstimationTask.
Parameters
sap the SedAdjustableParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createAdjustableParameter()
getAdjustableParameter(const std::string& sid)
getAdjustableParameter(unsigned int n)
getNumAdjustableParameters()
removeAdjustableParameter(const std::string& sid)
removeAdjustableParameter(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedAdjustableParameter::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addFitExperiment()
int SedParameterEstimationTask::addFitExperiment (const SedFitExperiment * sfe)
Adds a copy of the given SedFitExperiment to this SedParameterEstimationTask.
Parameters
sfe the SedFitExperiment object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createFitExperiment()
getFitExperiment(const std::string& sid)
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedFitExperiment::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedParameterEstimationTask * SedParameterEstimationTask::clone () const virtual
Creates and returns a deep copy of this SedParameterEstimationTask object.
Returns
a (deep) copy of this SedParameterEstimationTask object.
Reimplemented from SedAbstractTask.
References SedParameterEstimationTask().
Referenced by operator=(), and SedParameterEstimationTask().
createAdjustableParameter()
SedAdjustableParameter * SedParameterEstimationTask::createAdjustableParameter ()
Creates a new SedAdjustableParameter object, adds it to this SedParameterEstimationTask object and returns the SedAdjustableParameter object created.
Returns
a new SedAdjustableParameter object instance.
See also
addAdjustableParameter(const SedAdjustableParameter* object)
getAdjustableParameter(const std::string& sid)
getAdjustableParameter(unsigned int n)
getNumAdjustableParameters()
removeAdjustableParameter(const std::string& sid)
removeAdjustableParameter(unsigned int n)
createAlgorithm()
SedAlgorithm * SedParameterEstimationTask::createAlgorithm ()
Creates a new SedAlgorithm object, adds it to this SedParameterEstimationTask object and returns the SedAlgorithm object created.
Returns
a new SedAlgorithm object instance.
createFitExperiment()
SedFitExperiment * SedParameterEstimationTask::createFitExperiment ()
Creates a new SedFitExperiment object, adds it to this SedParameterEstimationTask object and returns the SedFitExperiment object created.
Returns
a new SedFitExperiment object instance.
See also
addFitExperiment(const SedFitExperiment* object)
getFitExperiment(const std::string& sid)
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
createLeastSquareObjectiveFunction()
SedLeastSquareObjectiveFunction * SedParameterEstimationTask::createLeastSquareObjectiveFunction ()
Creates a new SedLeastSquareObjectiveFunction object, adds it to this SedParameterEstimationTask object and returns the SedLeastSquareObjectiveFunction object created.
Returns
a new SedLeastSquareObjectiveFunction object instance.
getAdjustableParameter() [1/2]
SedAdjustableParameter * SedParameterEstimationTask::getAdjustableParameter (unsigned int n)
Get a SedAdjustableParameter from the SedParameterEstimationTask.
Parameters
n an unsigned int representing the index of the SedAdjustableParameter to retrieve.
Returns
the nth SedAdjustableParameter in the SedListOfAdjustableParameters within this SedParameterEstimationTask or NULL if no such object exists.
See also
addAdjustableParameter(const SedAdjustableParameter* object)
createAdjustableParameter()
getAdjustableParameter(const std::string& sid)
getNumAdjustableParameters()
removeAdjustableParameter(const std::string& sid)
removeAdjustableParameter(unsigned int n)
getAdjustableParameter() [2/2]
const SedAdjustableParameter * SedParameterEstimationTask::getAdjustableParameter (unsigned int n) const
Get a SedAdjustableParameter from the SedParameterEstimationTask.
Parameters
n an unsigned int representing the index of the SedAdjustableParameter to retrieve.
Returns
the nth SedAdjustableParameter in the SedListOfAdjustableParameters within this SedParameterEstimationTask or NULL if no such object exists.
See also
addAdjustableParameter(const SedAdjustableParameter* object)
createAdjustableParameter()
getAdjustableParameter(const std::string& sid)
getNumAdjustableParameters()
removeAdjustableParameter(const std::string& sid)
removeAdjustableParameter(unsigned int n)
getAdjustableParameterByModelReference() [1/2]
SedAdjustableParameter * SedParameterEstimationTask::getAdjustableParameterByModelReference (const std::string & sid)
Get a SedAdjustableParameter from the SedParameterEstimationTask based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedAdjustableParameter object to retrieve.
Returns
the first SedAdjustableParameter in this SedParameterEstimationTask based on the given modelReference attribute or NULL if no such SedAdjustableParameter exists.
getAdjustableParameterByModelReference() [2/2]
const SedAdjustableParameter * SedParameterEstimationTask::getAdjustableParameterByModelReference (const std::string & sid) const
Get a SedAdjustableParameter from the SedParameterEstimationTask based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedAdjustableParameter object to retrieve.
Returns
the first SedAdjustableParameter in this SedParameterEstimationTask based on the given modelReference attribute or NULL if no such SedAdjustableParameter exists.
getAlgorithm() [1/2]
SedAlgorithm * SedParameterEstimationTask::getAlgorithm ()
Returns the value of the "algorithm" element of this SedParameterEstimationTask.
Returns
the value of the "algorithm" element of this SedParameterEstimationTask as a SedAlgorithm*.
getAlgorithm() [2/2]
const SedAlgorithm * SedParameterEstimationTask::getAlgorithm () const
Returns the value of the "algorithm" element of this SedParameterEstimationTask.
Returns
the value of the "algorithm" element of this SedParameterEstimationTask as a SedAlgorithm*.
getAllElements()
List * SedParameterEstimationTask::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST, and SED_ADD_FILTERED_POINTER.
getElementBySId()
SedBase * SedParameterEstimationTask::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedParameterEstimationTask::getElementName () const virtual
Returns the XML element name of this SedParameterEstimationTask object.
For SedParameterEstimationTask, the XML element name is always "parameterEstimationTask".
Returns
the name of this element, i.e. "parameterEstimationTask".
Reimplemented from SedAbstractTask.
getFitExperiment() [1/4]
SedFitExperiment * SedParameterEstimationTask::getFitExperiment (const std::string & sid)
Get a SedFitExperiment from the SedParameterEstimationTask based on its identifier.
Parameters
sid a string representing the identifier of the SedFitExperiment to retrieve.
Returns
the SedFitExperiment in the SedListOfFitExperiments within this SedParameterEstimationTask with the given sid or NULL if no such SedFitExperiment exists.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
getFitExperiment() [2/4]
const SedFitExperiment * SedParameterEstimationTask::getFitExperiment (const std::string & sid) const
Get a SedFitExperiment from the SedParameterEstimationTask based on its identifier.
Parameters
sid a string representing the identifier of the SedFitExperiment to retrieve.
Returns
the SedFitExperiment in the SedListOfFitExperiments within this SedParameterEstimationTask with the given sid or NULL if no such SedFitExperiment exists.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
getFitExperiment() [3/4]
SedFitExperiment * SedParameterEstimationTask::getFitExperiment (unsigned int n)
Get a SedFitExperiment from the SedParameterEstimationTask.
Parameters
n an unsigned int representing the index of the SedFitExperiment to retrieve.
Returns
the nth SedFitExperiment in the SedListOfFitExperiments within this SedParameterEstimationTask or NULL if no such object exists.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(const std::string& sid)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
getFitExperiment() [4/4]
const SedFitExperiment * SedParameterEstimationTask::getFitExperiment (unsigned int n) const
Get a SedFitExperiment from the SedParameterEstimationTask.
Parameters
n an unsigned int representing the index of the SedFitExperiment to retrieve.
Returns
the nth SedFitExperiment in the SedListOfFitExperiments within this SedParameterEstimationTask or NULL if no such object exists.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(const std::string& sid)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
getListOfAdjustableParameters() [1/2]
SedListOfAdjustableParameters * SedParameterEstimationTask::getListOfAdjustableParameters ()
Returns the SedListOfAdjustableParameters from this SedParameterEstimationTask.
Returns
the SedListOfAdjustableParameters from this SedParameterEstimationTask.
See also
addAdjustableParameter(const SedAdjustableParameter* object)
createAdjustableParameter()
getAdjustableParameter(const std::string& sid)
getAdjustableParameter(unsigned int n)
getNumAdjustableParameters()
removeAdjustableParameter(const std::string& sid)
removeAdjustableParameter(unsigned int n)
getListOfAdjustableParameters() [2/2]
const SedListOfAdjustableParameters * SedParameterEstimationTask::getListOfAdjustableParameters () const
Returns the SedListOfAdjustableParameters from this SedParameterEstimationTask.
Returns
the SedListOfAdjustableParameters from this SedParameterEstimationTask.
See also
addAdjustableParameter(const SedAdjustableParameter* object)
createAdjustableParameter()
getAdjustableParameter(const std::string& sid)
getAdjustableParameter(unsigned int n)
getNumAdjustableParameters()
removeAdjustableParameter(const std::string& sid)
removeAdjustableParameter(unsigned int n)
getListOfFitExperiments() [1/2]
SedListOfFitExperiments * SedParameterEstimationTask::getListOfFitExperiments ()
Returns the SedListOfFitExperiments from this SedParameterEstimationTask.
Returns
the SedListOfFitExperiments from this SedParameterEstimationTask.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(const std::string& sid)
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
getListOfFitExperiments() [2/2]
const SedListOfFitExperiments * SedParameterEstimationTask::getListOfFitExperiments () const
Returns the SedListOfFitExperiments from this SedParameterEstimationTask.
Returns
the SedListOfFitExperiments from this SedParameterEstimationTask.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(const std::string& sid)
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
getNumAdjustableParameters()
unsigned int SedParameterEstimationTask::getNumAdjustableParameters () const
Get the number of SedAdjustableParameter objects in this SedParameterEstimationTask.
Returns
the number of SedAdjustableParameter objects in this SedParameterEstimationTask.
See also
addAdjustableParameter(const SedAdjustableParameter* object)
createAdjustableParameter()
getAdjustableParameter(const std::string& sid)
getAdjustableParameter(unsigned int n)
removeAdjustableParameter(const std::string& sid)
removeAdjustableParameter(unsigned int n)
Referenced by hasRequiredElements().
getNumFitExperiments()
unsigned int SedParameterEstimationTask::getNumFitExperiments () const
Get the number of SedFitExperiment objects in this SedParameterEstimationTask.
Returns
the number of SedFitExperiment objects in this SedParameterEstimationTask.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(const std::string& sid)
getFitExperiment(unsigned int n)
removeFitExperiment(const std::string& sid)
removeFitExperiment(unsigned int n)
Referenced by hasRequiredElements().
getObjective() [1/2]
SedObjective * SedParameterEstimationTask::getObjective ()
Returns the value of the "objective" element of this SedParameterEstimationTask.
Returns
the value of the "objective" element of this SedParameterEstimationTask as a SedObjective*.
getObjective() [2/2]
const SedObjective * SedParameterEstimationTask::getObjective () const
Returns the value of the "objective" element of this SedParameterEstimationTask.
Returns
the value of the "objective" element of this SedParameterEstimationTask as a SedObjective*.
getTypeCode()
int SedParameterEstimationTask::getTypeCode () const virtual
Returns the libSEDML type code for this SedParameterEstimationTask object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_TASK_PARAMETER_ESTIMATION, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedAbstractTask.
References SEDML_TASK_PARAMETER_ESTIMATION.
hasRequiredAttributes()
bool SedParameterEstimationTask::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedParameterEstimationTask object have been set.
Returns
true to indicate that all the required attributes of this SedParameterEstimationTask have been set, otherwise false is returned.
Reimplemented from SedAbstractTask.
References SedAbstractTask::hasRequiredAttributes().
hasRequiredElements()
bool SedParameterEstimationTask::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedParameterEstimationTask object have been set.
Returns
true to indicate that all the required elements of this SedParameterEstimationTask have been set, otherwise false is returned.
Note
The required elements for the SedParameterEstimationTask object are:
"algorithm"
"objective"
"adjustableParameter"
"fitExperiment"
References getNumAdjustableParameters(), getNumFitExperiments(), isSetAlgorithm(), and isSetObjective().
isSetAlgorithm()
bool SedParameterEstimationTask::isSetAlgorithm () const
Predicate returning true if this SedParameterEstimationTask's "algorithm" element is set.
Returns
true if this SedParameterEstimationTask's "algorithm" element has been set, otherwise false is returned.
Referenced by hasRequiredElements().
isSetObjective()
bool SedParameterEstimationTask::isSetObjective () const
Predicate returning true if this SedParameterEstimationTask's "objective" element is set.
Returns
true if this SedParameterEstimationTask's "objective" element has been set, otherwise false is returned.
Referenced by hasRequiredElements().
operator=()
SedParameterEstimationTask & SedParameterEstimationTask::operator= (const SedParameterEstimationTask & rhs)
Assignment operator for SedParameterEstimationTask.
Parameters
rhs the SedParameterEstimationTask object whose values are to be used as the basis of the assignment.
References clone(), and SedAbstractTask::operator=().
removeAdjustableParameter()
SedAdjustableParameter * SedParameterEstimationTask::removeAdjustableParameter (unsigned int n)
Removes the nth SedAdjustableParameter from this SedParameterEstimationTask and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAdjustableParameter to remove.
Returns
a pointer to the nth SedAdjustableParameter in this SedParameterEstimationTask.
See also
addAdjustableParameter(const SedAdjustableParameter* object)
createAdjustableParameter()
getAdjustableParameter(const std::string& sid)
getAdjustableParameter(unsigned int n)
getNumAdjustableParameters()
removeAdjustableParameter(const std::string& sid)
removeFitExperiment() [1/2]
SedFitExperiment * SedParameterEstimationTask::removeFitExperiment (const std::string & sid)
Removes the SedFitExperiment from this SedParameterEstimationTask based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedFitExperiment to remove.
Returns
the SedFitExperiment in this SedParameterEstimationTask based on the identifier or NULL if no such SedFitExperiment exists.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(const std::string& sid)
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(unsigned int n)
removeFitExperiment() [2/2]
SedFitExperiment * SedParameterEstimationTask::removeFitExperiment (unsigned int n)
Removes the nth SedFitExperiment from this SedParameterEstimationTask and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedFitExperiment to remove.
Returns
a pointer to the nth SedFitExperiment in this SedParameterEstimationTask.
See also
addFitExperiment(const SedFitExperiment* object)
createFitExperiment()
getFitExperiment(const std::string& sid)
getFitExperiment(unsigned int n)
getNumFitExperiments()
removeFitExperiment(const std::string& sid)
setAlgorithm()
int SedParameterEstimationTask::setAlgorithm (const SedAlgorithm * algorithm)
Sets the value of the "algorithm" element of this SedParameterEstimationTask.
Parameters
algorithm SedAlgorithm* value of the "algorithm" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedAlgorithm::clone(), and LIBSEDML_OPERATION_SUCCESS.
setObjective()
int SedParameterEstimationTask::setObjective (const SedObjective * objective)
Sets the value of the "objective" element of this SedParameterEstimationTask.
Parameters
objective SedObjective* value of the "objective" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedObjective::clone(), and LIBSEDML_OPERATION_SUCCESS.
unsetAlgorithm()
int SedParameterEstimationTask::unsetAlgorithm ()
Unsets the value of the "algorithm" element of this SedParameterEstimationTask.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetObjective()
int SedParameterEstimationTask::unsetObjective ()
Unsets the value of the "objective" element of this SedParameterEstimationTask.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedParameterEstimationTask.h
SedParameterEstimationTask.cpp