LIBSEDML API: SedDataSet Class Reference
SedDataSet Class Reference
#include <SedDataSet.h>
Public Member Functions
virtual SedDataSet * clone () const
const std::string & getDataReference () const
virtual const std::string & getElementName () const
const std::string & getLabel () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetDataReference () const
bool isSetLabel () const
SedDataSet & operator= (const SedDataSet &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedDataSet (const SedDataSet &orig)
SedDataSet (SedNamespaces *sedmlns)
SedDataSet (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setDataReference (const std::string &dataReference)
int setLabel (const std::string &label)
int unsetDataReference ()
int unsetLabel ()
virtual ~SedDataSet ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedDataSet class.
Constructor & Destructor Documentation
SedDataSet() [1/3]
SedDataSet::SedDataSet (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedDataSet using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedDataSet.
version an unsigned int, the SED-ML Version to assign to this SedDataSet.
Referenced by clone().
SedDataSet() [2/3]
SedDataSet::SedDataSet (SedNamespaces * sedmlns)
Creates a new SedDataSet using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedDataSet() [3/3]
SedDataSet::SedDataSet (const SedDataSet & orig)
Copy constructor for SedDataSet.
Parameters
orig the SedDataSet instance to copy.
~SedDataSet()
SedDataSet::~SedDataSet () virtual
Destructor for SedDataSet.
Member Function Documentation
clone()
SedDataSet * SedDataSet::clone () const virtual
Creates and returns a deep copy of this SedDataSet object.
Returns
a (deep) copy of this SedDataSet object.
Implements SedBase.
References SedDataSet().
getDataReference()
const std::string & SedDataSet::getDataReference () const
Returns the value of the "dataReference" attribute of this SedDataSet.
Returns
the value of the "dataReference" attribute of this SedDataSet as a string.
getElementName()
const std::string & SedDataSet::getElementName () const virtual
Returns the XML element name of this SedDataSet object.
For SedDataSet, the XML element name is always "dataSet".
Returns
the name of this element, i.e. "dataSet".
Implements SedBase.
getLabel()
const std::string & SedDataSet::getLabel () const
Returns the value of the "label" attribute of this SedDataSet.
Returns
the value of the "label" attribute of this SedDataSet as a string.
getTypeCode()
int SedDataSet::getTypeCode () const virtual
Returns the libSEDML type code for this SedDataSet object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_OUTPUT_DATASET, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_OUTPUT_DATASET.
hasRequiredAttributes()
bool SedDataSet::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedDataSet object have been set.
Returns
true to indicate that all the required attributes of this SedDataSet have been set, otherwise false is returned.
Note
The required attributes for the SedDataSet object are:
"id"
"label"
"dataReference"
References isSetDataReference(), SedBase::isSetId(), and isSetLabel().
Referenced by SedListOfDataSets::addDataSet(), and SedReport::addDataSet().
isSetDataReference()
bool SedDataSet::isSetDataReference () const
Predicate returning true if this SedDataSet's "dataReference" attribute is set.
Returns
true if this SedDataSet's "dataReference" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetLabel()
bool SedDataSet::isSetLabel () const
Predicate returning true if this SedDataSet's "label" attribute is set.
Returns
true if this SedDataSet's "label" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedDataSet & SedDataSet::operator= (const SedDataSet & rhs)
Assignment operator for SedDataSet.
Parameters
rhs the SedDataSet object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
renameSIdRefs()
void SedDataSet::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetDataReference(), and setDataReference().
setDataReference()
int SedDataSet::setDataReference (const std::string & dataReference)
Sets the value of the "dataReference" attribute of this SedDataSet.
Parameters
dataReference std::string& value of the "dataReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setLabel()
int SedDataSet::setLabel (const std::string & label)
Sets the value of the "label" attribute of this SedDataSet.
Parameters
label std::string& value of the "label" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with label = NULL or an empty string is equivalent to calling unsetLabel().
References LIBSEDML_OPERATION_SUCCESS.
unsetDataReference()
int SedDataSet::unsetDataReference ()
Unsets the value of the "dataReference" attribute of this SedDataSet.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetLabel()
int SedDataSet::unsetLabel ()
Unsets the value of the "label" attribute of this SedDataSet.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedDataSet.h
SedDataSet.cpp