LIBSEDML API: SedModel Class Reference
SedModel Class Reference
#include <SedModel.h>
Public Member Functions
int addChange (const SedChange *sc)
virtual SedModel * clone () const
SedAddXML * createAddXML ()
SedChangeAttribute * createChangeAttribute ()
SedChangeXML * createChangeXML ()
SedComputeChange * createComputeChange ()
SedRemoveXML * createRemoveXML ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedChange * getChange (unsigned int n)
const SedChange * getChange (unsigned int n) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
const std::string & getLanguage () const
SedListOfChanges * getListOfChanges ()
const SedListOfChanges * getListOfChanges () const
unsigned int getNumChanges () const
const std::string & getSource () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetLanguage () const
bool isSetSource () const
SedModel & operator= (const SedModel &rhs)
SedChange * removeChange (unsigned int n)
SedModel (const SedModel &orig)
SedModel (SedNamespaces *sedmlns)
SedModel (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setLanguage (const std::string &language)
int setSource (const std::string &source)
int unsetLanguage ()
int unsetSource ()
virtual ~SedModel ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedModel class.
Constructor & Destructor Documentation
SedModel() [1/3]
SedModel::SedModel (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedModel using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedModel.
version an unsigned int, the SED-ML Version to assign to this SedModel.
Referenced by clone().
SedModel() [2/3]
SedModel::SedModel (SedNamespaces * sedmlns)
Creates a new SedModel using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedModel() [3/3]
SedModel::SedModel (const SedModel & orig)
Copy constructor for SedModel.
Parameters
orig the SedModel instance to copy.
~SedModel()
SedModel::~SedModel () virtual
Destructor for SedModel.
Member Function Documentation
addChange()
int SedModel::addChange (const SedChange * sc)
Adds a copy of the given SedChange to this SedModel.
Parameters
sc the SedChange object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createChange()
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedChange::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedModel * SedModel::clone () const virtual
Creates and returns a deep copy of this SedModel object.
Returns
a (deep) copy of this SedModel object.
Implements SedBase.
References SedModel().
createAddXML()
SedAddXML * SedModel::createAddXML ()
Creates a new SedAddXML object, adds it to this SedModel object and returns the SedAddXML object created.
Returns
a new SedAddXML object instance.
See also
addChange(const SedChange* object)
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
createChangeAttribute()
SedChangeAttribute * SedModel::createChangeAttribute ()
Creates a new SedChangeAttribute object, adds it to this SedModel object and returns the SedChangeAttribute object created.
Returns
a new SedChangeAttribute object instance.
See also
addChange(const SedChange* object)
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
createChangeXML()
SedChangeXML * SedModel::createChangeXML ()
Creates a new SedChangeXML object, adds it to this SedModel object and returns the SedChangeXML object created.
Returns
a new SedChangeXML object instance.
See also
addChange(const SedChange* object)
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
createComputeChange()
SedComputeChange * SedModel::createComputeChange ()
Creates a new SedComputeChange object, adds it to this SedModel object and returns the SedComputeChange object created.
Returns
a new SedComputeChange object instance.
See also
addChange(const SedChange* object)
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
createRemoveXML()
SedRemoveXML * SedModel::createRemoveXML ()
Creates a new SedRemoveXML object, adds it to this SedModel object and returns the SedRemoveXML object created.
Returns
a new SedRemoveXML object instance.
See also
addChange(const SedChange* object)
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
getAllElements()
List * SedModel::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getChange() [1/2]
SedChange * SedModel::getChange (unsigned int n)
Get a SedChange from the SedModel.
Parameters
n an unsigned int representing the index of the SedChange to retrieve.
Returns
the nth SedChange in the SedListOfChanges within this SedModel or NULL if no such object exists.
See also
addChange(const SedChange* object)
createChange()
getChange(const std::string& sid)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
getChange() [2/2]
const SedChange * SedModel::getChange (unsigned int n) const
Get a SedChange from the SedModel.
Parameters
n an unsigned int representing the index of the SedChange to retrieve.
Returns
the nth SedChange in the SedListOfChanges within this SedModel or NULL if no such object exists.
See also
addChange(const SedChange* object)
createChange()
getChange(const std::string& sid)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
getElementBySId()
SedBase * SedModel::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedModel::getElementName () const virtual
Returns the XML element name of this SedModel object.
For SedModel, the XML element name is always "model".
Returns
the name of this element, i.e. "model".
Implements SedBase.
getLanguage()
const std::string & SedModel::getLanguage () const
Returns the value of the "language" attribute of this SedModel.
Returns
the value of the "language" attribute of this SedModel as a string.
getListOfChanges() [1/2]
SedListOfChanges * SedModel::getListOfChanges ()
Returns the SedListOfChanges from this SedModel.
Returns
the SedListOfChanges from this SedModel.
See also
addChange(const SedChange* object)
createChange()
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
getListOfChanges() [2/2]
const SedListOfChanges * SedModel::getListOfChanges () const
Returns the SedListOfChanges from this SedModel.
Returns
the SedListOfChanges from this SedModel.
See also
addChange(const SedChange* object)
createChange()
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
removeChange(unsigned int n)
getNumChanges()
unsigned int SedModel::getNumChanges () const
Get the number of SedChange objects in this SedModel.
Returns
the number of SedChange objects in this SedModel.
See also
addChange(const SedChange* object)
createChange()
getChange(const std::string& sid)
getChange(unsigned int n)
removeChange(const std::string& sid)
removeChange(unsigned int n)
getSource()
const std::string & SedModel::getSource () const
Returns the value of the "source" attribute of this SedModel.
Returns
the value of the "source" attribute of this SedModel as a string.
getTypeCode()
int SedModel::getTypeCode () const virtual
Returns the libSEDML type code for this SedModel object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_MODEL, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_MODEL.
hasRequiredAttributes()
bool SedModel::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedModel object have been set.
Returns
true to indicate that all the required attributes of this SedModel have been set, otherwise false is returned.
Note
The required attributes for the SedModel object are:
"id"
"source"
References SedBase::isSetId(), and isSetSource().
Referenced by SedDocument::addModel(), and SedListOfModels::addModel().
isSetLanguage()
bool SedModel::isSetLanguage () const
Predicate returning true if this SedModel's "language" attribute is set.
Returns
true if this SedModel's "language" attribute has been set, otherwise false is returned.
isSetSource()
bool SedModel::isSetSource () const
Predicate returning true if this SedModel's "source" attribute is set.
Returns
true if this SedModel's "source" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedModel & SedModel::operator= (const SedModel & rhs)
Assignment operator for SedModel.
Parameters
rhs the SedModel object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
removeChange()
SedChange * SedModel::removeChange (unsigned int n)
Removes the nth SedChange from this SedModel and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedChange to remove.
Returns
a pointer to the nth SedChange in this SedModel.
See also
addChange(const SedChange* object)
createChange()
getChange(const std::string& sid)
getChange(unsigned int n)
getNumChanges()
removeChange(const std::string& sid)
setLanguage()
int SedModel::setLanguage (const std::string & language)
Sets the value of the "language" attribute of this SedModel.
Parameters
language std::string& value of the "language" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with language = NULL or an empty string is equivalent to calling unsetLanguage().
References LIBSEDML_OPERATION_SUCCESS.
setSource()
int SedModel::setSource (const std::string & source)
Sets the value of the "source" attribute of this SedModel.
Parameters
source std::string& value of the "source" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with source = NULL or an empty string is equivalent to calling unsetSource().
References LIBSEDML_OPERATION_SUCCESS.
unsetLanguage()
int SedModel::unsetLanguage ()
Unsets the value of the "language" attribute of this SedModel.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetSource()
int SedModel::unsetSource ()
Unsets the value of the "source" attribute of this SedModel.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedModel.h
SedModel.cpp