LIBSEDML API: SedAdjustableParameter Class Reference
SedAdjustableParameter Class Reference
#include <SedAdjustableParameter.h>
Public Member Functions
int addExperimentReference (const SedExperimentReference *ser)
virtual SedAdjustableParameter * clone () const
SedBounds * createBounds ()
SedExperimentReference * createExperimentReference ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBounds * getBounds ()
const SedBounds * getBounds () const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedExperimentReference * getExperimentReference (unsigned int n)
const SedExperimentReference * getExperimentReference (unsigned int n) const
SedExperimentReference * getExperimentReferenceByExperimentId (const std::string &sid)
const SedExperimentReference * getExperimentReferenceByExperimentId (const std::string &sid) const
double getInitialValue () const
SedListOfExperimentReferences * getListOfExperimentReferences ()
const SedListOfExperimentReferences * getListOfExperimentReferences () const
const std::string & getModelReference () const
unsigned int getNumExperimentReferences () const
const std::string & getTarget () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetBounds () const
bool isSetInitialValue () const
bool isSetModelReference () const
bool isSetTarget () const
SedAdjustableParameter & operator= (const SedAdjustableParameter &rhs)
SedExperimentReference * removeExperimentReference (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedAdjustableParameter (const SedAdjustableParameter &orig)
SedAdjustableParameter (SedNamespaces *sedmlns)
SedAdjustableParameter (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setBounds (const SedBounds *bounds)
int setInitialValue (double initialValue)
int setModelReference (const std::string &modelReference)
int setTarget (const std::string &target)
int unsetBounds ()
int unsetInitialValue ()
int unsetModelReference ()
int unsetTarget ()
virtual ~SedAdjustableParameter ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAdjustableParameter class.
Constructor & Destructor Documentation
SedAdjustableParameter() [1/3]
SedAdjustableParameter::SedAdjustableParameter (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAdjustableParameter using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAdjustableParameter.
version an unsigned int, the SED-ML Version to assign to this SedAdjustableParameter.
Referenced by clone().
SedAdjustableParameter() [2/3]
SedAdjustableParameter::SedAdjustableParameter (SedNamespaces * sedmlns)
Creates a new SedAdjustableParameter using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedAdjustableParameter() [3/3]
SedAdjustableParameter::SedAdjustableParameter (const SedAdjustableParameter & orig)
Copy constructor for SedAdjustableParameter.
Parameters
orig the SedAdjustableParameter instance to copy.
References clone().
~SedAdjustableParameter()
SedAdjustableParameter::~SedAdjustableParameter () virtual
Destructor for SedAdjustableParameter.
Member Function Documentation
addExperimentReference()
int SedAdjustableParameter::addExperimentReference (const SedExperimentReference * ser)
Adds a copy of the given SedExperimentReference to this SedAdjustableParameter.
Parameters
ser the SedExperimentReference object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createExperimentReference()
getExperimentReference(const std::string& sid)
getExperimentReference(unsigned int n)
getNumExperimentReferences()
removeExperimentReference(const std::string& sid)
removeExperimentReference(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedExperimentReference::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedAdjustableParameter * SedAdjustableParameter::clone () const virtual
Creates and returns a deep copy of this SedAdjustableParameter object.
Returns
a (deep) copy of this SedAdjustableParameter object.
Implements SedBase.
References SedAdjustableParameter().
Referenced by operator=(), and SedAdjustableParameter().
createBounds()
SedBounds * SedAdjustableParameter::createBounds ()
Creates a new SedBounds object, adds it to this SedAdjustableParameter object and returns the SedBounds object created.
Returns
a new SedBounds object instance.
createExperimentReference()
SedExperimentReference * SedAdjustableParameter::createExperimentReference ()
Creates a new SedExperimentReference object, adds it to this SedAdjustableParameter object and returns the SedExperimentReference object created.
Returns
a new SedExperimentReference object instance.
See also
addExperimentReference(const SedExperimentReference* object)
getExperimentReference(const std::string& sid)
getExperimentReference(unsigned int n)
getNumExperimentReferences()
removeExperimentReference(const std::string& sid)
removeExperimentReference(unsigned int n)
getAllElements()
List * SedAdjustableParameter::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST, and SED_ADD_FILTERED_POINTER.
getBounds() [1/2]
SedBounds * SedAdjustableParameter::getBounds ()
Returns the value of the "bounds" element of this SedAdjustableParameter.
Returns
the value of the "bounds" element of this SedAdjustableParameter as a SedBounds*.
getBounds() [2/2]
const SedBounds * SedAdjustableParameter::getBounds () const
Returns the value of the "bounds" element of this SedAdjustableParameter.
Returns
the value of the "bounds" element of this SedAdjustableParameter as a SedBounds*.
getElementBySId()
SedBase * SedAdjustableParameter::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedAdjustableParameter::getElementName () const virtual
Returns the XML element name of this SedAdjustableParameter object.
For SedAdjustableParameter, the XML element name is always "adjustableParameter".
Returns
the name of this element, i.e. "adjustableParameter".
Implements SedBase.
getExperimentReference() [1/2]
SedExperimentReference * SedAdjustableParameter::getExperimentReference (unsigned int n)
Get a SedExperimentReference from the SedAdjustableParameter.
Parameters
n an unsigned int representing the index of the SedExperimentReference to retrieve.
Returns
the nth SedExperimentReference in the SedListOfExperimentReferences within this SedAdjustableParameter.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
getExperimentReference(const std::string& sid)
getNumExperimentReferences()
removeExperimentReference(const std::string& sid)
removeExperimentReference(unsigned int n)
getExperimentReference() [2/2]
const SedExperimentReference * SedAdjustableParameter::getExperimentReference (unsigned int n) const
Get a SedExperimentReference from the SedAdjustableParameter.
Parameters
n an unsigned int representing the index of the SedExperimentReference to retrieve.
Returns
the nth SedExperimentReference in the SedListOfExperimentReferences within this SedAdjustableParameter.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
getExperimentReference(const std::string& sid)
getNumExperimentReferences()
removeExperimentReference(const std::string& sid)
removeExperimentReference(unsigned int n)
getExperimentReferenceByExperimentId() [1/2]
SedExperimentReference * SedAdjustableParameter::getExperimentReferenceByExperimentId (const std::string & sid)
Get a SedExperimentReference from the SedAdjustableParameter based on the ExperimentId to which it refers.
Parameters
sid a string representing the "experimentId" attribute of the SedExperimentReference object to retrieve.
Returns
the first SedExperimentReference in this SedAdjustableParameter based on the given experimentId attribute or NULL if no such SedExperimentReference exists.
getExperimentReferenceByExperimentId() [2/2]
const SedExperimentReference * SedAdjustableParameter::getExperimentReferenceByExperimentId (const std::string & sid) const
Get a SedExperimentReference from the SedAdjustableParameter based on the ExperimentId to which it refers.
Parameters
sid a string representing the "experimentId" attribute of the SedExperimentReference object to retrieve.
Returns
the first SedExperimentReference in this SedAdjustableParameter based on the given experimentId attribute or NULL if no such SedExperimentReference exists.
getInitialValue()
double SedAdjustableParameter::getInitialValue () const
Returns the value of the "initialValue" attribute of this SedAdjustableParameter.
Returns
the value of the "initialValue" attribute of this SedAdjustableParameter as a double.
getListOfExperimentReferences() [1/2]
SedListOfExperimentReferences * SedAdjustableParameter::getListOfExperimentReferences ()
Returns the SedListOfExperimentReferences from this SedAdjustableParameter.
Returns
the SedListOfExperimentReferences from this SedAdjustableParameter.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
getExperimentReference(const std::string& sid)
getExperimentReference(unsigned int n)
getNumExperimentReferences()
removeExperimentReference(const std::string& sid)
removeExperimentReference(unsigned int n)
getListOfExperimentReferences() [2/2]
const SedListOfExperimentReferences * SedAdjustableParameter::getListOfExperimentReferences () const
Returns the SedListOfExperimentReferences from this SedAdjustableParameter.
Returns
the SedListOfExperimentReferences from this SedAdjustableParameter.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
getExperimentReference(const std::string& sid)
getExperimentReference(unsigned int n)
getNumExperimentReferences()
removeExperimentReference(const std::string& sid)
removeExperimentReference(unsigned int n)
getModelReference()
const std::string & SedAdjustableParameter::getModelReference () const
Returns the value of the "modelReference" attribute of this SedAdjustableParameter.
Returns
the value of the "modelReference" attribute of this SedAdjustableParameter as a string.
getNumExperimentReferences()
unsigned int SedAdjustableParameter::getNumExperimentReferences () const
Get the number of SedExperimentReference objects in this SedAdjustableParameter.
Returns
the number of SedExperimentReference objects in this SedAdjustableParameter.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
getExperimentReference(const std::string& sid)
getExperimentReference(unsigned int n)
removeExperimentReference(const std::string& sid)
removeExperimentReference(unsigned int n)
getTarget()
const std::string & SedAdjustableParameter::getTarget () const
Returns the value of the "target" attribute of this SedAdjustableParameter.
Returns
the value of the "target" attribute of this SedAdjustableParameter as a string.
getTypeCode()
int SedAdjustableParameter::getTypeCode () const virtual
Returns the libSEDML type code for this SedAdjustableParameter object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_ADJUSTABLE_PARAMETER, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_ADJUSTABLE_PARAMETER.
hasRequiredAttributes()
bool SedAdjustableParameter::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAdjustableParameter object have been set.
Returns
true to indicate that all the required attributes of this SedAdjustableParameter have been set, otherwise false is returned.
Referenced by SedListOfAdjustableParameters::addAdjustableParameter(), and SedParameterEstimationTask::addAdjustableParameter().
hasRequiredElements()
bool SedAdjustableParameter::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedAdjustableParameter object have been set.
Returns
true to indicate that all the required elements of this SedAdjustableParameter have been set, otherwise false is returned.
Note
The required elements for the SedAdjustableParameter object are:
"bounds"
References isSetBounds().
isSetBounds()
bool SedAdjustableParameter::isSetBounds () const
Predicate returning true if this SedAdjustableParameter's "bounds" element is set.
Returns
true if this SedAdjustableParameter's "bounds" element has been set, otherwise false is returned.
Referenced by hasRequiredElements().
isSetInitialValue()
bool SedAdjustableParameter::isSetInitialValue () const
Predicate returning true if this SedAdjustableParameter's "initialValue" attribute is set.
Returns
true if this SedAdjustableParameter's "initialValue" attribute has been set, otherwise false is returned.
Referenced by unsetInitialValue().
isSetModelReference()
bool SedAdjustableParameter::isSetModelReference () const
Predicate returning true if this SedAdjustableParameter's "modelReference" attribute is set.
Returns
true if this SedAdjustableParameter's "modelReference" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetTarget()
bool SedAdjustableParameter::isSetTarget () const
Predicate returning true if this SedAdjustableParameter's "target" attribute is set.
Returns
true if this SedAdjustableParameter's "target" attribute has been set, otherwise false is returned.
operator=()
SedAdjustableParameter & SedAdjustableParameter::operator= (const SedAdjustableParameter & rhs)
Assignment operator for SedAdjustableParameter.
Parameters
rhs the SedAdjustableParameter object whose values are to be used as the basis of the assignment.
References clone(), and SedBase::operator=().
removeExperimentReference()
SedExperimentReference * SedAdjustableParameter::removeExperimentReference (unsigned int n)
Removes the nth SedExperimentReference from this SedAdjustableParameter and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedExperimentReference to remove.
Returns
a pointer to the nth SedExperimentReference in this SedAdjustableParameter.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
getExperimentReference(const std::string& sid)
getExperimentReference(unsigned int n)
getNumExperimentReferences()
removeExperimentReference(const std::string& sid)
renameSIdRefs()
void SedAdjustableParameter::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetModelReference(), and setModelReference().
setBounds()
int SedAdjustableParameter::setBounds (const SedBounds * bounds)
Sets the value of the "bounds" element of this SedAdjustableParameter.
Parameters
bounds SedBounds* value of the "bounds" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedBounds::clone(), and LIBSEDML_OPERATION_SUCCESS.
setInitialValue()
int SedAdjustableParameter::setInitialValue (double initialValue)
Sets the value of the "initialValue" attribute of this SedAdjustableParameter.
Parameters
initialValue double value of the "initialValue" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setModelReference()
int SedAdjustableParameter::setModelReference (const std::string & modelReference)
Sets the value of the "modelReference" attribute of this SedAdjustableParameter.
Parameters
modelReference std::string& value of the "modelReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setTarget()
int SedAdjustableParameter::setTarget (const std::string & target)
Sets the value of the "target" attribute of this SedAdjustableParameter.
Parameters
target std::string& value of the "target" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with target = NULL or an empty string is equivalent to calling unsetTarget().
References LIBSEDML_OPERATION_SUCCESS.
unsetBounds()
int SedAdjustableParameter::unsetBounds ()
Unsets the value of the "bounds" element of this SedAdjustableParameter.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetInitialValue()
int SedAdjustableParameter::unsetInitialValue ()
Unsets the value of the "initialValue" attribute of this SedAdjustableParameter.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetInitialValue(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetModelReference()
int SedAdjustableParameter::unsetModelReference ()
Unsets the value of the "modelReference" attribute of this SedAdjustableParameter.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetTarget()
int SedAdjustableParameter::unsetTarget ()
Unsets the value of the "target" attribute of this SedAdjustableParameter.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedAdjustableParameter.h
SedAdjustableParameter.cpp