LIBSEDML API: SedListOfRanges Class Reference
SedListOfRanges Class Reference
#include <SedListOfRanges.h>
Public Member Functions
int addRange (const SedRange *sr)
virtual SedListOfRanges * clone () const
SedDataRange * createDataRange ()
SedFunctionalRange * createFunctionalRange ()
SedUniformRange * createUniformRange ()
SedVectorRange * createVectorRange ()
virtual SedRange * get (const std::string &sid)
virtual const SedRange * get (const std::string &sid) const
virtual SedRange * get (unsigned int n)
virtual const SedRange * get (unsigned int n) const
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
unsigned int getNumRanges () const
virtual int getTypeCode () const
SedListOfRanges & operator= (const SedListOfRanges &rhs)
virtual SedRange * remove (const std::string &sid)
virtual SedRange * remove (unsigned int n)
SedListOfRanges (const SedListOfRanges &orig)
SedListOfRanges (SedNamespaces *sedmlns)
SedListOfRanges (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedListOfRanges ()
Public Member Functions inherited from SedListOf
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedListOfRanges class.
Constructor & Destructor Documentation
SedListOfRanges() [1/3]
SedListOfRanges::SedListOfRanges (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOfRanges using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedListOfRanges.
version an unsigned int, the SED-ML Version to assign to this SedListOfRanges.
Referenced by clone().
SedListOfRanges() [2/3]
SedListOfRanges::SedListOfRanges (SedNamespaces * sedmlns)
Creates a new SedListOfRanges using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedListOfRanges() [3/3]
SedListOfRanges::SedListOfRanges (const SedListOfRanges & orig)
Copy constructor for SedListOfRanges.
Parameters
orig the SedListOfRanges instance to copy.
~SedListOfRanges()
SedListOfRanges::~SedListOfRanges () virtual
Destructor for SedListOfRanges.
Member Function Documentation
addRange()
int SedListOfRanges::addRange (const SedRange * sr)
Adds a copy of the given SedRange to this SedListOfRanges.
Parameters
sr the SedRange object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createRange()
get(const std::string& sid)
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::append(), SedBase::getLevel(), SedBase::getVersion(), SedRange::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedListOfRanges * SedListOfRanges::clone () const virtual
Creates and returns a deep copy of this SedListOfRanges object.
Returns
a (deep) copy of this SedListOfRanges object.
Reimplemented from SedListOf.
References SedListOfRanges().
createDataRange()
SedDataRange * SedListOfRanges::createDataRange ()
Creates a new SedDataRange object, adds it to this SedListOfRanges object and returns the SedDataRange object created.
Returns
a new SedDataRange object instance.
See also
addRange(const SedRange* object)
get(const std::string& sid)
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
createFunctionalRange()
SedFunctionalRange * SedListOfRanges::createFunctionalRange ()
Creates a new SedFunctionalRange object, adds it to this SedListOfRanges object and returns the SedFunctionalRange object created.
Returns
a new SedFunctionalRange object instance.
See also
addRange(const SedRange* object)
get(const std::string& sid)
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
createUniformRange()
SedUniformRange * SedListOfRanges::createUniformRange ()
Creates a new SedUniformRange object, adds it to this SedListOfRanges object and returns the SedUniformRange object created.
Returns
a new SedUniformRange object instance.
See also
addRange(const SedRange* object)
get(const std::string& sid)
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
createVectorRange()
SedVectorRange * SedListOfRanges::createVectorRange ()
Creates a new SedVectorRange object, adds it to this SedListOfRanges object and returns the SedVectorRange object created.
Returns
a new SedVectorRange object instance.
See also
addRange(const SedRange* object)
get(const std::string& sid)
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
get() [1/4]
SedRange * SedListOfRanges::get (const std::string & sid) virtual
Get a SedRange from the SedListOfRanges based on its identifier.
Parameters
sid a string representing the identifier of the SedRange to retrieve.
Returns
the SedRange in this SedListOfRanges with the given sid or NULL if no such SedRange exists.
See also
addRange(const SedRange* object)
createRange()
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
References get().
get() [2/4]
const SedRange * SedListOfRanges::get (const std::string & sid) const virtual
Get a SedRange from the SedListOfRanges based on its identifier.
Parameters
sid a string representing the identifier of the SedRange to retrieve.
Returns
the SedRange in this SedListOfRanges with the given sid or NULL if no such SedRange exists.
See also
addRange(const SedRange* object)
createRange()
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
get() [3/4]
SedRange * SedListOfRanges::get (unsigned int n) virtual
Get a SedRange from the SedListOfRanges.
Parameters
n an unsigned int representing the index of the SedRange to retrieve.
Returns
the nth SedRange in this SedListOfRanges or NULL if no such object exists.
See also
addRange(const SedRange* object)
createRange()
get(const std::string& sid)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
Referenced by get().
get() [4/4]
const SedRange * SedListOfRanges::get (unsigned int n) const virtual
Get a SedRange from the SedListOfRanges.
Parameters
n an unsigned int representing the index of the SedRange to retrieve.
Returns
the nth SedRange in this SedListOfRanges or NULL if no such object exists.
See also
addRange(const SedRange* object)
createRange()
get(const std::string& sid)
getNumRanges()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
getElementName()
const std::string & SedListOfRanges::getElementName () const virtual
Returns the XML element name of this SedListOfRanges object.
For SedListOfRanges, the XML element name is always "listOfRanges".
Returns
the name of this element, i.e. "listOfRanges".
Reimplemented from SedListOf.
getItemTypeCode()
int SedListOfRanges::getItemTypeCode () const virtual
Returns the libSEDML type code for the SED-ML objects contained in this SedListOfRanges object.
Returns
the SED-ML typecode for the objects contained in this SedListOfRanges: @sedmlconstant{SEDML_RANGE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedListOf.
References SEDML_RANGE.
getNumRanges()
unsigned int SedListOfRanges::getNumRanges () const
Get the number of SedRange objects in this SedListOfRanges.
Returns
the number of SedRange objects in this SedListOfRanges.
See also
addRange(const SedRange* object)
createRange()
get(const std::string& sid)
get(unsigned int n)
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::size().
getTypeCode()
int SedListOfRanges::getTypeCode () const virtual
Returns the libSEDML type code for this SedListOfRanges object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Reimplemented from SedListOf.
References SEDML_LIST_OF.
operator=()
SedListOfRanges & SedListOfRanges::operator= (const SedListOfRanges & rhs)
Assignment operator for SedListOfRanges.
Parameters
rhs the SedListOfRanges object whose values are to be used as the basis of the assignment.
References SedListOf::operator=().
remove() [1/2]
SedRange * SedListOfRanges::remove (const std::string & sid) virtual
Removes the SedRange from this SedListOfRanges based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedRange to remove.
Returns
the SedRange in this SedListOfRanges based on the identifier or NULL if no such SedRange exists.
See also
addRange(const SedRange* object)
createRange()
get(const std::string& sid)
get(unsigned int n)
getNumRanges()
remove(unsigned int n)
remove() [2/2]
SedRange * SedListOfRanges::remove (unsigned int n) virtual
Removes the nth SedRange from this SedListOfRanges and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedRange to remove.
Returns
a pointer to the nth SedRange in this SedListOfRanges.
See also
addRange(const SedRange* object)
createRange()
get(const std::string& sid)
get(unsigned int n)
getNumRanges()
remove(const std::string& sid)
Reimplemented from SedListOf.
References SedListOf::remove().
The documentation for this class was generated from the following files:
SedListOfRanges.h
SedListOfRanges.cpp