LIBSEDML API: SedListOfDataDescriptions Class Reference
SedListOfDataDescriptions Class Reference
#include <SedListOfDataDescriptions.h>
Public Member Functions
int addDataDescription (const SedDataDescription *sdd)
virtual SedListOfDataDescriptions * clone () const
SedDataDescription * createDataDescription ()
virtual SedDataDescription * get (const std::string &sid)
virtual const SedDataDescription * get (const std::string &sid) const
virtual SedDataDescription * get (unsigned int n)
virtual const SedDataDescription * get (unsigned int n) const
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
unsigned int getNumDataDescriptions () const
virtual int getTypeCode () const
SedListOfDataDescriptions & operator= (const SedListOfDataDescriptions &rhs)
virtual SedDataDescription * remove (const std::string &sid)
virtual SedDataDescription * remove (unsigned int n)
SedListOfDataDescriptions (const SedListOfDataDescriptions &orig)
SedListOfDataDescriptions (SedNamespaces *sedmlns)
SedListOfDataDescriptions (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedListOfDataDescriptions ()
Public Member Functions inherited from SedListOf
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedListOfDataDescriptions class.
Constructor & Destructor Documentation
SedListOfDataDescriptions() [1/3]
SedListOfDataDescriptions::SedListOfDataDescriptions (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOfDataDescriptions using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedListOfDataDescriptions.
version an unsigned int, the SED-ML Version to assign to this SedListOfDataDescriptions.
Referenced by clone().
SedListOfDataDescriptions() [2/3]
SedListOfDataDescriptions::SedListOfDataDescriptions (SedNamespaces * sedmlns)
Creates a new SedListOfDataDescriptions using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedListOfDataDescriptions() [3/3]
SedListOfDataDescriptions::SedListOfDataDescriptions (const SedListOfDataDescriptions & orig)
Copy constructor for SedListOfDataDescriptions.
Parameters
orig the SedListOfDataDescriptions instance to copy.
~SedListOfDataDescriptions()
SedListOfDataDescriptions::~SedListOfDataDescriptions () virtual
Destructor for SedListOfDataDescriptions.
Member Function Documentation
addDataDescription()
int SedListOfDataDescriptions::addDataDescription (const SedDataDescription * sdd)
Adds a copy of the given SedDataDescription to this SedListOfDataDescriptions.
Parameters
sdd the SedDataDescription object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createDataDescription()
get(const std::string& sid)
get(unsigned int n)
getNumDataDescriptions()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::append(), SedBase::getLevel(), SedBase::getVersion(), SedDataDescription::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedListOfDataDescriptions * SedListOfDataDescriptions::clone () const virtual
Creates and returns a deep copy of this SedListOfDataDescriptions object.
Returns
a (deep) copy of this SedListOfDataDescriptions object.
Reimplemented from SedListOf.
References SedListOfDataDescriptions().
createDataDescription()
SedDataDescription * SedListOfDataDescriptions::createDataDescription ()
Creates a new SedDataDescription object, adds it to this SedListOfDataDescriptions object and returns the SedDataDescription object created.
Returns
a new SedDataDescription object instance.
See also
addDataDescription(const SedDataDescription* object)
get(const std::string& sid)
get(unsigned int n)
getNumDataDescriptions()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
get() [1/4]
SedDataDescription * SedListOfDataDescriptions::get (const std::string & sid) virtual
Get a SedDataDescription from the SedListOfDataDescriptions based on its identifier.
Parameters
sid a string representing the identifier of the SedDataDescription to retrieve.
Returns
the SedDataDescription in this SedListOfDataDescriptions with the given sid or NULL if no such SedDataDescription exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
get(unsigned int n)
getNumDataDescriptions()
remove(const std::string& sid)
remove(unsigned int n)
References get().
get() [2/4]
const SedDataDescription * SedListOfDataDescriptions::get (const std::string & sid) const virtual
Get a SedDataDescription from the SedListOfDataDescriptions based on its identifier.
Parameters
sid a string representing the identifier of the SedDataDescription to retrieve.
Returns
the SedDataDescription in this SedListOfDataDescriptions with the given sid or NULL if no such SedDataDescription exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
get(unsigned int n)
getNumDataDescriptions()
remove(const std::string& sid)
remove(unsigned int n)
get() [3/4]
SedDataDescription * SedListOfDataDescriptions::get (unsigned int n) virtual
Get a SedDataDescription from the SedListOfDataDescriptions.
Parameters
n an unsigned int representing the index of the SedDataDescription to retrieve.
Returns
the nth SedDataDescription in this SedListOfDataDescriptions or NULL if no such object exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
get(const std::string& sid)
getNumDataDescriptions()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
Referenced by get().
get() [4/4]
const SedDataDescription * SedListOfDataDescriptions::get (unsigned int n) const virtual
Get a SedDataDescription from the SedListOfDataDescriptions.
Parameters
n an unsigned int representing the index of the SedDataDescription to retrieve.
Returns
the nth SedDataDescription in this SedListOfDataDescriptions or NULL if no such object exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
get(const std::string& sid)
getNumDataDescriptions()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
getElementName()
const std::string & SedListOfDataDescriptions::getElementName () const virtual
Returns the XML element name of this SedListOfDataDescriptions object.
For SedListOfDataDescriptions, the XML element name is always "listOfDataDescriptions".
Returns
the name of this element, i.e. "listOfDataDescriptions".
Reimplemented from SedListOf.
getItemTypeCode()
int SedListOfDataDescriptions::getItemTypeCode () const virtual
Returns the libSEDML type code for the SED-ML objects contained in this SedListOfDataDescriptions object.
Returns
the SED-ML typecode for the objects contained in this SedListOfDataDescriptions: @sedmlconstant{SEDML_DATA_DESCRIPTION, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedListOf.
References SEDML_DATA_DESCRIPTION.
getNumDataDescriptions()
unsigned int SedListOfDataDescriptions::getNumDataDescriptions () const
Get the number of SedDataDescription objects in this SedListOfDataDescriptions.
Returns
the number of SedDataDescription objects in this SedListOfDataDescriptions.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
get(const std::string& sid)
get(unsigned int n)
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::size().
getTypeCode()
int SedListOfDataDescriptions::getTypeCode () const virtual
Returns the libSEDML type code for this SedListOfDataDescriptions object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Reimplemented from SedListOf.
References SEDML_LIST_OF.
operator=()
SedListOfDataDescriptions & SedListOfDataDescriptions::operator= (const SedListOfDataDescriptions & rhs)
Assignment operator for SedListOfDataDescriptions.
Parameters
rhs the SedListOfDataDescriptions object whose values are to be used as the basis of the assignment.
References SedListOf::operator=().
remove() [1/2]
SedDataDescription * SedListOfDataDescriptions::remove (const std::string & sid) virtual
Removes the SedDataDescription from this SedListOfDataDescriptions based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedDataDescription to remove.
Returns
the SedDataDescription in this SedListOfDataDescriptions based on the identifier or NULL if no such SedDataDescription exists.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
get(const std::string& sid)
get(unsigned int n)
getNumDataDescriptions()
remove(unsigned int n)
remove() [2/2]
SedDataDescription * SedListOfDataDescriptions::remove (unsigned int n) virtual
Removes the nth SedDataDescription from this SedListOfDataDescriptions and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedDataDescription to remove.
Returns
a pointer to the nth SedDataDescription in this SedListOfDataDescriptions.
See also
addDataDescription(const SedDataDescription* object)
createDataDescription()
get(const std::string& sid)
get(unsigned int n)
getNumDataDescriptions()
remove(const std::string& sid)
Reimplemented from SedListOf.
References SedListOf::remove().
The documentation for this class was generated from the following files:
SedListOfDataDescriptions.h
SedListOfDataDescriptions.cpp