LIBSEDML API: SedUniformRange Class Reference
SedUniformRange Class Reference
#include <SedUniformRange.h>
Public Member Functions
virtual SedUniformRange * clone () const
virtual const std::string & getElementName () const
double getEnd () const
int getNumberOfPoints () const
int getNumberOfSteps () const
double getStart () const
const std::string & getType () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetEnd () const
bool isSetNumberOfPoints () const
bool isSetNumberOfSteps () const
bool isSetStart () const
bool isSetType () const
SedUniformRange & operator= (const SedUniformRange &rhs)
SedUniformRange (const SedUniformRange &orig)
SedUniformRange (SedNamespaces *sedmlns)
SedUniformRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setEnd (double end)
int setNumberOfPoints (int numberOfSteps)
int setNumberOfSteps (int numberOfSteps)
int setStart (double start)
int setType (const std::string &type)
int unsetEnd ()
int unsetNumberOfPoints ()
int unsetNumberOfSteps ()
int unsetStart ()
int unsetType ()
virtual ~SedUniformRange ()
Public Member Functions inherited from SedRange
virtual bool isSedDataRange () const
virtual bool isSedFunctionalRange () const
virtual bool isSedUniformRange () const
virtual bool isSedVectorRange () const
SedRange & operator= (const SedRange &rhs)
SedRange (const SedRange &orig)
SedRange (SedNamespaces *sedmlns)
SedRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedRange ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedUniformRange class.
Constructor & Destructor Documentation
SedUniformRange() [1/3]
SedUniformRange::SedUniformRange (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedUniformRange using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedUniformRange.
version an unsigned int, the SED-ML Version to assign to this SedUniformRange.
Referenced by clone().
SedUniformRange() [2/3]
SedUniformRange::SedUniformRange (SedNamespaces * sedmlns)
Creates a new SedUniformRange using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedUniformRange() [3/3]
SedUniformRange::SedUniformRange (const SedUniformRange & orig)
Copy constructor for SedUniformRange.
Parameters
orig the SedUniformRange instance to copy.
~SedUniformRange()
SedUniformRange::~SedUniformRange () virtual
Destructor for SedUniformRange.
Member Function Documentation
clone()
SedUniformRange * SedUniformRange::clone () const virtual
Creates and returns a deep copy of this SedUniformRange object.
Returns
a (deep) copy of this SedUniformRange object.
Reimplemented from SedRange.
References SedUniformRange().
getElementName()
const std::string & SedUniformRange::getElementName () const virtual
Returns the XML element name of this SedUniformRange object.
For SedUniformRange, the XML element name is always "uniformRange".
Returns
the name of this element, i.e. "uniformRange".
Reimplemented from SedRange.
getEnd()
double SedUniformRange::getEnd () const
Returns the value of the "end" attribute of this SedUniformRange.
Returns
the value of the "end" attribute of this SedUniformRange as a double.
getNumberOfPoints()
int SedUniformRange::getNumberOfPoints () const
Returns the value of the "numberOfSteps" attribute of this SedUniformRange.
Returns
the value of the "numberOfSteps" attribute of this SedUniformRange as a integer.
getNumberOfSteps()
int SedUniformRange::getNumberOfSteps () const
Returns the value of the "numberOfSteps" attribute of this SedUniformRange.
Returns
the value of the "numberOfSteps" attribute of this SedUniformRange as a integer.
getStart()
double SedUniformRange::getStart () const
Returns the value of the "start" attribute of this SedUniformRange.
Returns
the value of the "start" attribute of this SedUniformRange as a double.
getType()
const std::string & SedUniformRange::getType () const
Returns the value of the "type" attribute of this SedUniformRange.
Returns
the value of the "type" attribute of this SedUniformRange as a string.
getTypeCode()
int SedUniformRange::getTypeCode () const virtual
Returns the libSEDML type code for this SedUniformRange object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_RANGE_UNIFORMRANGE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedRange.
References SEDML_RANGE_UNIFORMRANGE.
hasRequiredAttributes()
bool SedUniformRange::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedUniformRange object have been set.
Returns
true to indicate that all the required attributes of this SedUniformRange have been set, otherwise false is returned.
Note
The required attributes for the SedUniformRange object are:
"start"
"end"
"numberOfSteps"
"type"
Reimplemented from SedRange.
References SedRange::hasRequiredAttributes(), isSetEnd(), isSetNumberOfSteps(), isSetStart(), and isSetType().
isSetEnd()
bool SedUniformRange::isSetEnd () const
Predicate returning true if this SedUniformRange's "end" attribute is set.
Returns
true if this SedUniformRange's "end" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and unsetEnd().
isSetNumberOfPoints()
bool SedUniformRange::isSetNumberOfPoints () const
Predicate returning true if this SedUniformRange's "numberOfSteps" attribute is set.
Returns
true if this SedUniformRange's "numberOfSteps" attribute has been set, otherwise false is returned.
isSetNumberOfSteps()
bool SedUniformRange::isSetNumberOfSteps () const
Predicate returning true if this SedUniformRange's "numberOfSteps" attribute is set.
Returns
true if this SedUniformRange's "numberOfSteps" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
isSetStart()
bool SedUniformRange::isSetStart () const
Predicate returning true if this SedUniformRange's "start" attribute is set.
Returns
true if this SedUniformRange's "start" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and unsetStart().
isSetType()
bool SedUniformRange::isSetType () const
Predicate returning true if this SedUniformRange's "type" attribute is set.
Returns
true if this SedUniformRange's "type" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedUniformRange & SedUniformRange::operator= (const SedUniformRange & rhs)
Assignment operator for SedUniformRange.
Parameters
rhs the SedUniformRange object whose values are to be used as the basis of the assignment.
References SedRange::operator=().
setEnd()
int SedUniformRange::setEnd (double end)
Sets the value of the "end" attribute of this SedUniformRange.
Parameters
end double value of the "end" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setNumberOfPoints()
int SedUniformRange::setNumberOfPoints (int numberOfSteps)
Sets the value of the "numberOfSteps" attribute of this SedUniformRange.
Parameters
numberOfSteps int value of the "numberOfSteps" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setNumberOfSteps()
int SedUniformRange::setNumberOfSteps (int numberOfSteps)
Sets the value of the "numberOfSteps" attribute of this SedUniformRange.
Parameters
numberOfSteps int value of the "numberOfSteps" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setStart()
int SedUniformRange::setStart (double start)
Sets the value of the "start" attribute of this SedUniformRange.
Parameters
start double value of the "start" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setType()
int SedUniformRange::setType (const std::string & type)
Sets the value of the "type" attribute of this SedUniformRange.
Parameters
type std::string& value of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with type = NULL or an empty string is equivalent to calling unsetType().
References LIBSEDML_OPERATION_SUCCESS.
unsetEnd()
int SedUniformRange::unsetEnd ()
Unsets the value of the "end" attribute of this SedUniformRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetEnd(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetNumberOfPoints()
int SedUniformRange::unsetNumberOfPoints ()
Unsets the value of the "numberOfSteps" attribute of this SedUniformRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetNumberOfSteps()
int SedUniformRange::unsetNumberOfSteps ()
Unsets the value of the "numberOfSteps" attribute of this SedUniformRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetStart()
int SedUniformRange::unsetStart ()
Unsets the value of the "start" attribute of this SedUniformRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetStart(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetType()
int SedUniformRange::unsetType ()
Unsets the value of the "type" attribute of this SedUniformRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedUniformRange.h
SedUniformRange.cpp