LIBSEDML API: SedRepeatedTask Class Reference
SedRepeatedTask Class Reference
#include <SedRepeatedTask.h>
Public Member Functions
int addRange (const SedRange *sr)
int addSubTask (const SedSubTask *sst)
int addTaskChange (const SedSetValue *ssv)
virtual SedRepeatedTask * clone () const
SedDataRange * createDataRange ()
SedFunctionalRange * createFunctionalRange ()
SedSubTask * createSubTask ()
SedSetValue * createTaskChange ()
SedUniformRange * createUniformRange ()
SedVectorRange * createVectorRange ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
bool getConcatenate () const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfRanges * getListOfRanges ()
const SedListOfRanges * getListOfRanges () const
SedListOfSubTasks * getListOfSubTasks ()
const SedListOfSubTasks * getListOfSubTasks () const
SedListOfSetValues * getListOfTaskChanges ()
const SedListOfSetValues * getListOfTaskChanges () const
unsigned int getNumRanges () const
unsigned int getNumSubTasks () const
unsigned int getNumTaskChanges () const
SedRange * getRange (const std::string &sid)
const SedRange * getRange (const std::string &sid) const
SedRange * getRange (unsigned int n)
const SedRange * getRange (unsigned int n) const
const std::string & getRangeId () const
bool getResetModel () const
SedSubTask * getSubTask (unsigned int n)
const SedSubTask * getSubTask (unsigned int n) const
SedSubTask * getSubTaskByTask (const std::string &sid)
const SedSubTask * getSubTaskByTask (const std::string &sid) const
SedSetValue * getTaskChange (unsigned int n)
const SedSetValue * getTaskChange (unsigned int n) const
SedSetValue * getTaskChangeByModelReference (const std::string &sid)
const SedSetValue * getTaskChangeByModelReference (const std::string &sid) const
SedSetValue * getTaskChangeByRange (const std::string &sid)
const SedSetValue * getTaskChangeByRange (const std::string &sid) const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetConcatenate () const
bool isSetRangeId () const
bool isSetResetModel () const
SedRepeatedTask & operator= (const SedRepeatedTask &rhs)
SedRange * removeRange (const std::string &sid)
SedRange * removeRange (unsigned int n)
SedSubTask * removeSubTask (unsigned int n)
SedSetValue * removeTaskChange (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedRepeatedTask (const SedRepeatedTask &orig)
SedRepeatedTask (SedNamespaces *sedmlns)
SedRepeatedTask (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setConcatenate (bool concatenate)
int setRangeId (const std::string &rangeId)
int setResetModel (bool resetModel)
int unsetConcatenate ()
int unsetRangeId ()
int unsetResetModel ()
virtual ~SedRepeatedTask ()
Public Member Functions inherited from SedAbstractTask
virtual bool isSedParameterEstimationTask () const
virtual bool isSedRepeatedTask () const
virtual bool isSedTask () const
SedAbstractTask & operator= (const SedAbstractTask &rhs)
SedAbstractTask (const SedAbstractTask &orig)
SedAbstractTask (SedNamespaces *sedmlns)
SedAbstractTask (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedAbstractTask ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedRepeatedTask class.
Constructor & Destructor Documentation
SedRepeatedTask() [1/3]
SedRepeatedTask::SedRepeatedTask (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedRepeatedTask using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedRepeatedTask.
version an unsigned int, the SED-ML Version to assign to this SedRepeatedTask.
Referenced by clone().
SedRepeatedTask() [2/3]
SedRepeatedTask::SedRepeatedTask (SedNamespaces * sedmlns)
Creates a new SedRepeatedTask using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedRepeatedTask() [3/3]
SedRepeatedTask::SedRepeatedTask (const SedRepeatedTask & orig)
Copy constructor for SedRepeatedTask.
Parameters
orig the SedRepeatedTask instance to copy.
~SedRepeatedTask()
SedRepeatedTask::~SedRepeatedTask () virtual
Destructor for SedRepeatedTask.
Member Function Documentation
addRange()
int SedRepeatedTask::addRange (const SedRange * sr)
Adds a copy of the given SedRange to this SedRepeatedTask.
Parameters
sr the SedRange object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createRange()
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedRange::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addSubTask()
int SedRepeatedTask::addSubTask (const SedSubTask * sst)
Adds a copy of the given SedSubTask to this SedRepeatedTask.
Parameters
sst the SedSubTask object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createSubTask()
getSubTask(const std::string& sid)
getSubTask(unsigned int n)
getNumSubTasks()
removeSubTask(const std::string& sid)
removeSubTask(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedSubTask::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addTaskChange()
int SedRepeatedTask::addTaskChange (const SedSetValue * ssv)
Adds a copy of the given SedSetValue to this SedRepeatedTask.
Parameters
ssv the SedSetValue object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedSetValue::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedRepeatedTask * SedRepeatedTask::clone () const virtual
Creates and returns a deep copy of this SedRepeatedTask object.
Returns
a (deep) copy of this SedRepeatedTask object.
Reimplemented from SedAbstractTask.
References SedRepeatedTask().
createDataRange()
SedDataRange * SedRepeatedTask::createDataRange ()
Creates a new SedDataRange object, adds it to this SedRepeatedTask object and returns the SedDataRange object created.
Returns
a new SedDataRange object instance.
See also
addRange(const SedRange* object)
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
createFunctionalRange()
SedFunctionalRange * SedRepeatedTask::createFunctionalRange ()
Creates a new SedFunctionalRange object, adds it to this SedRepeatedTask object and returns the SedFunctionalRange object created.
Returns
a new SedFunctionalRange object instance.
See also
addRange(const SedRange* object)
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
createSubTask()
SedSubTask * SedRepeatedTask::createSubTask ()
Creates a new SedSubTask object, adds it to this SedRepeatedTask object and returns the SedSubTask object created.
Returns
a new SedSubTask object instance.
See also
addSubTask(const SedSubTask* object)
getSubTask(const std::string& sid)
getSubTask(unsigned int n)
getNumSubTasks()
removeSubTask(const std::string& sid)
removeSubTask(unsigned int n)
createTaskChange()
SedSetValue * SedRepeatedTask::createTaskChange ()
Creates a new SedSetValue object, adds it to this SedRepeatedTask object and returns the SedSetValue object created.
Returns
a new SedSetValue object instance.
See also
addTaskChange(const SedSetValue* object)
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
createUniformRange()
SedUniformRange * SedRepeatedTask::createUniformRange ()
Creates a new SedUniformRange object, adds it to this SedRepeatedTask object and returns the SedUniformRange object created.
Returns
a new SedUniformRange object instance.
See also
addRange(const SedRange* object)
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
createVectorRange()
SedVectorRange * SedRepeatedTask::createVectorRange ()
Creates a new SedVectorRange object, adds it to this SedRepeatedTask object and returns the SedVectorRange object created.
Returns
a new SedVectorRange object instance.
See also
addRange(const SedRange* object)
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
getAllElements()
List * SedRepeatedTask::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getConcatenate()
bool SedRepeatedTask::getConcatenate () const
Returns the value of the "concatenate" attribute of this SedRepeatedTask.
Returns
the value of the "concatenate" attribute of this SedRepeatedTask as a boolean.
getElementBySId()
SedBase * SedRepeatedTask::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedRepeatedTask::getElementName () const virtual
Returns the XML element name of this SedRepeatedTask object.
For SedRepeatedTask, the XML element name is always "repeatedTask".
Returns
the name of this element, i.e. "repeatedTask".
Reimplemented from SedAbstractTask.
getListOfRanges() [1/2]
SedListOfRanges * SedRepeatedTask::getListOfRanges ()
Returns the SedListOfRanges from this SedRepeatedTask.
Returns
the SedListOfRanges from this SedRepeatedTask.
See also
addRange(const SedRange* object)
createRange()
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
getListOfRanges() [2/2]
const SedListOfRanges * SedRepeatedTask::getListOfRanges () const
Returns the SedListOfRanges from this SedRepeatedTask.
Returns
the SedListOfRanges from this SedRepeatedTask.
See also
addRange(const SedRange* object)
createRange()
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
getListOfSubTasks() [1/2]
SedListOfSubTasks * SedRepeatedTask::getListOfSubTasks ()
Returns the SedListOfSubTasks from this SedRepeatedTask.
Returns
the SedListOfSubTasks from this SedRepeatedTask.
See also
addSubTask(const SedSubTask* object)
createSubTask()
getSubTask(const std::string& sid)
getSubTask(unsigned int n)
getNumSubTasks()
removeSubTask(const std::string& sid)
removeSubTask(unsigned int n)
getListOfSubTasks() [2/2]
const SedListOfSubTasks * SedRepeatedTask::getListOfSubTasks () const
Returns the SedListOfSubTasks from this SedRepeatedTask.
Returns
the SedListOfSubTasks from this SedRepeatedTask.
See also
addSubTask(const SedSubTask* object)
createSubTask()
getSubTask(const std::string& sid)
getSubTask(unsigned int n)
getNumSubTasks()
removeSubTask(const std::string& sid)
removeSubTask(unsigned int n)
Referenced by SedDocument::sortOrderedObjects().
getListOfTaskChanges() [1/2]
SedListOfSetValues * SedRepeatedTask::getListOfTaskChanges ()
Returns the SedListOfSetValues from this SedRepeatedTask.
Returns
the SedListOfSetValues from this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getListOfTaskChanges() [2/2]
const SedListOfSetValues * SedRepeatedTask::getListOfTaskChanges () const
Returns the SedListOfSetValues from this SedRepeatedTask.
Returns
the SedListOfSetValues from this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getNumRanges()
unsigned int SedRepeatedTask::getNumRanges () const
Get the number of SedRange objects in this SedRepeatedTask.
Returns
the number of SedRange objects in this SedRepeatedTask.
See also
addRange(const SedRange* object)
createRange()
getRange(const std::string& sid)
getRange(unsigned int n)
removeRange(const std::string& sid)
removeRange(unsigned int n)
getNumSubTasks()
unsigned int SedRepeatedTask::getNumSubTasks () const
Get the number of SedSubTask objects in this SedRepeatedTask.
Returns
the number of SedSubTask objects in this SedRepeatedTask.
See also
addSubTask(const SedSubTask* object)
createSubTask()
getSubTask(const std::string& sid)
getSubTask(unsigned int n)
removeSubTask(const std::string& sid)
removeSubTask(unsigned int n)
getNumTaskChanges()
unsigned int SedRepeatedTask::getNumTaskChanges () const
Get the number of SedSetValue objects in this SedRepeatedTask.
Returns
the number of SedSetValue objects in this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getRange() [1/4]
SedRange * SedRepeatedTask::getRange (const std::string & sid)
Get a SedRange from the SedRepeatedTask based on its identifier.
Parameters
sid a string representing the identifier of the SedRange to retrieve.
Returns
the SedRange in the SedListOfRanges within this SedRepeatedTask with the given sid or NULL if no such SedRange exists.
See also
addRange(const SedRange* object)
createRange()
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
getRange() [2/4]
const SedRange * SedRepeatedTask::getRange (const std::string & sid) const
Get a SedRange from the SedRepeatedTask based on its identifier.
Parameters
sid a string representing the identifier of the SedRange to retrieve.
Returns
the SedRange in the SedListOfRanges within this SedRepeatedTask with the given sid or NULL if no such SedRange exists.
See also
addRange(const SedRange* object)
createRange()
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
getRange() [3/4]
SedRange * SedRepeatedTask::getRange (unsigned int n)
Get a SedRange from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedRange to retrieve.
Returns
the nth SedRange in the SedListOfRanges within this SedRepeatedTask or NULL if no such object exists.
See also
addRange(const SedRange* object)
createRange()
getRange(const std::string& sid)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
getRange() [4/4]
const SedRange * SedRepeatedTask::getRange (unsigned int n) const
Get a SedRange from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedRange to retrieve.
Returns
the nth SedRange in the SedListOfRanges within this SedRepeatedTask or NULL if no such object exists.
See also
addRange(const SedRange* object)
createRange()
getRange(const std::string& sid)
getNumRanges()
removeRange(const std::string& sid)
removeRange(unsigned int n)
getRangeId()
const std::string & SedRepeatedTask::getRangeId () const
Returns the value of the "range" attribute of this SedRepeatedTask.
Returns
the value of the "range" attribute of this SedRepeatedTask as a string.
getResetModel()
bool SedRepeatedTask::getResetModel () const
Returns the value of the "resetModel" attribute of this SedRepeatedTask.
Returns
the value of the "resetModel" attribute of this SedRepeatedTask as a boolean.
getSubTask() [1/2]
SedSubTask * SedRepeatedTask::getSubTask (unsigned int n)
Get a SedSubTask from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedSubTask to retrieve.
Returns
the nth SedSubTask in the SedListOfSubTasks within this SedRepeatedTask or NULL if no such object exists.
See also
addSubTask(const SedSubTask* object)
createSubTask()
getSubTask(const std::string& sid)
getNumSubTasks()
removeSubTask(const std::string& sid)
removeSubTask(unsigned int n)
getSubTask() [2/2]
const SedSubTask * SedRepeatedTask::getSubTask (unsigned int n) const
Get a SedSubTask from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedSubTask to retrieve.
Returns
the nth SedSubTask in the SedListOfSubTasks within this SedRepeatedTask or NULL if no such object exists.
See also
addSubTask(const SedSubTask* object)
createSubTask()
getSubTask(const std::string& sid)
getNumSubTasks()
removeSubTask(const std::string& sid)
removeSubTask(unsigned int n)
getSubTaskByTask() [1/2]
SedSubTask * SedRepeatedTask::getSubTaskByTask (const std::string & sid)
Get a SedSubTask from the SedRepeatedTask based on the Task to which it refers.
Parameters
sid a string representing the "task" attribute of the SedSubTask object to retrieve.
Returns
the first SedSubTask in this SedRepeatedTask based on the given task attribute or NULL if no such SedSubTask exists.
getSubTaskByTask() [2/2]
const SedSubTask * SedRepeatedTask::getSubTaskByTask (const std::string & sid) const
Get a SedSubTask from the SedRepeatedTask based on the Task to which it refers.
Parameters
sid a string representing the "task" attribute of the SedSubTask object to retrieve.
Returns
the first SedSubTask in this SedRepeatedTask based on the given task attribute or NULL if no such SedSubTask exists.
getTaskChange() [1/2]
SedSetValue * SedRepeatedTask::getTaskChange (unsigned int n)
Get a SedSetValue from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedSetValue to retrieve.
Returns
the nth SedSetValue in the SedListOfSetValues within this SedRepeatedTask or NULL if no such object exists.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getTaskChange() [2/2]
const SedSetValue * SedRepeatedTask::getTaskChange (unsigned int n) const
Get a SedSetValue from the SedRepeatedTask.
Parameters
n an unsigned int representing the index of the SedSetValue to retrieve.
Returns
the nth SedSetValue in the SedListOfSetValues within this SedRepeatedTask or NULL if no such object exists.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
removeTaskChange(unsigned int n)
getTaskChangeByModelReference() [1/2]
SedSetValue * SedRepeatedTask::getTaskChangeByModelReference (const std::string & sid)
Get a SedSetValue from the SedRepeatedTask based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given modelReference attribute or NULL if no such SedSetValue exists.
getTaskChangeByModelReference() [2/2]
const SedSetValue * SedRepeatedTask::getTaskChangeByModelReference (const std::string & sid) const
Get a SedSetValue from the SedRepeatedTask based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given modelReference attribute or NULL if no such SedSetValue exists.
getTaskChangeByRange() [1/2]
SedSetValue * SedRepeatedTask::getTaskChangeByRange (const std::string & sid)
Get a SedSetValue from the SedRepeatedTask based on the Range to which it refers.
Parameters
sid a string representing the "range" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given range attribute or NULL if no such SedSetValue exists.
getTaskChangeByRange() [2/2]
const SedSetValue * SedRepeatedTask::getTaskChangeByRange (const std::string & sid) const
Get a SedSetValue from the SedRepeatedTask based on the Range to which it refers.
Parameters
sid a string representing the "range" attribute of the SedSetValue object to retrieve.
Returns
the first SedSetValue in this SedRepeatedTask based on the given range attribute or NULL if no such SedSetValue exists.
getTypeCode()
int SedRepeatedTask::getTypeCode () const virtual
Returns the libSEDML type code for this SedRepeatedTask object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_TASK_REPEATEDTASK, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedAbstractTask.
References SEDML_TASK_REPEATEDTASK.
hasRequiredAttributes()
bool SedRepeatedTask::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedRepeatedTask object have been set.
Returns
true to indicate that all the required attributes of this SedRepeatedTask have been set, otherwise false is returned.
Reimplemented from SedAbstractTask.
References SedAbstractTask::hasRequiredAttributes().
hasRequiredElements()
bool SedRepeatedTask::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedRepeatedTask object have been set.
Returns
true to indicate that all the required elements of this SedRepeatedTask have been set, otherwise false is returned.
Note
The required elements for the SedRepeatedTask object are:
isSetConcatenate()
bool SedRepeatedTask::isSetConcatenate () const
Predicate returning true if this SedRepeatedTask's "concatenate" attribute is set.
Returns
true if this SedRepeatedTask's "concatenate" attribute has been set, otherwise false is returned.
Referenced by unsetConcatenate().
isSetRangeId()
bool SedRepeatedTask::isSetRangeId () const
Predicate returning true if this SedRepeatedTask's "range" attribute is set.
Returns
true if this SedRepeatedTask's "range" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetResetModel()
bool SedRepeatedTask::isSetResetModel () const
Predicate returning true if this SedRepeatedTask's "resetModel" attribute is set.
Returns
true if this SedRepeatedTask's "resetModel" attribute has been set, otherwise false is returned.
Referenced by unsetResetModel().
operator=()
SedRepeatedTask & SedRepeatedTask::operator= (const SedRepeatedTask & rhs)
Assignment operator for SedRepeatedTask.
Parameters
rhs the SedRepeatedTask object whose values are to be used as the basis of the assignment.
References SedAbstractTask::operator=().
removeRange() [1/2]
SedRange * SedRepeatedTask::removeRange (const std::string & sid)
Removes the SedRange from this SedRepeatedTask based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedRange to remove.
Returns
the SedRange in this SedRepeatedTask based on the identifier or NULL if no such SedRange exists.
See also
addRange(const SedRange* object)
createRange()
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(unsigned int n)
removeRange() [2/2]
SedRange * SedRepeatedTask::removeRange (unsigned int n)
Removes the nth SedRange from this SedRepeatedTask and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedRange to remove.
Returns
a pointer to the nth SedRange in this SedRepeatedTask.
See also
addRange(const SedRange* object)
createRange()
getRange(const std::string& sid)
getRange(unsigned int n)
getNumRanges()
removeRange(const std::string& sid)
removeSubTask()
SedSubTask * SedRepeatedTask::removeSubTask (unsigned int n)
Removes the nth SedSubTask from this SedRepeatedTask and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSubTask to remove.
Returns
a pointer to the nth SedSubTask in this SedRepeatedTask.
See also
addSubTask(const SedSubTask* object)
createSubTask()
getSubTask(const std::string& sid)
getSubTask(unsigned int n)
getNumSubTasks()
removeSubTask(const std::string& sid)
removeTaskChange()
SedSetValue * SedRepeatedTask::removeTaskChange (unsigned int n)
Removes the nth SedSetValue from this SedRepeatedTask and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSetValue to remove.
Returns
a pointer to the nth SedSetValue in this SedRepeatedTask.
See also
addTaskChange(const SedSetValue* object)
createTaskChange()
getTaskChange(const std::string& sid)
getTaskChange(unsigned int n)
getNumTaskChanges()
removeTaskChange(const std::string& sid)
renameSIdRefs()
void SedRepeatedTask::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetRangeId(), and setRangeId().
setConcatenate()
int SedRepeatedTask::setConcatenate (bool concatenate)
Sets the value of the "concatenate" attribute of this SedRepeatedTask.
Parameters
concatenate bool value of the "concatenate" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedBase::getLevel(), SedBase::getVersion(), LIBSEDML_OPERATION_SUCCESS, and LIBSEDML_UNEXPECTED_ATTRIBUTE.
setRangeId()
int SedRepeatedTask::setRangeId (const std::string & rangeId)
Sets the value of the "range" attribute of this SedRepeatedTask.
Parameters
rangeId std::string& value of the "range" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setResetModel()
int SedRepeatedTask::setResetModel (bool resetModel)
Sets the value of the "resetModel" attribute of this SedRepeatedTask.
Parameters
resetModel bool value of the "resetModel" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetConcatenate()
int SedRepeatedTask::unsetConcatenate ()
Unsets the value of the "concatenate" attribute of this SedRepeatedTask.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetConcatenate(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetRangeId()
int SedRepeatedTask::unsetRangeId ()
Unsets the value of the "range" attribute of this SedRepeatedTask.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetResetModel()
int SedRepeatedTask::unsetResetModel ()
Unsets the value of the "resetModel" attribute of this SedRepeatedTask.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetResetModel(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedRepeatedTask.h
SedRepeatedTask.cpp