LIBSEDML API: SedDataSource Class Reference
SedDataSource Class Reference
#include <SedDataSource.h>
Public Member Functions
int addSlice (const SedSlice *ss)
virtual SedDataSource * clone () const
SedSlice * createSlice ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
const std::string & getIndexSet () const
SedListOfSlices * getListOfSlices ()
const SedListOfSlices * getListOfSlices () const
unsigned int getNumSlices () const
SedSlice * getSlice (unsigned int n)
const SedSlice * getSlice (unsigned int n) const
SedSlice * getSliceByIndex (const std::string &sid)
const SedSlice * getSliceByIndex (const std::string &sid) const
SedSlice * getSliceByReference (const std::string &sid)
const SedSlice * getSliceByReference (const std::string &sid) const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetIndexSet () const
SedDataSource & operator= (const SedDataSource &rhs)
SedSlice * removeSlice (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedDataSource (const SedDataSource &orig)
SedDataSource (SedNamespaces *sedmlns)
SedDataSource (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setIndexSet (const std::string &indexSet)
int unsetIndexSet ()
virtual ~SedDataSource ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedDataSource class.
Constructor & Destructor Documentation
SedDataSource() [1/3]
SedDataSource::SedDataSource (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedDataSource using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedDataSource.
version an unsigned int, the SED-ML Version to assign to this SedDataSource.
Referenced by clone().
SedDataSource() [2/3]
SedDataSource::SedDataSource (SedNamespaces * sedmlns)
Creates a new SedDataSource using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedDataSource() [3/3]
SedDataSource::SedDataSource (const SedDataSource & orig)
Copy constructor for SedDataSource.
Parameters
orig the SedDataSource instance to copy.
~SedDataSource()
SedDataSource::~SedDataSource () virtual
Destructor for SedDataSource.
Member Function Documentation
addSlice()
int SedDataSource::addSlice (const SedSlice * ss)
Adds a copy of the given SedSlice to this SedDataSource.
Parameters
ss the SedSlice object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createSlice()
getSlice(const std::string& sid)
getSlice(unsigned int n)
getNumSlices()
removeSlice(const std::string& sid)
removeSlice(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedSlice::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedDataSource * SedDataSource::clone () const virtual
Creates and returns a deep copy of this SedDataSource object.
Returns
a (deep) copy of this SedDataSource object.
Implements SedBase.
References SedDataSource().
createSlice()
SedSlice * SedDataSource::createSlice ()
Creates a new SedSlice object, adds it to this SedDataSource object and returns the SedSlice object created.
Returns
a new SedSlice object instance.
See also
addSlice(const SedSlice* object)
getSlice(const std::string& sid)
getSlice(unsigned int n)
getNumSlices()
removeSlice(const std::string& sid)
removeSlice(unsigned int n)
getAllElements()
List * SedDataSource::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getElementBySId()
SedBase * SedDataSource::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedDataSource::getElementName () const virtual
Returns the XML element name of this SedDataSource object.
For SedDataSource, the XML element name is always "dataSource".
Returns
the name of this element, i.e. "dataSource".
Implements SedBase.
getIndexSet()
const std::string & SedDataSource::getIndexSet () const
Returns the value of the "indexSet" attribute of this SedDataSource.
Returns
the value of the "indexSet" attribute of this SedDataSource as a string.
getListOfSlices() [1/2]
SedListOfSlices * SedDataSource::getListOfSlices ()
Returns the SedListOfSlices from this SedDataSource.
Returns
the SedListOfSlices from this SedDataSource.
See also
addSlice(const SedSlice* object)
createSlice()
getSlice(const std::string& sid)
getSlice(unsigned int n)
getNumSlices()
removeSlice(const std::string& sid)
removeSlice(unsigned int n)
getListOfSlices() [2/2]
const SedListOfSlices * SedDataSource::getListOfSlices () const
Returns the SedListOfSlices from this SedDataSource.
Returns
the SedListOfSlices from this SedDataSource.
See also
addSlice(const SedSlice* object)
createSlice()
getSlice(const std::string& sid)
getSlice(unsigned int n)
getNumSlices()
removeSlice(const std::string& sid)
removeSlice(unsigned int n)
getNumSlices()
unsigned int SedDataSource::getNumSlices () const
Get the number of SedSlice objects in this SedDataSource.
Returns
the number of SedSlice objects in this SedDataSource.
See also
addSlice(const SedSlice* object)
createSlice()
getSlice(const std::string& sid)
getSlice(unsigned int n)
removeSlice(const std::string& sid)
removeSlice(unsigned int n)
getSlice() [1/2]
SedSlice * SedDataSource::getSlice (unsigned int n)
Get a SedSlice from the SedDataSource.
Parameters
n an unsigned int representing the index of the SedSlice to retrieve.
Returns
the nth SedSlice in the SedListOfSlices within this SedDataSource or NULL if no such object exists.
See also
addSlice(const SedSlice* object)
createSlice()
getSlice(const std::string& sid)
getNumSlices()
removeSlice(const std::string& sid)
removeSlice(unsigned int n)
getSlice() [2/2]
const SedSlice * SedDataSource::getSlice (unsigned int n) const
Get a SedSlice from the SedDataSource.
Parameters
n an unsigned int representing the index of the SedSlice to retrieve.
Returns
the nth SedSlice in the SedListOfSlices within this SedDataSource or NULL if no such object exists.
See also
addSlice(const SedSlice* object)
createSlice()
getSlice(const std::string& sid)
getNumSlices()
removeSlice(const std::string& sid)
removeSlice(unsigned int n)
getSliceByIndex() [1/2]
SedSlice * SedDataSource::getSliceByIndex (const std::string & sid)
Get a SedSlice from the SedDataSource based on the Index to which it refers.
Parameters
sid a string representing the "index" attribute of the SedSlice object to retrieve.
Returns
the first SedSlice in this SedDataSource based on the given index attribute or NULL if no such SedSlice exists.
getSliceByIndex() [2/2]
const SedSlice * SedDataSource::getSliceByIndex (const std::string & sid) const
Get a SedSlice from the SedDataSource based on the Index to which it refers.
Parameters
sid a string representing the "index" attribute of the SedSlice object to retrieve.
Returns
the first SedSlice in this SedDataSource based on the given index attribute or NULL if no such SedSlice exists.
getSliceByReference() [1/2]
SedSlice * SedDataSource::getSliceByReference (const std::string & sid)
Get a SedSlice from the SedDataSource based on the Reference to which it refers.
Parameters
sid a string representing the "reference" attribute of the SedSlice object to retrieve.
Returns
the first SedSlice in this SedDataSource based on the given reference attribute or NULL if no such SedSlice exists.
getSliceByReference() [2/2]
const SedSlice * SedDataSource::getSliceByReference (const std::string & sid) const
Get a SedSlice from the SedDataSource based on the Reference to which it refers.
Parameters
sid a string representing the "reference" attribute of the SedSlice object to retrieve.
Returns
the first SedSlice in this SedDataSource based on the given reference attribute or NULL if no such SedSlice exists.
getTypeCode()
int SedDataSource::getTypeCode () const virtual
Returns the libSEDML type code for this SedDataSource object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_DATA_SOURCE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_DATA_SOURCE.
hasRequiredAttributes()
bool SedDataSource::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedDataSource object have been set.
Returns
true to indicate that all the required attributes of this SedDataSource have been set, otherwise false is returned.
Note
The required attributes for the SedDataSource object are:
"id"
References SedBase::isSetId().
Referenced by SedDataDescription::addDataSource(), and SedListOfDataSources::addDataSource().
isSetIndexSet()
bool SedDataSource::isSetIndexSet () const
Predicate returning true if this SedDataSource's "indexSet" attribute is set.
Returns
true if this SedDataSource's "indexSet" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
operator=()
SedDataSource & SedDataSource::operator= (const SedDataSource & rhs)
Assignment operator for SedDataSource.
Parameters
rhs the SedDataSource object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
removeSlice()
SedSlice * SedDataSource::removeSlice (unsigned int n)
Removes the nth SedSlice from this SedDataSource and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSlice to remove.
Returns
a pointer to the nth SedSlice in this SedDataSource.
See also
addSlice(const SedSlice* object)
createSlice()
getSlice(const std::string& sid)
getSlice(unsigned int n)
getNumSlices()
removeSlice(const std::string& sid)
renameSIdRefs()
void SedDataSource::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetIndexSet(), and setIndexSet().
setIndexSet()
int SedDataSource::setIndexSet (const std::string & indexSet)
Sets the value of the "indexSet" attribute of this SedDataSource.
Parameters
indexSet std::string& value of the "indexSet" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetIndexSet()
int SedDataSource::unsetIndexSet ()
Unsets the value of the "indexSet" attribute of this SedDataSource.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedDataSource.h
SedDataSource.cpp