LIBSEDML API: SedNamespaces Class Reference
SedNamespaces Class Reference
#include <SedNamespaces.h>
Public Member Functions
int addNamespace (const std::string &uri, const std::string &prefix)
int addNamespaces (const XMLNamespaces *xmlns)
virtual SedNamespaces * clone () const
unsigned int getLevel ()
unsigned int getLevel () const
XMLNamespaces * getNamespaces ()
const XMLNamespaces * getNamespaces () const
virtual std::string getURI () const
unsigned int getVersion ()
unsigned int getVersion () const
bool isValidCombination ()
SedNamespaces & operator= (const SedNamespaces &rhs)
int removeNamespace (const std::string &uri)
SedNamespaces (const SedNamespaces &orig)
SedNamespaces (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedNamespaces ()
Static Public Member Functions
static void freeSedNamespaces (List *supportedNS)
static std::string getSedNamespaceURI (unsigned int level, unsigned int version)
static const List * getSupportedNamespaces ()
static bool isSedNamespace (const std::string &uri)
Detailed Description
@sbmlbrief{} TODO:Definition of the SedNamespaces class.
Constructor & Destructor Documentation
SedNamespaces() [1/2]
SedNamespaces::SedNamespaces (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedNamespaces object corresponding to the given SED-ML level and version.
Parameters
level the SED-ML level
version the SED-ML version
Referenced by clone(), and getSupportedNamespaces().
~SedNamespaces()
SedNamespaces::~SedNamespaces () virtual
Destroys this SedNamespaces object.
SedNamespaces() [2/2]
SedNamespaces::SedNamespaces (const SedNamespaces & orig)
Copy constructor; creates a copy of a SedNamespaces.
Parameters
orig the SedNamespaces instance to copy.
Member Function Documentation
addNamespace()
int SedNamespaces::addNamespace (const std::string & uri, const std::string & prefix)
Add an XML namespace (a pair of URI and prefix) to the set of namespaces within this SedNamespaces object.
Parameters
uri the XML namespace to be added.
prefix the prefix of the namespace to be added.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
References LIBSEDML_INVALID_OBJECT.
addNamespaces()
int SedNamespaces::addNamespaces (const XMLNamespaces * xmlns)
Add the given XML namespaces list to the set of namespaces within this SedNamespaces object.
Parameters
xmlns the XML namespaces to be added.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
References LIBSEDML_INVALID_OBJECT, and LIBSEDML_OPERATION_SUCCESS.
clone()
SedNamespaces * SedNamespaces::clone () const virtual
Creates and returns a deep copy of this SedNamespaces object.
Returns
the (deep) copy of this SedNamespaces object.
References SedNamespaces().
freeSedNamespaces()
void SedNamespaces::freeSedNamespaces (List * supportedNS) static
Frees the list of supported namespaces as generated by getSupportedNamespaces().
Parameters
supportedNS the list to be freed.
getLevel() [1/2]
unsigned int SedNamespaces::getLevel ()
Get the SED-ML Level of this SedNamespaces object.
Returns
the SED-ML Level of this SedNamespaces object.
Referenced by isValidCombination().
getLevel() [2/2]
unsigned int SedNamespaces::getLevel () const
Get the SED-ML Level of this SedNamespaces object.
Returns
the SED-ML Level of this SedNamespaces object.
getNamespaces() [1/2]
XMLNamespaces * SedNamespaces::getNamespaces ()
Get the XML namespaces list for this SedNamespaces object.
Returns
the XML namespaces of this SedNamespaces object.
Referenced by isValidCombination().
getNamespaces() [2/2]
const XMLNamespaces * SedNamespaces::getNamespaces () const
Get the XML namespaces list for this SedNamespaces object.
Returns
the XML namespaces of this SedNamespaces object.
getSedNamespaceURI()
std::string SedNamespaces::getSedNamespaceURI (unsigned int level, unsigned int version) static
Returns a string representing the SED-ML XML namespace for the given level and version of SED-ML.
Parameters
level the SED-ML level
version the SED-ML version
Returns
a string representing the SED-ML namespace that reflects the SED-ML Level and Version specified.
References LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V1, LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V2, LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V3, and LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V4.
Referenced by getURI().
getSupportedNamespaces()
const List * SedNamespaces::getSupportedNamespaces () static
Returns a list of all supported SedNamespaces in this version of libsedml.
Returns
a list with supported SED-ML namespaces.
References SedNamespaces().
getURI()
std::string SedNamespaces::getURI () const virtual
Returns a string representing the SED-ML XML namespace of this object.
Returns
a string representing the SED-ML namespace that reflects the SED-ML Level and Version of this object.
References getSedNamespaceURI().
Referenced by SedAbstractTask::SedAbstractTask(), SedAddXML::SedAddXML(), SedAdjustableParameter::SedAdjustableParameter(), SedAlgorithm::SedAlgorithm(), SedAlgorithmParameter::SedAlgorithmParameter(), SedAnalysis::SedAnalysis(), SedAppliedDimension::SedAppliedDimension(), SedAxis::SedAxis(), SedBounds::SedBounds(), SedChange::SedChange(), SedChangeAttribute::SedChangeAttribute(), SedChangeXML::SedChangeXML(), SedComputeChange::SedComputeChange(), SedCurve::SedCurve(), SedDataDescription::SedDataDescription(), SedDataGenerator::SedDataGenerator(), SedDataRange::SedDataRange(), SedDataSet::SedDataSet(), SedDataSource::SedDataSource(), SedExperimentReference::SedExperimentReference(), SedFill::SedFill(), SedFitExperiment::SedFitExperiment(), SedFitMapping::SedFitMapping(), SedFunctionalRange::SedFunctionalRange(), SedLeastSquareObjectiveFunction::SedLeastSquareObjectiveFunction(), SedLine::SedLine(), SedListOfAdjustableParameters::SedListOfAdjustableParameters(), SedListOfAlgorithmParameters::SedListOfAlgorithmParameters(), SedListOfAppliedDimensions::SedListOfAppliedDimensions(), SedListOfChanges::SedListOfChanges(), SedListOfCurves::SedListOfCurves(), SedListOfDataDescriptions::SedListOfDataDescriptions(), SedListOfDataGenerators::SedListOfDataGenerators(), SedListOfDataSets::SedListOfDataSets(), SedListOfDataSources::SedListOfDataSources(), SedListOfExperimentReferences::SedListOfExperimentReferences(), SedListOfFitExperiments::SedListOfFitExperiments(), SedListOfFitMappings::SedListOfFitMappings(), SedListOfModels::SedListOfModels(), SedListOfOutputs::SedListOfOutputs(), SedListOfParameters::SedListOfParameters(), SedListOfRanges::SedListOfRanges(), SedListOfSetValues::SedListOfSetValues(), SedListOfSimulations::SedListOfSimulations(), SedListOfSlices::SedListOfSlices(), SedListOfStyles::SedListOfStyles(), SedListOfSubPlots::SedListOfSubPlots(), SedListOfSubTasks::SedListOfSubTasks(), SedListOfSurfaces::SedListOfSurfaces(), SedListOfTasks::SedListOfTasks(), SedListOfVariables::SedListOfVariables(), SedMarker::SedMarker(), SedModel::SedModel(), SedObjective::SedObjective(), SedOneStep::SedOneStep(), SedOutput::SedOutput(), SedParameter::SedParameter(), SedParameterEstimationReport::SedParameterEstimationReport(), SedParameterEstimationResultPlot::SedParameterEstimationResultPlot(), SedParameterEstimationTask::SedParameterEstimationTask(), SedPlot::SedPlot(), SedPlot2D::SedPlot2D(), SedPlot3D::SedPlot3D(), SedRange::SedRange(), SedRemoveXML::SedRemoveXML(), SedRepeatedTask::SedRepeatedTask(), SedReport::SedReport(), SedSetValue::SedSetValue(), SedShadedArea::SedShadedArea(), SedSimulation::SedSimulation(), SedSteadyState::SedSteadyState(), SedStyle::SedStyle(), SedTask::SedTask(), SedVariable::SedVariable(), SedVectorRange::SedVectorRange(), and SedWaterfallPlot::SedWaterfallPlot().
getVersion() [1/2]
unsigned int SedNamespaces::getVersion ()
Get the SED-ML Version of this SedNamespaces object.
Returns
the SED-ML Version of this SedNamespaces object.
Referenced by isValidCombination().
getVersion() [2/2]
unsigned int SedNamespaces::getVersion () const
Get the SED-ML Version of this SedNamespaces object.
Returns
the SED-ML Version of this SedNamespaces object.
isSedNamespace()
bool SedNamespaces::isSedNamespace (const std::string & uri) static
Predicate returning true if the given URL is one of SED-ML XML namespaces.
Parameters
uri the URI of namespace
Returns
true if the "uri" is one of SED-ML namespaces, false otherwise.
References LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V1.
isValidCombination()
bool SedNamespaces::isValidCombination ()
Predicate returning true if the given set of namespaces represent a valid set
Returns
true if the set of namespaces is valid, false otherwise.
References getLevel(), getNamespaces(), getVersion(), LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V1, LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V2, LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V3, and LIBSEDML_CPP_NAMESPACE::SEDML_XMLNS_L1V4.
operator=()
SedNamespaces & SedNamespaces::operator= (const SedNamespaces & rhs)
Assignment operator for SedNamespaces.
removeNamespace()
int SedNamespaces::removeNamespace (const std::string & uri)
Removes an XML namespace from the set of namespaces within this SedNamespaces object.
Parameters
uri the XML namespace to be added.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INDEX_EXCEEDS_SIZE, OperationReturnValues_t}
References LIBSEDML_INVALID_OBJECT.
The documentation for this class was generated from the following files:
SedNamespaces.h
SedNamespaces.cpp