LIBSEDML API: SedAlgorithmParameter Class Reference
SedAlgorithmParameter Class Reference
#include <SedAlgorithmParameter.h>
Public Member Functions
int addAlgorithmParameter (const SedAlgorithmParameter *sap1)
virtual SedAlgorithmParameter * clone () const
SedAlgorithmParameter * createAlgorithmParameter ()
SedAlgorithmParameter * getAlgorithmParameter (unsigned int n)
const SedAlgorithmParameter * getAlgorithmParameter (unsigned int n) const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
const std::string & getKisaoID () const
int getKisaoIDasInt () const
SedListOfAlgorithmParameters * getListOfAlgorithmParameters ()
const SedListOfAlgorithmParameters * getListOfAlgorithmParameters () const
unsigned int getNumAlgorithmParameters () const
virtual int getTypeCode () const
const std::string & getValue () const
virtual bool hasRequiredAttributes () const
bool isSetKisaoID () const
bool isSetValue () const
SedAlgorithmParameter & operator= (const SedAlgorithmParameter &rhs)
SedAlgorithmParameter * removeAlgorithmParameter (unsigned int n)
SedAlgorithmParameter (const SedAlgorithmParameter &orig)
SedAlgorithmParameter (SedNamespaces *sedmlns)
SedAlgorithmParameter (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setKisaoID (const std::string &kisaoID)
int setKisaoID (int kisaoID)
int setValue (const std::string &value)
int unsetKisaoID ()
int unsetValue ()
virtual ~SedAlgorithmParameter ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAlgorithmParameter class.
Constructor & Destructor Documentation
SedAlgorithmParameter() [1/3]
SedAlgorithmParameter::SedAlgorithmParameter (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAlgorithmParameter using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAlgorithmParameter.
version an unsigned int, the SED-ML Version to assign to this SedAlgorithmParameter.
Referenced by clone(), and createAlgorithmParameter().
SedAlgorithmParameter() [2/3]
SedAlgorithmParameter::SedAlgorithmParameter (SedNamespaces * sedmlns)
Creates a new SedAlgorithmParameter using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedAlgorithmParameter() [3/3]
SedAlgorithmParameter::SedAlgorithmParameter (const SedAlgorithmParameter & orig)
Copy constructor for SedAlgorithmParameter.
Parameters
orig the SedAlgorithmParameter instance to copy.
References clone().
~SedAlgorithmParameter()
SedAlgorithmParameter::~SedAlgorithmParameter () virtual
Destructor for SedAlgorithmParameter.
Member Function Documentation
addAlgorithmParameter()
int SedAlgorithmParameter::addAlgorithmParameter (const SedAlgorithmParameter * sap1)
Adds a copy of the given SedAlgorithmParameter to this SedAlgorithmParameter.
Parameters
sap1 the SedAlgorithmParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedAlgorithmParameter * SedAlgorithmParameter::clone () const virtual
Creates and returns a deep copy of this SedAlgorithmParameter object.
Returns
a (deep) copy of this SedAlgorithmParameter object.
Implements SedBase.
References SedAlgorithmParameter().
Referenced by operator=(), and SedAlgorithmParameter().
createAlgorithmParameter()
SedAlgorithmParameter * SedAlgorithmParameter::createAlgorithmParameter ()
Creates a new SedAlgorithmParameter object, adds it to this SedAlgorithmParameter object and returns the SedAlgorithmParameter object created.
Returns
a new SedAlgorithmParameter object instance.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
References SedAlgorithmParameter().
getAlgorithmParameter() [1/2]
SedAlgorithmParameter * SedAlgorithmParameter::getAlgorithmParameter (unsigned int n)
Get a SedAlgorithmParameter from the SedAlgorithmParameter.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in the SedListOfAlgorithmParameters
within this SedAlgorithmParameter or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAlgorithmParameter() [2/2]
const SedAlgorithmParameter * SedAlgorithmParameter::getAlgorithmParameter (unsigned int n) const
Get a SedAlgorithmParameter from the SedAlgorithmParameter.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in the SedListOfAlgorithmParameters
within this SedAlgorithmParameter or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAllElements()
List * SedAlgorithmParameter::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_POINTER.
getElementBySId()
SedBase * SedAlgorithmParameter::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedAlgorithmParameter::getElementName () const virtual
Returns the XML element name of this SedAlgorithmParameter object.
For SedAlgorithmParameter, the XML element name is always "algorithmParameter".
Returns
the name of this element, i.e. "algorithmParameter".
Implements SedBase.
getKisaoID()
const std::string & SedAlgorithmParameter::getKisaoID () const
Returns the value of the "kisaoID" attribute of this SedAlgorithmParameter.
Returns
the value of the "kisaoID" attribute of this SedAlgorithmParameter as a string.
getKisaoIDasInt()
int SedAlgorithmParameter::getKisaoIDasInt () const
Returns
the KisaoTerm as integer if possible or -1 in case of failure
Referenced by setKisaoID().
getListOfAlgorithmParameters() [1/2]
SedListOfAlgorithmParameters * SedAlgorithmParameter::getListOfAlgorithmParameters ()
Returns the SedListOfAlgorithmParameters * from this SedAlgorithmParameter.
Returns
the SedListOfAlgorithmParameters * from this SedAlgorithmParameter.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getListOfAlgorithmParameters() [2/2]
const SedListOfAlgorithmParameters * SedAlgorithmParameter::getListOfAlgorithmParameters () const
Returns the SedListOfAlgorithmParameters * from this SedAlgorithmParameter.
Returns
the SedListOfAlgorithmParameters * from this SedAlgorithmParameter.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
unsigned int SedAlgorithmParameter::getNumAlgorithmParameters () const
Get the number of SedAlgorithmParameter objects in this SedAlgorithmParameter.
Returns
the number of SedAlgorithmParameter objects in this SedAlgorithmParameter.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getTypeCode()
int SedAlgorithmParameter::getTypeCode () const virtual
Returns the libSEDML type code for this SedAlgorithmParameter object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SIMULATION_ALGORITHM_PARAMETER, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_SIMULATION_ALGORITHM_PARAMETER.
getValue()
const std::string & SedAlgorithmParameter::getValue () const
Returns the value of the "value" attribute of this SedAlgorithmParameter.
Returns
the value of the "value" attribute of this SedAlgorithmParameter as a string.
hasRequiredAttributes()
bool SedAlgorithmParameter::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAlgorithmParameter object have been set.
Returns
true to indicate that all the required attributes of this SedAlgorithmParameter have been set, otherwise false is returned.
Note
The required attributes for the SedAlgorithmParameter object are:
"kisaoID"
"value"
References isSetKisaoID(), and isSetValue().
Referenced by SedAlgorithm::addAlgorithmParameter(), SedDocument::addAlgorithmParameter(), SedListOfAlgorithmParameters::addAlgorithmParameter(), and addAlgorithmParameter().
isSetKisaoID()
bool SedAlgorithmParameter::isSetKisaoID () const
Predicate returning true if this SedAlgorithmParameter's "kisaoID" attribute is set.
Returns
true if this SedAlgorithmParameter's "kisaoID" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
isSetValue()
bool SedAlgorithmParameter::isSetValue () const
Predicate returning true if this SedAlgorithmParameter's "value" attribute is set.
Returns
true if this SedAlgorithmParameter's "value" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedAlgorithmParameter & SedAlgorithmParameter::operator= (const SedAlgorithmParameter & rhs)
Assignment operator for SedAlgorithmParameter.
Parameters
rhs the SedAlgorithmParameter object whose values are to be used as the basis of the assignment.
References clone(), and SedBase::operator=().
removeAlgorithmParameter()
SedAlgorithmParameter * SedAlgorithmParameter::removeAlgorithmParameter (unsigned int n)
Removes the nth SedAlgorithmParameter from this SedAlgorithmParameter and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to remove.
Returns
a pointer to the nth SedAlgorithmParameter in this SedAlgorithmParameter.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
setKisaoID() [1/2]
int SedAlgorithmParameter::setKisaoID (const std::string & kisaoID)
Sets the value of the "kisaoID" attribute of this SedAlgorithmParameter.
Parameters
kisaoID std::string& value of the "kisaoID" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with kisaoID = NULL or an empty string is equivalent to calling unsetKisaoID().
References g_kisaomap, getKisaoIDasInt(), SedBase::isSetName(), LIBSEDML_OPERATION_SUCCESS, and SedBase::setName().
setKisaoID() [2/2]
int SedAlgorithmParameter::setKisaoID (int kisaoID)
Sets the KisaoId as integer
References g_kisaomap, SedBase::isSetName(), LIBSEDML_OPERATION_SUCCESS, and SedBase::setName().
setValue()
int SedAlgorithmParameter::setValue (const std::string & value)
Sets the value of the "value" attribute of this SedAlgorithmParameter.
Parameters
value std::string& value of the "value" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with value = NULL or an empty string is equivalent to calling unsetValue().
References LIBSEDML_OPERATION_SUCCESS.
unsetKisaoID()
int SedAlgorithmParameter::unsetKisaoID ()
Unsets the value of the "kisaoID" attribute of this SedAlgorithmParameter.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetValue()
int SedAlgorithmParameter::unsetValue ()
Unsets the value of the "value" attribute of this SedAlgorithmParameter.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedAlgorithmParameter.h
SedAlgorithmParameter.cpp