LIBSEDML API: SedLine Class Reference
SedLine Class Reference
#include <SedLine.h>
Public Member Functions
virtual SedLine * clone () const
const std::string & getColor () const
virtual const std::string & getElementName () const
double getThickness () const
LineType_t getType () const
std::string getTypeAsString () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetColor () const
bool isSetThickness () const
bool isSetType () const
SedLine & operator= (const SedLine &rhs)
SedLine (const SedLine &orig)
SedLine (SedNamespaces *sedmlns)
SedLine (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setColor (const std::string &color)
int setThickness (double thickness)
int setType (const LineType_t type)
int setType (const std::string &type)
int unsetColor ()
int unsetThickness ()
int unsetType ()
virtual ~SedLine ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedLine class.
Constructor & Destructor Documentation
SedLine() [1/3]
SedLine::SedLine (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedLine using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedLine.
version an unsigned int, the SED-ML Version to assign to this SedLine.
Referenced by clone().
SedLine() [2/3]
SedLine::SedLine (SedNamespaces * sedmlns)
Creates a new SedLine using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedLine() [3/3]
SedLine::SedLine (const SedLine & orig)
Copy constructor for SedLine.
Parameters
orig the SedLine instance to copy.
~SedLine()
SedLine::~SedLine () virtual
Destructor for SedLine.
Member Function Documentation
clone()
SedLine * SedLine::clone () const virtual
Creates and returns a deep copy of this SedLine object.
Returns
a (deep) copy of this SedLine object.
Implements SedBase.
References SedLine().
Referenced by SedStyle::setLineStyle().
getColor()
const std::string & SedLine::getColor () const
Returns the value of the "color" attribute of this SedLine.
Returns
the value of the "color" attribute of this SedLine as a string.
Referenced by SedDocument::getEffectiveStyle().
getElementName()
const std::string & SedLine::getElementName () const virtual
Returns the XML element name of this SedLine object.
For SedLine, the XML element name is always "line".
Returns
the name of this element, i.e. "line".
Implements SedBase.
getThickness()
double SedLine::getThickness () const
Returns the value of the "thickness" attribute of this SedLine.
Returns
the value of the "thickness" attribute of this SedLine as a double.
Referenced by SedDocument::getEffectiveStyle().
getType()
LineType_t SedLine::getType () const
Returns the value of the "type" attribute of this SedLine.
Returns
the value of the "type" attribute of this SedLine as a LineType_t.
The attribute "type" on a SedLine object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"none", TODO:add description
"solid", TODO:add description
"dash", TODO:add description
"dot", TODO:add description
"dashDot", TODO:add description
"dashDotDot", TODO:add description
The possible values returned by this method are:
@sbmlconstant{SEDML_LINETYPE_NONE, LineType_t}
@sbmlconstant{SEDML_LINETYPE_SOLID, LineType_t}
@sbmlconstant{SEDML_LINETYPE_DASH, LineType_t}
@sbmlconstant{SEDML_LINETYPE_DOT, LineType_t}
@sbmlconstant{SEDML_LINETYPE_DASHDOT, LineType_t}
@sbmlconstant{SEDML_LINETYPE_DASHDOTDOT, LineType_t}
@sbmlconstant{SEDML_LINETYPE_INVALID, LineType_t}
Referenced by SedDocument::getEffectiveStyle().
getTypeAsString()
std::string SedLine::getTypeAsString () const
Returns the value of the "type" attribute of this SedLine.
Returns
the value of the "type" attribute of this SedLine as a string.
The attribute "type" on a SedLine object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"none", TODO:add description
"solid", TODO:add description
"dash", TODO:add description
"dot", TODO:add description
"dashDot", TODO:add description
"dashDotDot", TODO:add description
The possible values returned by this method are:
"none"
"solid"
"dash"
"dot"
"dashDot"
"dashDotDot"
"invalid LineType value"
References LineType_toString().
getTypeCode()
int SedLine::getTypeCode () const virtual
Returns the libSEDML type code for this SedLine object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LINE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_LINE.
hasRequiredAttributes()
bool SedLine::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedLine object have been set.
Returns
true to indicate that all the required attributes of this SedLine have been set, otherwise false is returned.
isSetColor()
bool SedLine::isSetColor () const
Predicate returning true if this SedLine's "color" attribute is set.
Returns
true if this SedLine's "color" attribute has been set, otherwise false is returned.
Referenced by SedDocument::getEffectiveStyle().
isSetThickness()
bool SedLine::isSetThickness () const
Predicate returning true if this SedLine's "thickness" attribute is set.
Returns
true if this SedLine's "thickness" attribute has been set, otherwise false is returned.
Referenced by SedDocument::getEffectiveStyle(), and unsetThickness().
isSetType()
bool SedLine::isSetType () const
Predicate returning true if this SedLine's "type" attribute is set.
Returns
true if this SedLine's "type" attribute has been set, otherwise false is returned.
The attribute "type" on a SedLine object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"none", TODO:add description
"solid", TODO:add description
"dash", TODO:add description
"dot", TODO:add description
"dashDot", TODO:add description
"dashDotDot", TODO:add description
References SEDML_LINETYPE_INVALID.
Referenced by SedDocument::getEffectiveStyle().
operator=()
SedLine & SedLine::operator= (const SedLine & rhs)
Assignment operator for SedLine.
Parameters
rhs the SedLine object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
setColor()
int SedLine::setColor (const std::string & color)
Sets the value of the "color" attribute of this SedLine.
Parameters
color std::string& value of the "color" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with color = NULL or an empty string is equivalent to calling unsetColor().
References LIBSEDML_OPERATION_SUCCESS.
Referenced by SedDocument::getEffectiveStyle().
setThickness()
int SedLine::setThickness (double thickness)
Sets the value of the "thickness" attribute of this SedLine.
Parameters
thickness double value of the "thickness" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
Referenced by SedDocument::getEffectiveStyle().
setType() [1/2]
int SedLine::setType (const LineType_t type)
Sets the value of the "type" attribute of this SedLine.
Parameters
type intvalue of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedLine object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"none", TODO:add description
"solid", TODO:add description
"dash", TODO:add description
"dot", TODO:add description
"dashDot", TODO:add description
"dashDotDot", TODO:add description
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, LineType_isValid(), and SEDML_LINETYPE_INVALID.
Referenced by SedDocument::getEffectiveStyle().
setType() [2/2]
int SedLine::setType (const std::string & type)
Sets the value of the "type" attribute of this SedLine.
Parameters
type std::string& of the "type" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
The attribute "type" on a SedLine object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"none", TODO:add description
"solid", TODO:add description
"dash", TODO:add description
"dot", TODO:add description
"dashDot", TODO:add description
"dashDotDot", TODO:add description
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, LIBSEDML_OPERATION_SUCCESS, LineType_fromString(), and SEDML_LINETYPE_INVALID.
unsetColor()
int SedLine::unsetColor ()
Unsets the value of the "color" attribute of this SedLine.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetThickness()
int SedLine::unsetThickness ()
Unsets the value of the "thickness" attribute of this SedLine.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetThickness(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetType()
int SedLine::unsetType ()
Unsets the value of the "type" attribute of this SedLine.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
The attribute "type" on a SedLine object is used to TODO:add explanation
In the SBML Level 3 Version 1 Sedml specification, the following are the allowable values for "type":
"none", TODO:add description
"solid", TODO:add description
"dash", TODO:add description
"dot", TODO:add description
"dashDot", TODO:add description
"dashDotDot", TODO:add description
References LIBSEDML_OPERATION_SUCCESS, and SEDML_LINETYPE_INVALID.
The documentation for this class was generated from the following files:
SedLine.h
SedLine.cpp