LIBSEDML API: SedParameterEstimationResultPlot Class Reference
SedParameterEstimationResultPlot Class Reference
#include <SedParameterEstimationResultPlot.h>
Public Member Functions
virtual SedParameterEstimationResultPlot * clone () const
virtual const std::string & getElementName () const
const std::string & getTaskReference () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetTaskReference () const
SedParameterEstimationResultPlot & operator= (const SedParameterEstimationResultPlot &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedParameterEstimationResultPlot (const SedParameterEstimationResultPlot &orig)
SedParameterEstimationResultPlot (SedNamespaces *sedmlns)
SedParameterEstimationResultPlot (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setTaskReference (const std::string &taskReference)
int unsetTaskReference ()
virtual ~SedParameterEstimationResultPlot ()
Public Member Functions inherited from SedPlot
SedAxis * createXAxis ()
SedAxis * createYAxis ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
double getHeight () const
bool getLegend () const
double getWidth () const
SedAxis * getXAxis ()
const SedAxis * getXAxis () const
SedAxis * getYAxis ()
const SedAxis * getYAxis () const
virtual bool hasRequiredElements () const
bool isSetHeight () const
bool isSetLegend () const
bool isSetWidth () const
bool isSetXAxis () const
bool isSetYAxis () const
SedPlot & operator= (const SedPlot &rhs)
SedPlot (const SedPlot &orig)
SedPlot (SedNamespaces *sedmlns)
SedPlot (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setHeight (double height)
int setLegend (bool legend)
int setWidth (double width)
int setXAxis (const SedAxis *xAxis)
int setYAxis (const SedAxis *yAxis)
int unsetHeight ()
int unsetLegend ()
int unsetWidth ()
int unsetXAxis ()
int unsetYAxis ()
virtual ~SedPlot ()
Public Member Functions inherited from SedOutput
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedParameterEstimationResultPlot class.
Constructor & Destructor Documentation
SedParameterEstimationResultPlot() [1/3]
SedParameterEstimationResultPlot::SedParameterEstimationResultPlot (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedParameterEstimationResultPlot using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedParameterEstimationResultPlot.
version an unsigned int, the SED-ML Version to assign to this SedParameterEstimationResultPlot.
Referenced by clone().
SedParameterEstimationResultPlot() [2/3]
SedParameterEstimationResultPlot::SedParameterEstimationResultPlot (SedNamespaces * sedmlns)
Creates a new SedParameterEstimationResultPlot using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedParameterEstimationResultPlot() [3/3]
SedParameterEstimationResultPlot::SedParameterEstimationResultPlot (const SedParameterEstimationResultPlot & orig)
Copy constructor for SedParameterEstimationResultPlot.
Parameters
orig the SedParameterEstimationResultPlot instance to copy.
~SedParameterEstimationResultPlot()
SedParameterEstimationResultPlot::~SedParameterEstimationResultPlot () virtual
Destructor for SedParameterEstimationResultPlot.
Member Function Documentation
clone()
SedParameterEstimationResultPlot * SedParameterEstimationResultPlot::clone () const virtual
Creates and returns a deep copy of this SedParameterEstimationResultPlot object.
Returns
a (deep) copy of this SedParameterEstimationResultPlot object.
Reimplemented from SedPlot.
References SedParameterEstimationResultPlot().
getElementName()
const std::string & SedParameterEstimationResultPlot::getElementName () const virtual
Returns the XML element name of this SedParameterEstimationResultPlot object.
For SedParameterEstimationResultPlot, the XML element name is always "parameterEstimationResultPlot".
Returns
the name of this element, i.e. "parameterEstimationResultPlot".
Reimplemented from SedPlot.
getTaskReference()
const std::string & SedParameterEstimationResultPlot::getTaskReference () const
Returns the value of the "taskReference" attribute of this SedParameterEstimationResultPlot.
Returns
the value of the "taskReference" attribute of this SedParameterEstimationResultPlot as a string.
getTypeCode()
int SedParameterEstimationResultPlot::getTypeCode () const virtual
Returns the libSEDML type code for this SedParameterEstimationResultPlot object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_PARAMETERESTIMATIONRESULTPLOT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedPlot.
References SEDML_PARAMETERESTIMATIONRESULTPLOT.
hasRequiredAttributes()
bool SedParameterEstimationResultPlot::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedParameterEstimationResultPlot object have been set.
Returns
true to indicate that all the required attributes of this SedParameterEstimationResultPlot have been set, otherwise false is returned.
Note
The required attributes for the SedParameterEstimationResultPlot object are:
"taskReference"
Reimplemented from SedPlot.
References SedPlot::hasRequiredAttributes(), and isSetTaskReference().
isSetTaskReference()
bool SedParameterEstimationResultPlot::isSetTaskReference () const
Predicate returning true if this SedParameterEstimationResultPlot's "taskReference" attribute is set.
Returns
true if this SedParameterEstimationResultPlot's "taskReference" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
operator=()
SedParameterEstimationResultPlot & SedParameterEstimationResultPlot::operator= (const SedParameterEstimationResultPlot & rhs)
Assignment operator for SedParameterEstimationResultPlot.
Parameters
rhs the SedParameterEstimationResultPlot object whose values are to be used as the basis of the assignment.
References SedPlot::operator=().
renameSIdRefs()
void SedParameterEstimationResultPlot::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetTaskReference(), and setTaskReference().
setTaskReference()
int SedParameterEstimationResultPlot::setTaskReference (const std::string & taskReference)
Sets the value of the "taskReference" attribute of this SedParameterEstimationResultPlot.
Parameters
taskReference std::string& value of the "taskReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetTaskReference()
int SedParameterEstimationResultPlot::unsetTaskReference ()
Unsets the value of the "taskReference" attribute of this SedParameterEstimationResultPlot.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedParameterEstimationResultPlot.h
SedParameterEstimationResultPlot.cpp