LIBSEDML API: SedDataDescription Class Reference
SedDataDescription Class Reference
#include <SedDataDescription.h>
Public Member Functions
int addDataSource (const SedDataSource *sds)
virtual SedDataDescription * clone () const
SedDataSource * createDataSource ()
DimensionDescription * createDimensionDescription ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedDataSource * getDataSource (const std::string &sid)
const SedDataSource * getDataSource (const std::string &sid) const
SedDataSource * getDataSource (unsigned int n)
const SedDataSource * getDataSource (unsigned int n) const
SedDataSource * getDataSourceByIndexSet (const std::string &sid)
const SedDataSource * getDataSourceByIndexSet (const std::string &sid) const
DimensionDescription * getDimensionDescription ()
const DimensionDescription * getDimensionDescription () const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
const std::string & getFormat () const
SedListOfDataSources * getListOfDataSources ()
const SedListOfDataSources * getListOfDataSources () const
unsigned int getNumDataSources () const
const std::string & getSource () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetDimensionDescription () const
bool isSetFormat () const
bool isSetSource () const
SedDataDescription & operator= (const SedDataDescription &rhs)
SedDataSource * removeDataSource (const std::string &sid)
SedDataSource * removeDataSource (unsigned int n)
SedDataDescription (const SedDataDescription &orig)
SedDataDescription (SedNamespaces *sedmlns)
SedDataDescription (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setDimensionDescription (const DimensionDescription *dimensionDescription)
int setFormat (const std::string &format)
int setSource (const std::string &source)
int unsetDimensionDescription ()
int unsetFormat ()
int unsetSource ()
virtual ~SedDataDescription ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedDataDescription class.
Constructor & Destructor Documentation
SedDataDescription() [1/3]
SedDataDescription::SedDataDescription (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedDataDescription using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedDataDescription.
version an unsigned int, the SED-ML Version to assign to this SedDataDescription.
Referenced by clone().
SedDataDescription() [2/3]
SedDataDescription::SedDataDescription (SedNamespaces * sedmlns)
Creates a new SedDataDescription using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedDataDescription() [3/3]
SedDataDescription::SedDataDescription (const SedDataDescription & orig)
Copy constructor for SedDataDescription.
Parameters
orig the SedDataDescription instance to copy.
References clone().
~SedDataDescription()
SedDataDescription::~SedDataDescription () virtual
Destructor for SedDataDescription.
Member Function Documentation
addDataSource()
int SedDataDescription::addDataSource (const SedDataSource * sds)
Adds a copy of the given SedDataSource to this SedDataDescription.
Parameters
sds the SedDataSource object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createDataSource()
getDataSource(const std::string& sid)
getDataSource(unsigned int n)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedDataSource::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedDataDescription * SedDataDescription::clone () const virtual
Creates and returns a deep copy of this SedDataDescription object.
Returns
a (deep) copy of this SedDataDescription object.
Implements SedBase.
References SedDataDescription().
Referenced by operator=(), and SedDataDescription().
createDataSource()
SedDataSource * SedDataDescription::createDataSource ()
Creates a new SedDataSource object, adds it to this SedDataDescription object and returns the SedDataSource object created.
Returns
a new SedDataSource object instance.
See also
addDataSource(const SedDataSource* object)
getDataSource(const std::string& sid)
getDataSource(unsigned int n)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
createDimensionDescription()
DimensionDescription * SedDataDescription::createDimensionDescription ()
Creates a new DimensionDescription object, adds it to this SedDataDescription object and returns the DimensionDescription object created.
Returns
a new DimensionDescription object instance.
getAllElements()
List * SedDataDescription::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getDataSource() [1/4]
SedDataSource * SedDataDescription::getDataSource (const std::string & sid)
Get a SedDataSource from the SedDataDescription based on its identifier.
Parameters
sid a string representing the identifier of the SedDataSource to retrieve.
Returns
the SedDataSource in the SedListOfDataSources within this SedDataDescription with the given sid or NULL if no such SedDataSource exists.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(unsigned int n)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
getDataSource() [2/4]
const SedDataSource * SedDataDescription::getDataSource (const std::string & sid) const
Get a SedDataSource from the SedDataDescription based on its identifier.
Parameters
sid a string representing the identifier of the SedDataSource to retrieve.
Returns
the SedDataSource in the SedListOfDataSources within this SedDataDescription with the given sid or NULL if no such SedDataSource exists.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(unsigned int n)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
getDataSource() [3/4]
SedDataSource * SedDataDescription::getDataSource (unsigned int n)
Get a SedDataSource from the SedDataDescription.
Parameters
n an unsigned int representing the index of the SedDataSource to retrieve.
Returns
the nth SedDataSource in the SedListOfDataSources within this SedDataDescription.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(const std::string& sid)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
getDataSource() [4/4]
const SedDataSource * SedDataDescription::getDataSource (unsigned int n) const
Get a SedDataSource from the SedDataDescription.
Parameters
n an unsigned int representing the index of the SedDataSource to retrieve.
Returns
the nth SedDataSource in the SedListOfDataSources within this SedDataDescription.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(const std::string& sid)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
getDataSourceByIndexSet() [1/2]
SedDataSource * SedDataDescription::getDataSourceByIndexSet (const std::string & sid)
Get a SedDataSource from the SedDataDescription based on the IndexSet to which it refers.
Parameters
sid a string representing the "indexSet" attribute of the SedDataSource object to retrieve.
Returns
the first SedDataSource in this SedDataDescription based on the given indexSet attribute or NULL if no such SedDataSource exists.
getDataSourceByIndexSet() [2/2]
const SedDataSource * SedDataDescription::getDataSourceByIndexSet (const std::string & sid) const
Get a SedDataSource from the SedDataDescription based on the IndexSet to which it refers.
Parameters
sid a string representing the "indexSet" attribute of the SedDataSource object to retrieve.
Returns
the first SedDataSource in this SedDataDescription based on the given indexSet attribute or NULL if no such SedDataSource exists.
getDimensionDescription() [1/2]
DimensionDescription * SedDataDescription::getDimensionDescription ()
Returns the value of the "dimensionDescription" element of this SedDataDescription.
Returns
the value of the "dimensionDescription" element of this SedDataDescription as a LIBNUML_CPP_NAMESPACE_QUALIFIER DimensionDescription*.
getDimensionDescription() [2/2]
const DimensionDescription * SedDataDescription::getDimensionDescription () const
Returns the value of the "dimensionDescription" element of this SedDataDescription.
Returns
the value of the "dimensionDescription" element of this SedDataDescription as a LIBNUML_CPP_NAMESPACE_QUALIFIER DimensionDescription*.
getElementBySId()
SedBase * SedDataDescription::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedDataDescription::getElementName () const virtual
Returns the XML element name of this SedDataDescription object.
For SedDataDescription, the XML element name is always "dataDescription".
Returns
the name of this element, i.e. "dataDescription".
Implements SedBase.
getFormat()
const std::string & SedDataDescription::getFormat () const
Returns the value of the "format" attribute of this SedDataDescription.
Returns
the value of the "format" attribute of this SedDataDescription as a string.
getListOfDataSources() [1/2]
SedListOfDataSources * SedDataDescription::getListOfDataSources ()
Returns the SedListOfDataSources from this SedDataDescription.
Returns
the SedListOfDataSources from this SedDataDescription.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(const std::string& sid)
getDataSource(unsigned int n)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
getListOfDataSources() [2/2]
const SedListOfDataSources * SedDataDescription::getListOfDataSources () const
Returns the SedListOfDataSources from this SedDataDescription.
Returns
the SedListOfDataSources from this SedDataDescription.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(const std::string& sid)
getDataSource(unsigned int n)
getNumDataSources()
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
getNumDataSources()
unsigned int SedDataDescription::getNumDataSources () const
Get the number of SedDataSource objects in this SedDataDescription.
Returns
the number of SedDataSource objects in this SedDataDescription.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(const std::string& sid)
getDataSource(unsigned int n)
removeDataSource(const std::string& sid)
removeDataSource(unsigned int n)
getSource()
const std::string & SedDataDescription::getSource () const
Returns the value of the "source" attribute of this SedDataDescription.
Returns
the value of the "source" attribute of this SedDataDescription as a string.
getTypeCode()
int SedDataDescription::getTypeCode () const virtual
Returns the libSEDML type code for this SedDataDescription object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_DATA_DESCRIPTION, SedmlmlTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_DATA_DESCRIPTION.
hasRequiredAttributes()
bool SedDataDescription::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedDataDescription object have been set.
Returns
true to indicate that all the required attributes of this SedDataDescription have been set, otherwise false is returned.
Note
The required attributes for the SedDataDescription object are:
"id"
References SedBase::isSetId().
Referenced by SedDocument::addDataDescription(), and SedListOfDataDescriptions::addDataDescription().
isSetDimensionDescription()
bool SedDataDescription::isSetDimensionDescription () const
Predicate returning true if this SedDataDescription's "dimensionDescription" element is set.
Returns
true if this SedDataDescription's "dimensionDescription" element has been set, otherwise false is returned.
isSetFormat()
bool SedDataDescription::isSetFormat () const
Predicate returning true if this SedDataDescription's "format" attribute is set.
Returns
true if this SedDataDescription's "format" attribute has been set, otherwise false is returned.
isSetSource()
bool SedDataDescription::isSetSource () const
Predicate returning true if this SedDataDescription's "source" attribute is set.
Returns
true if this SedDataDescription's "source" attribute has been set, otherwise false is returned.
operator=()
SedDataDescription & SedDataDescription::operator= (const SedDataDescription & rhs)
Assignment operator for SedDataDescription.
Parameters
rhs the SedDataDescription object whose values are to be used as the basis of the assignment.
References clone(), and SedBase::operator=().
removeDataSource() [1/2]
SedDataSource * SedDataDescription::removeDataSource (const std::string & sid)
Removes the SedDataSource from this SedDataDescription based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedDataSource to remove.
Returns
the SedDataSource in this SedDataDescription based on the identifier or NULL if no such SedDataSource exists.
See also
addSedDataSource(const SedDataSource* object)
createDataSource()
getSedDataSource(const std::string& sid)
getSedDataSource(unsigned int n)
getNumDataSources()
removeSedDataSource(unsigned int n)
removeDataSource() [2/2]
SedDataSource * SedDataDescription::removeDataSource (unsigned int n)
Removes the nth SedDataSource from this SedDataDescription and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedDataSource to remove.
Returns
a pointer to the nth SedDataSource in this SedDataDescription.
See also
addDataSource(const SedDataSource* object)
createDataSource()
getDataSource(const std::string& sid)
getDataSource(unsigned int n)
getNumDataSources()
removeDataSource(const std::string& sid)
setDimensionDescription()
int SedDataDescription::setDimensionDescription (const DimensionDescription * dimensionDescription)
Sets the value of the "dimensionDescription" element of this SedDataDescription.
Parameters
dimensionDescription LIBNUML_CPP_NAMESPACE_QUALIFIER DimensionDescription* value of the "dimensionDescription" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setFormat()
int SedDataDescription::setFormat (const std::string & format)
Sets the value of the "format" attribute of this SedDataDescription.
Parameters
format std::string& value of the "format" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with format = NULL or an empty string is equivalent to calling unsetFormat().
References LIBSEDML_OPERATION_SUCCESS.
setSource()
int SedDataDescription::setSource (const std::string & source)
Sets the value of the "source" attribute of this SedDataDescription.
Parameters
source std::string& value of the "source" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with source = NULL or an empty string is equivalent to calling unsetSource().
References LIBSEDML_OPERATION_SUCCESS.
unsetDimensionDescription()
int SedDataDescription::unsetDimensionDescription ()
Unsets the value of the "dimensionDescription" element of this SedDataDescription.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetFormat()
int SedDataDescription::unsetFormat ()
Unsets the value of the "format" attribute of this SedDataDescription.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetSource()
int SedDataDescription::unsetSource ()
Unsets the value of the "source" attribute of this SedDataDescription.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedDataDescription.h
SedDataDescription.cpp