LIBSEDML API: SedSimulation Class Reference
SedSimulation Class Reference
#include <SedSimulation.h>
Public Member Functions
virtual SedSimulation * clone () const
SedAlgorithm * createAlgorithm ()
SedAlgorithm * getAlgorithm ()
const SedAlgorithm * getAlgorithm () const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
virtual bool isSedAnalysis () const
virtual bool isSedOneStep () const
virtual bool isSedSteadyState () const
virtual bool isSedUniformTimeCourse () const
bool isSetAlgorithm () const
SedSimulation & operator= (const SedSimulation &rhs)
SedSimulation (const SedSimulation &orig)
SedSimulation (SedNamespaces *sedmlns)
SedSimulation (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setAlgorithm (const SedAlgorithm *algorithm)
int unsetAlgorithm ()
virtual ~SedSimulation ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedSimulation class.
Constructor & Destructor Documentation
SedSimulation() [1/3]
SedSimulation::SedSimulation (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedSimulation using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedSimulation.
version an unsigned int, the SED-ML Version to assign to this SedSimulation.
Referenced by clone().
SedSimulation() [2/3]
SedSimulation::SedSimulation (SedNamespaces * sedmlns)
Creates a new SedSimulation using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedSimulation() [3/3]
SedSimulation::SedSimulation (const SedSimulation & orig)
Copy constructor for SedSimulation.
Parameters
orig the SedSimulation instance to copy.
References clone().
~SedSimulation()
SedSimulation::~SedSimulation () virtual
Destructor for SedSimulation.
Member Function Documentation
clone()
SedSimulation * SedSimulation::clone () const virtual
Creates and returns a deep copy of this SedSimulation object.
Returns
a (deep) copy of this SedSimulation object.
Implements SedBase.
Reimplemented in SedUniformTimeCourse, SedSteadyState, SedOneStep, and SedAnalysis.
References SedSimulation().
Referenced by operator=(), and SedSimulation().
createAlgorithm()
SedAlgorithm * SedSimulation::createAlgorithm ()
Creates a new SedAlgorithm object, adds it to this SedSimulation object and returns the SedAlgorithm object created.
Returns
a new SedAlgorithm object instance.
getAlgorithm() [1/2]
SedAlgorithm * SedSimulation::getAlgorithm ()
Returns the value of the "algorithm" element of this SedSimulation.
Returns
the value of the "algorithm" element of this SedSimulation as a SedAlgorithm*.
getAlgorithm() [2/2]
const SedAlgorithm * SedSimulation::getAlgorithm () const
Returns the value of the "algorithm" element of this SedSimulation.
Returns
the value of the "algorithm" element of this SedSimulation as a SedAlgorithm*.
getAllElements()
List * SedSimulation::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_POINTER.
getElementBySId()
SedBase * SedSimulation::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedSimulation::getElementName () const virtual
Returns the XML element name of this SedSimulation object.
For SedSimulation, the XML element name is always "simulation".
Returns
the name of this element, i.e. "simulation".
Implements SedBase.
Reimplemented in SedUniformTimeCourse, SedSteadyState, SedOneStep, and SedAnalysis.
getTypeCode()
int SedSimulation::getTypeCode () const virtual
Returns the libSEDML type code for this SedSimulation object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SIMULATION, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
Reimplemented in SedUniformTimeCourse, SedSteadyState, SedOneStep, and SedAnalysis.
References SEDML_SIMULATION.
hasRequiredAttributes()
bool SedSimulation::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedSimulation object have been set.
Returns
true to indicate that all the required attributes of this SedSimulation have been set, otherwise false is returned.
Note
The required attributes for the SedSimulation object are:
"id"
Reimplemented in SedUniformTimeCourse, SedSteadyState, SedOneStep, and SedAnalysis.
References SedBase::isSetId().
Referenced by SedDocument::addSimulation(), SedListOfSimulations::addSimulation(), SedAnalysis::hasRequiredAttributes(), SedOneStep::hasRequiredAttributes(), SedSteadyState::hasRequiredAttributes(), and SedUniformTimeCourse::hasRequiredAttributes().
hasRequiredElements()
bool SedSimulation::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedSimulation object have been set.
Returns
true to indicate that all the required elements of this SedSimulation have been set, otherwise false is returned.
Note
The required elements for the SedSimulation object are:
"algorithm"
References isSetAlgorithm().
Referenced by SedDocument::addSimulation(), and SedListOfSimulations::addSimulation().
isSedAnalysis()
bool SedSimulation::isSedAnalysis () const virtual
Predicate returning true if this abstract "SedSimulation" is of type SedAnalysis
Returns
true if this abstract "SedSimulation" is of type SedAnalysis, false otherwise
isSedOneStep()
bool SedSimulation::isSedOneStep () const virtual
Predicate returning true if this abstract "SedSimulation" is of type SedOneStep
Returns
true if this abstract "SedSimulation" is of type SedOneStep, false otherwise
isSedSteadyState()
bool SedSimulation::isSedSteadyState () const virtual
Predicate returning true if this abstract "SedSimulation" is of type SedSteadyState
Returns
true if this abstract "SedSimulation" is of type SedSteadyState, false otherwise
isSedUniformTimeCourse()
bool SedSimulation::isSedUniformTimeCourse () const virtual
Predicate returning true if this abstract "SedSimulation" is of type SedUniformTimeCourse
Returns
true if this abstract "SedSimulation" is of type SedUniformTimeCourse, false otherwise
isSetAlgorithm()
bool SedSimulation::isSetAlgorithm () const
Predicate returning true if this SedSimulation's "algorithm" element is set.
Returns
true if this SedSimulation's "algorithm" element has been set, otherwise false is returned.
Referenced by hasRequiredElements().
operator=()
SedSimulation & SedSimulation::operator= (const SedSimulation & rhs)
Assignment operator for SedSimulation.
Parameters
rhs the SedSimulation object whose values are to be used as the basis of the assignment.
References clone(), and SedBase::operator=().
Referenced by SedAnalysis::operator=(), SedOneStep::operator=(), SedSteadyState::operator=(), and SedUniformTimeCourse::operator=().
setAlgorithm()
int SedSimulation::setAlgorithm (const SedAlgorithm * algorithm)
Sets the value of the "algorithm" element of this SedSimulation.
Parameters
algorithm SedAlgorithm* value of the "algorithm" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedAlgorithm::clone(), and LIBSEDML_OPERATION_SUCCESS.
unsetAlgorithm()
int SedSimulation::unsetAlgorithm ()
Unsets the value of the "algorithm" element of this SedSimulation.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedSimulation.h
SedSimulation.cpp