LIBSEDML API: SedListOfExperimentReferences Class Reference
SedListOfExperimentReferences Class Reference
#include <SedListOfExperimentReferences.h>
Public Member Functions
int addExperimentReference (const SedExperimentReference *ser)
virtual SedListOfExperimentReferences * clone () const
SedExperimentReference * createExperimentReference ()
virtual SedExperimentReference * get (const std::string &sid)
virtual const SedExperimentReference * get (const std::string &sid) const
virtual SedExperimentReference * get (unsigned int n)
virtual const SedExperimentReference * get (unsigned int n) const
SedExperimentReference * getByExperimentId (const std::string &sid)
const SedExperimentReference * getByExperimentId (const std::string &sid) const
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
unsigned int getNumExperimentReferences () const
virtual int getTypeCode () const
SedListOfExperimentReferences & operator= (const SedListOfExperimentReferences &rhs)
virtual SedExperimentReference * remove (const std::string &sid)
virtual SedExperimentReference * remove (unsigned int n)
SedListOfExperimentReferences (const SedListOfExperimentReferences &orig)
SedListOfExperimentReferences (SedNamespaces *sedmlns)
SedListOfExperimentReferences (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedListOfExperimentReferences ()
Public Member Functions inherited from SedListOf
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedListOfExperimentReferences class.
Constructor & Destructor Documentation
SedListOfExperimentReferences() [1/3]
SedListOfExperimentReferences::SedListOfExperimentReferences (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOfExperimentReferences using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedListOfExperimentReferences.
version an unsigned int, the SED-ML Version to assign to this SedListOfExperimentReferences.
Referenced by clone().
SedListOfExperimentReferences() [2/3]
SedListOfExperimentReferences::SedListOfExperimentReferences (SedNamespaces * sedmlns)
Creates a new SedListOfExperimentReferences using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedListOfExperimentReferences() [3/3]
SedListOfExperimentReferences::SedListOfExperimentReferences (const SedListOfExperimentReferences & orig)
Copy constructor for SedListOfExperimentReferences.
Parameters
orig the SedListOfExperimentReferences instance to copy.
~SedListOfExperimentReferences()
SedListOfExperimentReferences::~SedListOfExperimentReferences () virtual
Destructor for SedListOfExperimentReferences.
Member Function Documentation
addExperimentReference()
int SedListOfExperimentReferences::addExperimentReference (const SedExperimentReference * ser)
Adds a copy of the given SedExperimentReference to this SedListOfExperimentReferences.
Parameters
ser the SedExperimentReference object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createExperimentReference()
get(const std::string& sid)
get(unsigned int n)
getNumExperimentReferences()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::append(), SedBase::getLevel(), SedBase::getVersion(), SedExperimentReference::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedListOfExperimentReferences * SedListOfExperimentReferences::clone () const virtual
Creates and returns a deep copy of this SedListOfExperimentReferences object.
Returns
a (deep) copy of this SedListOfExperimentReferences object.
Reimplemented from SedListOf.
References SedListOfExperimentReferences().
createExperimentReference()
SedExperimentReference * SedListOfExperimentReferences::createExperimentReference ()
Creates a new SedExperimentReference object, adds it to this SedListOfExperimentReferences object and returns the SedExperimentReference object created.
Returns
a new SedExperimentReference object instance.
See also
addExperimentReference(const SedExperimentReference* object)
get(const std::string& sid)
get(unsigned int n)
getNumExperimentReferences()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
get() [1/4]
SedExperimentReference * SedListOfExperimentReferences::get (const std::string & sid) virtual
Get a SedExperimentReference from the SedListOfExperimentReferences based on its identifier.
Parameters
sid a string representing the identifier of the SedExperimentReference to retrieve.
Returns
the SedExperimentReference in this SedListOfExperimentReferences with the given sid or NULL if no such SedExperimentReference exists.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
get(unsigned int n)
getNumExperimentReferences()
remove(const std::string& sid)
remove(unsigned int n)
References get().
get() [2/4]
const SedExperimentReference * SedListOfExperimentReferences::get (const std::string & sid) const virtual
Get a SedExperimentReference from the SedListOfExperimentReferences based on its identifier.
Parameters
sid a string representing the identifier of the SedExperimentReference to retrieve.
Returns
the SedExperimentReference in this SedListOfExperimentReferences with the given sid or NULL if no such SedExperimentReference exists.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
get(unsigned int n)
getNumExperimentReferences()
remove(const std::string& sid)
remove(unsigned int n)
get() [3/4]
SedExperimentReference * SedListOfExperimentReferences::get (unsigned int n) virtual
Get a SedExperimentReference from the SedListOfExperimentReferences.
Parameters
n an unsigned int representing the index of the SedExperimentReference to retrieve.
Returns
the nth SedExperimentReference in this SedListOfExperimentReferences or NULL if no such object exists.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
get(const std::string& sid)
getNumExperimentReferences()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
Referenced by get().
get() [4/4]
const SedExperimentReference * SedListOfExperimentReferences::get (unsigned int n) const virtual
Get a SedExperimentReference from the SedListOfExperimentReferences.
Parameters
n an unsigned int representing the index of the SedExperimentReference to retrieve.
Returns
the nth SedExperimentReference in this SedListOfExperimentReferences or NULL if no such object exists.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
get(const std::string& sid)
getNumExperimentReferences()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
getByExperimentId() [1/2]
SedExperimentReference * SedListOfExperimentReferences::getByExperimentId (const std::string & sid)
Get a SedExperimentReference from the SedListOfExperimentReferences based on the ExperimentId to which it refers.
Parameters
sid a string representing the "experimentId" attribute of the SedExperimentReference object to retrieve.
Returns
the first SedExperimentReference in this SedListOfExperimentReferences based on the given experimentId attribute or NULL if no such SedExperimentReference exists.
References getByExperimentId().
getByExperimentId() [2/2]
const SedExperimentReference * SedListOfExperimentReferences::getByExperimentId (const std::string & sid) const
Get a SedExperimentReference from the SedListOfExperimentReferences based on the ExperimentId to which it refers.
Parameters
sid a string representing the "experimentId" attribute of the SedExperimentReference object to retrieve.
Returns
the first SedExperimentReference in this SedListOfExperimentReferences based on the given experimentId attribute or NULL if no such SedExperimentReference exists.
Referenced by getByExperimentId().
getElementName()
const std::string & SedListOfExperimentReferences::getElementName () const virtual
Returns the XML element name of this SedListOfExperimentReferences object.
For SedListOfExperimentReferences, the XML element name is always "listOfExperimentReferences".
Returns
the name of this element, i.e. "listOfExperimentReferences".
Reimplemented from SedListOf.
getItemTypeCode()
int SedListOfExperimentReferences::getItemTypeCode () const virtual
Returns the libSEDML type code for the SED-ML objects contained in this SedListOfExperimentReferences object.
Returns
the SED-ML typecode for the objects contained in this SedListOfExperimentReferences: @sedmlconstant{SEDML_EXPERIMENT_REFERENCE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedListOf.
References SEDML_EXPERIMENT_REFERENCE.
getNumExperimentReferences()
unsigned int SedListOfExperimentReferences::getNumExperimentReferences () const
Get the number of SedExperimentReference objects in this SedListOfExperimentReferences.
Returns
the number of SedExperimentReference objects in this SedListOfExperimentReferences.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
get(const std::string& sid)
get(unsigned int n)
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::size().
getTypeCode()
int SedListOfExperimentReferences::getTypeCode () const virtual
Returns the libSEDML type code for this SedListOfExperimentReferences object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Reimplemented from SedListOf.
References SEDML_LIST_OF.
operator=()
SedListOfExperimentReferences & SedListOfExperimentReferences::operator= (const SedListOfExperimentReferences & rhs)
Assignment operator for SedListOfExperimentReferences.
Parameters
rhs the SedListOfExperimentReferences object whose values are to be used as the basis of the assignment.
References SedListOf::operator=().
remove() [1/2]
SedExperimentReference * SedListOfExperimentReferences::remove (const std::string & sid) virtual
Removes the SedExperimentReference from this SedListOfExperimentReferences based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedExperimentReference to remove.
Returns
the SedExperimentReference in this SedListOfExperimentReferences based on the identifier or NULL if no such SedExperimentReference exists.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
get(const std::string& sid)
get(unsigned int n)
getNumExperimentReferences()
remove(unsigned int n)
remove() [2/2]
SedExperimentReference * SedListOfExperimentReferences::remove (unsigned int n) virtual
Removes the nth SedExperimentReference from this SedListOfExperimentReferences and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedExperimentReference to remove.
Returns
a pointer to the nth SedExperimentReference in this SedListOfExperimentReferences.
See also
addExperimentReference(const SedExperimentReference* object)
createExperimentReference()
get(const std::string& sid)
get(unsigned int n)
getNumExperimentReferences()
remove(const std::string& sid)
Reimplemented from SedListOf.
References SedListOf::remove().
The documentation for this class was generated from the following files:
SedListOfExperimentReferences.h
SedListOfExperimentReferences.cpp