LIBSEDML API: SedAbstractCurve Class Reference
SedAbstractCurve Class Reference
#include <SedAbstractCurve.h>
Public Member Functions
virtual SedAbstractCurve * clone () const
virtual const std::string & getElementName () const
bool getLogX () const
int getOrder () const
const std::string & getStyle () const
virtual int getTypeCode () const
const std::string & getXDataReference () const
const std::string & getYAxis () const
virtual bool hasRequiredAttributes () const
virtual bool isSedCurve () const
virtual bool isSedShadedArea () const
bool isSetLogX () const
bool isSetOrder () const
bool isSetStyle () const
bool isSetXDataReference () const
bool isSetYAxis () const
SedAbstractCurve & operator= (const SedAbstractCurve &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedAbstractCurve (const SedAbstractCurve &orig)
SedAbstractCurve (SedNamespaces *sedmlns)
SedAbstractCurve (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setLogX (bool logX)
int setOrder (int order)
int setStyle (const std::string &style)
int setXDataReference (const std::string &xDataReference)
int setYAxis (const std::string &yAxis)
int unsetLogX ()
int unsetOrder ()
int unsetStyle ()
int unsetXDataReference ()
int unsetYAxis ()
virtual ~SedAbstractCurve ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAbstractCurve class.
Constructor & Destructor Documentation
SedAbstractCurve() [1/3]
SedAbstractCurve::SedAbstractCurve (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAbstractCurve using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAbstractCurve.
version an unsigned int, the SED-ML Version to assign to this SedAbstractCurve.
Referenced by clone().
SedAbstractCurve() [2/3]
SedAbstractCurve::SedAbstractCurve (SedNamespaces * sedmlns)
Creates a new SedAbstractCurve using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedAbstractCurve() [3/3]
SedAbstractCurve::SedAbstractCurve (const SedAbstractCurve & orig)
Copy constructor for SedAbstractCurve.
Parameters
orig the SedAbstractCurve instance to copy.
~SedAbstractCurve()
SedAbstractCurve::~SedAbstractCurve () virtual
Destructor for SedAbstractCurve.
Member Function Documentation
clone()
SedAbstractCurve * SedAbstractCurve::clone () const virtual
Creates and returns a deep copy of this SedAbstractCurve object.
Returns
a (deep) copy of this SedAbstractCurve object.
Implements SedBase.
Reimplemented in SedShadedArea, and SedCurve.
References SedAbstractCurve().
getElementName()
const std::string & SedAbstractCurve::getElementName () const virtual
Returns the XML element name of this SedAbstractCurve object.
For SedAbstractCurve, the XML element name is always "abstractCurve".
Returns
the name of this element, i.e. "abstractCurve".
Implements SedBase.
Reimplemented in SedShadedArea, and SedCurve.
getLogX()
bool SedAbstractCurve::getLogX () const
Returns the value of the "logX" attribute of this SedAbstractCurve.
Returns
the value of the "logX" attribute of this SedAbstractCurve as a boolean.
References SedBase::getParentSedObject(), SedAxis::getType(), SedBase::getTypeCode(), SedBase::getVersion(), SedPlot::getXAxis(), isSetLogX(), SedAxis::isSetType(), SEDML_AXISTYPE_LOG10, SEDML_OUTPUT_PLOT2D, and SEDML_OUTPUT_PLOT3D.
getOrder()
int SedAbstractCurve::getOrder () const
Returns the value of the "order" attribute of this SedAbstractCurve.
Returns
the value of the "order" attribute of this SedAbstractCurve as a integer.
Referenced by AbstractCurvesOrderComparator::operator()().
getStyle()
const std::string & SedAbstractCurve::getStyle () const
Returns the value of the "style" attribute of this SedAbstractCurve.
Returns
the value of the "style" attribute of this SedAbstractCurve as a string.
getTypeCode()
int SedAbstractCurve::getTypeCode () const virtual
Returns the libSEDML type code for this SedAbstractCurve object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_ABSTRACTCURVE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
Reimplemented in SedShadedArea, and SedCurve.
References SEDML_ABSTRACTCURVE.
getXDataReference()
const std::string & SedAbstractCurve::getXDataReference () const
Returns the value of the "xDataReference" attribute of this SedAbstractCurve.
Returns
the value of the "xDataReference" attribute of this SedAbstractCurve as a string.
getYAxis()
const std::string & SedAbstractCurve::getYAxis () const
Returns the value of the "yAxis" attribute of this SedAbstractCurve.
Returns
the value of the "yAxis" attribute of this SedAbstractCurve as a string.
Referenced by SedCurve::getLogY().
hasRequiredAttributes()
bool SedAbstractCurve::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAbstractCurve object have been set.
Returns
true to indicate that all the required attributes of this SedAbstractCurve have been set, otherwise false is returned.
Reimplemented in SedShadedArea, and SedCurve.
Referenced by SedListOfCurves::addCurve(), SedPlot2D::addCurve(), SedCurve::hasRequiredAttributes(), and SedShadedArea::hasRequiredAttributes().
isSedCurve()
bool SedAbstractCurve::isSedCurve () const virtual
Predicate returning true if this abstract "SedAbstractCurve" is of type SedCurve
Returns
true if this abstract "SedAbstractCurve" is of type SedCurve, false otherwise
isSedShadedArea()
bool SedAbstractCurve::isSedShadedArea () const virtual
Predicate returning true if this abstract "SedAbstractCurve" is of type SedShadedArea
Returns
true if this abstract "SedAbstractCurve" is of type SedShadedArea, false otherwise
isSetLogX()
bool SedAbstractCurve::isSetLogX () const
Predicate returning true if this SedAbstractCurve's "logX" attribute is set.
Returns
true if this SedAbstractCurve's "logX" attribute has been set, otherwise false is returned.
Referenced by getLogX(), and unsetLogX().
isSetOrder()
bool SedAbstractCurve::isSetOrder () const
Predicate returning true if this SedAbstractCurve's "order" attribute is set.
Returns
true if this SedAbstractCurve's "order" attribute has been set, otherwise false is returned.
Referenced by AbstractCurvesOrderComparator::operator()().
isSetStyle()
bool SedAbstractCurve::isSetStyle () const
Predicate returning true if this SedAbstractCurve's "style" attribute is set.
Returns
true if this SedAbstractCurve's "style" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetXDataReference()
bool SedAbstractCurve::isSetXDataReference () const
Predicate returning true if this SedAbstractCurve's "xDataReference" attribute is set.
Returns
true if this SedAbstractCurve's "xDataReference" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetYAxis()
bool SedAbstractCurve::isSetYAxis () const
Predicate returning true if this SedAbstractCurve's "yAxis" attribute is set.
Returns
true if this SedAbstractCurve's "yAxis" attribute has been set, otherwise false is returned.
operator=()
SedAbstractCurve & SedAbstractCurve::operator= (const SedAbstractCurve & rhs)
Assignment operator for SedAbstractCurve.
Parameters
rhs the SedAbstractCurve object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
Referenced by SedCurve::operator=(), and SedShadedArea::operator=().
renameSIdRefs()
void SedAbstractCurve::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
Reimplemented in SedShadedArea, and SedCurve.
References isSetStyle(), isSetXDataReference(), setStyle(), and setXDataReference().
setLogX()
int SedAbstractCurve::setLogX (bool logX)
Sets the value of the "logX" attribute of this SedAbstractCurve.
Parameters
logX bool value of the "logX" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setOrder()
int SedAbstractCurve::setOrder (int order)
Sets the value of the "order" attribute of this SedAbstractCurve.
Parameters
order int value of the "order" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setStyle()
int SedAbstractCurve::setStyle (const std::string & style)
Sets the value of the "style" attribute of this SedAbstractCurve.
Parameters
style std::string& value of the "style" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setXDataReference()
int SedAbstractCurve::setXDataReference (const std::string & xDataReference)
Sets the value of the "xDataReference" attribute of this SedAbstractCurve.
Parameters
xDataReference std::string& value of the "xDataReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setYAxis()
int SedAbstractCurve::setYAxis (const std::string & yAxis)
Sets the value of the "yAxis" attribute of this SedAbstractCurve.
Parameters
yAxis std::string& value of the "yAxis" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with yAxis = NULL or an empty string is equivalent to calling unsetYAxis().
References LIBSEDML_OPERATION_SUCCESS.
unsetLogX()
int SedAbstractCurve::unsetLogX ()
Unsets the value of the "logX" attribute of this SedAbstractCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetLogX(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetOrder()
int SedAbstractCurve::unsetOrder ()
Unsets the value of the "order" attribute of this SedAbstractCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetStyle()
int SedAbstractCurve::unsetStyle ()
Unsets the value of the "style" attribute of this SedAbstractCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetXDataReference()
int SedAbstractCurve::unsetXDataReference ()
Unsets the value of the "xDataReference" attribute of this SedAbstractCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetYAxis()
int SedAbstractCurve::unsetYAxis ()
Unsets the value of the "yAxis" attribute of this SedAbstractCurve.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedAbstractCurve.h
SedAbstractCurve.cpp