LIBSEDML API: SedSlice Class Reference
SedSlice Class Reference
#include <SedSlice.h>
Public Member Functions
virtual SedSlice * clone () const
virtual const std::string & getElementName () const
int getEndIndex () const
const std::string & getIndex () const
const std::string & getReference () const
int getStartIndex () const
virtual int getTypeCode () const
const std::string & getValue () const
virtual bool hasRequiredAttributes () const
bool isSetEndIndex () const
bool isSetIndex () const
bool isSetReference () const
bool isSetStartIndex () const
bool isSetValue () const
SedSlice & operator= (const SedSlice &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedSlice (const SedSlice &orig)
SedSlice (SedNamespaces *sedmlns)
SedSlice (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setEndIndex (int endIndex)
int setIndex (const std::string &index)
int setReference (const std::string &reference)
int setStartIndex (int startIndex)
int setValue (const std::string &value)
int unsetEndIndex ()
int unsetIndex ()
int unsetReference ()
int unsetStartIndex ()
int unsetValue ()
virtual ~SedSlice ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedSlice class.
Constructor & Destructor Documentation
SedSlice() [1/3]
SedSlice::SedSlice (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedSlice using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedSlice.
version an unsigned int, the SED-ML Version to assign to this SedSlice.
Referenced by clone().
SedSlice() [2/3]
SedSlice::SedSlice (SedNamespaces * sedmlns)
Creates a new SedSlice using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedSlice() [3/3]
SedSlice::SedSlice (const SedSlice & orig)
Copy constructor for SedSlice.
Parameters
orig the SedSlice instance to copy.
~SedSlice()
SedSlice::~SedSlice () virtual
Destructor for SedSlice.
Member Function Documentation
clone()
SedSlice * SedSlice::clone () const virtual
Creates and returns a deep copy of this SedSlice object.
Returns
a (deep) copy of this SedSlice object.
Implements SedBase.
References SedSlice().
getElementName()
const std::string & SedSlice::getElementName () const virtual
Returns the XML element name of this SedSlice object.
For SedSlice, the XML element name is always "slice".
Returns
the name of this element, i.e. "slice".
Implements SedBase.
getEndIndex()
int SedSlice::getEndIndex () const
Returns the value of the "endIndex" attribute of this SedSlice.
Returns
the value of the "endIndex" attribute of this SedSlice as a integer.
getIndex()
const std::string & SedSlice::getIndex () const
Returns the value of the "index" attribute of this SedSlice.
Returns
the value of the "index" attribute of this SedSlice as a string.
getReference()
const std::string & SedSlice::getReference () const
Returns the value of the "reference" attribute of this SedSlice.
Returns
the value of the "reference" attribute of this SedSlice as a string.
getStartIndex()
int SedSlice::getStartIndex () const
Returns the value of the "startIndex" attribute of this SedSlice.
Returns
the value of the "startIndex" attribute of this SedSlice as a integer.
getTypeCode()
int SedSlice::getTypeCode () const virtual
Returns the libSEDML type code for this SedSlice object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_DATA_SLICE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_DATA_SLICE.
getValue()
const std::string & SedSlice::getValue () const
Returns the value of the "value" attribute of this SedSlice.
Returns
the value of the "value" attribute of this SedSlice as a string.
hasRequiredAttributes()
bool SedSlice::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedSlice object have been set.
Returns
true to indicate that all the required attributes of this SedSlice have been set, otherwise false is returned.
Note
The required attributes for the SedSlice object are:
"reference"
"value"
References isSetReference(), and isSetValue().
Referenced by SedDataSource::addSlice(), and SedListOfSlices::addSlice().
isSetEndIndex()
bool SedSlice::isSetEndIndex () const
Predicate returning true if this SedSlice's "endIndex" attribute is set.
Returns
true if this SedSlice's "endIndex" attribute has been set, otherwise false is returned.
isSetIndex()
bool SedSlice::isSetIndex () const
Predicate returning true if this SedSlice's "index" attribute is set.
Returns
true if this SedSlice's "index" attribute has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetReference()
bool SedSlice::isSetReference () const
Predicate returning true if this SedSlice's "reference" attribute is set.
Returns
true if this SedSlice's "reference" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
isSetStartIndex()
bool SedSlice::isSetStartIndex () const
Predicate returning true if this SedSlice's "startIndex" attribute is set.
Returns
true if this SedSlice's "startIndex" attribute has been set, otherwise false is returned.
isSetValue()
bool SedSlice::isSetValue () const
Predicate returning true if this SedSlice's "value" attribute is set.
Returns
true if this SedSlice's "value" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedSlice & SedSlice::operator= (const SedSlice & rhs)
Assignment operator for SedSlice.
Parameters
rhs the SedSlice object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
renameSIdRefs()
void SedSlice::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetIndex(), isSetReference(), setIndex(), and setReference().
setEndIndex()
int SedSlice::setEndIndex (int endIndex)
Sets the value of the "endIndex" attribute of this SedSlice.
Parameters
endIndex int value of the "endIndex" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setIndex()
int SedSlice::setIndex (const std::string & index)
Sets the value of the "index" attribute of this SedSlice.
Parameters
index std::string& value of the "index" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setReference()
int SedSlice::setReference (const std::string & reference)
Sets the value of the "reference" attribute of this SedSlice.
Parameters
reference std::string& value of the "reference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setStartIndex()
int SedSlice::setStartIndex (int startIndex)
Sets the value of the "startIndex" attribute of this SedSlice.
Parameters
startIndex int value of the "startIndex" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setValue()
int SedSlice::setValue (const std::string & value)
Sets the value of the "value" attribute of this SedSlice.
Parameters
value std::string& value of the "value" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with value = NULL or an empty string is equivalent to calling unsetValue().
References LIBSEDML_OPERATION_SUCCESS.
unsetEndIndex()
int SedSlice::unsetEndIndex ()
Unsets the value of the "endIndex" attribute of this SedSlice.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetIndex()
int SedSlice::unsetIndex ()
Unsets the value of the "index" attribute of this SedSlice.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetReference()
int SedSlice::unsetReference ()
Unsets the value of the "reference" attribute of this SedSlice.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetStartIndex()
int SedSlice::unsetStartIndex ()
Unsets the value of the "startIndex" attribute of this SedSlice.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetValue()
int SedSlice::unsetValue ()
Unsets the value of the "value" attribute of this SedSlice.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedSlice.h
SedSlice.cpp