LIBSEDML API: SedUniformTimeCourse Class Reference
SedUniformTimeCourse Class Reference
#include <SedUniformTimeCourse.h>
Public Member Functions
virtual SedUniformTimeCourse * clone () const
virtual const std::string & getElementName () const
double getInitialTime () const
int getNumberOfPoints () const
int getNumberOfSteps () const
double getOutputEndTime () const
double getOutputStartTime () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetInitialTime () const
bool isSetNumberOfPoints () const
bool isSetNumberOfSteps () const
bool isSetOutputEndTime () const
bool isSetOutputStartTime () const
SedUniformTimeCourse & operator= (const SedUniformTimeCourse &rhs)
SedUniformTimeCourse (const SedUniformTimeCourse &orig)
SedUniformTimeCourse (SedNamespaces *sedmlns)
SedUniformTimeCourse (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setInitialTime (double initialTime)
int setNumberOfPoints (int numberOfSteps)
int setNumberOfSteps (int numberOfSteps)
int setOutputEndTime (double outputEndTime)
int setOutputStartTime (double outputStartTime)
int unsetInitialTime ()
int unsetNumberOfPoints ()
int unsetNumberOfSteps ()
int unsetOutputEndTime ()
int unsetOutputStartTime ()
virtual ~SedUniformTimeCourse ()
Public Member Functions inherited from SedSimulation
SedAlgorithm * createAlgorithm ()
SedAlgorithm * getAlgorithm ()
const SedAlgorithm * getAlgorithm () const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual bool hasRequiredElements () const
virtual bool isSedAnalysis () const
virtual bool isSedOneStep () const
virtual bool isSedSteadyState () const
virtual bool isSedUniformTimeCourse () const
bool isSetAlgorithm () const
SedSimulation & operator= (const SedSimulation &rhs)
SedSimulation (const SedSimulation &orig)
SedSimulation (SedNamespaces *sedmlns)
SedSimulation (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setAlgorithm (const SedAlgorithm *algorithm)
int unsetAlgorithm ()
virtual ~SedSimulation ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedUniformTimeCourse class.
Constructor & Destructor Documentation
SedUniformTimeCourse() [1/3]
SedUniformTimeCourse::SedUniformTimeCourse (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedUniformTimeCourse using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedUniformTimeCourse.
version an unsigned int, the SED-ML Version to assign to this SedUniformTimeCourse.
Referenced by clone().
SedUniformTimeCourse() [2/3]
SedUniformTimeCourse::SedUniformTimeCourse (SedNamespaces * sedmlns)
Creates a new SedUniformTimeCourse using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
SedUniformTimeCourse() [3/3]
SedUniformTimeCourse::SedUniformTimeCourse (const SedUniformTimeCourse & orig)
Copy constructor for SedUniformTimeCourse.
Parameters
orig the SedUniformTimeCourse instance to copy.
~SedUniformTimeCourse()
SedUniformTimeCourse::~SedUniformTimeCourse () virtual
Destructor for SedUniformTimeCourse.
Member Function Documentation
clone()
SedUniformTimeCourse * SedUniformTimeCourse::clone () const virtual
Creates and returns a deep copy of this SedUniformTimeCourse object.
Returns
a (deep) copy of this SedUniformTimeCourse object.
Reimplemented from SedSimulation.
References SedUniformTimeCourse().
getElementName()
const std::string & SedUniformTimeCourse::getElementName () const virtual
Returns the XML element name of this SedUniformTimeCourse object.
For SedUniformTimeCourse, the XML element name is always "uniformTimeCourse".
Returns
the name of this element, i.e. "uniformTimeCourse".
Reimplemented from SedSimulation.
getInitialTime()
double SedUniformTimeCourse::getInitialTime () const
Returns the value of the "initialTime" attribute of this SedUniformTimeCourse.
Returns
the value of the "initialTime" attribute of this SedUniformTimeCourse as a double.
getNumberOfPoints()
int SedUniformTimeCourse::getNumberOfPoints () const
Returns the value of the "numberOfSteps" attribute of this SedUniformTimeCourse.
Returns
the value of the "numberOfSteps" attribute of this SedUniformTimeCourse as a integer.
getNumberOfSteps()
int SedUniformTimeCourse::getNumberOfSteps () const
Returns the value of the "numberOfSteps" attribute of this SedUniformTimeCourse.
Returns
the value of the "numberOfSteps" attribute of this SedUniformTimeCourse as a integer.
getOutputEndTime()
double SedUniformTimeCourse::getOutputEndTime () const
Returns the value of the "outputEndTime" attribute of this SedUniformTimeCourse.
Returns
the value of the "outputEndTime" attribute of this SedUniformTimeCourse as a double.
getOutputStartTime()
double SedUniformTimeCourse::getOutputStartTime () const
Returns the value of the "outputStartTime" attribute of this SedUniformTimeCourse.
Returns
the value of the "outputStartTime" attribute of this SedUniformTimeCourse as a double.
getTypeCode()
int SedUniformTimeCourse::getTypeCode () const virtual
Returns the libSEDML type code for this SedUniformTimeCourse object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SIMULATION_UNIFORMTIMECOURSE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedSimulation.
References SEDML_SIMULATION_UNIFORMTIMECOURSE.
hasRequiredAttributes()
bool SedUniformTimeCourse::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedUniformTimeCourse object have been set.
Returns
true to indicate that all the required attributes of this SedUniformTimeCourse have been set, otherwise false is returned.
Note
The required attributes for the SedUniformTimeCourse object are:
"initialTime"
"outputStartTime"
"outputEndTime"
Reimplemented from SedSimulation.
References SedSimulation::hasRequiredAttributes(), isSetInitialTime(), isSetOutputEndTime(), and isSetOutputStartTime().
isSetInitialTime()
bool SedUniformTimeCourse::isSetInitialTime () const
Predicate returning true if this SedUniformTimeCourse's "initialTime" attribute is set.
Returns
true if this SedUniformTimeCourse's "initialTime" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and unsetInitialTime().
isSetNumberOfPoints()
bool SedUniformTimeCourse::isSetNumberOfPoints () const
Predicate returning true if this SedUniformTimeCourse's "numberOfSteps" attribute is set.
Returns
true if this SedUniformTimeCourse's "numberOfSteps" attribute has been set, otherwise false is returned.
isSetNumberOfSteps()
bool SedUniformTimeCourse::isSetNumberOfSteps () const
Predicate returning true if this SedUniformTimeCourse's "numberOfSteps" attribute is set.
Returns
true if this SedUniformTimeCourse's "numberOfSteps" attribute has been set, otherwise false is returned.
isSetOutputEndTime()
bool SedUniformTimeCourse::isSetOutputEndTime () const
Predicate returning true if this SedUniformTimeCourse's "outputEndTime" attribute is set.
Returns
true if this SedUniformTimeCourse's "outputEndTime" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and unsetOutputEndTime().
isSetOutputStartTime()
bool SedUniformTimeCourse::isSetOutputStartTime () const
Predicate returning true if this SedUniformTimeCourse's "outputStartTime" attribute is set.
Returns
true if this SedUniformTimeCourse's "outputStartTime" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and unsetOutputStartTime().
operator=()
SedUniformTimeCourse & SedUniformTimeCourse::operator= (const SedUniformTimeCourse & rhs)
Assignment operator for SedUniformTimeCourse.
Parameters
rhs the SedUniformTimeCourse object whose values are to be used as the basis of the assignment.
References SedSimulation::operator=().
setInitialTime()
int SedUniformTimeCourse::setInitialTime (double initialTime)
Sets the value of the "initialTime" attribute of this SedUniformTimeCourse.
Parameters
initialTime double value of the "initialTime" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setNumberOfPoints()
int SedUniformTimeCourse::setNumberOfPoints (int numberOfSteps)
Sets the value of the "numberOfSteps" attribute of this SedUniformTimeCourse.
Parameters
numberOfSteps int value of the "numberOfSteps" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setNumberOfSteps()
int SedUniformTimeCourse::setNumberOfSteps (int numberOfSteps)
Sets the value of the "numberOfSteps" attribute of this SedUniformTimeCourse.
Parameters
numberOfSteps int value of the "numberOfSteps" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setOutputEndTime()
int SedUniformTimeCourse::setOutputEndTime (double outputEndTime)
Sets the value of the "outputEndTime" attribute of this SedUniformTimeCourse.
Parameters
outputEndTime double value of the "outputEndTime" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
setOutputStartTime()
int SedUniformTimeCourse::setOutputStartTime (double outputStartTime)
Sets the value of the "outputStartTime" attribute of this SedUniformTimeCourse.
Parameters
outputStartTime double value of the "outputStartTime" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetInitialTime()
int SedUniformTimeCourse::unsetInitialTime ()
Unsets the value of the "initialTime" attribute of this SedUniformTimeCourse.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetInitialTime(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetNumberOfPoints()
int SedUniformTimeCourse::unsetNumberOfPoints ()
Unsets the value of the "numberOfSteps" attribute of this SedUniformTimeCourse.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetNumberOfSteps()
int SedUniformTimeCourse::unsetNumberOfSteps ()
Unsets the value of the "numberOfSteps" attribute of this SedUniformTimeCourse.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
unsetOutputEndTime()
int SedUniformTimeCourse::unsetOutputEndTime ()
Unsets the value of the "outputEndTime" attribute of this SedUniformTimeCourse.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetOutputEndTime(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
unsetOutputStartTime()
int SedUniformTimeCourse::unsetOutputStartTime ()
Unsets the value of the "outputStartTime" attribute of this SedUniformTimeCourse.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetOutputStartTime(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedUniformTimeCourse.h
SedUniformTimeCourse.cpp