LIBSEDML API: local.cpp File Reference
ruby/local.cpp File Reference
Implementation of the local class.
#include <cstddef>
#include "sedml/SedBase.h"
Functions
int fixNegativeIndex (int i, SedListOf *l)
struct swig_type_info * GetDowncastSwigType (SedBase *sb)
Detailed Description
Implementation of the local class.
Author
DEVISER
Function Documentation
fixNegativeIndex()
int fixNegativeIndex (int i, SedListOf * l)
References SedListOf::size().
GetDowncastSwigType()
struct swig_type_info* GetDowncastSwigType (SedBase * sb)
Returns
the most specific Swig type for the given SedBase object.
References SedBase::getElementName(), SedBase::getTypeCode(), SEDML_ABSTRACTCURVE, SEDML_ADJUSTABLE_PARAMETER, SEDML_APPLIEDDIMENSION, SEDML_AXIS, SEDML_BOUNDS, SEDML_CHANGE, SEDML_CHANGE_ADDXML, SEDML_CHANGE_ATTRIBUTE, SEDML_CHANGE_CHANGEXML, SEDML_CHANGE_COMPUTECHANGE, SEDML_CHANGE_REMOVEXML, SEDML_DATA_DESCRIPTION, SEDML_DATA_RANGE, SEDML_DATA_SLICE, SEDML_DATA_SOURCE, SEDML_DATAGENERATOR, SEDML_DOCUMENT, SEDML_EXPERIMENT_REFERENCE, SEDML_FIGURE, SEDML_FILL, SEDML_FIT_EXPERIMENT, SEDML_FITMAPPING, SEDML_LEAST_SQUARE_OBJECTIVE, SEDML_LINE, SEDML_LIST_OF, SEDML_MARKER, SEDML_MODEL, SEDML_OBJECTIVE, SEDML_OUTPUT, SEDML_OUTPUT_CURVE, SEDML_OUTPUT_DATASET, SEDML_OUTPUT_PLOT, SEDML_OUTPUT_PLOT2D, SEDML_OUTPUT_PLOT3D, SEDML_OUTPUT_REPORT, SEDML_OUTPUT_SURFACE, SEDML_PARAMETER, SEDML_PARAMETERESTIMATIONRESULTPLOT, SEDML_RANGE, SEDML_RANGE_FUNCTIONALRANGE, SEDML_RANGE_UNIFORMRANGE, SEDML_RANGE_VECTORRANGE, SEDML_SEDML_ABSTRACTTASK, SEDML_SHADEDAREA, SEDML_SIMULATION, SEDML_SIMULATION_ALGORITHM, SEDML_SIMULATION_ALGORITHM_PARAMETER, SEDML_SIMULATION_ANALYSIS, SEDML_SIMULATION_ONESTEP, SEDML_SIMULATION_STEADYSTATE, SEDML_SIMULATION_UNIFORMTIMECOURSE, SEDML_STYLE, SEDML_SUBPLOT, SEDML_TASK, SEDML_TASK_PARAMETER_ESTIMATION, SEDML_TASK_REPEATEDTASK, SEDML_TASK_SETVALUE, SEDML_TASK_SUBTASK, and SEDML_VARIABLE.