LIBSEDML API: SedComputeChange Class Reference
SedComputeChange Class Reference
#include <SedComputeChange.h>
Public Member Functions
int addParameter (const SedParameter *sp)
int addVariable (const SedVariable *sv)
virtual SedComputeChange * clone () const
SedParameter * createParameter ()
SedVariable * createVariable ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfParameters * getListOfParameters ()
const SedListOfParameters * getListOfParameters () const
SedListOfVariables * getListOfVariables ()
const SedListOfVariables * getListOfVariables () const
ASTNode * getMath ()
const ASTNode * getMath () const
unsigned int getNumParameters () const
unsigned int getNumVariables () const
SedParameter * getParameter (const std::string &sid)
const SedParameter * getParameter (const std::string &sid) const
SedParameter * getParameter (unsigned int n)
const SedParameter * getParameter (unsigned int n) const
const std::string & getSymbol () const
virtual int getTypeCode () const
SedVariable * getVariable (const std::string &sid)
const SedVariable * getVariable (const std::string &sid) const
SedVariable * getVariable (unsigned int n)
const SedVariable * getVariable (unsigned int n) const
SedVariable * getVariableByModelReference (const std::string &sid)
const SedVariable * getVariableByModelReference (const std::string &sid) const
SedVariable * getVariableByTaskReference (const std::string &sid)
const SedVariable * getVariableByTaskReference (const std::string &sid) const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
bool isSetMath () const
bool isSetSymbol () const
SedComputeChange & operator= (const SedComputeChange &rhs)
SedParameter * removeParameter (const std::string &sid)
SedParameter * removeParameter (unsigned int n)
SedVariable * removeVariable (const std::string &sid)
SedVariable * removeVariable (unsigned int n)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedComputeChange (const SedComputeChange &orig)
SedComputeChange (SedNamespaces *sedmlns)
SedComputeChange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setMath (const ASTNode *math)
int setSymbol (const std::string &symbol)
int unsetMath ()
int unsetSymbol ()
virtual ~SedComputeChange ()
Public Member Functions inherited from SedChange
const std::string & getTarget () const
virtual bool isSedAddXML () const
virtual bool isSedChangeAttribute () const
virtual bool isSedChangeXML () const
virtual bool isSedComputeChange () const
virtual bool isSedRemoveXML () const
bool isSetTarget () const
SedChange & operator= (const SedChange &rhs)
SedChange (const SedChange &orig)
SedChange (SedNamespaces *sedmlns)
SedChange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setTarget (const std::string &target)
int unsetTarget ()
virtual ~SedChange ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Static Protected Member Functions inherited from SedChange
static std::string _trim (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedComputeChange class.
Constructor & Destructor Documentation
SedComputeChange() [1/3]
SedComputeChange::SedComputeChange (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedComputeChange using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedComputeChange.
version an unsigned int, the SED-ML Version to assign to this SedComputeChange.
Referenced by clone().
SedComputeChange() [2/3]
SedComputeChange::SedComputeChange (SedNamespaces * sedmlns)
Creates a new SedComputeChange using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedComputeChange() [3/3]
SedComputeChange::SedComputeChange (const SedComputeChange & orig)
Copy constructor for SedComputeChange.
Parameters
orig the SedComputeChange instance to copy.
~SedComputeChange()
SedComputeChange::~SedComputeChange () virtual
Destructor for SedComputeChange.
Member Function Documentation
addParameter()
int SedComputeChange::addParameter (const SedParameter * sp)
Adds a copy of the given SedParameter to this SedComputeChange.
Parameters
sp the SedParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedParameter::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
addVariable()
int SedComputeChange::addVariable (const SedVariable * sv)
Adds a copy of the given SedVariable to this SedComputeChange.
Parameters
sv the SedVariable object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedVariable::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedComputeChange * SedComputeChange::clone () const virtual
Creates and returns a deep copy of this SedComputeChange object.
Returns
a (deep) copy of this SedComputeChange object.
Reimplemented from SedChange.
References SedComputeChange().
createParameter()
SedParameter * SedComputeChange::createParameter ()
Creates a new SedParameter object, adds it to this SedComputeChange object and returns the SedParameter object created.
Returns
a new SedParameter object instance.
See also
addParameter(const SedParameter* object)
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
createVariable()
SedVariable * SedComputeChange::createVariable ()
Creates a new SedVariable object, adds it to this SedComputeChange object and returns the SedVariable object created.
Returns
a new SedVariable object instance.
See also
addVariable(const SedVariable* object)
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getAllElements()
List * SedComputeChange::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getElementBySId()
SedBase * SedComputeChange::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedComputeChange::getElementName () const virtual
Returns the XML element name of this SedComputeChange object.
For SedComputeChange, the XML element name is always "computeChange".
Returns
the name of this element, i.e. "computeChange".
Reimplemented from SedChange.
getListOfParameters() [1/2]
SedListOfParameters * SedComputeChange::getListOfParameters ()
Returns the SedListOfParameters from this SedComputeChange.
Returns
the SedListOfParameters from this SedComputeChange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getListOfParameters() [2/2]
const SedListOfParameters * SedComputeChange::getListOfParameters () const
Returns the SedListOfParameters from this SedComputeChange.
Returns
the SedListOfParameters from this SedComputeChange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getListOfVariables() [1/2]
SedListOfVariables * SedComputeChange::getListOfVariables ()
Returns the SedListOfVariables from this SedComputeChange.
Returns
the SedListOfVariables from this SedComputeChange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getListOfVariables() [2/2]
const SedListOfVariables * SedComputeChange::getListOfVariables () const
Returns the SedListOfVariables from this SedComputeChange.
Returns
the SedListOfVariables from this SedComputeChange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getMath() [1/2]
ASTNode * SedComputeChange::getMath ()
Returns the value of the "math" element of this SedComputeChange.
Returns
the value of the "math" element of this SedComputeChange as a LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode*.
getMath() [2/2]
const ASTNode * SedComputeChange::getMath () const
Returns the value of the "math" element of this SedComputeChange.
Returns
the value of the "math" element of this SedComputeChange as a LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode*.
getNumParameters()
unsigned int SedComputeChange::getNumParameters () const
Get the number of SedParameter objects in this SedComputeChange.
Returns
the number of SedParameter objects in this SedComputeChange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getNumVariables()
unsigned int SedComputeChange::getNumVariables () const
Get the number of SedVariable objects in this SedComputeChange.
Returns
the number of SedVariable objects in this SedComputeChange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getParameter() [1/4]
SedParameter * SedComputeChange::getParameter (const std::string & sid)
Get a SedParameter from the SedComputeChange based on its identifier.
Parameters
sid a string representing the identifier of the SedParameter to retrieve.
Returns
the SedParameter in the SedListOfParameters within this SedComputeChange with the given sid or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [2/4]
const SedParameter * SedComputeChange::getParameter (const std::string & sid) const
Get a SedParameter from the SedComputeChange based on its identifier.
Parameters
sid a string representing the identifier of the SedParameter to retrieve.
Returns
the SedParameter in the SedListOfParameters within this SedComputeChange with the given sid or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [3/4]
SedParameter * SedComputeChange::getParameter (unsigned int n)
Get a SedParameter from the SedComputeChange.
Parameters
n an unsigned int representing the index of the SedParameter to retrieve.
Returns
the nth SedParameter in the SedListOfParameters within this SedComputeChange or NULL if no such object exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getParameter() [4/4]
const SedParameter * SedComputeChange::getParameter (unsigned int n) const
Get a SedParameter from the SedComputeChange.
Parameters
n an unsigned int representing the index of the SedParameter to retrieve.
Returns
the nth SedParameter in the SedListOfParameters within this SedComputeChange or NULL if no such object exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getNumParameters()
removeParameter(const std::string& sid)
removeParameter(unsigned int n)
getSymbol()
const std::string & SedComputeChange::getSymbol () const
Returns the value of the "symbol" attribute of this SedComputeChange.
Returns
the value of the "symbol" attribute of this SedComputeChange as a string.
References SedBase::getLevel(), and SedBase::getVersion().
getTypeCode()
int SedComputeChange::getTypeCode () const virtual
Returns the libSEDML type code for this SedComputeChange object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_CHANGE_COMPUTECHANGE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedChange.
References SEDML_CHANGE_COMPUTECHANGE.
getVariable() [1/4]
SedVariable * SedComputeChange::getVariable (const std::string & sid)
Get a SedVariable from the SedComputeChange based on its identifier.
Parameters
sid a string representing the identifier of the SedVariable to retrieve.
Returns
the SedVariable in the SedListOfVariables within this SedComputeChange with the given sid or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [2/4]
const SedVariable * SedComputeChange::getVariable (const std::string & sid) const
Get a SedVariable from the SedComputeChange based on its identifier.
Parameters
sid a string representing the identifier of the SedVariable to retrieve.
Returns
the SedVariable in the SedListOfVariables within this SedComputeChange with the given sid or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [3/4]
SedVariable * SedComputeChange::getVariable (unsigned int n)
Get a SedVariable from the SedComputeChange.
Parameters
n an unsigned int representing the index of the SedVariable to retrieve.
Returns
the nth SedVariable in the SedListOfVariables within this SedComputeChange or NULL if no such object exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariable() [4/4]
const SedVariable * SedComputeChange::getVariable (unsigned int n) const
Get a SedVariable from the SedComputeChange.
Parameters
n an unsigned int representing the index of the SedVariable to retrieve.
Returns
the nth SedVariable in the SedListOfVariables within this SedComputeChange or NULL if no such object exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getNumVariables()
removeVariable(const std::string& sid)
removeVariable(unsigned int n)
getVariableByModelReference() [1/2]
SedVariable * SedComputeChange::getVariableByModelReference (const std::string & sid)
Get a SedVariable from the SedComputeChange based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedComputeChange based on the given modelReference attribute or NULL if no such SedVariable exists.
getVariableByModelReference() [2/2]
const SedVariable * SedComputeChange::getVariableByModelReference (const std::string & sid) const
Get a SedVariable from the SedComputeChange based on the ModelReference to which it refers.
Parameters
sid a string representing the "modelReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedComputeChange based on the given modelReference attribute or NULL if no such SedVariable exists.
getVariableByTaskReference() [1/2]
SedVariable * SedComputeChange::getVariableByTaskReference (const std::string & sid)
Get a SedVariable from the SedComputeChange based on the TaskReference to which it refers.
Parameters
sid a string representing the "taskReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedComputeChange based on the given taskReference attribute or NULL if no such SedVariable exists.
getVariableByTaskReference() [2/2]
const SedVariable * SedComputeChange::getVariableByTaskReference (const std::string & sid) const
Get a SedVariable from the SedComputeChange based on the TaskReference to which it refers.
Parameters
sid a string representing the "taskReference" attribute of the SedVariable object to retrieve.
Returns
the first SedVariable in this SedComputeChange based on the given taskReference attribute or NULL if no such SedVariable exists.
hasRequiredAttributes()
bool SedComputeChange::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedComputeChange object have been set.
Returns
true to indicate that all the required attributes of this SedComputeChange have been set, otherwise false is returned.
Reimplemented from SedChange.
References SedChange::hasRequiredAttributes().
hasRequiredElements()
bool SedComputeChange::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedComputeChange object have been set.
Returns
true to indicate that all the required elements of this SedComputeChange have been set, otherwise false is returned.
Note
The required elements for the SedComputeChange object are:
isSetMath()
bool SedComputeChange::isSetMath () const
Predicate returning true if this SedComputeChange's "math" element is set.
Returns
true if this SedComputeChange's "math" element has been set, otherwise false is returned.
Referenced by renameSIdRefs().
isSetSymbol()
bool SedComputeChange::isSetSymbol () const
Predicate returning true if this SedComputeChange's "symbol" attribute is set.
Returns
true if this SedComputeChange's "symbol" attribute has been set, otherwise false is returned.
References SedBase::getLevel(), and SedBase::getVersion().
operator=()
SedComputeChange & SedComputeChange::operator= (const SedComputeChange & rhs)
Assignment operator for SedComputeChange.
Parameters
rhs the SedComputeChange object whose values are to be used as the basis of the assignment.
References SedChange::operator=().
removeParameter() [1/2]
SedParameter * SedComputeChange::removeParameter (const std::string & sid)
Removes the SedParameter from this SedComputeChange based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedParameter to remove.
Returns
the SedParameter in this SedComputeChange based on the identifier or NULL if no such SedParameter exists.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(unsigned int n)
removeParameter() [2/2]
SedParameter * SedComputeChange::removeParameter (unsigned int n)
Removes the nth SedParameter from this SedComputeChange and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedParameter to remove.
Returns
a pointer to the nth SedParameter in this SedComputeChange.
See also
addParameter(const SedParameter* object)
createParameter()
getParameter(const std::string& sid)
getParameter(unsigned int n)
getNumParameters()
removeParameter(const std::string& sid)
removeVariable() [1/2]
SedVariable * SedComputeChange::removeVariable (const std::string & sid)
Removes the SedVariable from this SedComputeChange based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedVariable to remove.
Returns
the SedVariable in this SedComputeChange based on the identifier or NULL if no such SedVariable exists.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(unsigned int n)
removeVariable() [2/2]
SedVariable * SedComputeChange::removeVariable (unsigned int n)
Removes the nth SedVariable from this SedComputeChange and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedVariable to remove.
Returns
a pointer to the nth SedVariable in this SedComputeChange.
See also
addVariable(const SedVariable* object)
createVariable()
getVariable(const std::string& sid)
getVariable(unsigned int n)
getNumVariables()
removeVariable(const std::string& sid)
renameSIdRefs()
void SedComputeChange::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetMath().
setMath()
int SedComputeChange::setMath (const ASTNode * math)
Sets the value of the "math" element of this SedComputeChange.
Parameters
math LIBSBML_CPP_NAMESPACE_QUALIFIER ASTNode* value of the "math" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_OBJECT, and LIBSEDML_OPERATION_SUCCESS.
setSymbol()
int SedComputeChange::setSymbol (const std::string & symbol)
Sets the value of the "symbol" attribute of this SedComputeChange.
Parameters
symbol std::string& value of the "symbol" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with symbol = NULL or an empty string is equivalent to calling unsetSymbol().
References SedBase::getLevel(), SedBase::getVersion(), LIBSEDML_OPERATION_SUCCESS, and LIBSEDML_UNEXPECTED_ATTRIBUTE.
unsetMath()
int SedComputeChange::unsetMath ()
Unsets the value of the "math" element of this SedComputeChange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetSymbol()
int SedComputeChange::unsetSymbol ()
Unsets the value of the "symbol" attribute of this SedComputeChange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedComputeChange.h
SedComputeChange.cpp