LIBSEDML API: SedReport Class Reference
SedReport Class Reference
#include <SedReport.h>
Public Member Functions
int addDataSet (const SedDataSet *sds)
virtual SedReport * clone () const
SedDataSet * createDataSet ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedDataSet * getDataSet (const std::string &sid)
const SedDataSet * getDataSet (const std::string &sid) const
SedDataSet * getDataSet (unsigned int n)
const SedDataSet * getDataSet (unsigned int n) const
SedDataSet * getDataSetByDataReference (const std::string &sid)
const SedDataSet * getDataSetByDataReference (const std::string &sid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedListOfDataSets * getListOfDataSets ()
const SedListOfDataSets * getListOfDataSets () const
unsigned int getNumDataSets () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
virtual bool hasRequiredElements () const
SedReport & operator= (const SedReport &rhs)
SedDataSet * removeDataSet (const std::string &sid)
SedDataSet * removeDataSet (unsigned int n)
SedReport (const SedReport &orig)
SedReport (SedNamespaces *sedmlns)
SedReport (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedReport ()
Public Member Functions inherited from SedOutput
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedReport class.
Constructor & Destructor Documentation
SedReport() [1/3]
SedReport::SedReport (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedReport using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedReport.
version an unsigned int, the SED-ML Version to assign to this SedReport.
Referenced by clone().
SedReport() [2/3]
SedReport::SedReport (SedNamespaces * sedmlns)
Creates a new SedReport using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedReport() [3/3]
SedReport::SedReport (const SedReport & orig)
Copy constructor for SedReport.
Parameters
orig the SedReport instance to copy.
~SedReport()
SedReport::~SedReport () virtual
Destructor for SedReport.
Member Function Documentation
addDataSet()
int SedReport::addDataSet (const SedDataSet * sds)
Adds a copy of the given SedDataSet to this SedReport.
Parameters
sds the SedDataSet object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createDataSet()
getDataSet(const std::string& sid)
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
References SedBase::getId(), SedBase::getLevel(), SedBase::getVersion(), SedDataSet::hasRequiredAttributes(), SedBase::isSetId(), LIBSEDML_DUPLICATE_OBJECT_ID, LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedReport * SedReport::clone () const virtual
Creates and returns a deep copy of this SedReport object.
Returns
a (deep) copy of this SedReport object.
Reimplemented from SedOutput.
References SedReport().
createDataSet()
SedDataSet * SedReport::createDataSet ()
Creates a new SedDataSet object, adds it to this SedReport object and returns the SedDataSet object created.
Returns
a new SedDataSet object instance.
See also
addDataSet(const SedDataSet* object)
getDataSet(const std::string& sid)
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getAllElements()
List * SedReport::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getDataSet() [1/4]
SedDataSet * SedReport::getDataSet (const std::string & sid)
Get a SedDataSet from the SedReport based on its identifier.
Parameters
sid a string representing the identifier of the SedDataSet to retrieve.
Returns
the SedDataSet in the SedListOfDataSets within this SedReport with the given sid or NULL if no such SedDataSet exists.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getDataSet() [2/4]
const SedDataSet * SedReport::getDataSet (const std::string & sid) const
Get a SedDataSet from the SedReport based on its identifier.
Parameters
sid a string representing the identifier of the SedDataSet to retrieve.
Returns
the SedDataSet in the SedListOfDataSets within this SedReport with the given sid or NULL if no such SedDataSet exists.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getDataSet() [3/4]
SedDataSet * SedReport::getDataSet (unsigned int n)
Get a SedDataSet from the SedReport.
Parameters
n an unsigned int representing the index of the SedDataSet to retrieve.
Returns
the nth SedDataSet in the SedListOfDataSets within this SedReport or NULL if no such object exists.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(const std::string& sid)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getDataSet() [4/4]
const SedDataSet * SedReport::getDataSet (unsigned int n) const
Get a SedDataSet from the SedReport.
Parameters
n an unsigned int representing the index of the SedDataSet to retrieve.
Returns
the nth SedDataSet in the SedListOfDataSets within this SedReport or NULL if no such object exists.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(const std::string& sid)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getDataSetByDataReference() [1/2]
SedDataSet * SedReport::getDataSetByDataReference (const std::string & sid)
Get a SedDataSet from the SedReport based on the DataReference to which it refers.
Parameters
sid a string representing the "dataReference" attribute of the SedDataSet object to retrieve.
Returns
the first SedDataSet in this SedReport based on the given dataReference attribute or NULL if no such SedDataSet exists.
getDataSetByDataReference() [2/2]
const SedDataSet * SedReport::getDataSetByDataReference (const std::string & sid) const
Get a SedDataSet from the SedReport based on the DataReference to which it refers.
Parameters
sid a string representing the "dataReference" attribute of the SedDataSet object to retrieve.
Returns
the first SedDataSet in this SedReport based on the given dataReference attribute or NULL if no such SedDataSet exists.
getElementBySId()
SedBase * SedReport::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedReport::getElementName () const virtual
Returns the XML element name of this SedReport object.
For SedReport, the XML element name is always "report".
Returns
the name of this element, i.e. "report".
Reimplemented from SedOutput.
getListOfDataSets() [1/2]
SedListOfDataSets * SedReport::getListOfDataSets ()
Returns the SedListOfDataSets from this SedReport.
Returns
the SedListOfDataSets from this SedReport.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(const std::string& sid)
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getListOfDataSets() [2/2]
const SedListOfDataSets * SedReport::getListOfDataSets () const
Returns the SedListOfDataSets from this SedReport.
Returns
the SedListOfDataSets from this SedReport.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(const std::string& sid)
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getNumDataSets()
unsigned int SedReport::getNumDataSets () const
Get the number of SedDataSet objects in this SedReport.
Returns
the number of SedDataSet objects in this SedReport.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(const std::string& sid)
getDataSet(unsigned int n)
removeDataSet(const std::string& sid)
removeDataSet(unsigned int n)
getTypeCode()
int SedReport::getTypeCode () const virtual
Returns the libSEDML type code for this SedReport object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_OUTPUT_REPORT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedOutput.
References SEDML_OUTPUT_REPORT.
hasRequiredAttributes()
bool SedReport::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedReport object have been set.
Returns
true to indicate that all the required attributes of this SedReport have been set, otherwise false is returned.
Reimplemented from SedOutput.
References SedOutput::hasRequiredAttributes().
hasRequiredElements()
bool SedReport::hasRequiredElements () const virtual
Predicate returning true if all the required elements for this SedReport object have been set.
Returns
true to indicate that all the required elements of this SedReport have been set, otherwise false is returned.
Note
The required elements for the SedReport object are:
operator=()
SedReport & SedReport::operator= (const SedReport & rhs)
Assignment operator for SedReport.
Parameters
rhs the SedReport object whose values are to be used as the basis of the assignment.
References SedOutput::operator=().
removeDataSet() [1/2]
SedDataSet * SedReport::removeDataSet (const std::string & sid)
Removes the SedDataSet from this SedReport based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedDataSet to remove.
Returns
the SedDataSet in this SedReport based on the identifier or NULL if no such SedDataSet exists.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(const std::string& sid)
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(unsigned int n)
removeDataSet() [2/2]
SedDataSet * SedReport::removeDataSet (unsigned int n)
Removes the nth SedDataSet from this SedReport and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedDataSet to remove.
Returns
a pointer to the nth SedDataSet in this SedReport.
See also
addDataSet(const SedDataSet* object)
createDataSet()
getDataSet(const std::string& sid)
getDataSet(unsigned int n)
getNumDataSets()
removeDataSet(const std::string& sid)
The documentation for this class was generated from the following files:
SedReport.h
SedReport.cpp