LIBSEDML API: SedListOfSurfaces Class Reference
SedListOfSurfaces Class Reference
#include <SedListOfSurfaces.h>
Public Member Functions
int addSurface (const SedSurface *ss)
virtual SedListOfSurfaces * clone () const
SedSurface * createSurface ()
virtual SedSurface * get (const std::string &sid)
virtual const SedSurface * get (const std::string &sid) const
virtual SedSurface * get (unsigned int n)
virtual const SedSurface * get (unsigned int n) const
SedSurface * getByStyle (const std::string &sid)
const SedSurface * getByStyle (const std::string &sid) const
SedSurface * getByXDataReference (const std::string &sid)
const SedSurface * getByXDataReference (const std::string &sid) const
SedSurface * getByYDataReference (const std::string &sid)
const SedSurface * getByYDataReference (const std::string &sid) const
SedSurface * getByZDataReference (const std::string &sid)
const SedSurface * getByZDataReference (const std::string &sid) const
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
unsigned int getNumSurfaces () const
virtual int getTypeCode () const
SedListOfSurfaces & operator= (const SedListOfSurfaces &rhs)
virtual SedSurface * remove (const std::string &sid)
virtual SedSurface * remove (unsigned int n)
SedListOfSurfaces (const SedListOfSurfaces &orig)
SedListOfSurfaces (SedNamespaces *sedmlns)
SedListOfSurfaces (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
void sort ()
virtual ~SedListOfSurfaces ()
Public Member Functions inherited from SedListOf
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedListOfSurfaces class.
Constructor & Destructor Documentation
SedListOfSurfaces() [1/3]
SedListOfSurfaces::SedListOfSurfaces (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOfSurfaces using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedListOfSurfaces.
version an unsigned int, the SED-ML Version to assign to this SedListOfSurfaces.
Referenced by clone().
SedListOfSurfaces() [2/3]
SedListOfSurfaces::SedListOfSurfaces (SedNamespaces * sedmlns)
Creates a new SedListOfSurfaces using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedListOfSurfaces() [3/3]
SedListOfSurfaces::SedListOfSurfaces (const SedListOfSurfaces & orig)
Copy constructor for SedListOfSurfaces.
Parameters
orig the SedListOfSurfaces instance to copy.
~SedListOfSurfaces()
SedListOfSurfaces::~SedListOfSurfaces () virtual
Destructor for SedListOfSurfaces.
Member Function Documentation
addSurface()
int SedListOfSurfaces::addSurface (const SedSurface * ss)
Adds a copy of the given SedSurface to this SedListOfSurfaces.
Parameters
ss the SedSurface object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createSurface()
get(const std::string& sid)
get(unsigned int n)
getNumSurfaces()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::append(), SedBase::getLevel(), SedBase::getVersion(), SedSurface::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedListOfSurfaces * SedListOfSurfaces::clone () const virtual
Creates and returns a deep copy of this SedListOfSurfaces object.
Returns
a (deep) copy of this SedListOfSurfaces object.
Reimplemented from SedListOf.
References SedListOfSurfaces().
createSurface()
SedSurface * SedListOfSurfaces::createSurface ()
Creates a new SedSurface object, adds it to this SedListOfSurfaces object and returns the SedSurface object created.
Returns
a new SedSurface object instance.
See also
addSurface(const SedSurface* object)
get(const std::string& sid)
get(unsigned int n)
getNumSurfaces()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
get() [1/4]
SedSurface * SedListOfSurfaces::get (const std::string & sid) virtual
Get a SedSurface from the SedListOfSurfaces based on its identifier.
Parameters
sid a string representing the identifier of the SedSurface to retrieve.
Returns
the SedSurface in this SedListOfSurfaces with the given sid or NULL if no such SedSurface exists.
See also
addSurface(const SedSurface* object)
createSurface()
get(unsigned int n)
getNumSurfaces()
remove(const std::string& sid)
remove(unsigned int n)
References get().
get() [2/4]
const SedSurface * SedListOfSurfaces::get (const std::string & sid) const virtual
Get a SedSurface from the SedListOfSurfaces based on its identifier.
Parameters
sid a string representing the identifier of the SedSurface to retrieve.
Returns
the SedSurface in this SedListOfSurfaces with the given sid or NULL if no such SedSurface exists.
See also
addSurface(const SedSurface* object)
createSurface()
get(unsigned int n)
getNumSurfaces()
remove(const std::string& sid)
remove(unsigned int n)
get() [3/4]
SedSurface * SedListOfSurfaces::get (unsigned int n) virtual
Get a SedSurface from the SedListOfSurfaces.
Parameters
n an unsigned int representing the index of the SedSurface to retrieve.
Returns
the nth SedSurface in this SedListOfSurfaces or NULL if no such object exists.
See also
addSurface(const SedSurface* object)
createSurface()
get(const std::string& sid)
getNumSurfaces()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
Referenced by get().
get() [4/4]
const SedSurface * SedListOfSurfaces::get (unsigned int n) const virtual
Get a SedSurface from the SedListOfSurfaces.
Parameters
n an unsigned int representing the index of the SedSurface to retrieve.
Returns
the nth SedSurface in this SedListOfSurfaces or NULL if no such object exists.
See also
addSurface(const SedSurface* object)
createSurface()
get(const std::string& sid)
getNumSurfaces()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
getByStyle() [1/2]
SedSurface * SedListOfSurfaces::getByStyle (const std::string & sid)
Get a SedSurface from the SedListOfSurfaces based on the Style to which it refers.
Parameters
sid a string representing the "style" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given style attribute or NULL if no such SedSurface exists.
References getByStyle().
getByStyle() [2/2]
const SedSurface * SedListOfSurfaces::getByStyle (const std::string & sid) const
Get a SedSurface from the SedListOfSurfaces based on the Style to which it refers.
Parameters
sid a string representing the "style" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given style attribute or NULL if no such SedSurface exists.
Referenced by getByStyle().
getByXDataReference() [1/2]
SedSurface * SedListOfSurfaces::getByXDataReference (const std::string & sid)
Get a SedSurface from the SedListOfSurfaces based on the XDataReference to which it refers.
Parameters
sid a string representing the "xDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given xDataReference attribute or NULL if no such SedSurface exists.
References getByXDataReference().
getByXDataReference() [2/2]
const SedSurface * SedListOfSurfaces::getByXDataReference (const std::string & sid) const
Get a SedSurface from the SedListOfSurfaces based on the XDataReference to which it refers.
Parameters
sid a string representing the "xDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given xDataReference attribute or NULL if no such SedSurface exists.
Referenced by getByXDataReference().
getByYDataReference() [1/2]
SedSurface * SedListOfSurfaces::getByYDataReference (const std::string & sid)
Get a SedSurface from the SedListOfSurfaces based on the YDataReference to which it refers.
Parameters
sid a string representing the "yDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given yDataReference attribute or NULL if no such SedSurface exists.
References getByYDataReference().
getByYDataReference() [2/2]
const SedSurface * SedListOfSurfaces::getByYDataReference (const std::string & sid) const
Get a SedSurface from the SedListOfSurfaces based on the YDataReference to which it refers.
Parameters
sid a string representing the "yDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given yDataReference attribute or NULL if no such SedSurface exists.
Referenced by getByYDataReference().
getByZDataReference() [1/2]
SedSurface * SedListOfSurfaces::getByZDataReference (const std::string & sid)
Get a SedSurface from the SedListOfSurfaces based on the ZDataReference to which it refers.
Parameters
sid a string representing the "zDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given zDataReference attribute or NULL if no such SedSurface exists.
References getByZDataReference().
getByZDataReference() [2/2]
const SedSurface * SedListOfSurfaces::getByZDataReference (const std::string & sid) const
Get a SedSurface from the SedListOfSurfaces based on the ZDataReference to which it refers.
Parameters
sid a string representing the "zDataReference" attribute of the SedSurface object to retrieve.
Returns
the first SedSurface in this SedListOfSurfaces based on the given zDataReference attribute or NULL if no such SedSurface exists.
Referenced by getByZDataReference().
getElementName()
const std::string & SedListOfSurfaces::getElementName () const virtual
Returns the XML element name of this SedListOfSurfaces object.
For SedListOfSurfaces, the XML element name is always "listOfSurfaces".
Returns
the name of this element, i.e. "listOfSurfaces".
Reimplemented from SedListOf.
getItemTypeCode()
int SedListOfSurfaces::getItemTypeCode () const virtual
Returns the libSEDML type code for the SED-ML objects contained in this SedListOfSurfaces object.
Returns
the SED-ML typecode for the objects contained in this SedListOfSurfaces: @sedmlconstant{SEDML_OUTPUT_SURFACE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedListOf.
References SEDML_OUTPUT_SURFACE.
getNumSurfaces()
unsigned int SedListOfSurfaces::getNumSurfaces () const
Get the number of SedSurface objects in this SedListOfSurfaces.
Returns
the number of SedSurface objects in this SedListOfSurfaces.
See also
addSurface(const SedSurface* object)
createSurface()
get(const std::string& sid)
get(unsigned int n)
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::size().
getTypeCode()
int SedListOfSurfaces::getTypeCode () const virtual
Returns the libSEDML type code for this SedListOfSurfaces object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Reimplemented from SedListOf.
References SEDML_LIST_OF.
operator=()
SedListOfSurfaces & SedListOfSurfaces::operator= (const SedListOfSurfaces & rhs)
Assignment operator for SedListOfSurfaces.
Parameters
rhs the SedListOfSurfaces object whose values are to be used as the basis of the assignment.
References SedListOf::operator=().
remove() [1/2]
SedSurface * SedListOfSurfaces::remove (const std::string & sid) virtual
Removes the SedSurface from this SedListOfSurfaces based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedSurface to remove.
Returns
the SedSurface in this SedListOfSurfaces based on the identifier or NULL if no such SedSurface exists.
See also
addSurface(const SedSurface* object)
createSurface()
get(const std::string& sid)
get(unsigned int n)
getNumSurfaces()
remove(unsigned int n)
remove() [2/2]
SedSurface * SedListOfSurfaces::remove (unsigned int n) virtual
Removes the nth SedSurface from this SedListOfSurfaces and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedSurface to remove.
Returns
a pointer to the nth SedSurface in this SedListOfSurfaces.
See also
addSurface(const SedSurface* object)
createSurface()
get(const std::string& sid)
get(unsigned int n)
getNumSurfaces()
remove(const std::string& sid)
Reimplemented from SedListOf.
References SedListOf::remove().
sort()
void SedListOfSurfaces::sort ()
Sort the SedListOfCurves according to the 'order' attribute.
Referenced by SedDocument::sortOrderedObjects().
The documentation for this class was generated from the following files:
SedListOfSurfaces.h
SedListOfSurfaces.cpp