LIBSEDML API: SedListOfFitMappings Class Reference
SedListOfFitMappings Class Reference
#include <SedListOfFitMappings.h>
Public Member Functions
int addFitMapping (const SedFitMapping *sfm)
virtual SedListOfFitMappings * clone () const
SedFitMapping * createFitMapping ()
virtual SedFitMapping * get (const std::string &sid)
virtual const SedFitMapping * get (const std::string &sid) const
virtual SedFitMapping * get (unsigned int n)
virtual const SedFitMapping * get (unsigned int n) const
SedFitMapping * getByDataSource (const std::string &sid)
const SedFitMapping * getByDataSource (const std::string &sid) const
SedFitMapping * getByPointWeight (const std::string &sid)
const SedFitMapping * getByPointWeight (const std::string &sid) const
SedFitMapping * getByTarget (const std::string &sid)
const SedFitMapping * getByTarget (const std::string &sid) const
virtual const std::string & getElementName () const
virtual int getItemTypeCode () const
unsigned int getNumFitMappings () const
virtual int getTypeCode () const
SedListOfFitMappings & operator= (const SedListOfFitMappings &rhs)
virtual SedFitMapping * remove (const std::string &sid)
virtual SedFitMapping * remove (unsigned int n)
SedListOfFitMappings (const SedListOfFitMappings &orig)
SedListOfFitMappings (SedNamespaces *sedmlns)
SedListOfFitMappings (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedListOfFitMappings ()
Public Member Functions inherited from SedListOf
int append (const SedBase *item)
int appendAndOwn (SedBase *disownedItem)
virtual int appendFrom (const SedListOf *list)
void clear (bool doDelete=true)
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual SedBase * getElementBySId (const std::string &id)
int insert (int location, const SedBase *item)
int insertAndOwn (int location, SedBase *disownedItem)
SedListOf & operator= (const SedListOf &rhs)
virtual int removeFromParentAndDelete ()
SedListOf (const SedListOf &orig)
SedListOf (SedNamespaces *sedmlns)
SedListOf (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
unsigned int size () const
virtual ~SedListOf ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedListOfFitMappings class.
Constructor & Destructor Documentation
SedListOfFitMappings() [1/3]
SedListOfFitMappings::SedListOfFitMappings (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedListOfFitMappings using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedListOfFitMappings.
version an unsigned int, the SED-ML Version to assign to this SedListOfFitMappings.
Referenced by clone().
SedListOfFitMappings() [2/3]
SedListOfFitMappings::SedListOfFitMappings (SedNamespaces * sedmlns)
Creates a new SedListOfFitMappings using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedListOfFitMappings() [3/3]
SedListOfFitMappings::SedListOfFitMappings (const SedListOfFitMappings & orig)
Copy constructor for SedListOfFitMappings.
Parameters
orig the SedListOfFitMappings instance to copy.
~SedListOfFitMappings()
SedListOfFitMappings::~SedListOfFitMappings () virtual
Destructor for SedListOfFitMappings.
Member Function Documentation
addFitMapping()
int SedListOfFitMappings::addFitMapping (const SedFitMapping * sfm)
Adds a copy of the given SedFitMapping to this SedListOfFitMappings.
Parameters
sfm the SedFitMapping object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createFitMapping()
get(const std::string& sid)
get(unsigned int n)
getNumFitMappings()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::append(), SedBase::getLevel(), SedBase::getVersion(), SedFitMapping::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedListOfFitMappings * SedListOfFitMappings::clone () const virtual
Creates and returns a deep copy of this SedListOfFitMappings object.
Returns
a (deep) copy of this SedListOfFitMappings object.
Reimplemented from SedListOf.
References SedListOfFitMappings().
createFitMapping()
SedFitMapping * SedListOfFitMappings::createFitMapping ()
Creates a new SedFitMapping object, adds it to this SedListOfFitMappings object and returns the SedFitMapping object created.
Returns
a new SedFitMapping object instance.
See also
addFitMapping(const SedFitMapping* object)
get(const std::string& sid)
get(unsigned int n)
getNumFitMappings()
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::appendAndOwn().
get() [1/4]
SedFitMapping * SedListOfFitMappings::get (const std::string & sid) virtual
Get a SedFitMapping from the SedListOfFitMappings based on its identifier.
Parameters
sid a string representing the identifier of the SedFitMapping to retrieve.
Returns
the SedFitMapping in this SedListOfFitMappings with the given sid or NULL if no such SedFitMapping exists.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
get(unsigned int n)
getNumFitMappings()
remove(const std::string& sid)
remove(unsigned int n)
References get().
get() [2/4]
const SedFitMapping * SedListOfFitMappings::get (const std::string & sid) const virtual
Get a SedFitMapping from the SedListOfFitMappings based on its identifier.
Parameters
sid a string representing the identifier of the SedFitMapping to retrieve.
Returns
the SedFitMapping in this SedListOfFitMappings with the given sid or NULL if no such SedFitMapping exists.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
get(unsigned int n)
getNumFitMappings()
remove(const std::string& sid)
remove(unsigned int n)
get() [3/4]
SedFitMapping * SedListOfFitMappings::get (unsigned int n) virtual
Get a SedFitMapping from the SedListOfFitMappings.
Parameters
n an unsigned int representing the index of the SedFitMapping to retrieve.
Returns
the nth SedFitMapping in this SedListOfFitMappings or NULL if no such object exists.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
get(const std::string& sid)
getNumFitMappings()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
Referenced by get().
get() [4/4]
const SedFitMapping * SedListOfFitMappings::get (unsigned int n) const virtual
Get a SedFitMapping from the SedListOfFitMappings.
Parameters
n an unsigned int representing the index of the SedFitMapping to retrieve.
Returns
the nth SedFitMapping in this SedListOfFitMappings or NULL if no such object exists.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
get(const std::string& sid)
getNumFitMappings()
remove(const std::string& sid)
remove(unsigned int n)
Reimplemented from SedListOf.
References SedListOf::get().
getByDataSource() [1/2]
SedFitMapping * SedListOfFitMappings::getByDataSource (const std::string & sid)
Get a SedFitMapping from the SedListOfFitMappings based on the DataSource to which it refers.
Parameters
sid a string representing the "dataSource" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedListOfFitMappings based on the given dataSource attribute or NULL if no such SedFitMapping exists.
References getByDataSource().
getByDataSource() [2/2]
const SedFitMapping * SedListOfFitMappings::getByDataSource (const std::string & sid) const
Get a SedFitMapping from the SedListOfFitMappings based on the DataSource to which it refers.
Parameters
sid a string representing the "dataSource" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedListOfFitMappings based on the given dataSource attribute or NULL if no such SedFitMapping exists.
Referenced by getByDataSource().
getByPointWeight() [1/2]
SedFitMapping * SedListOfFitMappings::getByPointWeight (const std::string & sid)
Get a SedFitMapping from the SedListOfFitMappings based on the PointWeight to which it refers.
Parameters
sid a string representing the "pointWeight" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedListOfFitMappings based on the given pointWeight attribute or NULL if no such SedFitMapping exists.
References getByPointWeight().
getByPointWeight() [2/2]
const SedFitMapping * SedListOfFitMappings::getByPointWeight (const std::string & sid) const
Get a SedFitMapping from the SedListOfFitMappings based on the PointWeight to which it refers.
Parameters
sid a string representing the "pointWeight" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedListOfFitMappings based on the given pointWeight attribute or NULL if no such SedFitMapping exists.
Referenced by getByPointWeight().
getByTarget() [1/2]
SedFitMapping * SedListOfFitMappings::getByTarget (const std::string & sid)
Get a SedFitMapping from the SedListOfFitMappings based on the Target to which it refers.
Parameters
sid a string representing the "target" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedListOfFitMappings based on the given target attribute or NULL if no such SedFitMapping exists.
References getByTarget().
getByTarget() [2/2]
const SedFitMapping * SedListOfFitMappings::getByTarget (const std::string & sid) const
Get a SedFitMapping from the SedListOfFitMappings based on the Target to which it refers.
Parameters
sid a string representing the "target" attribute of the SedFitMapping object to retrieve.
Returns
the first SedFitMapping in this SedListOfFitMappings based on the given target attribute or NULL if no such SedFitMapping exists.
Referenced by getByTarget().
getElementName()
const std::string & SedListOfFitMappings::getElementName () const virtual
Returns the XML element name of this SedListOfFitMappings object.
For SedListOfFitMappings, the XML element name is always "listOfFitMappings".
Returns
the name of this element, i.e. "listOfFitMappings".
Reimplemented from SedListOf.
getItemTypeCode()
int SedListOfFitMappings::getItemTypeCode () const virtual
Returns the libSEDML type code for the SED-ML objects contained in this SedListOfFitMappings object.
Returns
the SED-ML typecode for the objects contained in this SedListOfFitMappings: @sedmlconstant{SEDML_FITMAPPING, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedListOf.
References SEDML_FITMAPPING.
getNumFitMappings()
unsigned int SedListOfFitMappings::getNumFitMappings () const
Get the number of SedFitMapping objects in this SedListOfFitMappings.
Returns
the number of SedFitMapping objects in this SedListOfFitMappings.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
get(const std::string& sid)
get(unsigned int n)
remove(const std::string& sid)
remove(unsigned int n)
References SedListOf::size().
getTypeCode()
int SedListOfFitMappings::getTypeCode () const virtual
Returns the libSEDML type code for this SedListOfFitMappings object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_LIST_OF, SedTypeCode_t}.
Reimplemented from SedListOf.
References SEDML_LIST_OF.
operator=()
SedListOfFitMappings & SedListOfFitMappings::operator= (const SedListOfFitMappings & rhs)
Assignment operator for SedListOfFitMappings.
Parameters
rhs the SedListOfFitMappings object whose values are to be used as the basis of the assignment.
References SedListOf::operator=().
remove() [1/2]
SedFitMapping * SedListOfFitMappings::remove (const std::string & sid) virtual
Removes the SedFitMapping from this SedListOfFitMappings based on its identifier and returns a pointer to it.
Parameters
sid a string representing the identifier of the SedFitMapping to remove.
Returns
the SedFitMapping in this SedListOfFitMappings based on the identifier or NULL if no such SedFitMapping exists.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
get(const std::string& sid)
get(unsigned int n)
getNumFitMappings()
remove(unsigned int n)
remove() [2/2]
SedFitMapping * SedListOfFitMappings::remove (unsigned int n) virtual
Removes the nth SedFitMapping from this SedListOfFitMappings and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedFitMapping to remove.
Returns
a pointer to the nth SedFitMapping in this SedListOfFitMappings.
See also
addFitMapping(const SedFitMapping* object)
createFitMapping()
get(const std::string& sid)
get(unsigned int n)
getNumFitMappings()
remove(const std::string& sid)
Reimplemented from SedListOf.
References SedListOf::remove().
The documentation for this class was generated from the following files:
SedListOfFitMappings.h
SedListOfFitMappings.cpp