LIBSEDML API: SedAlgorithm Class Reference
SedAlgorithm Class Reference
#include <SedAlgorithm.h>
Public Member Functions
int addAlgorithmParameter (const SedAlgorithmParameter *sap)
virtual SedAlgorithm * clone () const
SedAlgorithmParameter * createAlgorithmParameter ()
SedAlgorithmParameter * getAlgorithmParameter (unsigned int n)
const SedAlgorithmParameter * getAlgorithmParameter (unsigned int n) const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
const std::string & getKisaoID () const
int getKisaoIDasInt () const
SedListOfAlgorithmParameters * getListOfAlgorithmParameters ()
const SedListOfAlgorithmParameters * getListOfAlgorithmParameters () const
unsigned int getNumAlgorithmParameters () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetKisaoID () const
SedAlgorithm & operator= (const SedAlgorithm &rhs)
SedAlgorithmParameter * removeAlgorithmParameter (const std::string &id)
SedAlgorithmParameter * removeAlgorithmParameter (unsigned int n)
SedAlgorithm (const SedAlgorithm &orig)
SedAlgorithm (SedNamespaces *sedmlns)
SedAlgorithm (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setKisaoID (const std::string &kisaoID)
int setKisaoID (int kisaoID)
int unsetKisaoID ()
virtual ~SedAlgorithm ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAlgorithm class.
Constructor & Destructor Documentation
SedAlgorithm() [1/3]
SedAlgorithm::SedAlgorithm (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAlgorithm using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAlgorithm.
version an unsigned int, the SED-ML Version to assign to this SedAlgorithm.
Referenced by clone().
SedAlgorithm() [2/3]
SedAlgorithm::SedAlgorithm (SedNamespaces * sedmlns)
Creates a new SedAlgorithm using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedAlgorithm() [3/3]
SedAlgorithm::SedAlgorithm (const SedAlgorithm & orig)
Copy constructor for SedAlgorithm.
Parameters
orig the SedAlgorithm instance to copy.
~SedAlgorithm()
SedAlgorithm::~SedAlgorithm () virtual
Destructor for SedAlgorithm.
Member Function Documentation
addAlgorithmParameter()
int SedAlgorithm::addAlgorithmParameter (const SedAlgorithmParameter * sap)
Adds a copy of the given SedAlgorithmParameter to this SedAlgorithm.
Parameters
sap the SedAlgorithmParameter object to add.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_OBJECT, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_LEVEL_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_PKG_VERSION_MISMATCH, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_DUPLICATE_OBJECT_ID, OperationReturnValues_t}
See also
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
References SedBase::getLevel(), SedBase::getVersion(), SedAlgorithmParameter::hasRequiredAttributes(), LIBSEDML_INVALID_OBJECT, LIBSEDML_LEVEL_MISMATCH, LIBSEDML_NAMESPACES_MISMATCH, LIBSEDML_OPERATION_FAILED, LIBSEDML_VERSION_MISMATCH, and SedBase::matchesRequiredSedNamespacesForAddition().
clone()
SedAlgorithm * SedAlgorithm::clone () const virtual
Creates and returns a deep copy of this SedAlgorithm object.
Returns
a (deep) copy of this SedAlgorithm object.
Implements SedBase.
References SedAlgorithm().
Referenced by SedFitExperiment::setAlgorithm(), SedParameterEstimationTask::setAlgorithm(), and SedSimulation::setAlgorithm().
createAlgorithmParameter()
SedAlgorithmParameter * SedAlgorithm::createAlgorithmParameter ()
Creates a new SedAlgorithmParameter object, adds it to this SedAlgorithm object and returns the SedAlgorithmParameter object created.
Returns
a new SedAlgorithmParameter object instance.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAlgorithmParameter() [1/2]
SedAlgorithmParameter * SedAlgorithm::getAlgorithmParameter (unsigned int n)
Get a SedAlgorithmParameter from the SedAlgorithm.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in the SedListOfAlgorithmParameters within this SedAlgorithm or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAlgorithmParameter() [2/2]
const SedAlgorithmParameter * SedAlgorithm::getAlgorithmParameter (unsigned int n) const
Get a SedAlgorithmParameter from the SedAlgorithm.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to retrieve.
Returns
the nth SedAlgorithmParameter in the SedListOfAlgorithmParameters within this SedAlgorithm or NULL if no such object exists.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getAllElements()
List * SedAlgorithm::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_LIST.
getElementBySId()
SedBase * SedAlgorithm::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedAlgorithm::getElementName () const virtual
Returns the XML element name of this SedAlgorithm object.
For SedAlgorithm, the XML element name is always "algorithm".
Returns
the name of this element, i.e. "algorithm".
Implements SedBase.
getKisaoID()
const std::string & SedAlgorithm::getKisaoID () const
Returns the value of the "kisaoID" attribute of this SedAlgorithm.
Returns
the value of the "kisaoID" attribute of this SedAlgorithm as a string.
getKisaoIDasInt()
int SedAlgorithm::getKisaoIDasInt () const
Returns
the KisaoTerm as integer if possible or -1 in case of failure
Referenced by setKisaoID().
getListOfAlgorithmParameters() [1/2]
SedListOfAlgorithmParameters * SedAlgorithm::getListOfAlgorithmParameters ()
Returns the SedListOfAlgorithmParameters from this SedAlgorithm.
Returns
the SedListOfAlgorithmParameters from this SedAlgorithm.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getListOfAlgorithmParameters() [2/2]
const SedListOfAlgorithmParameters * SedAlgorithm::getListOfAlgorithmParameters () const
Returns the SedListOfAlgorithmParameters from this SedAlgorithm.
Returns
the SedListOfAlgorithmParameters from this SedAlgorithm.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
unsigned int SedAlgorithm::getNumAlgorithmParameters () const
Get the number of SedAlgorithmParameter objects in this SedAlgorithm.
Returns
the number of SedAlgorithmParameter objects in this SedAlgorithm.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter(unsigned int n)
getTypeCode()
int SedAlgorithm::getTypeCode () const virtual
Returns the libSEDML type code for this SedAlgorithm object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SIMULATION_ALGORITHM, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_SIMULATION_ALGORITHM.
hasRequiredAttributes()
bool SedAlgorithm::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAlgorithm object have been set.
Returns
true to indicate that all the required attributes of this SedAlgorithm have been set, otherwise false is returned.
Note
The required attributes for the SedAlgorithm object are:
"kisaoID"
References isSetKisaoID().
isSetKisaoID()
bool SedAlgorithm::isSetKisaoID () const
Predicate returning true if this SedAlgorithm's "kisaoID" attribute is set.
Returns
true if this SedAlgorithm's "kisaoID" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes().
operator=()
SedAlgorithm & SedAlgorithm::operator= (const SedAlgorithm & rhs)
Assignment operator for SedAlgorithm.
Parameters
rhs the SedAlgorithm object whose values are to be used as the basis of the assignment.
References SedBase::operator=().
removeAlgorithmParameter() [1/2]
SedAlgorithmParameter * SedAlgorithm::removeAlgorithmParameter (const std::string & id)
Removes the SedAlgorithmParameter with the given id from this SedAlgorithm and returns a pointer to it.
Parameters
id a string representing the id of the SedAlgorithmParameter to remove.
Returns
a pointer to the nth SedAlgorithmParameter in this SedAlgorithm.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
removeAlgorithmParameter() [2/2]
SedAlgorithmParameter * SedAlgorithm::removeAlgorithmParameter (unsigned int n)
Removes the nth SedAlgorithmParameter from this SedAlgorithm and returns a pointer to it.
Parameters
n an unsigned int representing the index of the SedAlgorithmParameter to remove.
Returns
a pointer to the nth SedAlgorithmParameter in this SedAlgorithm.
See also
addAlgorithmParameter(const SedAlgorithmParameter* object)
createAlgorithmParameter()
getAlgorithmParameter(const std::string& sid)
getAlgorithmParameter(unsigned int n)
getNumAlgorithmParameters()
removeAlgorithmParameter(const std::string& sid)
setKisaoID() [1/2]
int SedAlgorithm::setKisaoID (const std::string & kisaoID)
Sets the value of the "kisaoID" attribute of this SedAlgorithm.
Parameters
kisaoID std::string& value of the "kisaoID" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
Calling this function with kisaoID = NULL or an empty string is equivalent to calling unsetKisaoID().
References g_kisaomap, getKisaoIDasInt(), SedBase::isSetName(), LIBSEDML_OPERATION_SUCCESS, and SedBase::setName().
setKisaoID() [2/2]
int SedAlgorithm::setKisaoID (int kisaoID)
Sets the KisaoId as integer
References g_kisaomap, SedBase::isSetName(), LIBSEDML_OPERATION_SUCCESS, and SedBase::setName().
unsetKisaoID()
int SedAlgorithm::unsetKisaoID ()
Unsets the value of the "kisaoID" attribute of this SedAlgorithm.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedAlgorithm.h
SedAlgorithm.cpp