LIBSEDML API: SedOneStep Class Reference
SedOneStep Class Reference
#include <SedOneStep.h>
Public Member Functions
virtual SedOneStep * clone () const
virtual const std::string & getElementName () const
double getStep () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetStep () const
SedOneStep & operator= (const SedOneStep &rhs)
SedOneStep (const SedOneStep &orig)
SedOneStep (SedNamespaces *sedmlns)
SedOneStep (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setStep (double step)
int unsetStep ()
virtual ~SedOneStep ()
Public Member Functions inherited from SedSimulation
SedAlgorithm * createAlgorithm ()
SedAlgorithm * getAlgorithm ()
const SedAlgorithm * getAlgorithm () const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual bool hasRequiredElements () const
virtual bool isSedAnalysis () const
virtual bool isSedOneStep () const
virtual bool isSedSteadyState () const
virtual bool isSedUniformTimeCourse () const
bool isSetAlgorithm () const
SedSimulation & operator= (const SedSimulation &rhs)
SedSimulation (const SedSimulation &orig)
SedSimulation (SedNamespaces *sedmlns)
SedSimulation (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setAlgorithm (const SedAlgorithm *algorithm)
int unsetAlgorithm ()
virtual ~SedSimulation ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedOneStep class.
Constructor & Destructor Documentation
SedOneStep() [1/3]
SedOneStep::SedOneStep (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedOneStep using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedOneStep.
version an unsigned int, the SED-ML Version to assign to this SedOneStep.
Referenced by clone().
SedOneStep() [2/3]
SedOneStep::SedOneStep (SedNamespaces * sedmlns)
Creates a new SedOneStep using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedOneStep() [3/3]
SedOneStep::SedOneStep (const SedOneStep & orig)
Copy constructor for SedOneStep.
Parameters
orig the SedOneStep instance to copy.
~SedOneStep()
SedOneStep::~SedOneStep () virtual
Destructor for SedOneStep.
Member Function Documentation
clone()
SedOneStep * SedOneStep::clone () const virtual
Creates and returns a deep copy of this SedOneStep object.
Returns
a (deep) copy of this SedOneStep object.
Reimplemented from SedSimulation.
References SedOneStep().
getElementName()
const std::string & SedOneStep::getElementName () const virtual
Returns the XML element name of this SedOneStep object.
For SedOneStep, the XML element name is always "oneStep".
Returns
the name of this element, i.e. "oneStep".
Reimplemented from SedSimulation.
getStep()
double SedOneStep::getStep () const
Returns the value of the "step" attribute of this SedOneStep.
Returns
the value of the "step" attribute of this SedOneStep as a double.
getTypeCode()
int SedOneStep::getTypeCode () const virtual
Returns the libSEDML type code for this SedOneStep object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SIMULATION_ONESTEP, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedSimulation.
References SEDML_SIMULATION_ONESTEP.
hasRequiredAttributes()
bool SedOneStep::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedOneStep object have been set.
Returns
true to indicate that all the required attributes of this SedOneStep have been set, otherwise false is returned.
Note
The required attributes for the SedOneStep object are:
"step"
Reimplemented from SedSimulation.
References SedSimulation::hasRequiredAttributes(), and isSetStep().
isSetStep()
bool SedOneStep::isSetStep () const
Predicate returning true if this SedOneStep's "step" attribute is set.
Returns
true if this SedOneStep's "step" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and unsetStep().
operator=()
SedOneStep & SedOneStep::operator= (const SedOneStep & rhs)
Assignment operator for SedOneStep.
Parameters
rhs the SedOneStep object whose values are to be used as the basis of the assignment.
References SedSimulation::operator=().
setStep()
int SedOneStep::setStep (double step)
Sets the value of the "step" attribute of this SedOneStep.
Parameters
step double value of the "step" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetStep()
int SedOneStep::unsetStep ()
Unsets the value of the "step" attribute of this SedOneStep.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References isSetStep(), LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedOneStep.h
SedOneStep.cpp