LIBSEDML API: SedStyle Class Reference
SedStyle Class Reference
#include <SedStyle.h>
Public Member Functions
virtual SedStyle * clone () const
SedFill * createFillStyle ()
SedLine * createLineStyle ()
SedMarker * createMarkerStyle ()
virtual List * getAllElements (SedElementFilter *filter=NULL)
const std::string & getBaseStyle () const
virtual SedBase * getElementBySId (const std::string &id)
virtual const std::string & getElementName () const
SedFill * getFillStyle ()
const SedFill * getFillStyle () const
SedLine * getLineStyle ()
const SedLine * getLineStyle () const
SedMarker * getMarkerStyle ()
const SedMarker * getMarkerStyle () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetBaseStyle () const
bool isSetFillStyle () const
bool isSetLineStyle () const
bool isSetMarkerStyle () const
SedStyle & operator= (const SedStyle &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedStyle (const SedStyle &orig)
SedStyle (SedNamespaces *sedmlns)
SedStyle (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setBaseStyle (const std::string &baseStyle)
int setFillStyle (const SedFill *fillStyle)
int setLineStyle (const SedLine *lineStyle)
int setMarkerStyle (const SedMarker *markerStyle)
int unsetBaseStyle ()
int unsetFillStyle ()
int unsetLineStyle ()
int unsetMarkerStyle ()
virtual ~SedStyle ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedStyle class.
Constructor & Destructor Documentation
SedStyle() [1/3]
SedStyle::SedStyle (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedStyle using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedStyle.
version an unsigned int, the SED-ML Version to assign to this SedStyle.
Referenced by clone().
SedStyle() [2/3]
SedStyle::SedStyle (SedNamespaces * sedmlns)
Creates a new SedStyle using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedStyle() [3/3]
SedStyle::SedStyle (const SedStyle & orig)
Copy constructor for SedStyle.
Parameters
orig the SedStyle instance to copy.
References clone().
~SedStyle()
SedStyle::~SedStyle () virtual
Destructor for SedStyle.
Member Function Documentation
clone()
SedStyle * SedStyle::clone () const virtual
Creates and returns a deep copy of this SedStyle object.
Returns
a (deep) copy of this SedStyle object.
Implements SedBase.
References SedStyle().
Referenced by operator=(), and SedStyle().
createFillStyle()
SedFill * SedStyle::createFillStyle ()
Creates a new SedFill object, adds it to this SedStyle object and returns the SedFill object created.
Returns
a new SedFill object instance.
createLineStyle()
SedLine * SedStyle::createLineStyle ()
Creates a new SedLine object, adds it to this SedStyle object and returns the SedLine object created.
Returns
a new SedLine object instance.
createMarkerStyle()
SedMarker * SedStyle::createMarkerStyle ()
Creates a new SedMarker object, adds it to this SedStyle object and returns the SedMarker object created.
Returns
a new SedMarker object instance.
getAllElements()
List * SedStyle::getAllElements (SedElementFilter * filter = NULL) virtual
Returns a List of all child SedBase objects, including those nested to an arbitrary depth.
Parameters
filter an ElementFilter that may impose restrictions on the objects to be retrieved.
Returns
a List pointer of pointers to all SedBase child objects with any restriction imposed.
Reimplemented from SedBase.
References SED_ADD_FILTERED_POINTER.
getBaseStyle()
const std::string & SedStyle::getBaseStyle () const
Returns the value of the "baseStyle" attribute of this SedStyle.
Returns
the value of the "baseStyle" attribute of this SedStyle as a string.
Referenced by SedDocument::getEffectiveStyle().
getElementBySId()
SedBase * SedStyle::getElementBySId (const std::string & id) virtual
Returns the first child element that has the given id in the model-wide SId namespace, or NULL if no such object is found.
Parameters
id a string representing the id attribute of the object to retrieve.
Returns
a pointer to the SedBase element with the given id. If no such object is found, this method returns NULL.
Reimplemented from SedBase.
References SedBase::getElementBySId().
getElementName()
const std::string & SedStyle::getElementName () const virtual
Returns the XML element name of this SedStyle object.
For SedStyle, the XML element name is always "style".
Returns
the name of this element, i.e. "style".
Implements SedBase.
getFillStyle() [1/2]
SedFill * SedStyle::getFillStyle ()
Returns the value of the "fill" element of this SedStyle.
Returns
the value of the "fill" element of this SedStyle as a SedFill*.
getFillStyle() [2/2]
const SedFill * SedStyle::getFillStyle () const
Returns the value of the "fill" element of this SedStyle.
Returns
the value of the "fill" element of this SedStyle as a SedFill*. SedFill*.
Referenced by SedDocument::getEffectiveStyle().
getLineStyle() [1/2]
SedLine * SedStyle::getLineStyle ()
Returns the value of the "line" element of this SedStyle.
Returns
the value of the "line" element of this SedStyle as a SedLine*.
getLineStyle() [2/2]
const SedLine * SedStyle::getLineStyle () const
Returns the value of the "line" element of this SedStyle.
Returns
the value of the "line" element of this SedStyle as a SedLine*.
Referenced by SedDocument::getEffectiveStyle().
getMarkerStyle() [1/2]
SedMarker * SedStyle::getMarkerStyle ()
Returns the value of the "marker" element of this SedStyle.
Returns
the value of the "marker" element of this SedStyle as a SedMarker*.
getMarkerStyle() [2/2]
const SedMarker * SedStyle::getMarkerStyle () const
Returns the value of the "marker" element of this SedStyle.
Returns
the value of the "marker" element of this SedStyle as a SedMarker*.
Referenced by SedDocument::getEffectiveStyle().
getTypeCode()
int SedStyle::getTypeCode () const virtual
Returns the libSEDML type code for this SedStyle object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_STYLE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedBase.
References SEDML_STYLE.
hasRequiredAttributes()
bool SedStyle::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedStyle object have been set.
Returns
true to indicate that all the required attributes of this SedStyle have been set, otherwise false is returned.
Note
The required attributes for the SedStyle object are:
"id"
References SedBase::isSetId().
Referenced by SedDocument::addStyle(), and SedListOfStyles::addStyle().
isSetBaseStyle()
bool SedStyle::isSetBaseStyle () const
Predicate returning true if this SedStyle's "baseStyle" attribute is set.
Returns
true if this SedStyle's "baseStyle" attribute has been set, otherwise false is returned.
Referenced by SedDocument::getEffectiveStyle(), and renameSIdRefs().
isSetFillStyle()
bool SedStyle::isSetFillStyle () const
Predicate returning true if this SedStyle's "fill" element is set.
Returns
true if this SedStyle's "fill" element has been set, otherwise false is returned.
Referenced by SedDocument::getEffectiveStyle().
isSetLineStyle()
bool SedStyle::isSetLineStyle () const
Predicate returning true if this SedStyle's "line" element is set.
Returns
true if this SedStyle's "line" element has been set, otherwise false is returned.
Referenced by SedDocument::getEffectiveStyle().
isSetMarkerStyle()
bool SedStyle::isSetMarkerStyle () const
Predicate returning true if this SedStyle's "marker" element is set.
Returns
true if this SedStyle's "marker" element has been set, otherwise false is returned.
Referenced by SedDocument::getEffectiveStyle().
operator=()
SedStyle & SedStyle::operator= (const SedStyle & rhs)
Assignment operator for SedStyle.
Parameters
rhs the SedStyle object whose values are to be used as the basis of the assignment.
References clone(), and SedBase::operator=().
renameSIdRefs()
void SedStyle::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetBaseStyle(), and setBaseStyle().
setBaseStyle()
int SedStyle::setBaseStyle (const std::string & baseStyle)
Sets the value of the "baseStyle" attribute of this SedStyle.
Parameters
baseStyle std::string& value of the "baseStyle" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
setFillStyle()
int SedStyle::setFillStyle (const SedFill * fillStyle)
Sets the value of the "fill" element of this SedStyle.
Parameters
fill SedFill* value of the "fill" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedFill::clone(), and LIBSEDML_OPERATION_SUCCESS.
Referenced by SedDocument::getEffectiveStyle().
setLineStyle()
int SedStyle::setLineStyle (const SedLine * lineStyle)
Sets the value of the "line" element of this SedStyle.
Parameters
line SedLine* value of the "line" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedLine::clone(), and LIBSEDML_OPERATION_SUCCESS.
Referenced by SedDocument::getEffectiveStyle().
setMarkerStyle()
int SedStyle::setMarkerStyle (const SedMarker * markerStyle)
Sets the value of the "marker" element of this SedStyle.
Parameters
marker SedMarker* value of the "marker" element to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References SedMarker::clone(), and LIBSEDML_OPERATION_SUCCESS.
Referenced by SedDocument::getEffectiveStyle().
unsetBaseStyle()
int SedStyle::unsetBaseStyle ()
Unsets the value of the "baseStyle" attribute of this SedStyle.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
Referenced by SedDocument::getEffectiveStyle().
unsetFillStyle()
int SedStyle::unsetFillStyle ()
Unsets the value of the "fill" element of this SedStyle.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetLineStyle()
int SedStyle::unsetLineStyle ()
Unsets the value of the "line" element of this SedStyle.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
unsetMarkerStyle()
int SedStyle::unsetMarkerStyle ()
Unsets the value of the "marker" element of this SedStyle.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedStyle.h
SedStyle.cpp