LIBSEDML API: SedDataRange Class Reference
SedDataRange Class Reference
#include <SedDataRange.h>
Public Member Functions
virtual SedDataRange * clone () const
virtual const std::string & getElementName () const
const std::string & getSourceReference () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetSourceReference () const
SedDataRange & operator= (const SedDataRange &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedDataRange (const SedDataRange &orig)
SedDataRange (SedNamespaces *sedmlns)
SedDataRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setSourceReference (const std::string &sourceReference)
int unsetSourceReference ()
virtual ~SedDataRange ()
Public Member Functions inherited from SedRange
virtual bool isSedDataRange () const
virtual bool isSedFunctionalRange () const
virtual bool isSedUniformRange () const
virtual bool isSedVectorRange () const
SedRange & operator= (const SedRange &rhs)
SedRange (const SedRange &orig)
SedRange (SedNamespaces *sedmlns)
SedRange (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedRange ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedDataRange class.
Constructor & Destructor Documentation
SedDataRange() [1/3]
SedDataRange::SedDataRange (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedDataRange using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedDataRange.
version an unsigned int, the SED-ML Version to assign to this SedDataRange.
Referenced by clone().
SedDataRange() [2/3]
SedDataRange::SedDataRange (SedNamespaces * sedmlns)
Creates a new SedDataRange using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedDataRange() [3/3]
SedDataRange::SedDataRange (const SedDataRange & orig)
Copy constructor for SedDataRange.
Parameters
orig the SedDataRange instance to copy.
~SedDataRange()
SedDataRange::~SedDataRange () virtual
Destructor for SedDataRange.
Member Function Documentation
clone()
SedDataRange * SedDataRange::clone () const virtual
Creates and returns a deep copy of this SedDataRange object.
Returns
a (deep) copy of this SedDataRange object.
Reimplemented from SedRange.
References SedDataRange().
getElementName()
const std::string & SedDataRange::getElementName () const virtual
Returns the XML element name of this SedDataRange object.
For SedDataRange, the XML element name is always "dataRange".
Returns
the name of this element, i.e. "dataRange".
Reimplemented from SedRange.
getSourceReference()
const std::string & SedDataRange::getSourceReference () const
Returns the value of the "sourceReference" attribute of this SedDataRange.
Returns
the value of the "sourceReference" attribute of this SedDataRange as a string.
getTypeCode()
int SedDataRange::getTypeCode () const virtual
Returns the libSEDML type code for this SedDataRange object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_DATA_RANGE, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedRange.
References SEDML_DATA_RANGE.
hasRequiredAttributes()
bool SedDataRange::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedDataRange object have been set.
Returns
true to indicate that all the required attributes of this SedDataRange have been set, otherwise false is returned.
Note
The required attributes for the SedDataRange object are:
"sourceReference"
Reimplemented from SedRange.
References SedRange::hasRequiredAttributes(), and isSetSourceReference().
isSetSourceReference()
bool SedDataRange::isSetSourceReference () const
Predicate returning true if this SedDataRange's "sourceReference" attribute is set.
Returns
true if this SedDataRange's "sourceReference" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
operator=()
SedDataRange & SedDataRange::operator= (const SedDataRange & rhs)
Assignment operator for SedDataRange.
Parameters
rhs the SedDataRange object whose values are to be used as the basis of the assignment.
References SedRange::operator=().
renameSIdRefs()
void SedDataRange::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetSourceReference(), and setSourceReference().
setSourceReference()
int SedDataRange::setSourceReference (const std::string & sourceReference)
Sets the value of the "sourceReference" attribute of this SedDataRange.
Parameters
sourceReference std::string& value of the "sourceReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetSourceReference()
int SedDataRange::unsetSourceReference ()
Unsets the value of the "sourceReference" attribute of this SedDataRange.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedDataRange.h
SedDataRange.cpp