LIBSEDML API: SedParameterEstimationReport Class Reference
SedParameterEstimationReport Class Reference
#include <SedParameterEstimationReport.h>
Public Member Functions
virtual SedParameterEstimationReport * clone () const
virtual const std::string & getElementName () const
const std::string & getTaskReference () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
bool isSetTaskReference () const
SedParameterEstimationReport & operator= (const SedParameterEstimationReport &rhs)
virtual void renameSIdRefs (const std::string &oldid, const std::string &newid)
SedParameterEstimationReport (const SedParameterEstimationReport &orig)
SedParameterEstimationReport (SedNamespaces *sedmlns)
SedParameterEstimationReport (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setTaskReference (const std::string &taskReference)
int unsetTaskReference ()
virtual ~SedParameterEstimationReport ()
Public Member Functions inherited from SedOutput
virtual bool isSedFigure () const
virtual bool isSedParameterEstimationResultPlot () const
virtual bool isSedPlot2D () const
virtual bool isSedPlot3D () const
virtual bool isSedReport () const
SedOutput & operator= (const SedOutput &rhs)
SedOutput (const SedOutput &orig)
SedOutput (SedNamespaces *sedmlns)
SedOutput (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedOutput ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
virtual List * getAllElements (SedElementFilter *filter=NULL)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual SedBase * getElementBySId (const std::string &id)
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedParameterEstimationReport class.
Constructor & Destructor Documentation
SedParameterEstimationReport() [1/3]
SedParameterEstimationReport::SedParameterEstimationReport (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedParameterEstimationReport using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedParameterEstimationReport.
version an unsigned int, the SED-ML Version to assign to this SedParameterEstimationReport.
Referenced by clone().
SedParameterEstimationReport() [2/3]
SedParameterEstimationReport::SedParameterEstimationReport (SedNamespaces * sedmlns)
Creates a new SedParameterEstimationReport using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedParameterEstimationReport() [3/3]
SedParameterEstimationReport::SedParameterEstimationReport (const SedParameterEstimationReport & orig)
Copy constructor for SedParameterEstimationReport.
Parameters
orig the SedParameterEstimationReport instance to copy.
~SedParameterEstimationReport()
SedParameterEstimationReport::~SedParameterEstimationReport () virtual
Destructor for SedParameterEstimationReport.
Member Function Documentation
clone()
SedParameterEstimationReport * SedParameterEstimationReport::clone () const virtual
Creates and returns a deep copy of this SedParameterEstimationReport object.
Returns
a (deep) copy of this SedParameterEstimationReport object.
Reimplemented from SedOutput.
References SedParameterEstimationReport().
getElementName()
const std::string & SedParameterEstimationReport::getElementName () const virtual
Returns the XML element name of this SedParameterEstimationReport object.
For SedParameterEstimationReport, the XML element name is always "parameterEstimationReport".
Returns
the name of this element, i.e. "parameterEstimationReport".
Reimplemented from SedOutput.
getTaskReference()
const std::string & SedParameterEstimationReport::getTaskReference () const
Returns the value of the "taskReference" attribute of this SedParameterEstimationReport.
Returns
the value of the "taskReference" attribute of this SedParameterEstimationReport as a string.
getTypeCode()
int SedParameterEstimationReport::getTypeCode () const virtual
Returns the libSEDML type code for this SedParameterEstimationReport object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_PARAMETERESTIMATIONREPORT, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedOutput.
References SEDML_PARAMETERESTIMATIONREPORT.
hasRequiredAttributes()
bool SedParameterEstimationReport::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedParameterEstimationReport object have been set.
Returns
true to indicate that all the required attributes of this SedParameterEstimationReport have been set, otherwise false is returned.
Note
The required attributes for the SedParameterEstimationReport object are:
"taskReference"
Reimplemented from SedOutput.
References SedOutput::hasRequiredAttributes(), and isSetTaskReference().
isSetTaskReference()
bool SedParameterEstimationReport::isSetTaskReference () const
Predicate returning true if this SedParameterEstimationReport's "taskReference" attribute is set.
Returns
true if this SedParameterEstimationReport's "taskReference" attribute has been set, otherwise false is returned.
Referenced by hasRequiredAttributes(), and renameSIdRefs().
operator=()
SedParameterEstimationReport & SedParameterEstimationReport::operator= (const SedParameterEstimationReport & rhs)
Assignment operator for SedParameterEstimationReport.
Parameters
rhs the SedParameterEstimationReport object whose values are to be used as the basis of the assignment.
References SedOutput::operator=().
renameSIdRefs()
void SedParameterEstimationReport::renameSIdRefs (const std::string & oldid, const std::string & newid) virtual
References isSetTaskReference(), and setTaskReference().
setTaskReference()
int SedParameterEstimationReport::setTaskReference (const std::string & taskReference)
Sets the value of the "taskReference" attribute of this SedParameterEstimationReport.
Parameters
taskReference std::string& value of the "taskReference" attribute to be set.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_INVALID_ATTRIBUTE_VALUE, OperationReturnValues_t}
References LIBSEDML_INVALID_ATTRIBUTE_VALUE, and LIBSEDML_OPERATION_SUCCESS.
Referenced by renameSIdRefs().
unsetTaskReference()
int SedParameterEstimationReport::unsetTaskReference ()
Unsets the value of the "taskReference" attribute of this SedParameterEstimationReport.
@sedmlconstant{LIBSEDML_OPERATION_SUCCESS, OperationReturnValues_t}
@sedmlconstant{LIBSEDML_OPERATION_FAILED, OperationReturnValues_t}
References LIBSEDML_OPERATION_FAILED, and LIBSEDML_OPERATION_SUCCESS.
The documentation for this class was generated from the following files:
SedParameterEstimationReport.h
SedParameterEstimationReport.cpp