LIBSEDML API: SedAnalysis Class Reference
SedAnalysis Class Reference
#include <SedAnalysis.h>
Public Member Functions
virtual SedAnalysis * clone () const
virtual const std::string & getElementName () const
virtual int getTypeCode () const
virtual bool hasRequiredAttributes () const
SedAnalysis & operator= (const SedAnalysis &rhs)
SedAnalysis (const SedAnalysis &orig)
SedAnalysis (SedNamespaces *sedmlns)
SedAnalysis (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
virtual ~SedAnalysis ()
Public Member Functions inherited from SedSimulation
SedAlgorithm * createAlgorithm ()
SedAlgorithm * getAlgorithm ()
const SedAlgorithm * getAlgorithm () const
virtual List * getAllElements (SedElementFilter *filter=NULL)
virtual SedBase * getElementBySId (const std::string &id)
virtual bool hasRequiredElements () const
virtual bool isSedAnalysis () const
virtual bool isSedOneStep () const
virtual bool isSedSteadyState () const
virtual bool isSedUniformTimeCourse () const
bool isSetAlgorithm () const
SedSimulation & operator= (const SedSimulation &rhs)
SedSimulation (const SedSimulation &orig)
SedSimulation (SedNamespaces *sedmlns)
SedSimulation (unsigned int level=SEDML_DEFAULT_LEVEL, unsigned int version=SEDML_DEFAULT_VERSION)
int setAlgorithm (const SedAlgorithm *algorithm)
int unsetAlgorithm ()
virtual ~SedSimulation ()
Public Member Functions inherited from SedBase
virtual int appendAnnotation (const std::string &annotation)
virtual int appendAnnotation (const XMLNode *annotation)
int appendNotes (const std::string &notes)
int appendNotes (const XMLNode *notes)
SedBase * getAncestorOfType (int type)
const SedBase * getAncestorOfType (int type) const
XMLNode * getAnnotation ()
const XMLNode * getAnnotation () const
std::string getAnnotationString ()
std::string getAnnotationString () const
unsigned int getColumn () const
virtual SedBase * getElementByMetaId (const std::string &metaid)
virtual const SedBase * getElementByMetaId (const std::string &metaid) const
virtual const SedBase * getElementBySId (const std::string &metaid) const
virtual const XMLNamespaces * getElementNamespaces () const
SedErrorLog * getErrorLog ()
virtual const std::string & getId () const
unsigned int getLevel () const
unsigned int getLine () const
std::string & getMetaId ()
const std::string & getMetaId () const
virtual const std::string & getName () const
virtual XMLNamespaces * getNamespaces ()
virtual const XMLNamespaces * getNamespaces () const
XMLNode * getNotes ()
const XMLNode * getNotes () const
std::string getNotesString ()
std::string getNotesString () const
SedBase * getParentSedObject ()
const SedBase * getParentSedObject () const
SedDocument * getSedDocument ()
const SedDocument * getSedDocument () const
void * getUserData () const
unsigned int getVersion () const
bool hasValidLevelVersionNamespaceCombination ()
bool isSetAnnotation () const
virtual bool isSetId () const
bool isSetMetaId () const
virtual bool isSetName () const
bool isSetNotes () const
bool isSetUserData () const
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb)
bool matchesRequiredSedNamespacesForAddition (const SedBase *sb) const
bool matchesSedNamespaces (const SedBase *sb)
bool matchesSedNamespaces (const SedBase *sb) const
SedBase & operator= (const SedBase &rhs)
virtual int removeFromParentAndDelete ()
int removeTopLevelAnnotationElement (const std::string elementName, const std::string elementURI="")
int replaceTopLevelAnnotationElement (const std::string &annotation)
int replaceTopLevelAnnotationElement (const XMLNode *annotation)
virtual int setAnnotation (const std::string &annotation)
virtual int setAnnotation (XMLNode *annotation)
virtual int setId (const std::string &sid)
int setMetaId (const std::string &metaid)
virtual int setName (const std::string &name)
int setNamespaces (XMLNamespaces *xmlns)
int setNotes (const std::string &notes, bool addXHTMLMarkup=false)
int setNotes (const XMLNode *notes)
int setUserData (void *userData)
char * toSed ()
int unsetAnnotation ()
virtual int unsetId ()
int unsetMetaId ()
virtual int unsetName ()
int unsetNotes ()
int unsetUserData ()
virtual ~SedBase ()
Additional Inherited Members
Protected Member Functions inherited from SedBase
bool getHasBeenDeleted () const
virtual void setElementText (const std::string &text)
Detailed Description
@sbmlbrief{sedml} TODO:Definition of the SedAnalysis class.
Constructor & Destructor Documentation
SedAnalysis() [1/3]
SedAnalysis::SedAnalysis (unsigned int level = SEDML_DEFAULT_LEVEL, unsigned int version = SEDML_DEFAULT_VERSION)
Creates a new SedAnalysis using the given SED-ML Level and @ p version values.
Parameters
level an unsigned int, the SED-ML Level to assign to this SedAnalysis.
version an unsigned int, the SED-ML Version to assign to this SedAnalysis.
Referenced by clone().
SedAnalysis() [2/3]
SedAnalysis::SedAnalysis (SedNamespaces * sedmlns)
Creates a new SedAnalysis using the given SedNamespaces object sedmlns.
Parameters
sedmlns the SedNamespaces object.
References SedNamespaces::getURI().
SedAnalysis() [3/3]
SedAnalysis::SedAnalysis (const SedAnalysis & orig)
Copy constructor for SedAnalysis.
Parameters
orig the SedAnalysis instance to copy.
~SedAnalysis()
SedAnalysis::~SedAnalysis () virtual
Destructor for SedAnalysis.
Member Function Documentation
clone()
SedAnalysis * SedAnalysis::clone () const virtual
Creates and returns a deep copy of this SedAnalysis object.
Returns
a (deep) copy of this SedAnalysis object.
Reimplemented from SedSimulation.
References SedAnalysis().
getElementName()
const std::string & SedAnalysis::getElementName () const virtual
Returns the XML element name of this SedAnalysis object.
For SedAnalysis, the XML element name is always "analysis".
Returns
the name of this element, i.e. "analysis".
Reimplemented from SedSimulation.
getTypeCode()
int SedAnalysis::getTypeCode () const virtual
Returns the libSEDML type code for this SedAnalysis object.
Returns
the SED-ML type code for this object: @sedmlconstant{SEDML_SIMULATION_ANALYSIS, SedTypeCode_t}.
See also
getElementName()
Reimplemented from SedSimulation.
References SEDML_SIMULATION_ANALYSIS.
hasRequiredAttributes()
bool SedAnalysis::hasRequiredAttributes () const virtual
Predicate returning true if all the required attributes for this SedAnalysis object have been set.
Returns
true to indicate that all the required attributes of this SedAnalysis have been set, otherwise false is returned.
Reimplemented from SedSimulation.
References SedSimulation::hasRequiredAttributes().
operator=()
SedAnalysis & SedAnalysis::operator= (const SedAnalysis & rhs)
Assignment operator for SedAnalysis.
Parameters
rhs the SedAnalysis object whose values are to be used as the basis of the assignment.
References SedSimulation::operator=().
The documentation for this class was generated from the following files:
SedAnalysis.h
SedAnalysis.cpp